Adjustments to accommodate new GCloud SQL auth proxy
PERTS/gymnast pull request #89
Opened 2023-08-25 15:51 UTC by isaacahuvia

Because of updates to our database storage/firewalls, the old method of connecting to Triton and Saturn databases will no longer work for analysts. In order to access these data now, analysts will have to connect to the databases via terminal first (instructions [here](https://docs.google.com/document/d/184dsSF-esWgJ-TS_da3--UkFNb1oIur-r99X-7Xmhfg/edit)), and only once they have established a connection via an open terminal, use the normal data loading functions in R. Moreover, there are a couple of tweaks that had to be implemented in the R code to accommodate this new process; thus this PR. These changes include (1) changing the IP address for Triton and Saturn to the localhost server, and (2) specifying the port numbers for Triton and Saturn. These port numbers align with the script used in the terminal to connect to the databases. 

A couple of considerations:
- Once we implement this, I don't think analysts will be able to access any Triton or Saturn data without using the terminal to connect to GCloud
- Port numbers are hard-coded in here, which shouldn't be a problem so long as we don't change them in the script that we use to connect via the terminal
- Are there other databases that analysts will need to access that we need to accommodate here? (Neptune?)

2023-08-29 21:33 UTC, sarah-gripshover-PERTS requested changes
Thanks for updating this @isaacahuvia ! @chris-perts please quickly review this PR when you get a chance. Isaac, my only requested change is just to let me know how you tested this — did you pull some data with it and verify that it works correctly?

Maybe we should all sit down at the next research team meeting and actually run the terminal script together on our own machines and make sure we all can do it.

2023-08-30 21:15 UTC, isaacahuvia commented
> Thanks for updating this @isaacahuvia ! @chris-perts please quickly review this PR when you get a chance. Isaac, my only requested change is just to let me know how you tested this — did you pull some data with it and verify that it works correctly?

Yes, I tested this by successfully accessing Saturn and Triton data via this method. Maybe there are other data quality double-checks that I should do, but I figured the only things that could go wrong here would prevent me from accessing data altogether. 

> Maybe we should all sit down at the next research team meeting and actually run the terminal script together on our own machines and make sure we all can do it.

Yes! We should all try to do the installation steps beforehand from Chris's walkthrough doc.

2023-08-31 01:19 UTC, chris-perts approved these changes
Nit: include a link to the applicable docs in comments or a readme. No need to duplicate details, just make it easy to find the right instructions.

2023-08-31 01:23 UTC, chris-perts commented
Was there a need to have an additional password file for Saturn? I don't remember.

Also the reason for the change is that this system is safer and allows me to maintain fewer firewall exceptions about who is allowed to connect.

Note that the readonly user passwords are as sensitive as ever and should always be kept in a crypt or password manager.

Thanks Isaac!

2023-08-31 14:58 UTC, isaacahuvia commented
> Was there a need to have an additional password file for Saturn? I don't remember.

All of the passwords are still the passwords from the analysis crypt that we keep on Box. I didn't have to create any additional password files for this, the gymnast workflow already looks to the passwords in that crypt.

2023-09-11 14:37 UTC, sarah-gripshover-PERTS approved these changes
Thanks for dealing with this, Isaac!

2023-09-14 17:56 UTC, rumenPERTS commented
September 2023
PERTS Newsletter


** A Cool Update to a Hot September
------------------------------------------------------------
As we bid farewell to the warmth of summer, we hope your school year is off to a great start! In this edition, we invite you to join our national improvement network and will share some guidance for securing state or federal funds for your Elevate community. We also provide powerful Ascend reflections from community college students and faculty, and an update on the “archive” feature that’ll let you access last year’s reports.


** Join a National Network of Student Experience Champions!
------------------------------------------------------------
The Elevate Facilitator Network (https://perts.net/efn-flier) (EFN) convenes educators and instructional leaders who facilitate Elevate communities of practice. Network members meet throughout the school year to build their improvement coaching skills and share insights with an amazing community of student experience champions from across the nation. Membership is open to Elevate Leads with a premium services partnership.
If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use discount code FALL23 for a 15% discount!
Sign Up for a Consultation (https://perts.net/consultation)


** Secure Federal or State Dollars to Fund Your Elevate CoP💰
------------------------------------------------------------
Federal and state funds are sometimes earmarked for programs that meet specific “tiers of evidence.” We’ve put together a guide to help education leaders secure those funds by citing the evidence tier relevant to their Elevate implementation.
Review the ESSA Evidence Tiers for Elevate (https://docs.google.com/document/d/1G8nZGAumUIr1BcGWtrHaPvT4p00jznLvVv2hgKJ8OTc/preview)


** Latest Updates for 2023-2024
------------------------------------------------------------
Thanks to your valuable feedback and insights from the latest research, we have made some big updates to make our programs easier and more impactful, including a new archive feature to view last year's Elevate and Ascend reports that will be available by September 30.
Review Elevate Updates for 2023-24 (https://elevate-support.perts.net/support/solutions/articles/67000723611-what-enhancements-were-made-to-elevate-for-2023-24-)
Review Ascend Updates for 2023-24 (https://ascend-support.perts.net/support/solutions/articles/67000723612-what-enhancements-were-made-to-ascend-for-2023-24-)


** Join Us in Atlanta for the SEL Exchange!
------------------------------------------------------------
PERTS has been chosen as a featured speaker at the SEL Exchange 2023, hosted by the Collaborative for Academic, Social, and Emotional Learning (CASEL)! We cordially invite you to join us for an engaging afternoon of conversation as we delve into experiences and insights from the Elevate Network that have empowered students to cultivate robust academic, social, and emotional skills.
Register for the CASEL SEL Exchange 2023 (https://selexchange.casel.org/2023-registration/)


** Implementation Tips
------------------------------------------------------------
* Gain some insight and inspiration (https://elevate-support.perts.net/support/solutions/articles/67000713395-how-can-i-prepare-teachers-to-implement-elevate-) from individuals who have supported teachers in implementation.
* Maximize student survey participation with these best practices (https://perts.freshdesk.com/en/support/solutions/articles/67000441438-how-do-i-maximize-student-participation-in-ascend-elevate-) !
* Review participation rates & survey fidelity responses with our CoP protocols (https://perts.freshdesk.com/support/solutions/articles/67000676394-community-of-practice-meeting-protocols) .


** Improving Student Experience in the College Classroom
------------------------------------------------------------
In this powerful webinar, faculty and researchers describe insights and reflections from LEARN (the Learning for Equity Ascend Research Network). LEARN convened faculty from multiple colleges as they used Ascend to improve the quality and equity of their students’ classroom experiences.
https://ascend-support.perts.net/support/solutions/articles/67000723457-lessons-from-the-learn-network-webinar-may-2023
“
What I've really come to value about [PERTS] is that it shows me the difference between my intent and my impact and has provided me with tools to match those better.

Dr. Sushilla Knottenbelt, Director & Senior Lecturer
University of New Mexico
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=316caa3e4a)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=316caa3e4a)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-09-14 17:56 UTC, rumenPERTS commented
September 2023
PERTS Newsletter


** A Cool Update to a Hot September
------------------------------------------------------------
As we bid farewell to the warmth of summer, we hope your school year is off to a great start! In this edition, we invite you to join our national improvement network and will share some guidance for securing state or federal funds for your Elevate community. We also provide powerful Ascend reflections from community college students and faculty, and an update on the “archive” feature that’ll let you access last year’s reports.


** Join a National Network of Student Experience Champions!
------------------------------------------------------------
The Elevate Facilitator Network (https://perts.net/efn-flier) (EFN) convenes educators and instructional leaders who facilitate Elevate communities of practice. Network members meet throughout the school year to build their improvement coaching skills and share insights with an amazing community of student experience champions from across the nation. Membership is open to Elevate Leads with a premium services partnership.
If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use discount code FALL23 for a 15% discount!
Sign Up for a Consultation (https://perts.net/consultation)


** Secure Federal or State Dollars to Fund Your Elevate CoP💰
------------------------------------------------------------
Federal and state funds are sometimes earmarked for programs that meet specific “tiers of evidence.” We’ve put together a guide to help education leaders secure those funds by citing the evidence tier relevant to their Elevate implementation.
Review the ESSA Evidence Tiers for Elevate (https://docs.google.com/document/d/1G8nZGAumUIr1BcGWtrHaPvT4p00jznLvVv2hgKJ8OTc/preview)


** Latest Updates for 2023-2024
------------------------------------------------------------
Thanks to your valuable feedback and insights from the latest research, we have made some big updates to make our programs easier and more impactful, including a new archive feature to view last year's Elevate and Ascend reports that will be available by September 30.
Review Elevate Updates for 2023-24 (https://elevate-support.perts.net/support/solutions/articles/67000723611-what-enhancements-were-made-to-elevate-for-2023-24-)
Review Ascend Updates for 2023-24 (https://ascend-support.perts.net/support/solutions/articles/67000723612-what-enhancements-were-made-to-ascend-for-2023-24-)


** Join Us in Atlanta for the SEL Exchange!
------------------------------------------------------------
PERTS has been chosen as a featured speaker at the SEL Exchange 2023, hosted by the Collaborative for Academic, Social, and Emotional Learning (CASEL)! We cordially invite you to join us for an engaging afternoon of conversation as we delve into experiences and insights from the Elevate Network that have empowered students to cultivate robust academic, social, and emotional skills.
Register for the CASEL SEL Exchange 2023 (https://selexchange.casel.org/2023-registration/)


** Implementation Tips
------------------------------------------------------------
* Gain some insight and inspiration (https://elevate-support.perts.net/support/solutions/articles/67000713395-how-can-i-prepare-teachers-to-implement-elevate-) from individuals who have supported teachers in implementation.
* Maximize student survey participation with these best practices (https://perts.freshdesk.com/en/support/solutions/articles/67000441438-how-do-i-maximize-student-participation-in-ascend-elevate-) !
* Review participation rates & survey fidelity responses with our CoP protocols (https://perts.freshdesk.com/support/solutions/articles/67000676394-community-of-practice-meeting-protocols) .


** Improving Student Experience in the College Classroom
------------------------------------------------------------
In this powerful webinar, faculty and researchers describe insights and reflections from LEARN (the Learning for Equity Ascend Research Network). LEARN convened faculty from multiple colleges as they used Ascend to improve the quality and equity of their students’ classroom experiences.
https://ascend-support.perts.net/support/solutions/articles/67000723457-lessons-from-the-learn-network-webinar-may-2023
“
What I've really come to value about [PERTS] is that it shows me the difference between my intent and my impact and has provided me with tools to match those better.

Dr. Sushilla Knottenbelt, Director & Senior Lecturer
University of New Mexico
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=316caa3e4a)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=316caa3e4a)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-09-14 17:56 UTC, rumenPERTS commented
September 2023
PERTS Newsletter


** A Cool Update to a Hot September
------------------------------------------------------------
As we bid farewell to the warmth of summer, we hope your school year is off to a great start! In this edition, we invite you to join our national improvement network and will share some guidance for securing state or federal funds for your Elevate community. We also provide powerful Ascend reflections from community college students and faculty, and an update on the “archive” feature that’ll let you access last year’s reports.


** Join a National Network of Student Experience Champions!
------------------------------------------------------------
The Elevate Facilitator Network (https://perts.net/efn-flier) (EFN) convenes educators and instructional leaders who facilitate Elevate communities of practice. Network members meet throughout the school year to build their improvement coaching skills and share insights with an amazing community of student experience champions from across the nation. Membership is open to Elevate Leads with a premium services partnership.
If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use discount code FALL23 for a 15% discount!
Sign Up for a Consultation (https://perts.net/consultation)


** Secure Federal or State Dollars to Fund Your Elevate CoP💰
------------------------------------------------------------
Federal and state funds are sometimes earmarked for programs that meet specific “tiers of evidence.” We’ve put together a guide to help education leaders secure those funds by citing the evidence tier relevant to their Elevate implementation.
Review the ESSA Evidence Tiers for Elevate (https://docs.google.com/document/d/1G8nZGAumUIr1BcGWtrHaPvT4p00jznLvVv2hgKJ8OTc/preview)


** Latest Updates for 2023-2024
------------------------------------------------------------
Thanks to your valuable feedback and insights from the latest research, we have made some big updates to make our programs easier and more impactful, including a new archive feature to view last year's Elevate and Ascend reports that will be available by September 30.
Review Elevate Updates for 2023-24 (https://elevate-support.perts.net/support/solutions/articles/67000723611-what-enhancements-were-made-to-elevate-for-2023-24-)
Review Ascend Updates for 2023-24 (https://ascend-support.perts.net/support/solutions/articles/67000723612-what-enhancements-were-made-to-ascend-for-2023-24-)


** Join Us in Atlanta for the SEL Exchange!
------------------------------------------------------------
PERTS has been chosen as a featured speaker at the SEL Exchange 2023, hosted by the Collaborative for Academic, Social, and Emotional Learning (CASEL)! We cordially invite you to join us for an engaging afternoon of conversation as we delve into experiences and insights from the Elevate Network that have empowered students to cultivate robust academic, social, and emotional skills.
Register for the CASEL SEL Exchange 2023 (https://selexchange.casel.org/2023-registration/)


** Implementation Tips
------------------------------------------------------------
* Gain some insight and inspiration (https://elevate-support.perts.net/support/solutions/articles/67000713395-how-can-i-prepare-teachers-to-implement-elevate-) from individuals who have supported teachers in implementation.
* Maximize student survey participation with these best practices (https://perts.freshdesk.com/en/support/solutions/articles/67000441438-how-do-i-maximize-student-participation-in-ascend-elevate-) !
* Review participation rates & survey fidelity responses with our CoP protocols (https://perts.freshdesk.com/support/solutions/articles/67000676394-community-of-practice-meeting-protocols) .


** Improving Student Experience in the College Classroom
------------------------------------------------------------
In this powerful webinar, faculty and researchers describe insights and reflections from LEARN (the Learning for Equity Ascend Research Network). LEARN convened faculty from multiple colleges as they used Ascend to improve the quality and equity of their students’ classroom experiences.
https://ascend-support.perts.net/support/solutions/articles/67000723457-lessons-from-the-learn-network-webinar-may-2023
“
What I've really come to value about [PERTS] is that it shows me the difference between my intent and my impact and has provided me with tools to match those better.

Dr. Sushilla Knottenbelt, Director & Senior Lecturer
University of New Mexico
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=316caa3e4a)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=316caa3e4a)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-09-14 17:57 UTC, rumenPERTS commented
September 2023
PERTS Newsletter


** A Cool Update to a Hot September
------------------------------------------------------------
As we bid farewell to the warmth of summer, we hope your school year is off to a great start! In this edition, we invite you to join our national improvement network and will share some guidance for securing state or federal funds for your Elevate community. We also provide powerful Ascend reflections from community college students and faculty, and an update on the “archive” feature that’ll let you access last year’s reports.


** Join a National Network of Student Experience Champions!
------------------------------------------------------------
The Elevate Facilitator Network (https://perts.net/efn-flier) (EFN) convenes educators and instructional leaders who facilitate Elevate communities of practice. Network members meet throughout the school year to build their improvement coaching skills and share insights with an amazing community of student experience champions from across the nation. Membership is open to Elevate Leads with a premium services partnership.
If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use discount code FALL23 for a 15% discount!
Sign Up for a Consultation (https://perts.net/consultation)


** Secure Federal or State Dollars to Fund Your Elevate CoP💰
------------------------------------------------------------
Federal and state funds are sometimes earmarked for programs that meet specific “tiers of evidence.” We’ve put together a guide to help education leaders secure those funds by citing the evidence tier relevant to their Elevate implementation.
Review the ESSA Evidence Tiers for Elevate (https://docs.google.com/document/d/1G8nZGAumUIr1BcGWtrHaPvT4p00jznLvVv2hgKJ8OTc/preview)


** Latest Updates for 2023-2024
------------------------------------------------------------
Thanks to your valuable feedback and insights from the latest research, we have made some big updates to make our programs easier and more impactful, including a new archive feature to view last year's Elevate and Ascend reports that will be available by September 30.
Review Elevate Updates for 2023-24 (https://elevate-support.perts.net/support/solutions/articles/67000723611-what-enhancements-were-made-to-elevate-for-2023-24-)
Review Ascend Updates for 2023-24 (https://ascend-support.perts.net/support/solutions/articles/67000723612-what-enhancements-were-made-to-ascend-for-2023-24-)


** Join Us in Atlanta for the SEL Exchange!
------------------------------------------------------------
PERTS has been chosen as a featured speaker at the SEL Exchange 2023, hosted by the Collaborative for Academic, Social, and Emotional Learning (CASEL)! We cordially invite you to join us for an engaging afternoon of conversation as we delve into experiences and insights from the Elevate Network that have empowered students to cultivate robust academic, social, and emotional skills.
Register for the CASEL SEL Exchange 2023 (https://selexchange.casel.org/2023-registration/)


** Implementation Tips
------------------------------------------------------------
* Gain some insight and inspiration (https://elevate-support.perts.net/support/solutions/articles/67000713395-how-can-i-prepare-teachers-to-implement-elevate-) from individuals who have supported teachers in implementation.
* Maximize student survey participation with these best practices (https://perts.freshdesk.com/en/support/solutions/articles/67000441438-how-do-i-maximize-student-participation-in-ascend-elevate-) !
* Review participation rates & survey fidelity responses with our CoP protocols (https://perts.freshdesk.com/support/solutions/articles/67000676394-community-of-practice-meeting-protocols) .


** Improving Student Experience in the College Classroom
------------------------------------------------------------
In this powerful webinar, faculty and researchers describe insights and reflections from LEARN (the Learning for Equity Ascend Research Network). LEARN convened faculty from multiple colleges as they used Ascend to improve the quality and equity of their students’ classroom experiences.
https://ascend-support.perts.net/support/solutions/articles/67000723457-lessons-from-the-learn-network-webinar-may-2023
“
What I've really come to value about [PERTS] is that it shows me the difference between my intent and my impact and has provided me with tools to match those better.

Dr. Sushilla Knottenbelt, Director & Senior Lecturer
University of New Mexico
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=8af4b6e57d&c=316caa3e4a)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=8af4b6e57d&c=316caa3e4a)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-09-14 17:57 UTC, rumenPERTS commented
September 2023
PERTS Newsletter


** A Cool Update to a Hot September
------------------------------------------------------------
As we bid farewell to the warmth of summer, we hope your school year is off to a great start! In this edition, we invite you to join our national improvement network and will share some guidance for securing state or federal funds for your Elevate community. We also provide powerful Ascend reflections from community college students and faculty, and an update on the “archive” feature that’ll let you access last year’s reports.


** Join a National Network of Student Experience Champions!
------------------------------------------------------------
The Elevate Facilitator Network (https://perts.net/efn-flier) (EFN) convenes educators and instructional leaders who facilitate Elevate communities of practice. Network members meet throughout the school year to build their improvement coaching skills and share insights with an amazing community of student experience champions from across the nation. Membership is open to Elevate Leads with a premium services partnership.
If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use discount code FALL23 for a 15% discount!
Sign Up for a Consultation (https://perts.net/consultation)


** Secure Federal or State Dollars to Fund Your Elevate CoP💰
------------------------------------------------------------
Federal and state funds are sometimes earmarked for programs that meet specific “tiers of evidence.” We’ve put together a guide to help education leaders secure those funds by citing the evidence tier relevant to their Elevate implementation.
Review the ESSA Evidence Tiers for Elevate (https://docs.google.com/document/d/1G8nZGAumUIr1BcGWtrHaPvT4p00jznLvVv2hgKJ8OTc/preview)


** Latest Updates for 2023-2024
------------------------------------------------------------
Thanks to your valuable feedback and insights from the latest research, we have made some big updates to make our programs easier and more impactful, including a new archive feature to view last year's Elevate and Ascend reports that will be available by September 30.
Review Elevate Updates for 2023-24 (https://elevate-support.perts.net/support/solutions/articles/67000723611-what-enhancements-were-made-to-elevate-for-2023-24-)
Review Ascend Updates for 2023-24 (https://ascend-support.perts.net/support/solutions/articles/67000723612-what-enhancements-were-made-to-ascend-for-2023-24-)


** Join Us in Atlanta for the SEL Exchange!
------------------------------------------------------------
PERTS has been chosen as a featured speaker at the SEL Exchange 2023, hosted by the Collaborative for Academic, Social, and Emotional Learning (CASEL)! We cordially invite you to join us for an engaging afternoon of conversation as we delve into experiences and insights from the Elevate Network that have empowered students to cultivate robust academic, social, and emotional skills.
Register for the CASEL SEL Exchange 2023 (https://selexchange.casel.org/2023-registration/)


** Implementation Tips
------------------------------------------------------------
* Gain some insight and inspiration (https://elevate-support.perts.net/support/solutions/articles/67000713395-how-can-i-prepare-teachers-to-implement-elevate-) from individuals who have supported teachers in implementation.
* Maximize student survey participation with these best practices (https://perts.freshdesk.com/en/support/solutions/articles/67000441438-how-do-i-maximize-student-participation-in-ascend-elevate-) !
* Review participation rates & survey fidelity responses with our CoP protocols (https://perts.freshdesk.com/support/solutions/articles/67000676394-community-of-practice-meeting-protocols) .


** Improving Student Experience in the College Classroom
------------------------------------------------------------
In this powerful webinar, faculty and researchers describe insights and reflections from LEARN (the Learning for Equity Ascend Research Network). LEARN convened faculty from multiple colleges as they used Ascend to improve the quality and equity of their students’ classroom experiences.
https://ascend-support.perts.net/support/solutions/articles/67000723457-lessons-from-the-learn-network-webinar-may-2023
“
What I've really come to value about [PERTS] is that it shows me the difference between my intent and my impact and has provided me with tools to match those better.

Dr. Sushilla Knottenbelt, Director & Senior Lecturer
University of New Mexico
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=316caa3e4a)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=316caa3e4a)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-09-14 17:57 UTC, rumenPERTS commented
September 2023
PERTS Newsletter


** A Cool Update to a Hot September
------------------------------------------------------------
As we bid farewell to the warmth of summer, we hope your school year is off to a great start! In this edition, we invite you to join our national improvement network and will share some guidance for securing state or federal funds for your Elevate community. We also provide powerful Ascend reflections from community college students and faculty, and an update on the “archive” feature that’ll let you access last year’s reports.


** Join a National Network of Student Experience Champions!
------------------------------------------------------------
The Elevate Facilitator Network (https://perts.net/efn-flier) (EFN) convenes educators and instructional leaders who facilitate Elevate communities of practice. Network members meet throughout the school year to build their improvement coaching skills and share insights with an amazing community of student experience champions from across the nation. Membership is open to Elevate Leads with a premium services partnership.
If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use discount code FALL23 for a 15% discount!
Sign Up for a Consultation (https://perts.net/consultation)


** Secure Federal or State Dollars to Fund Your Elevate CoP💰
------------------------------------------------------------
Federal and state funds are sometimes earmarked for programs that meet specific “tiers of evidence.” We’ve put together a guide to help education leaders secure those funds by citing the evidence tier relevant to their Elevate implementation.
Review the ESSA Evidence Tiers for Elevate (https://docs.google.com/document/d/1G8nZGAumUIr1BcGWtrHaPvT4p00jznLvVv2hgKJ8OTc/preview)


** Latest Updates for 2023-2024
------------------------------------------------------------
Thanks to your valuable feedback and insights from the latest research, we have made some big updates to make our programs easier and more impactful, including a new archive feature to view last year's Elevate and Ascend reports that will be available by September 30.
Review Elevate Updates for 2023-24 (https://elevate-support.perts.net/support/solutions/articles/67000723611-what-enhancements-were-made-to-elevate-for-2023-24-)
Review Ascend Updates for 2023-24 (https://ascend-support.perts.net/support/solutions/articles/67000723612-what-enhancements-were-made-to-ascend-for-2023-24-)


** Join Us in Atlanta for the SEL Exchange!
------------------------------------------------------------
PERTS has been chosen as a featured speaker at the SEL Exchange 2023, hosted by the Collaborative for Academic, Social, and Emotional Learning (CASEL)! We cordially invite you to join us for an engaging afternoon of conversation as we delve into experiences and insights from the Elevate Network that have empowered students to cultivate robust academic, social, and emotional skills.
Register for the CASEL SEL Exchange 2023 (https://selexchange.casel.org/2023-registration/)


** Implementation Tips
------------------------------------------------------------
* Gain some insight and inspiration (https://elevate-support.perts.net/support/solutions/articles/67000713395-how-can-i-prepare-teachers-to-implement-elevate-) from individuals who have supported teachers in implementation.
* Maximize student survey participation with these best practices (https://perts.freshdesk.com/en/support/solutions/articles/67000441438-how-do-i-maximize-student-participation-in-ascend-elevate-) !
* Review participation rates & survey fidelity responses with our CoP protocols (https://perts.freshdesk.com/support/solutions/articles/67000676394-community-of-practice-meeting-protocols) .


** Improving Student Experience in the College Classroom
------------------------------------------------------------
In this powerful webinar, faculty and researchers describe insights and reflections from LEARN (the Learning for Equity Ascend Research Network). LEARN convened faculty from multiple colleges as they used Ascend to improve the quality and equity of their students’ classroom experiences.
https://ascend-support.perts.net/support/solutions/articles/67000723457-lessons-from-the-learn-network-webinar-may-2023
“
What I've really come to value about [PERTS] is that it shows me the difference between my intent and my impact and has provided me with tools to match those better.

Dr. Sushilla Knottenbelt, Director & Senior Lecturer
University of New Mexico
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=9dba3d787d&c=316caa3e4a)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=9dba3d787d&c=316caa3e4a)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-09-14 17:57 UTC, rumenPERTS commented
September 2023
PERTS Newsletter


** A Cool Update to a Hot September
------------------------------------------------------------
As we bid farewell to the warmth of summer, we hope your school year is off to a great start! In this edition, we invite you to join our national improvement network and will share some guidance for securing state or federal funds for your Elevate community. We also provide powerful Ascend reflections from community college students and faculty, and an update on the “archive” feature that’ll let you access last year’s reports.


** Join a National Network of Student Experience Champions!
------------------------------------------------------------
The Elevate Facilitator Network (https://perts.net/efn-flier) (EFN) convenes educators and instructional leaders who facilitate Elevate communities of practice. Network members meet throughout the school year to build their improvement coaching skills and share insights with an amazing community of student experience champions from across the nation. Membership is open to Elevate Leads with a premium services partnership.
If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use discount code FALL23 for a 15% discount!
Sign Up for a Consultation (https://perts.net/consultation)


** Secure Federal or State Dollars to Fund Your Elevate CoP💰
------------------------------------------------------------
Federal and state funds are sometimes earmarked for programs that meet specific “tiers of evidence.” We’ve put together a guide to help education leaders secure those funds by citing the evidence tier relevant to their Elevate implementation.
Review the ESSA Evidence Tiers for Elevate (https://docs.google.com/document/d/1G8nZGAumUIr1BcGWtrHaPvT4p00jznLvVv2hgKJ8OTc/preview)


** Latest Updates for 2023-2024
------------------------------------------------------------
Thanks to your valuable feedback and insights from the latest research, we have made some big updates to make our programs easier and more impactful, including a new archive feature to view last year's Elevate and Ascend reports that will be available by September 30.
Review Elevate Updates for 2023-24 (https://elevate-support.perts.net/support/solutions/articles/67000723611-what-enhancements-were-made-to-elevate-for-2023-24-)
Review Ascend Updates for 2023-24 (https://ascend-support.perts.net/support/solutions/articles/67000723612-what-enhancements-were-made-to-ascend-for-2023-24-)


** Join Us in Atlanta for the SEL Exchange!
------------------------------------------------------------
PERTS has been chosen as a featured speaker at the SEL Exchange 2023, hosted by the Collaborative for Academic, Social, and Emotional Learning (CASEL)! We cordially invite you to join us for an engaging afternoon of conversation as we delve into experiences and insights from the Elevate Network that have empowered students to cultivate robust academic, social, and emotional skills.
Register for the CASEL SEL Exchange 2023 (https://selexchange.casel.org/2023-registration/)


** Implementation Tips
------------------------------------------------------------
* Gain some insight and inspiration (https://elevate-support.perts.net/support/solutions/articles/67000713395-how-can-i-prepare-teachers-to-implement-elevate-) from individuals who have supported teachers in implementation.
* Maximize student survey participation with these best practices (https://perts.freshdesk.com/en/support/solutions/articles/67000441438-how-do-i-maximize-student-participation-in-ascend-elevate-) !
* Review participation rates & survey fidelity responses with our CoP protocols (https://perts.freshdesk.com/support/solutions/articles/67000676394-community-of-practice-meeting-protocols) .


** Improving Student Experience in the College Classroom
------------------------------------------------------------
In this powerful webinar, faculty and researchers describe insights and reflections from LEARN (the Learning for Equity Ascend Research Network). LEARN convened faculty from multiple colleges as they used Ascend to improve the quality and equity of their students’ classroom experiences.
https://ascend-support.perts.net/support/solutions/articles/67000723457-lessons-from-the-learn-network-webinar-may-2023
“
What I've really come to value about [PERTS] is that it shows me the difference between my intent and my impact and has provided me with tools to match those better.

Dr. Sushilla Knottenbelt, Director & Senior Lecturer
University of New Mexico
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=316caa3e4a)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=316caa3e4a)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-09-14 17:58 UTC, rumenPERTS commented
September 2023
PERTS Newsletter


** A Cool Update to a Hot September
------------------------------------------------------------
As we bid farewell to the warmth of summer, we hope your school year is off to a great start! In this edition, we invite you to join our national improvement network and will share some guidance for securing state or federal funds for your Elevate community. We also provide powerful Ascend reflections from community college students and faculty, and an update on the “archive” feature that’ll let you access last year’s reports.


** Join a National Network of Student Experience Champions!
------------------------------------------------------------
The Elevate Facilitator Network (https://perts.net/efn-flier) (EFN) convenes educators and instructional leaders who facilitate Elevate communities of practice. Network members meet throughout the school year to build their improvement coaching skills and share insights with an amazing community of student experience champions from across the nation. Membership is open to Elevate Leads with a premium services partnership.
If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use discount code FALL23 for a 15% discount!
Sign Up for a Consultation (https://perts.net/consultation)


** Secure Federal or State Dollars to Fund Your Elevate CoP💰
------------------------------------------------------------
Federal and state funds are sometimes earmarked for programs that meet specific “tiers of evidence.” We’ve put together a guide to help education leaders secure those funds by citing the evidence tier relevant to their Elevate implementation.
Review the ESSA Evidence Tiers for Elevate (https://docs.google.com/document/d/1G8nZGAumUIr1BcGWtrHaPvT4p00jznLvVv2hgKJ8OTc/preview)


** Latest Updates for 2023-2024
------------------------------------------------------------
Thanks to your valuable feedback and insights from the latest research, we have made some big updates to make our programs easier and more impactful, including a new archive feature to view last year's Elevate and Ascend reports that will be available by September 30.
Review Elevate Updates for 2023-24 (https://elevate-support.perts.net/support/solutions/articles/67000723611-what-enhancements-were-made-to-elevate-for-2023-24-)
Review Ascend Updates for 2023-24 (https://ascend-support.perts.net/support/solutions/articles/67000723612-what-enhancements-were-made-to-ascend-for-2023-24-)


** Join Us in Atlanta for the SEL Exchange!
------------------------------------------------------------
PERTS has been chosen as a featured speaker at the SEL Exchange 2023, hosted by the Collaborative for Academic, Social, and Emotional Learning (CASEL)! We cordially invite you to join us for an engaging afternoon of conversation as we delve into experiences and insights from the Elevate Network that have empowered students to cultivate robust academic, social, and emotional skills.
Register for the CASEL SEL Exchange 2023 (https://selexchange.casel.org/2023-registration/)


** Implementation Tips
------------------------------------------------------------
* Gain some insight and inspiration (https://elevate-support.perts.net/support/solutions/articles/67000713395-how-can-i-prepare-teachers-to-implement-elevate-) from individuals who have supported teachers in implementation.
* Maximize student survey participation with these best practices (https://perts.freshdesk.com/en/support/solutions/articles/67000441438-how-do-i-maximize-student-participation-in-ascend-elevate-) !
* Review participation rates & survey fidelity responses with our CoP protocols (https://perts.freshdesk.com/support/solutions/articles/67000676394-community-of-practice-meeting-protocols) .


** Improving Student Experience in the College Classroom
------------------------------------------------------------
In this powerful webinar, faculty and researchers describe insights and reflections from LEARN (the Learning for Equity Ascend Research Network). LEARN convened faculty from multiple colleges as they used Ascend to improve the quality and equity of their students’ classroom experiences.
https://ascend-support.perts.net/support/solutions/articles/67000723457-lessons-from-the-learn-network-webinar-may-2023
“
What I've really come to value about [PERTS] is that it shows me the difference between my intent and my impact and has provided me with tools to match those better.

Dr. Sushilla Knottenbelt, Director & Senior Lecturer
University of New Mexico
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=c3d5069a39&c=316caa3e4a)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=c3d5069a39&c=316caa3e4a)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-09-21 21:30 UTC, merged

2023-10-24 20:03 UTC, rumenPERTS commented
October 2023
PERTS Newsletter


** No Tricks Here, Only Treats!
------------------------------------------------------------
We have some spooktacular updates from this October!

We’re pleased to share that archived Elevate & Ascend reports from the 2022-23 school year are now accessible. We also share an Elevate superstar’s recommendations for implementing student surveys, recently published in Edutopia. Other goodies include key implementation tips for a successful Elevate & Ascend baseline cycle, how to catch up with PERTS at upcoming conferences, and a scary good discount!


** What's New in Elevate & Ascend?
------------------------------------------------------------
By popular request, reports from 2022-23 can now be accessed! Learn how to access last school year’s reports by clicking the article below.
Learn How to Access Your Report Archive (https://perts.freshdesk.com/support/solutions/articles/67000724532)


** Edutopia: 6 Steps for Implementing Student Surveys
------------------------------------------------------------
A screenshot of the article from Edutopia's website. Titled "6 Steps for Implementing Student Surveys." There is a teacher demonstrating on a markerboard to a group of young adolescent students in a classroom environment.
In this article, high school teacher and Elevate Superstar, Shannon Feineis, explains how she partners with students to improve classroom learning conditions and student engagement.

Using Elevate, Shannon’s classroom community scores went from 78 percent to an impressive 96 percent, in addition to a remarkable increase in average test scores from 77 percent to 91 percent!
Read Shannon’s Edutopia Article (https://www.edutopia.org/article/implementing-student-surveys)


** Implementation Tips
------------------------------------------------------------

If you’re just getting started with Elevate or Ascend, be sure to communicate intentionally to students about the survey’s purpose. Research (http://perts.net/research/fidelity-predicts-improvement) shows that learning conditions improve significantly more when communication fidelity is high.
* Aim for at least 80% survey participation (https://perts.freshdesk.com/support/solutions/articles/67000441438-how-do-i-increase-survey-participation-and-buy-in-) https://perts.freshdesk.com/support/solutions/articles/67000441438-how-do-i-increase-survey-participation-and-buy-in-with your students.
* Strive to reach at least 80% communication fidelity (https://perts.freshdesk.com/support/solutions/articles/67000671408-how-to-use-communication-fidelity) across all classes.


** Join Us in Atlanta for the SEL Exchange!
------------------------------------------------------------
A promotional banner with two headshots of the two ladies (Lilia Diaz de Lewis and Sarah Gripshover) who will be presenting at the publicized event. This presentation takes place on November 8 from 1-2:30p ET at the Omni Center in Atlanta, GA.
The 2023 SEL Exchange is just around the corner, and PERTS has been chosen as a featured speaker! Please join us for an afternoon where we share experiences and insights from teachers in the Elevate Network — teachers who helped their students develop strong academic, social, and emotional skills. Hope to see you there!


** San Ramon Valley to Present at the 2024 NCE Conference!
------------------------------------------------------------

Congratulations to our partners at San Ramon Valley USD who have been selected  to present at the National Conference on Education, hosted by the American Association of School Administrators (AASA)! Their presentation, titled Promoting School Connectedness through Elevating Student Voice, will touch on how they have used Elevate to effectively measure student voice and school connectedness.
The conference will be held between February 15–17, 2024 at the San Diego Convention Center. Early registration ends on October 31!
Register for the 2024 National Conference on Education (https://reg.cmrus.com/aasa2024)


** CAP Webinar: Learning from Our Students’ Experiences to Create Classroom Cultures that Promote Equity
------------------------------------------------------------
https://ascend-support.perts.net/support/solutions/articles/67000723457-lessons-from-the-learn-network-webinar-may-2023
Join us for a conversation about the Ascend professional development model and new research into its use in California community colleges. Faculty work together in Ascend communities of practice to learn evidence-based practices and to test the impact of those practices in their own classrooms. The webinar will take place Friday, October 27 from 1-2p PT.
Register for the CAP Webinar (https://accelerationproject.org/event/fall-2023-webinars-teaching-matters-for-equity/)


** “Eerie-resistible” Savings This October!
------------------------------------------------------------
If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use the discount code TREAT2023 when you schedule a consultation and receive a 20% discount!
Sign Up for a Consultation (https://perts.net/consultation)
“
As we ask teachers to create spaces that honor the humanity of young people, we have to create those same spaces for teachers to do that work.

Jessica Bunzol, Transformation Coach
Network for College Success
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=6dd393b59f)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=6dd393b59f)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-10-24 20:04 UTC, rumenPERTS commented
October 2023
PERTS Newsletter


** No Tricks Here, Only Treats!
------------------------------------------------------------
We have some spooktacular updates from this October!

We’re pleased to share that archived Elevate & Ascend reports from the 2022-23 school year are now accessible. We also share an Elevate superstar’s recommendations for implementing student surveys, recently published in Edutopia. Other goodies include key implementation tips for a successful Elevate & Ascend baseline cycle, how to catch up with PERTS at upcoming conferences, and a scary good discount!


** What's New in Elevate & Ascend?
------------------------------------------------------------
By popular request, reports from 2022-23 can now be accessed! Learn how to access last school year’s reports by clicking the article below.
Learn How to Access Your Report Archive (https://perts.freshdesk.com/support/solutions/articles/67000724532)


** Edutopia: 6 Steps for Implementing Student Surveys
------------------------------------------------------------
A screenshot of the article from Edutopia's website. Titled "6 Steps for Implementing Student Surveys." There is a teacher demonstrating on a markerboard to a group of young adolescent students in a classroom environment.
In this article, high school teacher and Elevate Superstar, Shannon Feineis, explains how she partners with students to improve classroom learning conditions and student engagement.

Using Elevate, Shannon’s classroom community scores went from 78 percent to an impressive 96 percent, in addition to a remarkable increase in average test scores from 77 percent to 91 percent!
Read Shannon’s Edutopia Article (https://www.edutopia.org/article/implementing-student-surveys)


** Implementation Tips
------------------------------------------------------------

If you’re just getting started with Elevate or Ascend, be sure to communicate intentionally to students about the survey’s purpose. Research (http://perts.net/research/fidelity-predicts-improvement) shows that learning conditions improve significantly more when communication fidelity is high.
* Aim for at least 80% survey participation (https://perts.freshdesk.com/support/solutions/articles/67000441438-how-do-i-increase-survey-participation-and-buy-in-) https://perts.freshdesk.com/support/solutions/articles/67000441438-how-do-i-increase-survey-participation-and-buy-in-with your students.
* Strive to reach at least 80% communication fidelity (https://perts.freshdesk.com/support/solutions/articles/67000671408-how-to-use-communication-fidelity) across all classes.


** Join Us in Atlanta for the SEL Exchange!
------------------------------------------------------------
A promotional banner with two headshots of the two ladies (Lilia Diaz de Lewis and Sarah Gripshover) who will be presenting at the publicized event. This presentation takes place on November 8 from 1-2:30p ET at the Omni Center in Atlanta, GA.
The 2023 SEL Exchange is just around the corner, and PERTS has been chosen as a featured speaker! Please join us for an afternoon where we share experiences and insights from teachers in the Elevate Network — teachers who helped their students develop strong academic, social, and emotional skills. Hope to see you there!


** San Ramon Valley to Present at the 2024 NCE Conference!
------------------------------------------------------------

Congratulations to our partners at San Ramon Valley USD who have been selected  to present at the National Conference on Education, hosted by the American Association of School Administrators (AASA)! Their presentation, titled Promoting School Connectedness through Elevating Student Voice, will touch on how they have used Elevate to effectively measure student voice and school connectedness.
The conference will be held between February 15–17, 2024 at the San Diego Convention Center. Early registration ends on October 31!
Register for the 2024 National Conference on Education (https://reg.cmrus.com/aasa2024)


** CAP Webinar: Learning from Our Students’ Experiences to Create Classroom Cultures that Promote Equity
------------------------------------------------------------
https://ascend-support.perts.net/support/solutions/articles/67000723457-lessons-from-the-learn-network-webinar-may-2023
Join us for a conversation about the Ascend professional development model and new research into its use in California community colleges. Faculty work together in Ascend communities of practice to learn evidence-based practices and to test the impact of those practices in their own classrooms. The webinar will take place Friday, October 27 from 1-2p PT.
Register for the CAP Webinar (https://accelerationproject.org/event/fall-2023-webinars-teaching-matters-for-equity/)


** “Eerie-resistible” Savings This October!
------------------------------------------------------------
If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use the discount code TREAT2023 when you schedule a consultation and receive a 20% discount!
Sign Up for a Consultation (https://perts.net/consultation)
“
As we ask teachers to create spaces that honor the humanity of young people, we have to create those same spaces for teachers to do that work.

Jessica Bunzol, Transformation Coach
Network for College Success
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=6dd393b59f)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=6dd393b59f)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-10-24 20:04 UTC, rumenPERTS commented
October 2023
PERTS Newsletter


** No Tricks Here, Only Treats!
------------------------------------------------------------
We have some spooktacular updates from this October!

We’re pleased to share that archived Elevate & Ascend reports from the 2022-23 school year are now accessible. We also share an Elevate superstar’s recommendations for implementing student surveys, recently published in Edutopia. Other goodies include key implementation tips for a successful Elevate & Ascend baseline cycle, how to catch up with PERTS at upcoming conferences, and a scary good discount!


** What's New in Elevate & Ascend?
------------------------------------------------------------
By popular request, reports from 2022-23 can now be accessed! Learn how to access last school year’s reports by clicking the article below.
Learn How to Access Your Report Archive (https://perts.freshdesk.com/support/solutions/articles/67000724532)


** Edutopia: 6 Steps for Implementing Student Surveys
------------------------------------------------------------
A screenshot of the article from Edutopia's website. Titled "6 Steps for Implementing Student Surveys." There is a teacher demonstrating on a markerboard to a group of young adolescent students in a classroom environment.
In this article, high school teacher and Elevate Superstar, Shannon Feineis, explains how she partners with students to improve classroom learning conditions and student engagement.

Using Elevate, Shannon’s classroom community scores went from 78 percent to an impressive 96 percent, in addition to a remarkable increase in average test scores from 77 percent to 91 percent!
Read Shannon’s Edutopia Article (https://www.edutopia.org/article/implementing-student-surveys)


** Implementation Tips
------------------------------------------------------------

If you’re just getting started with Elevate or Ascend, be sure to communicate intentionally to students about the survey’s purpose. Research (http://perts.net/research/fidelity-predicts-improvement) shows that learning conditions improve significantly more when communication fidelity is high.
* Aim for at least 80% survey participation (https://perts.freshdesk.com/support/solutions/articles/67000441438-how-do-i-increase-survey-participation-and-buy-in-) https://perts.freshdesk.com/support/solutions/articles/67000441438-how-do-i-increase-survey-participation-and-buy-in-with your students.
* Strive to reach at least 80% communication fidelity (https://perts.freshdesk.com/support/solutions/articles/67000671408-how-to-use-communication-fidelity) across all classes.


** Join Us in Atlanta for the SEL Exchange!
------------------------------------------------------------
A promotional banner with two headshots of the two ladies (Lilia Diaz de Lewis and Sarah Gripshover) who will be presenting at the publicized event. This presentation takes place on November 8 from 1-2:30p ET at the Omni Center in Atlanta, GA.
The 2023 SEL Exchange is just around the corner, and PERTS has been chosen as a featured speaker! Please join us for an afternoon where we share experiences and insights from teachers in the Elevate Network — teachers who helped their students develop strong academic, social, and emotional skills. Hope to see you there!


** San Ramon Valley to Present at the 2024 NCE Conference!
------------------------------------------------------------

Congratulations to our partners at San Ramon Valley USD who have been selected  to present at the National Conference on Education, hosted by the American Association of School Administrators (AASA)! Their presentation, titled Promoting School Connectedness through Elevating Student Voice, will touch on how they have used Elevate to effectively measure student voice and school connectedness.
The conference will be held between February 15–17, 2024 at the San Diego Convention Center. Early registration ends on October 31!
Register for the 2024 National Conference on Education (https://reg.cmrus.com/aasa2024)


** CAP Webinar: Learning from Our Students’ Experiences to Create Classroom Cultures that Promote Equity
------------------------------------------------------------
https://ascend-support.perts.net/support/solutions/articles/67000723457-lessons-from-the-learn-network-webinar-may-2023
Join us for a conversation about the Ascend professional development model and new research into its use in California community colleges. Faculty work together in Ascend communities of practice to learn evidence-based practices and to test the impact of those practices in their own classrooms. The webinar will take place Friday, October 27 from 1-2p PT.
Register for the CAP Webinar (https://accelerationproject.org/event/fall-2023-webinars-teaching-matters-for-equity/)


** “Eerie-resistible” Savings This October!
------------------------------------------------------------
If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use the discount code TREAT2023 when you schedule a consultation and receive a 20% discount!
Sign Up for a Consultation (https://perts.net/consultation)
“
As we ask teachers to create spaces that honor the humanity of young people, we have to create those same spaces for teachers to do that work.

Jessica Bunzol, Transformation Coach
Network for College Success
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=6dd393b59f)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=6dd393b59f)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-10-24 20:04 UTC, rumenPERTS commented
October 2023
PERTS Newsletter


** No Tricks Here, Only Treats!
------------------------------------------------------------
We have some spooktacular updates from this October!

We’re pleased to share that archived Elevate & Ascend reports from the 2022-23 school year are now accessible. We also share an Elevate superstar’s recommendations for implementing student surveys, recently published in Edutopia. Other goodies include key implementation tips for a successful Elevate & Ascend baseline cycle, how to catch up with PERTS at upcoming conferences, and a scary good discount!


** What's New in Elevate & Ascend?
------------------------------------------------------------
By popular request, reports from 2022-23 can now be accessed! Learn how to access last school year’s reports by clicking the article below.
Learn How to Access Your Report Archive (https://perts.freshdesk.com/support/solutions/articles/67000724532)


** Edutopia: 6 Steps for Implementing Student Surveys
------------------------------------------------------------
A screenshot of the article from Edutopia's website. Titled "6 Steps for Implementing Student Surveys." There is a teacher demonstrating on a markerboard to a group of young adolescent students in a classroom environment.
In this article, high school teacher and Elevate Superstar, Shannon Feineis, explains how she partners with students to improve classroom learning conditions and student engagement.

Using Elevate, Shannon’s classroom community scores went from 78 percent to an impressive 96 percent, in addition to a remarkable increase in average test scores from 77 percent to 91 percent!
Read Shannon’s Edutopia Article (https://www.edutopia.org/article/implementing-student-surveys)


** Implementation Tips
------------------------------------------------------------

If you’re just getting started with Elevate or Ascend, be sure to communicate intentionally to students about the survey’s purpose. Research (http://perts.net/research/fidelity-predicts-improvement) shows that learning conditions improve significantly more when communication fidelity is high.
* Aim for at least 80% survey participation (https://perts.freshdesk.com/support/solutions/articles/67000441438-how-do-i-increase-survey-participation-and-buy-in-) https://perts.freshdesk.com/support/solutions/articles/67000441438-how-do-i-increase-survey-participation-and-buy-in-with your students.
* Strive to reach at least 80% communication fidelity (https://perts.freshdesk.com/support/solutions/articles/67000671408-how-to-use-communication-fidelity) across all classes.


** Join Us in Atlanta for the SEL Exchange!
------------------------------------------------------------
A promotional banner with two headshots of the two ladies (Lilia Diaz de Lewis and Sarah Gripshover) who will be presenting at the publicized event. This presentation takes place on November 8 from 1-2:30p ET at the Omni Center in Atlanta, GA.
The 2023 SEL Exchange is just around the corner, and PERTS has been chosen as a featured speaker! Please join us for an afternoon where we share experiences and insights from teachers in the Elevate Network — teachers who helped their students develop strong academic, social, and emotional skills. Hope to see you there!


** San Ramon Valley to Present at the 2024 NCE Conference!
------------------------------------------------------------

Congratulations to our partners at San Ramon Valley USD who have been selected  to present at the National Conference on Education, hosted by the American Association of School Administrators (AASA)! Their presentation, titled Promoting School Connectedness through Elevating Student Voice, will touch on how they have used Elevate to effectively measure student voice and school connectedness.
The conference will be held between February 15–17, 2024 at the San Diego Convention Center. Early registration ends on October 31!
Register for the 2024 National Conference on Education (https://reg.cmrus.com/aasa2024)


** CAP Webinar: Learning from Our Students’ Experiences to Create Classroom Cultures that Promote Equity
------------------------------------------------------------
https://ascend-support.perts.net/support/solutions/articles/67000723457-lessons-from-the-learn-network-webinar-may-2023
Join us for a conversation about the Ascend professional development model and new research into its use in California community colleges. Faculty work together in Ascend communities of practice to learn evidence-based practices and to test the impact of those practices in their own classrooms. The webinar will take place Friday, October 27 from 1-2p PT.
Register for the CAP Webinar (https://accelerationproject.org/event/fall-2023-webinars-teaching-matters-for-equity/)


** “Eerie-resistible” Savings This October!
------------------------------------------------------------
If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use the discount code TREAT2023 when you schedule a consultation and receive a 20% discount!
Sign Up for a Consultation (https://perts.net/consultation)
“
As we ask teachers to create spaces that honor the humanity of young people, we have to create those same spaces for teachers to do that work.

Jessica Bunzol, Transformation Coach
Network for College Success
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=8af4b6e57d&c=6dd393b59f)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=8af4b6e57d&c=6dd393b59f)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-10-24 20:04 UTC, rumenPERTS commented
October 2023
PERTS Newsletter


** No Tricks Here, Only Treats!
------------------------------------------------------------
We have some spooktacular updates from this October!

We’re pleased to share that archived Elevate & Ascend reports from the 2022-23 school year are now accessible. We also share an Elevate superstar’s recommendations for implementing student surveys, recently published in Edutopia. Other goodies include key implementation tips for a successful Elevate & Ascend baseline cycle, how to catch up with PERTS at upcoming conferences, and a scary good discount!


** What's New in Elevate & Ascend?
------------------------------------------------------------
By popular request, reports from 2022-23 can now be accessed! Learn how to access last school year’s reports by clicking the article below.
Learn How to Access Your Report Archive (https://perts.freshdesk.com/support/solutions/articles/67000724532)


** Edutopia: 6 Steps for Implementing Student Surveys
------------------------------------------------------------
A screenshot of the article from Edutopia's website. Titled "6 Steps for Implementing Student Surveys." There is a teacher demonstrating on a markerboard to a group of young adolescent students in a classroom environment.
In this article, high school teacher and Elevate Superstar, Shannon Feineis, explains how she partners with students to improve classroom learning conditions and student engagement.

Using Elevate, Shannon’s classroom community scores went from 78 percent to an impressive 96 percent, in addition to a remarkable increase in average test scores from 77 percent to 91 percent!
Read Shannon’s Edutopia Article (https://www.edutopia.org/article/implementing-student-surveys)


** Implementation Tips
------------------------------------------------------------

If you’re just getting started with Elevate or Ascend, be sure to communicate intentionally to students about the survey’s purpose. Research (http://perts.net/research/fidelity-predicts-improvement) shows that learning conditions improve significantly more when communication fidelity is high.
* Aim for at least 80% survey participation (https://perts.freshdesk.com/support/solutions/articles/67000441438-how-do-i-increase-survey-participation-and-buy-in-) https://perts.freshdesk.com/support/solutions/articles/67000441438-how-do-i-increase-survey-participation-and-buy-in-with your students.
* Strive to reach at least 80% communication fidelity (https://perts.freshdesk.com/support/solutions/articles/67000671408-how-to-use-communication-fidelity) across all classes.


** Join Us in Atlanta for the SEL Exchange!
------------------------------------------------------------
A promotional banner with two headshots of the two ladies (Lilia Diaz de Lewis and Sarah Gripshover) who will be presenting at the publicized event. This presentation takes place on November 8 from 1-2:30p ET at the Omni Center in Atlanta, GA.
The 2023 SEL Exchange is just around the corner, and PERTS has been chosen as a featured speaker! Please join us for an afternoon where we share experiences and insights from teachers in the Elevate Network — teachers who helped their students develop strong academic, social, and emotional skills. Hope to see you there!


** San Ramon Valley to Present at the 2024 NCE Conference!
------------------------------------------------------------

Congratulations to our partners at San Ramon Valley USD who have been selected  to present at the National Conference on Education, hosted by the American Association of School Administrators (AASA)! Their presentation, titled Promoting School Connectedness through Elevating Student Voice, will touch on how they have used Elevate to effectively measure student voice and school connectedness.
The conference will be held between February 15–17, 2024 at the San Diego Convention Center. Early registration ends on October 31!
Register for the 2024 National Conference on Education (https://reg.cmrus.com/aasa2024)


** CAP Webinar: Learning from Our Students’ Experiences to Create Classroom Cultures that Promote Equity
------------------------------------------------------------
https://ascend-support.perts.net/support/solutions/articles/67000723457-lessons-from-the-learn-network-webinar-may-2023
Join us for a conversation about the Ascend professional development model and new research into its use in California community colleges. Faculty work together in Ascend communities of practice to learn evidence-based practices and to test the impact of those practices in their own classrooms. The webinar will take place Friday, October 27 from 1-2p PT.
Register for the CAP Webinar (https://accelerationproject.org/event/fall-2023-webinars-teaching-matters-for-equity/)


** “Eerie-resistible” Savings This October!
------------------------------------------------------------
If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use the discount code TREAT2023 when you schedule a consultation and receive a 20% discount!
Sign Up for a Consultation (https://perts.net/consultation)
“
As we ask teachers to create spaces that honor the humanity of young people, we have to create those same spaces for teachers to do that work.

Jessica Bunzol, Transformation Coach
Network for College Success
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=6dd393b59f)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=6dd393b59f)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-10-24 20:04 UTC, rumenPERTS commented
October 2023
PERTS Newsletter


** No Tricks Here, Only Treats!
------------------------------------------------------------
We have some spooktacular updates from this October!

We’re pleased to share that archived Elevate & Ascend reports from the 2022-23 school year are now accessible. We also share an Elevate superstar’s recommendations for implementing student surveys, recently published in Edutopia. Other goodies include key implementation tips for a successful Elevate & Ascend baseline cycle, how to catch up with PERTS at upcoming conferences, and a scary good discount!


** What's New in Elevate & Ascend?
------------------------------------------------------------
By popular request, reports from 2022-23 can now be accessed! Learn how to access last school year’s reports by clicking the article below.
Learn How to Access Your Report Archive (https://perts.freshdesk.com/support/solutions/articles/67000724532)


** Edutopia: 6 Steps for Implementing Student Surveys
------------------------------------------------------------
A screenshot of the article from Edutopia's website. Titled "6 Steps for Implementing Student Surveys." There is a teacher demonstrating on a markerboard to a group of young adolescent students in a classroom environment.
In this article, high school teacher and Elevate Superstar, Shannon Feineis, explains how she partners with students to improve classroom learning conditions and student engagement.

Using Elevate, Shannon’s classroom community scores went from 78 percent to an impressive 96 percent, in addition to a remarkable increase in average test scores from 77 percent to 91 percent!
Read Shannon’s Edutopia Article (https://www.edutopia.org/article/implementing-student-surveys)


** Implementation Tips
------------------------------------------------------------

If you’re just getting started with Elevate or Ascend, be sure to communicate intentionally to students about the survey’s purpose. Research (http://perts.net/research/fidelity-predicts-improvement) shows that learning conditions improve significantly more when communication fidelity is high.
* Aim for at least 80% survey participation (https://perts.freshdesk.com/support/solutions/articles/67000441438-how-do-i-increase-survey-participation-and-buy-in-) https://perts.freshdesk.com/support/solutions/articles/67000441438-how-do-i-increase-survey-participation-and-buy-in-with your students.
* Strive to reach at least 80% communication fidelity (https://perts.freshdesk.com/support/solutions/articles/67000671408-how-to-use-communication-fidelity) across all classes.


** Join Us in Atlanta for the SEL Exchange!
------------------------------------------------------------
A promotional banner with two headshots of the two ladies (Lilia Diaz de Lewis and Sarah Gripshover) who will be presenting at the publicized event. This presentation takes place on November 8 from 1-2:30p ET at the Omni Center in Atlanta, GA.
The 2023 SEL Exchange is just around the corner, and PERTS has been chosen as a featured speaker! Please join us for an afternoon where we share experiences and insights from teachers in the Elevate Network — teachers who helped their students develop strong academic, social, and emotional skills. Hope to see you there!


** San Ramon Valley to Present at the 2024 NCE Conference!
------------------------------------------------------------

Congratulations to our partners at San Ramon Valley USD who have been selected  to present at the National Conference on Education, hosted by the American Association of School Administrators (AASA)! Their presentation, titled Promoting School Connectedness through Elevating Student Voice, will touch on how they have used Elevate to effectively measure student voice and school connectedness.
The conference will be held between February 15–17, 2024 at the San Diego Convention Center. Early registration ends on October 31!
Register for the 2024 National Conference on Education (https://reg.cmrus.com/aasa2024)


** CAP Webinar: Learning from Our Students’ Experiences to Create Classroom Cultures that Promote Equity
------------------------------------------------------------
https://ascend-support.perts.net/support/solutions/articles/67000723457-lessons-from-the-learn-network-webinar-may-2023
Join us for a conversation about the Ascend professional development model and new research into its use in California community colleges. Faculty work together in Ascend communities of practice to learn evidence-based practices and to test the impact of those practices in their own classrooms. The webinar will take place Friday, October 27 from 1-2p PT.
Register for the CAP Webinar (https://accelerationproject.org/event/fall-2023-webinars-teaching-matters-for-equity/)


** “Eerie-resistible” Savings This October!
------------------------------------------------------------
If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use the discount code TREAT2023 when you schedule a consultation and receive a 20% discount!
Sign Up for a Consultation (https://perts.net/consultation)
“
As we ask teachers to create spaces that honor the humanity of young people, we have to create those same spaces for teachers to do that work.

Jessica Bunzol, Transformation Coach
Network for College Success
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=9dba3d787d&c=6dd393b59f)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=9dba3d787d&c=6dd393b59f)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-10-24 20:05 UTC, rumenPERTS commented
October 2023
PERTS Newsletter


** No Tricks Here, Only Treats!
------------------------------------------------------------
We have some spooktacular updates from this October!

We’re pleased to share that archived Elevate & Ascend reports from the 2022-23 school year are now accessible. We also share an Elevate superstar’s recommendations for implementing student surveys, recently published in Edutopia. Other goodies include key implementation tips for a successful Elevate & Ascend baseline cycle, how to catch up with PERTS at upcoming conferences, and a scary good discount!


** What's New in Elevate & Ascend?
------------------------------------------------------------
By popular request, reports from 2022-23 can now be accessed! Learn how to access last school year’s reports by clicking the article below.
Learn How to Access Your Report Archive (https://perts.freshdesk.com/support/solutions/articles/67000724532)


** Edutopia: 6 Steps for Implementing Student Surveys
------------------------------------------------------------
A screenshot of the article from Edutopia's website. Titled "6 Steps for Implementing Student Surveys." There is a teacher demonstrating on a markerboard to a group of young adolescent students in a classroom environment.
In this article, high school teacher and Elevate Superstar, Shannon Feineis, explains how she partners with students to improve classroom learning conditions and student engagement.

Using Elevate, Shannon’s classroom community scores went from 78 percent to an impressive 96 percent, in addition to a remarkable increase in average test scores from 77 percent to 91 percent!
Read Shannon’s Edutopia Article (https://www.edutopia.org/article/implementing-student-surveys)


** Implementation Tips
------------------------------------------------------------

If you’re just getting started with Elevate or Ascend, be sure to communicate intentionally to students about the survey’s purpose. Research (http://perts.net/research/fidelity-predicts-improvement) shows that learning conditions improve significantly more when communication fidelity is high.
* Aim for at least 80% survey participation (https://perts.freshdesk.com/support/solutions/articles/67000441438-how-do-i-increase-survey-participation-and-buy-in-) https://perts.freshdesk.com/support/solutions/articles/67000441438-how-do-i-increase-survey-participation-and-buy-in-with your students.
* Strive to reach at least 80% communication fidelity (https://perts.freshdesk.com/support/solutions/articles/67000671408-how-to-use-communication-fidelity) across all classes.


** Join Us in Atlanta for the SEL Exchange!
------------------------------------------------------------
A promotional banner with two headshots of the two ladies (Lilia Diaz de Lewis and Sarah Gripshover) who will be presenting at the publicized event. This presentation takes place on November 8 from 1-2:30p ET at the Omni Center in Atlanta, GA.
The 2023 SEL Exchange is just around the corner, and PERTS has been chosen as a featured speaker! Please join us for an afternoon where we share experiences and insights from teachers in the Elevate Network — teachers who helped their students develop strong academic, social, and emotional skills. Hope to see you there!


** San Ramon Valley to Present at the 2024 NCE Conference!
------------------------------------------------------------

Congratulations to our partners at San Ramon Valley USD who have been selected  to present at the National Conference on Education, hosted by the American Association of School Administrators (AASA)! Their presentation, titled Promoting School Connectedness through Elevating Student Voice, will touch on how they have used Elevate to effectively measure student voice and school connectedness.
The conference will be held between February 15–17, 2024 at the San Diego Convention Center. Early registration ends on October 31!
Register for the 2024 National Conference on Education (https://reg.cmrus.com/aasa2024)


** CAP Webinar: Learning from Our Students’ Experiences to Create Classroom Cultures that Promote Equity
------------------------------------------------------------
https://ascend-support.perts.net/support/solutions/articles/67000723457-lessons-from-the-learn-network-webinar-may-2023
Join us for a conversation about the Ascend professional development model and new research into its use in California community colleges. Faculty work together in Ascend communities of practice to learn evidence-based practices and to test the impact of those practices in their own classrooms. The webinar will take place Friday, October 27 from 1-2p PT.
Register for the CAP Webinar (https://accelerationproject.org/event/fall-2023-webinars-teaching-matters-for-equity/)


** “Eerie-resistible” Savings This October!
------------------------------------------------------------
If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use the discount code TREAT2023 when you schedule a consultation and receive a 20% discount!
Sign Up for a Consultation (https://perts.net/consultation)
“
As we ask teachers to create spaces that honor the humanity of young people, we have to create those same spaces for teachers to do that work.

Jessica Bunzol, Transformation Coach
Network for College Success
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=6dd393b59f)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=6dd393b59f)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-10-24 20:06 UTC, rumenPERTS commented
October 2023
PERTS Newsletter


** No Tricks Here, Only Treats!
------------------------------------------------------------
We have some spooktacular updates from this October!

We’re pleased to share that archived Elevate & Ascend reports from the 2022-23 school year are now accessible. We also share an Elevate superstar’s recommendations for implementing student surveys, recently published in Edutopia. Other goodies include key implementation tips for a successful Elevate & Ascend baseline cycle, how to catch up with PERTS at upcoming conferences, and a scary good discount!


** What's New in Elevate & Ascend?
------------------------------------------------------------
By popular request, reports from 2022-23 can now be accessed! Learn how to access last school year’s reports by clicking the article below.
Learn How to Access Your Report Archive (https://perts.freshdesk.com/support/solutions/articles/67000724532)


** Edutopia: 6 Steps for Implementing Student Surveys
------------------------------------------------------------
A screenshot of the article from Edutopia's website. Titled "6 Steps for Implementing Student Surveys." There is a teacher demonstrating on a markerboard to a group of young adolescent students in a classroom environment.
In this article, high school teacher and Elevate Superstar, Shannon Feineis, explains how she partners with students to improve classroom learning conditions and student engagement.

Using Elevate, Shannon’s classroom community scores went from 78 percent to an impressive 96 percent, in addition to a remarkable increase in average test scores from 77 percent to 91 percent!
Read Shannon’s Edutopia Article (https://www.edutopia.org/article/implementing-student-surveys)


** Implementation Tips
------------------------------------------------------------

If you’re just getting started with Elevate or Ascend, be sure to communicate intentionally to students about the survey’s purpose. Research (http://perts.net/research/fidelity-predicts-improvement) shows that learning conditions improve significantly more when communication fidelity is high.
* Aim for at least 80% survey participation (https://perts.freshdesk.com/support/solutions/articles/67000441438-how-do-i-increase-survey-participation-and-buy-in-) https://perts.freshdesk.com/support/solutions/articles/67000441438-how-do-i-increase-survey-participation-and-buy-in-with your students.
* Strive to reach at least 80% communication fidelity (https://perts.freshdesk.com/support/solutions/articles/67000671408-how-to-use-communication-fidelity) across all classes.


** Join Us in Atlanta for the SEL Exchange!
------------------------------------------------------------
A promotional banner with two headshots of the two ladies (Lilia Diaz de Lewis and Sarah Gripshover) who will be presenting at the publicized event. This presentation takes place on November 8 from 1-2:30p ET at the Omni Center in Atlanta, GA.
The 2023 SEL Exchange is just around the corner, and PERTS has been chosen as a featured speaker! Please join us for an afternoon where we share experiences and insights from teachers in the Elevate Network — teachers who helped their students develop strong academic, social, and emotional skills. Hope to see you there!


** San Ramon Valley to Present at the 2024 NCE Conference!
------------------------------------------------------------

Congratulations to our partners at San Ramon Valley USD who have been selected  to present at the National Conference on Education, hosted by the American Association of School Administrators (AASA)! Their presentation, titled Promoting School Connectedness through Elevating Student Voice, will touch on how they have used Elevate to effectively measure student voice and school connectedness.
The conference will be held between February 15–17, 2024 at the San Diego Convention Center. Early registration ends on October 31!
Register for the 2024 National Conference on Education (https://reg.cmrus.com/aasa2024)


** CAP Webinar: Learning from Our Students’ Experiences to Create Classroom Cultures that Promote Equity
------------------------------------------------------------
https://ascend-support.perts.net/support/solutions/articles/67000723457-lessons-from-the-learn-network-webinar-may-2023
Join us for a conversation about the Ascend professional development model and new research into its use in California community colleges. Faculty work together in Ascend communities of practice to learn evidence-based practices and to test the impact of those practices in their own classrooms. The webinar will take place Friday, October 27 from 1-2p PT.
Register for the CAP Webinar (https://accelerationproject.org/event/fall-2023-webinars-teaching-matters-for-equity/)


** “Eerie-resistible” Savings This October!
------------------------------------------------------------
If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use the discount code TREAT2023 when you schedule a consultation and receive a 20% discount!
Sign Up for a Consultation (https://perts.net/consultation)
“
As we ask teachers to create spaces that honor the humanity of young people, we have to create those same spaces for teachers to do that work.

Jessica Bunzol, Transformation Coach
Network for College Success
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=6dd393b59f)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=6dd393b59f)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-10-24 20:06 UTC, rumenPERTS commented
October 2023
PERTS Newsletter


** No Tricks Here, Only Treats!
------------------------------------------------------------
We have some spooktacular updates from this October!

We’re pleased to share that archived Elevate & Ascend reports from the 2022-23 school year are now accessible. We also share an Elevate superstar’s recommendations for implementing student surveys, recently published in Edutopia. Other goodies include key implementation tips for a successful Elevate & Ascend baseline cycle, how to catch up with PERTS at upcoming conferences, and a scary good discount!


** What's New in Elevate & Ascend?
------------------------------------------------------------
By popular request, reports from 2022-23 can now be accessed! Learn how to access last school year’s reports by clicking the article below.
Learn How to Access Your Report Archive (https://perts.freshdesk.com/support/solutions/articles/67000724532)


** Edutopia: 6 Steps for Implementing Student Surveys
------------------------------------------------------------
A screenshot of the article from Edutopia's website. Titled "6 Steps for Implementing Student Surveys." There is a teacher demonstrating on a markerboard to a group of young adolescent students in a classroom environment.
In this article, high school teacher and Elevate Superstar, Shannon Feineis, explains how she partners with students to improve classroom learning conditions and student engagement.

Using Elevate, Shannon’s classroom community scores went from 78 percent to an impressive 96 percent, in addition to a remarkable increase in average test scores from 77 percent to 91 percent!
Read Shannon’s Edutopia Article (https://www.edutopia.org/article/implementing-student-surveys)


** Implementation Tips
------------------------------------------------------------

If you’re just getting started with Elevate or Ascend, be sure to communicate intentionally to students about the survey’s purpose. Research (http://perts.net/research/fidelity-predicts-improvement) shows that learning conditions improve significantly more when communication fidelity is high.
* Aim for at least 80% survey participation (https://perts.freshdesk.com/support/solutions/articles/67000441438-how-do-i-increase-survey-participation-and-buy-in-) https://perts.freshdesk.com/support/solutions/articles/67000441438-how-do-i-increase-survey-participation-and-buy-in-with your students.
* Strive to reach at least 80% communication fidelity (https://perts.freshdesk.com/support/solutions/articles/67000671408-how-to-use-communication-fidelity) across all classes.


** Join Us in Atlanta for the SEL Exchange!
------------------------------------------------------------
A promotional banner with two headshots of the two ladies (Lilia Diaz de Lewis and Sarah Gripshover) who will be presenting at the publicized event. This presentation takes place on November 8 from 1-2:30p ET at the Omni Center in Atlanta, GA.
The 2023 SEL Exchange is just around the corner, and PERTS has been chosen as a featured speaker! Please join us for an afternoon where we share experiences and insights from teachers in the Elevate Network — teachers who helped their students develop strong academic, social, and emotional skills. Hope to see you there!


** San Ramon Valley to Present at the 2024 NCE Conference!
------------------------------------------------------------

Congratulations to our partners at San Ramon Valley USD who have been selected  to present at the National Conference on Education, hosted by the American Association of School Administrators (AASA)! Their presentation, titled Promoting School Connectedness through Elevating Student Voice, will touch on how they have used Elevate to effectively measure student voice and school connectedness.
The conference will be held between February 15–17, 2024 at the San Diego Convention Center. Early registration ends on October 31!
Register for the 2024 National Conference on Education (https://reg.cmrus.com/aasa2024)


** CAP Webinar: Learning from Our Students’ Experiences to Create Classroom Cultures that Promote Equity
------------------------------------------------------------
https://ascend-support.perts.net/support/solutions/articles/67000723457-lessons-from-the-learn-network-webinar-may-2023
Join us for a conversation about the Ascend professional development model and new research into its use in California community colleges. Faculty work together in Ascend communities of practice to learn evidence-based practices and to test the impact of those practices in their own classrooms. The webinar will take place Friday, October 27 from 1-2p PT.
Register for the CAP Webinar (https://accelerationproject.org/event/fall-2023-webinars-teaching-matters-for-equity/)


** “Eerie-resistible” Savings This October!
------------------------------------------------------------
If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use the discount code TREAT2023 when you schedule a consultation and receive a 20% discount!
Sign Up for a Consultation (https://perts.net/consultation)
“
As we ask teachers to create spaces that honor the humanity of young people, we have to create those same spaces for teachers to do that work.

Jessica Bunzol, Transformation Coach
Network for College Success
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=c3d5069a39&c=6dd393b59f)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=c3d5069a39&c=6dd393b59f)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-10-27 19:49 UTC, londeree4 commented on R/saturn.R
> +
This documentation was helpful and I was able to connect effectively.

2023-10-27 19:50 UTC, londeree4 reviewed
Approved! I know this is already merged though - just saw you requested it 3 days ago.

2023-11-15 22:28 UTC, rumenPERTS commented
November 2023
PERTS Newsletter
This season, we are filled with a cornucopia of exciting updates! We're delighted to announce an update to our Elevate/Ascend participation dashboards, and we’re happy to report that the California Acceleration Project webinar was a great success! In this update:
* Explore valuable insights on reviewing your first cycle Elevate/Ascend reports
* Discover creative ways to utilize Elevate/Ascend data in your teaching portfolios
* Ready to get started with Elevate/Ascend? Take advantage of our generous discount, our way of expressing gratitude to you.


** Focus on Communication Fidelity!
------------------------------------------------------------
If your report shows that communication fidelity is below 80%, make it your priority to improve it! Research (https://perts.net/research/fidelity-predicts-improvement) shows that high communication fidelity is essential for meaningful growth and is the best predictor of improvement in learning conditions.
Read How to Improve Communication Fidelity (https://perts.freshdesk.com/en/support/solutions/articles/67000671408-how-to-use-communication-fidelity)


** Implementation Tips💡
------------------------------------------------------------

Teachers, as you begin to review your reports, here are some resources and considerations:
* Review how to use your Elevate or Ascend reports (https://perts.freshdesk.com/en/support/solutions/articles/67000676734-how-do-i-use-my-ascend-elevate-report-) as a starting point.
* Engage in a discussion about your survey results (https://perts.freshdesk.com/en/support/solutions/articles/67000695496-how-can-i-debrief-results-with-students-) with your students. This can be a powerful way to show them that you value their feedback, and may also lead to improvements in communication fidelity scores!

Facilitators can support teachers with their data with these tools:
* Use our baseline protocol to review survey results and create a plan for improvement (for Elevate (https://elevate-support.perts.net/support/solutions/articles/67000676394-community-of-practice-meeting-protocols#baseline) or Ascend (https://ascend-support.perts.net/en/support/solutions/articles/67000676395-community-of-practice-meeting-protocols#baseline) ).
* These reflection questions (https://perts.freshdesk.com/en/support/solutions/articles/67000695502-how-can-i-support-instructors-as-they-review-feedback-from-students-) can help facilitators guide teachers towards constructive actions based on their initial reactions to the data.
* Looking for additional meeting protocols? Access them for Elevate (https://elevate-support.perts.net/support/solutions/articles/67000676394-community-of-practice-meeting-protocols) and Ascend (https://ascend-support.perts.net/support/solutions/articles/67000676395-community-of-practice-meeting-protocols) .


** Use Your Data to Show Your Growth!
------------------------------------------------------------

Are you in an evaluation year? Teachers can demonstrate progress toward their professional goals and provide evidence of elevating student voice by integrating Elevate/Ascend data into their teaching portfolios. Use your data to showcase your skills, growth, and impact in the classroom.
Read How to Use Elevate to Strengthen Your Teaching Portfolio (https://perts.net/elevate/teaching-portfolio)
Read How to Use Ascend to Strengthen Your Teaching Portfolio (https://perts.net/ascend/teaching-portfolio)


** CAP Webinar: Learning from Our Students’ Experiences to Create Classroom Cultures that Promote Equity
------------------------------------------------------------
Thank you to everyone who joined us for this webinar hosted by the California Acceleration Project (CAP), featuring Dr. Claudia Escobar, Kathy Wada, and Dr. Norman Lorenz. The presenters discussed Ascend's professional development model and the latest research from its implementation in California community colleges through the Learning for Equity Ascend Research Network (LEARN). They also shared their experiences in studying and cultivating classroom cultures that promote equity.
Read about LEARN and watch the 2023 CAP Webinar (https://ascend-support.perts.net/support/solutions/articles/67000723457)


** What's New in Elevate/Ascend?
------------------------------------------------------------

New participation dashboards are incoming and better than ever! The new "Participation by Class Lead" table provides a survey status for each survey, by teacher. Please note, as with other teacher-level participation data, this table will only be displayed for Community Leads and Network Leads.
Read How to Use the Community Participation Dashboard (https://perts.freshdesk.com/en/support/solutions/articles/67000677400-how-to-use-the-community-participation-dashboard)


** We’re Thankful for You This Season 🍂
------------------------------------------------------------
We’re very grateful for educators like you who are making a difference in the lives of your students. If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use the discount code THANKS23 when you schedule a consultation and receive a bountiful 20% discount!
Schedule a Consultation (https://perts.net/consultation)
“
Asking students exactly what they want is the best way to get them on board with you overall. That is the most powerful thing about the PERTS survey; it lets the students know that I want their feedback and that I will use it to make class better for them.

Anna Stewart, Teacher
Yulee Middle School
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=90d6dd6c82)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=90d6dd6c82)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-11-15 22:28 UTC, rumenPERTS commented
November 2023
PERTS Newsletter
This season, we are filled with a cornucopia of exciting updates! We're delighted to announce an update to our Elevate/Ascend participation dashboards, and we’re happy to report that the California Acceleration Project webinar was a great success! In this update:
* Explore valuable insights on reviewing your first cycle Elevate/Ascend reports
* Discover creative ways to utilize Elevate/Ascend data in your teaching portfolios
* Ready to get started with Elevate/Ascend? Take advantage of our generous discount, our way of expressing gratitude to you.


** Focus on Communication Fidelity!
------------------------------------------------------------
If your report shows that communication fidelity is below 80%, make it your priority to improve it! Research (https://perts.net/research/fidelity-predicts-improvement) shows that high communication fidelity is essential for meaningful growth and is the best predictor of improvement in learning conditions.
Read How to Improve Communication Fidelity (https://perts.freshdesk.com/en/support/solutions/articles/67000671408-how-to-use-communication-fidelity)


** Implementation Tips💡
------------------------------------------------------------

Teachers, as you begin to review your reports, here are some resources and considerations:
* Review how to use your Elevate or Ascend reports (https://perts.freshdesk.com/en/support/solutions/articles/67000676734-how-do-i-use-my-ascend-elevate-report-) as a starting point.
* Engage in a discussion about your survey results (https://perts.freshdesk.com/en/support/solutions/articles/67000695496-how-can-i-debrief-results-with-students-) with your students. This can be a powerful way to show them that you value their feedback, and may also lead to improvements in communication fidelity scores!

Facilitators can support teachers with their data with these tools:
* Use our baseline protocol to review survey results and create a plan for improvement (for Elevate (https://elevate-support.perts.net/support/solutions/articles/67000676394-community-of-practice-meeting-protocols#baseline) or Ascend (https://ascend-support.perts.net/en/support/solutions/articles/67000676395-community-of-practice-meeting-protocols#baseline) ).
* These reflection questions (https://perts.freshdesk.com/en/support/solutions/articles/67000695502-how-can-i-support-instructors-as-they-review-feedback-from-students-) can help facilitators guide teachers towards constructive actions based on their initial reactions to the data.
* Looking for additional meeting protocols? Access them for Elevate (https://elevate-support.perts.net/support/solutions/articles/67000676394-community-of-practice-meeting-protocols) and Ascend (https://ascend-support.perts.net/support/solutions/articles/67000676395-community-of-practice-meeting-protocols) .


** Use Your Data to Show Your Growth!
------------------------------------------------------------

Are you in an evaluation year? Teachers can demonstrate progress toward their professional goals and provide evidence of elevating student voice by integrating Elevate/Ascend data into their teaching portfolios. Use your data to showcase your skills, growth, and impact in the classroom.
Read How to Use Elevate to Strengthen Your Teaching Portfolio (https://perts.net/elevate/teaching-portfolio)
Read How to Use Ascend to Strengthen Your Teaching Portfolio (https://perts.net/ascend/teaching-portfolio)


** CAP Webinar: Learning from Our Students’ Experiences to Create Classroom Cultures that Promote Equity
------------------------------------------------------------
Thank you to everyone who joined us for this webinar hosted by the California Acceleration Project (CAP), featuring Dr. Claudia Escobar, Kathy Wada, and Dr. Norman Lorenz. The presenters discussed Ascend's professional development model and the latest research from its implementation in California community colleges through the Learning for Equity Ascend Research Network (LEARN). They also shared their experiences in studying and cultivating classroom cultures that promote equity.
Read about LEARN and watch the 2023 CAP Webinar (https://ascend-support.perts.net/support/solutions/articles/67000723457)


** What's New in Elevate/Ascend?
------------------------------------------------------------

New participation dashboards are incoming and better than ever! The new "Participation by Class Lead" table provides a survey status for each survey, by teacher. Please note, as with other teacher-level participation data, this table will only be displayed for Community Leads and Network Leads.
Read How to Use the Community Participation Dashboard (https://perts.freshdesk.com/en/support/solutions/articles/67000677400-how-to-use-the-community-participation-dashboard)


** We’re Thankful for You This Season 🍂
------------------------------------------------------------
We’re very grateful for educators like you who are making a difference in the lives of your students. If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use the discount code THANKS23 when you schedule a consultation and receive a bountiful 20% discount!
Schedule a Consultation (https://perts.net/consultation)
“
Asking students exactly what they want is the best way to get them on board with you overall. That is the most powerful thing about the PERTS survey; it lets the students know that I want their feedback and that I will use it to make class better for them.

Anna Stewart, Teacher
Yulee Middle School
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=90d6dd6c82)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=90d6dd6c82)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-11-15 22:28 UTC, rumenPERTS commented
November 2023
PERTS Newsletter
This season, we are filled with a cornucopia of exciting updates! We're delighted to announce an update to our Elevate/Ascend participation dashboards, and we’re happy to report that the California Acceleration Project webinar was a great success! In this update:
* Explore valuable insights on reviewing your first cycle Elevate/Ascend reports
* Discover creative ways to utilize Elevate/Ascend data in your teaching portfolios
* Ready to get started with Elevate/Ascend? Take advantage of our generous discount, our way of expressing gratitude to you.


** Focus on Communication Fidelity!
------------------------------------------------------------
If your report shows that communication fidelity is below 80%, make it your priority to improve it! Research (https://perts.net/research/fidelity-predicts-improvement) shows that high communication fidelity is essential for meaningful growth and is the best predictor of improvement in learning conditions.
Read How to Improve Communication Fidelity (https://perts.freshdesk.com/en/support/solutions/articles/67000671408-how-to-use-communication-fidelity)


** Implementation Tips💡
------------------------------------------------------------

Teachers, as you begin to review your reports, here are some resources and considerations:
* Review how to use your Elevate or Ascend reports (https://perts.freshdesk.com/en/support/solutions/articles/67000676734-how-do-i-use-my-ascend-elevate-report-) as a starting point.
* Engage in a discussion about your survey results (https://perts.freshdesk.com/en/support/solutions/articles/67000695496-how-can-i-debrief-results-with-students-) with your students. This can be a powerful way to show them that you value their feedback, and may also lead to improvements in communication fidelity scores!

Facilitators can support teachers with their data with these tools:
* Use our baseline protocol to review survey results and create a plan for improvement (for Elevate (https://elevate-support.perts.net/support/solutions/articles/67000676394-community-of-practice-meeting-protocols#baseline) or Ascend (https://ascend-support.perts.net/en/support/solutions/articles/67000676395-community-of-practice-meeting-protocols#baseline) ).
* These reflection questions (https://perts.freshdesk.com/en/support/solutions/articles/67000695502-how-can-i-support-instructors-as-they-review-feedback-from-students-) can help facilitators guide teachers towards constructive actions based on their initial reactions to the data.
* Looking for additional meeting protocols? Access them for Elevate (https://elevate-support.perts.net/support/solutions/articles/67000676394-community-of-practice-meeting-protocols) and Ascend (https://ascend-support.perts.net/support/solutions/articles/67000676395-community-of-practice-meeting-protocols) .


** Use Your Data to Show Your Growth!
------------------------------------------------------------

Are you in an evaluation year? Teachers can demonstrate progress toward their professional goals and provide evidence of elevating student voice by integrating Elevate/Ascend data into their teaching portfolios. Use your data to showcase your skills, growth, and impact in the classroom.
Read How to Use Elevate to Strengthen Your Teaching Portfolio (https://perts.net/elevate/teaching-portfolio)
Read How to Use Ascend to Strengthen Your Teaching Portfolio (https://perts.net/ascend/teaching-portfolio)


** CAP Webinar: Learning from Our Students’ Experiences to Create Classroom Cultures that Promote Equity
------------------------------------------------------------
Thank you to everyone who joined us for this webinar hosted by the California Acceleration Project (CAP), featuring Dr. Claudia Escobar, Kathy Wada, and Dr. Norman Lorenz. The presenters discussed Ascend's professional development model and the latest research from its implementation in California community colleges through the Learning for Equity Ascend Research Network (LEARN). They also shared their experiences in studying and cultivating classroom cultures that promote equity.
Read about LEARN and watch the 2023 CAP Webinar (https://ascend-support.perts.net/support/solutions/articles/67000723457)


** What's New in Elevate/Ascend?
------------------------------------------------------------

New participation dashboards are incoming and better than ever! The new "Participation by Class Lead" table provides a survey status for each survey, by teacher. Please note, as with other teacher-level participation data, this table will only be displayed for Community Leads and Network Leads.
Read How to Use the Community Participation Dashboard (https://perts.freshdesk.com/en/support/solutions/articles/67000677400-how-to-use-the-community-participation-dashboard)


** We’re Thankful for You This Season 🍂
------------------------------------------------------------
We’re very grateful for educators like you who are making a difference in the lives of your students. If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use the discount code THANKS23 when you schedule a consultation and receive a bountiful 20% discount!
Schedule a Consultation (https://perts.net/consultation)
“
Asking students exactly what they want is the best way to get them on board with you overall. That is the most powerful thing about the PERTS survey; it lets the students know that I want their feedback and that I will use it to make class better for them.

Anna Stewart, Teacher
Yulee Middle School
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=90d6dd6c82)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=90d6dd6c82)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-11-15 22:28 UTC, rumenPERTS commented
November 2023
PERTS Newsletter
This season, we are filled with a cornucopia of exciting updates! We're delighted to announce an update to our Elevate/Ascend participation dashboards, and we’re happy to report that the California Acceleration Project webinar was a great success! In this update:
* Explore valuable insights on reviewing your first cycle Elevate/Ascend reports
* Discover creative ways to utilize Elevate/Ascend data in your teaching portfolios
* Ready to get started with Elevate/Ascend? Take advantage of our generous discount, our way of expressing gratitude to you.


** Focus on Communication Fidelity!
------------------------------------------------------------
If your report shows that communication fidelity is below 80%, make it your priority to improve it! Research (https://perts.net/research/fidelity-predicts-improvement) shows that high communication fidelity is essential for meaningful growth and is the best predictor of improvement in learning conditions.
Read How to Improve Communication Fidelity (https://perts.freshdesk.com/en/support/solutions/articles/67000671408-how-to-use-communication-fidelity)


** Implementation Tips💡
------------------------------------------------------------

Teachers, as you begin to review your reports, here are some resources and considerations:
* Review how to use your Elevate or Ascend reports (https://perts.freshdesk.com/en/support/solutions/articles/67000676734-how-do-i-use-my-ascend-elevate-report-) as a starting point.
* Engage in a discussion about your survey results (https://perts.freshdesk.com/en/support/solutions/articles/67000695496-how-can-i-debrief-results-with-students-) with your students. This can be a powerful way to show them that you value their feedback, and may also lead to improvements in communication fidelity scores!

Facilitators can support teachers with their data with these tools:
* Use our baseline protocol to review survey results and create a plan for improvement (for Elevate (https://elevate-support.perts.net/support/solutions/articles/67000676394-community-of-practice-meeting-protocols#baseline) or Ascend (https://ascend-support.perts.net/en/support/solutions/articles/67000676395-community-of-practice-meeting-protocols#baseline) ).
* These reflection questions (https://perts.freshdesk.com/en/support/solutions/articles/67000695502-how-can-i-support-instructors-as-they-review-feedback-from-students-) can help facilitators guide teachers towards constructive actions based on their initial reactions to the data.
* Looking for additional meeting protocols? Access them for Elevate (https://elevate-support.perts.net/support/solutions/articles/67000676394-community-of-practice-meeting-protocols) and Ascend (https://ascend-support.perts.net/support/solutions/articles/67000676395-community-of-practice-meeting-protocols) .


** Use Your Data to Show Your Growth!
------------------------------------------------------------

Are you in an evaluation year? Teachers can demonstrate progress toward their professional goals and provide evidence of elevating student voice by integrating Elevate/Ascend data into their teaching portfolios. Use your data to showcase your skills, growth, and impact in the classroom.
Read How to Use Elevate to Strengthen Your Teaching Portfolio (https://perts.net/elevate/teaching-portfolio)
Read How to Use Ascend to Strengthen Your Teaching Portfolio (https://perts.net/ascend/teaching-portfolio)


** CAP Webinar: Learning from Our Students’ Experiences to Create Classroom Cultures that Promote Equity
------------------------------------------------------------
Thank you to everyone who joined us for this webinar hosted by the California Acceleration Project (CAP), featuring Dr. Claudia Escobar, Kathy Wada, and Dr. Norman Lorenz. The presenters discussed Ascend's professional development model and the latest research from its implementation in California community colleges through the Learning for Equity Ascend Research Network (LEARN). They also shared their experiences in studying and cultivating classroom cultures that promote equity.
Read about LEARN and watch the 2023 CAP Webinar (https://ascend-support.perts.net/support/solutions/articles/67000723457)


** What's New in Elevate/Ascend?
------------------------------------------------------------

New participation dashboards are incoming and better than ever! The new "Participation by Class Lead" table provides a survey status for each survey, by teacher. Please note, as with other teacher-level participation data, this table will only be displayed for Community Leads and Network Leads.
Read How to Use the Community Participation Dashboard (https://perts.freshdesk.com/en/support/solutions/articles/67000677400-how-to-use-the-community-participation-dashboard)


** We’re Thankful for You This Season 🍂
------------------------------------------------------------
We’re very grateful for educators like you who are making a difference in the lives of your students. If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use the discount code THANKS23 when you schedule a consultation and receive a bountiful 20% discount!
Schedule a Consultation (https://perts.net/consultation)
“
Asking students exactly what they want is the best way to get them on board with you overall. That is the most powerful thing about the PERTS survey; it lets the students know that I want their feedback and that I will use it to make class better for them.

Anna Stewart, Teacher
Yulee Middle School
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=8af4b6e57d&c=90d6dd6c82)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=8af4b6e57d&c=90d6dd6c82)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-11-15 22:28 UTC, rumenPERTS commented
November 2023
PERTS Newsletter
This season, we are filled with a cornucopia of exciting updates! We're delighted to announce an update to our Elevate/Ascend participation dashboards, and we’re happy to report that the California Acceleration Project webinar was a great success! In this update:
* Explore valuable insights on reviewing your first cycle Elevate/Ascend reports
* Discover creative ways to utilize Elevate/Ascend data in your teaching portfolios
* Ready to get started with Elevate/Ascend? Take advantage of our generous discount, our way of expressing gratitude to you.


** Focus on Communication Fidelity!
------------------------------------------------------------
If your report shows that communication fidelity is below 80%, make it your priority to improve it! Research (https://perts.net/research/fidelity-predicts-improvement) shows that high communication fidelity is essential for meaningful growth and is the best predictor of improvement in learning conditions.
Read How to Improve Communication Fidelity (https://perts.freshdesk.com/en/support/solutions/articles/67000671408-how-to-use-communication-fidelity)


** Implementation Tips💡
------------------------------------------------------------

Teachers, as you begin to review your reports, here are some resources and considerations:
* Review how to use your Elevate or Ascend reports (https://perts.freshdesk.com/en/support/solutions/articles/67000676734-how-do-i-use-my-ascend-elevate-report-) as a starting point.
* Engage in a discussion about your survey results (https://perts.freshdesk.com/en/support/solutions/articles/67000695496-how-can-i-debrief-results-with-students-) with your students. This can be a powerful way to show them that you value their feedback, and may also lead to improvements in communication fidelity scores!

Facilitators can support teachers with their data with these tools:
* Use our baseline protocol to review survey results and create a plan for improvement (for Elevate (https://elevate-support.perts.net/support/solutions/articles/67000676394-community-of-practice-meeting-protocols#baseline) or Ascend (https://ascend-support.perts.net/en/support/solutions/articles/67000676395-community-of-practice-meeting-protocols#baseline) ).
* These reflection questions (https://perts.freshdesk.com/en/support/solutions/articles/67000695502-how-can-i-support-instructors-as-they-review-feedback-from-students-) can help facilitators guide teachers towards constructive actions based on their initial reactions to the data.
* Looking for additional meeting protocols? Access them for Elevate (https://elevate-support.perts.net/support/solutions/articles/67000676394-community-of-practice-meeting-protocols) and Ascend (https://ascend-support.perts.net/support/solutions/articles/67000676395-community-of-practice-meeting-protocols) .


** Use Your Data to Show Your Growth!
------------------------------------------------------------

Are you in an evaluation year? Teachers can demonstrate progress toward their professional goals and provide evidence of elevating student voice by integrating Elevate/Ascend data into their teaching portfolios. Use your data to showcase your skills, growth, and impact in the classroom.
Read How to Use Elevate to Strengthen Your Teaching Portfolio (https://perts.net/elevate/teaching-portfolio)
Read How to Use Ascend to Strengthen Your Teaching Portfolio (https://perts.net/ascend/teaching-portfolio)


** CAP Webinar: Learning from Our Students’ Experiences to Create Classroom Cultures that Promote Equity
------------------------------------------------------------
Thank you to everyone who joined us for this webinar hosted by the California Acceleration Project (CAP), featuring Dr. Claudia Escobar, Kathy Wada, and Dr. Norman Lorenz. The presenters discussed Ascend's professional development model and the latest research from its implementation in California community colleges through the Learning for Equity Ascend Research Network (LEARN). They also shared their experiences in studying and cultivating classroom cultures that promote equity.
Read about LEARN and watch the 2023 CAP Webinar (https://ascend-support.perts.net/support/solutions/articles/67000723457)


** What's New in Elevate/Ascend?
------------------------------------------------------------

New participation dashboards are incoming and better than ever! The new "Participation by Class Lead" table provides a survey status for each survey, by teacher. Please note, as with other teacher-level participation data, this table will only be displayed for Community Leads and Network Leads.
Read How to Use the Community Participation Dashboard (https://perts.freshdesk.com/en/support/solutions/articles/67000677400-how-to-use-the-community-participation-dashboard)


** We’re Thankful for You This Season 🍂
------------------------------------------------------------
We’re very grateful for educators like you who are making a difference in the lives of your students. If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use the discount code THANKS23 when you schedule a consultation and receive a bountiful 20% discount!
Schedule a Consultation (https://perts.net/consultation)
“
Asking students exactly what they want is the best way to get them on board with you overall. That is the most powerful thing about the PERTS survey; it lets the students know that I want their feedback and that I will use it to make class better for them.

Anna Stewart, Teacher
Yulee Middle School
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=90d6dd6c82)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=90d6dd6c82)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-11-15 22:28 UTC, rumenPERTS commented
November 2023
PERTS Newsletter
This season, we are filled with a cornucopia of exciting updates! We're delighted to announce an update to our Elevate/Ascend participation dashboards, and we’re happy to report that the California Acceleration Project webinar was a great success! In this update:
* Explore valuable insights on reviewing your first cycle Elevate/Ascend reports
* Discover creative ways to utilize Elevate/Ascend data in your teaching portfolios
* Ready to get started with Elevate/Ascend? Take advantage of our generous discount, our way of expressing gratitude to you.


** Focus on Communication Fidelity!
------------------------------------------------------------
If your report shows that communication fidelity is below 80%, make it your priority to improve it! Research (https://perts.net/research/fidelity-predicts-improvement) shows that high communication fidelity is essential for meaningful growth and is the best predictor of improvement in learning conditions.
Read How to Improve Communication Fidelity (https://perts.freshdesk.com/en/support/solutions/articles/67000671408-how-to-use-communication-fidelity)


** Implementation Tips💡
------------------------------------------------------------

Teachers, as you begin to review your reports, here are some resources and considerations:
* Review how to use your Elevate or Ascend reports (https://perts.freshdesk.com/en/support/solutions/articles/67000676734-how-do-i-use-my-ascend-elevate-report-) as a starting point.
* Engage in a discussion about your survey results (https://perts.freshdesk.com/en/support/solutions/articles/67000695496-how-can-i-debrief-results-with-students-) with your students. This can be a powerful way to show them that you value their feedback, and may also lead to improvements in communication fidelity scores!

Facilitators can support teachers with their data with these tools:
* Use our baseline protocol to review survey results and create a plan for improvement (for Elevate (https://elevate-support.perts.net/support/solutions/articles/67000676394-community-of-practice-meeting-protocols#baseline) or Ascend (https://ascend-support.perts.net/en/support/solutions/articles/67000676395-community-of-practice-meeting-protocols#baseline) ).
* These reflection questions (https://perts.freshdesk.com/en/support/solutions/articles/67000695502-how-can-i-support-instructors-as-they-review-feedback-from-students-) can help facilitators guide teachers towards constructive actions based on their initial reactions to the data.
* Looking for additional meeting protocols? Access them for Elevate (https://elevate-support.perts.net/support/solutions/articles/67000676394-community-of-practice-meeting-protocols) and Ascend (https://ascend-support.perts.net/support/solutions/articles/67000676395-community-of-practice-meeting-protocols) .


** Use Your Data to Show Your Growth!
------------------------------------------------------------

Are you in an evaluation year? Teachers can demonstrate progress toward their professional goals and provide evidence of elevating student voice by integrating Elevate/Ascend data into their teaching portfolios. Use your data to showcase your skills, growth, and impact in the classroom.
Read How to Use Elevate to Strengthen Your Teaching Portfolio (https://perts.net/elevate/teaching-portfolio)
Read How to Use Ascend to Strengthen Your Teaching Portfolio (https://perts.net/ascend/teaching-portfolio)


** CAP Webinar: Learning from Our Students’ Experiences to Create Classroom Cultures that Promote Equity
------------------------------------------------------------
Thank you to everyone who joined us for this webinar hosted by the California Acceleration Project (CAP), featuring Dr. Claudia Escobar, Kathy Wada, and Dr. Norman Lorenz. The presenters discussed Ascend's professional development model and the latest research from its implementation in California community colleges through the Learning for Equity Ascend Research Network (LEARN). They also shared their experiences in studying and cultivating classroom cultures that promote equity.
Read about LEARN and watch the 2023 CAP Webinar (https://ascend-support.perts.net/support/solutions/articles/67000723457)


** What's New in Elevate/Ascend?
------------------------------------------------------------

New participation dashboards are incoming and better than ever! The new "Participation by Class Lead" table provides a survey status for each survey, by teacher. Please note, as with other teacher-level participation data, this table will only be displayed for Community Leads and Network Leads.
Read How to Use the Community Participation Dashboard (https://perts.freshdesk.com/en/support/solutions/articles/67000677400-how-to-use-the-community-participation-dashboard)


** We’re Thankful for You This Season 🍂
------------------------------------------------------------
We’re very grateful for educators like you who are making a difference in the lives of your students. If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use the discount code THANKS23 when you schedule a consultation and receive a bountiful 20% discount!
Schedule a Consultation (https://perts.net/consultation)
“
Asking students exactly what they want is the best way to get them on board with you overall. That is the most powerful thing about the PERTS survey; it lets the students know that I want their feedback and that I will use it to make class better for them.

Anna Stewart, Teacher
Yulee Middle School
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=9dba3d787d&c=90d6dd6c82)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=9dba3d787d&c=90d6dd6c82)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-11-15 22:28 UTC, rumenPERTS commented
November 2023
PERTS Newsletter
This season, we are filled with a cornucopia of exciting updates! We're delighted to announce an update to our Elevate/Ascend participation dashboards, and we’re happy to report that the California Acceleration Project webinar was a great success! In this update:
* Explore valuable insights on reviewing your first cycle Elevate/Ascend reports
* Discover creative ways to utilize Elevate/Ascend data in your teaching portfolios
* Ready to get started with Elevate/Ascend? Take advantage of our generous discount, our way of expressing gratitude to you.


** Focus on Communication Fidelity!
------------------------------------------------------------
If your report shows that communication fidelity is below 80%, make it your priority to improve it! Research (https://perts.net/research/fidelity-predicts-improvement) shows that high communication fidelity is essential for meaningful growth and is the best predictor of improvement in learning conditions.
Read How to Improve Communication Fidelity (https://perts.freshdesk.com/en/support/solutions/articles/67000671408-how-to-use-communication-fidelity)


** Implementation Tips💡
------------------------------------------------------------

Teachers, as you begin to review your reports, here are some resources and considerations:
* Review how to use your Elevate or Ascend reports (https://perts.freshdesk.com/en/support/solutions/articles/67000676734-how-do-i-use-my-ascend-elevate-report-) as a starting point.
* Engage in a discussion about your survey results (https://perts.freshdesk.com/en/support/solutions/articles/67000695496-how-can-i-debrief-results-with-students-) with your students. This can be a powerful way to show them that you value their feedback, and may also lead to improvements in communication fidelity scores!

Facilitators can support teachers with their data with these tools:
* Use our baseline protocol to review survey results and create a plan for improvement (for Elevate (https://elevate-support.perts.net/support/solutions/articles/67000676394-community-of-practice-meeting-protocols#baseline) or Ascend (https://ascend-support.perts.net/en/support/solutions/articles/67000676395-community-of-practice-meeting-protocols#baseline) ).
* These reflection questions (https://perts.freshdesk.com/en/support/solutions/articles/67000695502-how-can-i-support-instructors-as-they-review-feedback-from-students-) can help facilitators guide teachers towards constructive actions based on their initial reactions to the data.
* Looking for additional meeting protocols? Access them for Elevate (https://elevate-support.perts.net/support/solutions/articles/67000676394-community-of-practice-meeting-protocols) and Ascend (https://ascend-support.perts.net/support/solutions/articles/67000676395-community-of-practice-meeting-protocols) .


** Use Your Data to Show Your Growth!
------------------------------------------------------------

Are you in an evaluation year? Teachers can demonstrate progress toward their professional goals and provide evidence of elevating student voice by integrating Elevate/Ascend data into their teaching portfolios. Use your data to showcase your skills, growth, and impact in the classroom.
Read How to Use Elevate to Strengthen Your Teaching Portfolio (https://perts.net/elevate/teaching-portfolio)
Read How to Use Ascend to Strengthen Your Teaching Portfolio (https://perts.net/ascend/teaching-portfolio)


** CAP Webinar: Learning from Our Students’ Experiences to Create Classroom Cultures that Promote Equity
------------------------------------------------------------
Thank you to everyone who joined us for this webinar hosted by the California Acceleration Project (CAP), featuring Dr. Claudia Escobar, Kathy Wada, and Dr. Norman Lorenz. The presenters discussed Ascend's professional development model and the latest research from its implementation in California community colleges through the Learning for Equity Ascend Research Network (LEARN). They also shared their experiences in studying and cultivating classroom cultures that promote equity.
Read about LEARN and watch the 2023 CAP Webinar (https://ascend-support.perts.net/support/solutions/articles/67000723457)


** What's New in Elevate/Ascend?
------------------------------------------------------------

New participation dashboards are incoming and better than ever! The new "Participation by Class Lead" table provides a survey status for each survey, by teacher. Please note, as with other teacher-level participation data, this table will only be displayed for Community Leads and Network Leads.
Read How to Use the Community Participation Dashboard (https://perts.freshdesk.com/en/support/solutions/articles/67000677400-how-to-use-the-community-participation-dashboard)


** We’re Thankful for You This Season 🍂
------------------------------------------------------------
We’re very grateful for educators like you who are making a difference in the lives of your students. If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use the discount code THANKS23 when you schedule a consultation and receive a bountiful 20% discount!
Schedule a Consultation (https://perts.net/consultation)
“
Asking students exactly what they want is the best way to get them on board with you overall. That is the most powerful thing about the PERTS survey; it lets the students know that I want their feedback and that I will use it to make class better for them.

Anna Stewart, Teacher
Yulee Middle School
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=90d6dd6c82)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=90d6dd6c82)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-11-15 22:28 UTC, rumenPERTS commented
November 2023
PERTS Newsletter
This season, we are filled with a cornucopia of exciting updates! We're delighted to announce an update to our Elevate/Ascend participation dashboards, and we’re happy to report that the California Acceleration Project webinar was a great success! In this update:
* Explore valuable insights on reviewing your first cycle Elevate/Ascend reports
* Discover creative ways to utilize Elevate/Ascend data in your teaching portfolios
* Ready to get started with Elevate/Ascend? Take advantage of our generous discount, our way of expressing gratitude to you.


** Focus on Communication Fidelity!
------------------------------------------------------------
If your report shows that communication fidelity is below 80%, make it your priority to improve it! Research (https://perts.net/research/fidelity-predicts-improvement) shows that high communication fidelity is essential for meaningful growth and is the best predictor of improvement in learning conditions.
Read How to Improve Communication Fidelity (https://perts.freshdesk.com/en/support/solutions/articles/67000671408-how-to-use-communication-fidelity)


** Implementation Tips💡
------------------------------------------------------------

Teachers, as you begin to review your reports, here are some resources and considerations:
* Review how to use your Elevate or Ascend reports (https://perts.freshdesk.com/en/support/solutions/articles/67000676734-how-do-i-use-my-ascend-elevate-report-) as a starting point.
* Engage in a discussion about your survey results (https://perts.freshdesk.com/en/support/solutions/articles/67000695496-how-can-i-debrief-results-with-students-) with your students. This can be a powerful way to show them that you value their feedback, and may also lead to improvements in communication fidelity scores!

Facilitators can support teachers with their data with these tools:
* Use our baseline protocol to review survey results and create a plan for improvement (for Elevate (https://elevate-support.perts.net/support/solutions/articles/67000676394-community-of-practice-meeting-protocols#baseline) or Ascend (https://ascend-support.perts.net/en/support/solutions/articles/67000676395-community-of-practice-meeting-protocols#baseline) ).
* These reflection questions (https://perts.freshdesk.com/en/support/solutions/articles/67000695502-how-can-i-support-instructors-as-they-review-feedback-from-students-) can help facilitators guide teachers towards constructive actions based on their initial reactions to the data.
* Looking for additional meeting protocols? Access them for Elevate (https://elevate-support.perts.net/support/solutions/articles/67000676394-community-of-practice-meeting-protocols) and Ascend (https://ascend-support.perts.net/support/solutions/articles/67000676395-community-of-practice-meeting-protocols) .


** Use Your Data to Show Your Growth!
------------------------------------------------------------

Are you in an evaluation year? Teachers can demonstrate progress toward their professional goals and provide evidence of elevating student voice by integrating Elevate/Ascend data into their teaching portfolios. Use your data to showcase your skills, growth, and impact in the classroom.
Read How to Use Elevate to Strengthen Your Teaching Portfolio (https://perts.net/elevate/teaching-portfolio)
Read How to Use Ascend to Strengthen Your Teaching Portfolio (https://perts.net/ascend/teaching-portfolio)


** CAP Webinar: Learning from Our Students’ Experiences to Create Classroom Cultures that Promote Equity
------------------------------------------------------------
Thank you to everyone who joined us for this webinar hosted by the California Acceleration Project (CAP), featuring Dr. Claudia Escobar, Kathy Wada, and Dr. Norman Lorenz. The presenters discussed Ascend's professional development model and the latest research from its implementation in California community colleges through the Learning for Equity Ascend Research Network (LEARN). They also shared their experiences in studying and cultivating classroom cultures that promote equity.
Read about LEARN and watch the 2023 CAP Webinar (https://ascend-support.perts.net/support/solutions/articles/67000723457)


** What's New in Elevate/Ascend?
------------------------------------------------------------

New participation dashboards are incoming and better than ever! The new "Participation by Class Lead" table provides a survey status for each survey, by teacher. Please note, as with other teacher-level participation data, this table will only be displayed for Community Leads and Network Leads.
Read How to Use the Community Participation Dashboard (https://perts.freshdesk.com/en/support/solutions/articles/67000677400-how-to-use-the-community-participation-dashboard)


** We’re Thankful for You This Season 🍂
------------------------------------------------------------
We’re very grateful for educators like you who are making a difference in the lives of your students. If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use the discount code THANKS23 when you schedule a consultation and receive a bountiful 20% discount!
Schedule a Consultation (https://perts.net/consultation)
“
Asking students exactly what they want is the best way to get them on board with you overall. That is the most powerful thing about the PERTS survey; it lets the students know that I want their feedback and that I will use it to make class better for them.

Anna Stewart, Teacher
Yulee Middle School
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=90d6dd6c82)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=90d6dd6c82)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-11-15 22:28 UTC, rumenPERTS commented
November 2023
PERTS Newsletter
This season, we are filled with a cornucopia of exciting updates! We're delighted to announce an update to our Elevate/Ascend participation dashboards, and we’re happy to report that the California Acceleration Project webinar was a great success! In this update:
* Explore valuable insights on reviewing your first cycle Elevate/Ascend reports
* Discover creative ways to utilize Elevate/Ascend data in your teaching portfolios
* Ready to get started with Elevate/Ascend? Take advantage of our generous discount, our way of expressing gratitude to you.


** Focus on Communication Fidelity!
------------------------------------------------------------
If your report shows that communication fidelity is below 80%, make it your priority to improve it! Research (https://perts.net/research/fidelity-predicts-improvement) shows that high communication fidelity is essential for meaningful growth and is the best predictor of improvement in learning conditions.
Read How to Improve Communication Fidelity (https://perts.freshdesk.com/en/support/solutions/articles/67000671408-how-to-use-communication-fidelity)


** Implementation Tips💡
------------------------------------------------------------

Teachers, as you begin to review your reports, here are some resources and considerations:
* Review how to use your Elevate or Ascend reports (https://perts.freshdesk.com/en/support/solutions/articles/67000676734-how-do-i-use-my-ascend-elevate-report-) as a starting point.
* Engage in a discussion about your survey results (https://perts.freshdesk.com/en/support/solutions/articles/67000695496-how-can-i-debrief-results-with-students-) with your students. This can be a powerful way to show them that you value their feedback, and may also lead to improvements in communication fidelity scores!

Facilitators can support teachers with their data with these tools:
* Use our baseline protocol to review survey results and create a plan for improvement (for Elevate (https://elevate-support.perts.net/support/solutions/articles/67000676394-community-of-practice-meeting-protocols#baseline) or Ascend (https://ascend-support.perts.net/en/support/solutions/articles/67000676395-community-of-practice-meeting-protocols#baseline) ).
* These reflection questions (https://perts.freshdesk.com/en/support/solutions/articles/67000695502-how-can-i-support-instructors-as-they-review-feedback-from-students-) can help facilitators guide teachers towards constructive actions based on their initial reactions to the data.
* Looking for additional meeting protocols? Access them for Elevate (https://elevate-support.perts.net/support/solutions/articles/67000676394-community-of-practice-meeting-protocols) and Ascend (https://ascend-support.perts.net/support/solutions/articles/67000676395-community-of-practice-meeting-protocols) .


** Use Your Data to Show Your Growth!
------------------------------------------------------------

Are you in an evaluation year? Teachers can demonstrate progress toward their professional goals and provide evidence of elevating student voice by integrating Elevate/Ascend data into their teaching portfolios. Use your data to showcase your skills, growth, and impact in the classroom.
Read How to Use Elevate to Strengthen Your Teaching Portfolio (https://perts.net/elevate/teaching-portfolio)
Read How to Use Ascend to Strengthen Your Teaching Portfolio (https://perts.net/ascend/teaching-portfolio)


** CAP Webinar: Learning from Our Students’ Experiences to Create Classroom Cultures that Promote Equity
------------------------------------------------------------
Thank you to everyone who joined us for this webinar hosted by the California Acceleration Project (CAP), featuring Dr. Claudia Escobar, Kathy Wada, and Dr. Norman Lorenz. The presenters discussed Ascend's professional development model and the latest research from its implementation in California community colleges through the Learning for Equity Ascend Research Network (LEARN). They also shared their experiences in studying and cultivating classroom cultures that promote equity.
Read about LEARN and watch the 2023 CAP Webinar (https://ascend-support.perts.net/support/solutions/articles/67000723457)


** What's New in Elevate/Ascend?
------------------------------------------------------------

New participation dashboards are incoming and better than ever! The new "Participation by Class Lead" table provides a survey status for each survey, by teacher. Please note, as with other teacher-level participation data, this table will only be displayed for Community Leads and Network Leads.
Read How to Use the Community Participation Dashboard (https://perts.freshdesk.com/en/support/solutions/articles/67000677400-how-to-use-the-community-participation-dashboard)


** We’re Thankful for You This Season 🍂
------------------------------------------------------------
We’re very grateful for educators like you who are making a difference in the lives of your students. If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use the discount code THANKS23 when you schedule a consultation and receive a bountiful 20% discount!
Schedule a Consultation (https://perts.net/consultation)
“
Asking students exactly what they want is the best way to get them on board with you overall. That is the most powerful thing about the PERTS survey; it lets the students know that I want their feedback and that I will use it to make class better for them.

Anna Stewart, Teacher
Yulee Middle School
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=90d6dd6c82)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=90d6dd6c82)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-11-15 22:28 UTC, rumenPERTS commented
November 2023
PERTS Newsletter
This season, we are filled with a cornucopia of exciting updates! We're delighted to announce an update to our Elevate/Ascend participation dashboards, and we’re happy to report that the California Acceleration Project webinar was a great success! In this update:
* Explore valuable insights on reviewing your first cycle Elevate/Ascend reports
* Discover creative ways to utilize Elevate/Ascend data in your teaching portfolios
* Ready to get started with Elevate/Ascend? Take advantage of our generous discount, our way of expressing gratitude to you.


** Focus on Communication Fidelity!
------------------------------------------------------------
If your report shows that communication fidelity is below 80%, make it your priority to improve it! Research (https://perts.net/research/fidelity-predicts-improvement) shows that high communication fidelity is essential for meaningful growth and is the best predictor of improvement in learning conditions.
Read How to Improve Communication Fidelity (https://perts.freshdesk.com/en/support/solutions/articles/67000671408-how-to-use-communication-fidelity)


** Implementation Tips💡
------------------------------------------------------------

Teachers, as you begin to review your reports, here are some resources and considerations:
* Review how to use your Elevate or Ascend reports (https://perts.freshdesk.com/en/support/solutions/articles/67000676734-how-do-i-use-my-ascend-elevate-report-) as a starting point.
* Engage in a discussion about your survey results (https://perts.freshdesk.com/en/support/solutions/articles/67000695496-how-can-i-debrief-results-with-students-) with your students. This can be a powerful way to show them that you value their feedback, and may also lead to improvements in communication fidelity scores!

Facilitators can support teachers with their data with these tools:
* Use our baseline protocol to review survey results and create a plan for improvement (for Elevate (https://elevate-support.perts.net/support/solutions/articles/67000676394-community-of-practice-meeting-protocols#baseline) or Ascend (https://ascend-support.perts.net/en/support/solutions/articles/67000676395-community-of-practice-meeting-protocols#baseline) ).
* These reflection questions (https://perts.freshdesk.com/en/support/solutions/articles/67000695502-how-can-i-support-instructors-as-they-review-feedback-from-students-) can help facilitators guide teachers towards constructive actions based on their initial reactions to the data.
* Looking for additional meeting protocols? Access them for Elevate (https://elevate-support.perts.net/support/solutions/articles/67000676394-community-of-practice-meeting-protocols) and Ascend (https://ascend-support.perts.net/support/solutions/articles/67000676395-community-of-practice-meeting-protocols) .


** Use Your Data to Show Your Growth!
------------------------------------------------------------

Are you in an evaluation year? Teachers can demonstrate progress toward their professional goals and provide evidence of elevating student voice by integrating Elevate/Ascend data into their teaching portfolios. Use your data to showcase your skills, growth, and impact in the classroom.
Read How to Use Elevate to Strengthen Your Teaching Portfolio (https://perts.net/elevate/teaching-portfolio)
Read How to Use Ascend to Strengthen Your Teaching Portfolio (https://perts.net/ascend/teaching-portfolio)


** CAP Webinar: Learning from Our Students’ Experiences to Create Classroom Cultures that Promote Equity
------------------------------------------------------------
Thank you to everyone who joined us for this webinar hosted by the California Acceleration Project (CAP), featuring Dr. Claudia Escobar, Kathy Wada, and Dr. Norman Lorenz. The presenters discussed Ascend's professional development model and the latest research from its implementation in California community colleges through the Learning for Equity Ascend Research Network (LEARN). They also shared their experiences in studying and cultivating classroom cultures that promote equity.
Read about LEARN and watch the 2023 CAP Webinar (https://ascend-support.perts.net/support/solutions/articles/67000723457)


** What's New in Elevate/Ascend?
------------------------------------------------------------

New participation dashboards are incoming and better than ever! The new "Participation by Class Lead" table provides a survey status for each survey, by teacher. Please note, as with other teacher-level participation data, this table will only be displayed for Community Leads and Network Leads.
Read How to Use the Community Participation Dashboard (https://perts.freshdesk.com/en/support/solutions/articles/67000677400-how-to-use-the-community-participation-dashboard)


** We’re Thankful for You This Season 🍂
------------------------------------------------------------
We’re very grateful for educators like you who are making a difference in the lives of your students. If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use the discount code THANKS23 when you schedule a consultation and receive a bountiful 20% discount!
Schedule a Consultation (https://perts.net/consultation)
“
Asking students exactly what they want is the best way to get them on board with you overall. That is the most powerful thing about the PERTS survey; it lets the students know that I want their feedback and that I will use it to make class better for them.

Anna Stewart, Teacher
Yulee Middle School
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=90d6dd6c82)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=90d6dd6c82)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-11-15 22:28 UTC, rumenPERTS commented
November 2023
PERTS Newsletter
This season, we are filled with a cornucopia of exciting updates! We're delighted to announce an update to our Elevate/Ascend participation dashboards, and we’re happy to report that the California Acceleration Project webinar was a great success! In this update:
* Explore valuable insights on reviewing your first cycle Elevate/Ascend reports
* Discover creative ways to utilize Elevate/Ascend data in your teaching portfolios
* Ready to get started with Elevate/Ascend? Take advantage of our generous discount, our way of expressing gratitude to you.


** Focus on Communication Fidelity!
------------------------------------------------------------
If your report shows that communication fidelity is below 80%, make it your priority to improve it! Research (https://perts.net/research/fidelity-predicts-improvement) shows that high communication fidelity is essential for meaningful growth and is the best predictor of improvement in learning conditions.
Read How to Improve Communication Fidelity (https://perts.freshdesk.com/en/support/solutions/articles/67000671408-how-to-use-communication-fidelity)


** Implementation Tips💡
------------------------------------------------------------

Teachers, as you begin to review your reports, here are some resources and considerations:
* Review how to use your Elevate or Ascend reports (https://perts.freshdesk.com/en/support/solutions/articles/67000676734-how-do-i-use-my-ascend-elevate-report-) as a starting point.
* Engage in a discussion about your survey results (https://perts.freshdesk.com/en/support/solutions/articles/67000695496-how-can-i-debrief-results-with-students-) with your students. This can be a powerful way to show them that you value their feedback, and may also lead to improvements in communication fidelity scores!

Facilitators can support teachers with their data with these tools:
* Use our baseline protocol to review survey results and create a plan for improvement (for Elevate (https://elevate-support.perts.net/support/solutions/articles/67000676394-community-of-practice-meeting-protocols#baseline) or Ascend (https://ascend-support.perts.net/en/support/solutions/articles/67000676395-community-of-practice-meeting-protocols#baseline) ).
* These reflection questions (https://perts.freshdesk.com/en/support/solutions/articles/67000695502-how-can-i-support-instructors-as-they-review-feedback-from-students-) can help facilitators guide teachers towards constructive actions based on their initial reactions to the data.
* Looking for additional meeting protocols? Access them for Elevate (https://elevate-support.perts.net/support/solutions/articles/67000676394-community-of-practice-meeting-protocols) and Ascend (https://ascend-support.perts.net/support/solutions/articles/67000676395-community-of-practice-meeting-protocols) .


** Use Your Data to Show Your Growth!
------------------------------------------------------------

Are you in an evaluation year? Teachers can demonstrate progress toward their professional goals and provide evidence of elevating student voice by integrating Elevate/Ascend data into their teaching portfolios. Use your data to showcase your skills, growth, and impact in the classroom.
Read How to Use Elevate to Strengthen Your Teaching Portfolio (https://perts.net/elevate/teaching-portfolio)
Read How to Use Ascend to Strengthen Your Teaching Portfolio (https://perts.net/ascend/teaching-portfolio)


** CAP Webinar: Learning from Our Students’ Experiences to Create Classroom Cultures that Promote Equity
------------------------------------------------------------
Thank you to everyone who joined us for this webinar hosted by the California Acceleration Project (CAP), featuring Dr. Claudia Escobar, Kathy Wada, and Dr. Norman Lorenz. The presenters discussed Ascend's professional development model and the latest research from its implementation in California community colleges through the Learning for Equity Ascend Research Network (LEARN). They also shared their experiences in studying and cultivating classroom cultures that promote equity.
Read about LEARN and watch the 2023 CAP Webinar (https://ascend-support.perts.net/support/solutions/articles/67000723457)


** What's New in Elevate/Ascend?
------------------------------------------------------------

New participation dashboards are incoming and better than ever! The new "Participation by Class Lead" table provides a survey status for each survey, by teacher. Please note, as with other teacher-level participation data, this table will only be displayed for Community Leads and Network Leads.
Read How to Use the Community Participation Dashboard (https://perts.freshdesk.com/en/support/solutions/articles/67000677400-how-to-use-the-community-participation-dashboard)


** We’re Thankful for You This Season 🍂
------------------------------------------------------------
We’re very grateful for educators like you who are making a difference in the lives of your students. If you’re supporting 10 or more educators to use Elevate or Ascend, get in touch and let us know how we can support your goals. Use the discount code THANKS23 when you schedule a consultation and receive a bountiful 20% discount!
Schedule a Consultation (https://perts.net/consultation)
“
Asking students exactly what they want is the best way to get them on board with you overall. That is the most powerful thing about the PERTS survey; it lets the students know that I want their feedback and that I will use it to make class better for them.

Anna Stewart, Teacher
Yulee Middle School
Our Programs
Elevate for Grades 6-12 (https://perts.net/elevate)
Ascend for Higher Ed (https://perts.net/ascend)
Catalyze for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=c3d5069a39&c=90d6dd6c82)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=c3d5069a39&c=90d6dd6c82)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-12-14 19:32 UTC, rumenPERTS commented
December Newsletter 2023


** Season's Greetings!
------------------------------------------------------------

We're excited to present a flurry of resources tailored to help support your efforts in centering student experience. In this winter edition, discover tools, strategies, and practices designed to foster warm conversations between you and your students. Explore ways to make the most of this winter season and elevate the learning experience in your classroom!


** Join Our Team!
------------------------------------------------------------

We are seeking a full-time Research Fellow to help shape the national conversation about equity in education. If you have a strong background in research and are passionate about making a lasting impact in the field, we encourage you to explore this role. Accepting applications through January 31, 2024.
Review the Research Fellow Role (https://perts.net/researchfellow)

Are you a motivated leader and educational equity champion eager to improve the way students experience school and learning? PERTS is looking for an experienced leader to join our team as a Partnership Manager! Accepting applications through February 5, 2024.
Review the Partnership Manager Role (https://perts.net/partnershipmanager)


** New Release from the BELE Network!
------------------------------------------------------------
Centering Student Experience: A playbook for improving student outcomes by centering student experience
Unlocking the full potential of public education requires a collective effort to reshape an outdated system. Modern research shows that students are more engaged when learning aligns with their interests and needs. BELE’s latest release, Centering Student Experience: A Playbook for Improving Student Outcomes, provides a selection of research-backed, role-specific tools (like PERTS Elevate (http://perts.net/elevate) ), resources, and practices to help you impact students’ learning and experiences.
Access the BELE Playbook (https://library.belenetwork.org/resources/playbook/)


** Debrief Survey Results with Students
------------------------------------------------------------

Sharing your survey results with your students and including them in the process of determining how to act on your data is critical.

It lets them know you care about their feedback and helps them take ownership of their learning. The article below includes suggestions to facilitate data conversations with students.
Read How Can I Debrief Results with Students (https://elevate-support.perts.net/support/solutions/articles/67000695496-how-can-i-debrief-results-with-students-)


** A Blast from Winter's Past: Elevate Showcase
------------------------------------------------------------
Last year, PERTS hosted the Elevate Showcase: Centering Classroom Experience to Catalyze Engagement & Learning with great success!

Listen to the classroom experiences from a featured student panel, as well as insights from teachers, researchers, and education leaders from across the country as they showcased their innovative work in centering student voices to catalyze change within the classroom.

You can also access the slides and resources (http://perts.net/elevate/showcase22-resources) from this event.
Watch the Showcase Recording (https://elevate-support.perts.net/support/solutions/articles/67000712638-elevate-showcase-october-2022-full-video)


** 'Tis the Season of Giving!
------------------------------------------------------------
In the spirit of giving, we express our appreciation for the remarkable educators shaping the future. If you're championing 10 or more educators using Elevate or Ascend, connect with us to align your goals.

Enter code WONDERLAND20 when scheduling a consultation before the end of this year and enjoy a generous 20% discount—a gift from us to you!
Schedule a Consultation Today (https://perts.net/consultation)
"
I used to think that I made students feel like they belong in the classroom simply by being fair and respectful. Now, I think that by learning more about my students' backgrounds and interests, I can strengthen their sense of belonging even more.


Teacher,
Mineola School District
New to Elevate? Start Here!
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
** Website (https://www.perts.net)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=1a87ba0bb8)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=1a87ba0bb8)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-12-14 19:33 UTC, rumenPERTS commented
December Newsletter 2023


** Season's Greetings!
------------------------------------------------------------

We're excited to present a flurry of resources tailored to help support your efforts in centering student experience. In this winter edition, discover tools, strategies, and practices designed to foster warm conversations between you and your students. Explore ways to make the most of this winter season and elevate the learning experience in your classroom!


** Join Our Team!
------------------------------------------------------------

We are seeking a full-time Research Fellow to help shape the national conversation about equity in education. If you have a strong background in research and are passionate about making a lasting impact in the field, we encourage you to explore this role. Accepting applications through January 31, 2024.
Review the Research Fellow Role (https://perts.net/researchfellow)

Are you a motivated leader and educational equity champion eager to improve the way students experience school and learning? PERTS is looking for an experienced leader to join our team as a Partnership Manager! Accepting applications through February 5, 2024.
Review the Partnership Manager Role (https://perts.net/partnershipmanager)


** New Release from the BELE Network!
------------------------------------------------------------
Centering Student Experience: A playbook for improving student outcomes by centering student experience
Unlocking the full potential of public education requires a collective effort to reshape an outdated system. Modern research shows that students are more engaged when learning aligns with their interests and needs. BELE’s latest release, Centering Student Experience: A Playbook for Improving Student Outcomes, provides a selection of research-backed, role-specific tools (like PERTS Elevate (http://perts.net/elevate) ), resources, and practices to help you impact students’ learning and experiences.
Access the BELE Playbook (https://library.belenetwork.org/resources/playbook/)


** Debrief Survey Results with Students
------------------------------------------------------------

Sharing your survey results with your students and including them in the process of determining how to act on your data is critical.

It lets them know you care about their feedback and helps them take ownership of their learning. The article below includes suggestions to facilitate data conversations with students.
Read How Can I Debrief Results with Students (https://elevate-support.perts.net/support/solutions/articles/67000695496-how-can-i-debrief-results-with-students-)


** A Blast from Winter's Past: Elevate Showcase
------------------------------------------------------------
Last year, PERTS hosted the Elevate Showcase: Centering Classroom Experience to Catalyze Engagement & Learning with great success!

Listen to the classroom experiences from a featured student panel, as well as insights from teachers, researchers, and education leaders from across the country as they showcased their innovative work in centering student voices to catalyze change within the classroom.

You can also access the slides and resources (http://perts.net/elevate/showcase22-resources) from this event.
Watch the Showcase Recording (https://elevate-support.perts.net/support/solutions/articles/67000712638-elevate-showcase-october-2022-full-video)


** 'Tis the Season of Giving!
------------------------------------------------------------
In the spirit of giving, we express our appreciation for the remarkable educators shaping the future. If you're championing 10 or more educators using Elevate or Ascend, connect with us to align your goals.

Enter code WONDERLAND20 when scheduling a consultation before the end of this year and enjoy a generous 20% discount—a gift from us to you!
Schedule a Consultation Today (https://perts.net/consultation)
"
I used to think that I made students feel like they belong in the classroom simply by being fair and respectful. Now, I think that by learning more about my students' backgrounds and interests, I can strengthen their sense of belonging even more.


Teacher,
Mineola School District
New to Elevate? Start Here!
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
** Website (https://www.perts.net)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=1a87ba0bb8)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=1a87ba0bb8)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-12-14 19:33 UTC, rumenPERTS commented
December Newsletter 2023


** Season's Greetings!
------------------------------------------------------------

We're excited to present a flurry of resources tailored to help support your efforts in centering student experience. In this winter edition, discover tools, strategies, and practices designed to foster warm conversations between you and your students. Explore ways to make the most of this winter season and elevate the learning experience in your classroom!


** Join Our Team!
------------------------------------------------------------

We are seeking a full-time Research Fellow to help shape the national conversation about equity in education. If you have a strong background in research and are passionate about making a lasting impact in the field, we encourage you to explore this role. Accepting applications through January 31, 2024.
Review the Research Fellow Role (https://perts.net/researchfellow)

Are you a motivated leader and educational equity champion eager to improve the way students experience school and learning? PERTS is looking for an experienced leader to join our team as a Partnership Manager! Accepting applications through February 5, 2024.
Review the Partnership Manager Role (https://perts.net/partnershipmanager)


** New Release from the BELE Network!
------------------------------------------------------------
Centering Student Experience: A playbook for improving student outcomes by centering student experience
Unlocking the full potential of public education requires a collective effort to reshape an outdated system. Modern research shows that students are more engaged when learning aligns with their interests and needs. BELE’s latest release, Centering Student Experience: A Playbook for Improving Student Outcomes, provides a selection of research-backed, role-specific tools (like PERTS Elevate (http://perts.net/elevate) ), resources, and practices to help you impact students’ learning and experiences.
Access the BELE Playbook (https://library.belenetwork.org/resources/playbook/)


** Debrief Survey Results with Students
------------------------------------------------------------

Sharing your survey results with your students and including them in the process of determining how to act on your data is critical.

It lets them know you care about their feedback and helps them take ownership of their learning. The article below includes suggestions to facilitate data conversations with students.
Read How Can I Debrief Results with Students (https://elevate-support.perts.net/support/solutions/articles/67000695496-how-can-i-debrief-results-with-students-)


** A Blast from Winter's Past: Elevate Showcase
------------------------------------------------------------
Last year, PERTS hosted the Elevate Showcase: Centering Classroom Experience to Catalyze Engagement & Learning with great success!

Listen to the classroom experiences from a featured student panel, as well as insights from teachers, researchers, and education leaders from across the country as they showcased their innovative work in centering student voices to catalyze change within the classroom.

You can also access the slides and resources (http://perts.net/elevate/showcase22-resources) from this event.
Watch the Showcase Recording (https://elevate-support.perts.net/support/solutions/articles/67000712638-elevate-showcase-october-2022-full-video)


** 'Tis the Season of Giving!
------------------------------------------------------------
In the spirit of giving, we express our appreciation for the remarkable educators shaping the future. If you're championing 10 or more educators using Elevate or Ascend, connect with us to align your goals.

Enter code WONDERLAND20 when scheduling a consultation before the end of this year and enjoy a generous 20% discount—a gift from us to you!
Schedule a Consultation Today (https://perts.net/consultation)
"
I used to think that I made students feel like they belong in the classroom simply by being fair and respectful. Now, I think that by learning more about my students' backgrounds and interests, I can strengthen their sense of belonging even more.


Teacher,
Mineola School District
New to Elevate? Start Here!
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
** Website (https://www.perts.net)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=1a87ba0bb8)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=1a87ba0bb8)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-12-14 19:33 UTC, rumenPERTS commented
December Newsletter 2023


** Season's Greetings!
------------------------------------------------------------

We're excited to present a flurry of resources tailored to help support your efforts in centering student experience. In this winter edition, discover tools, strategies, and practices designed to foster warm conversations between you and your students. Explore ways to make the most of this winter season and elevate the learning experience in your classroom!


** Join Our Team!
------------------------------------------------------------

We are seeking a full-time Research Fellow to help shape the national conversation about equity in education. If you have a strong background in research and are passionate about making a lasting impact in the field, we encourage you to explore this role. Accepting applications through January 31, 2024.
Review the Research Fellow Role (https://perts.net/researchfellow)

Are you a motivated leader and educational equity champion eager to improve the way students experience school and learning? PERTS is looking for an experienced leader to join our team as a Partnership Manager! Accepting applications through February 5, 2024.
Review the Partnership Manager Role (https://perts.net/partnershipmanager)


** New Release from the BELE Network!
------------------------------------------------------------
Centering Student Experience: A playbook for improving student outcomes by centering student experience
Unlocking the full potential of public education requires a collective effort to reshape an outdated system. Modern research shows that students are more engaged when learning aligns with their interests and needs. BELE’s latest release, Centering Student Experience: A Playbook for Improving Student Outcomes, provides a selection of research-backed, role-specific tools (like PERTS Elevate (http://perts.net/elevate) ), resources, and practices to help you impact students’ learning and experiences.
Access the BELE Playbook (https://library.belenetwork.org/resources/playbook/)


** Debrief Survey Results with Students
------------------------------------------------------------

Sharing your survey results with your students and including them in the process of determining how to act on your data is critical.

It lets them know you care about their feedback and helps them take ownership of their learning. The article below includes suggestions to facilitate data conversations with students.
Read How Can I Debrief Results with Students (https://elevate-support.perts.net/support/solutions/articles/67000695496-how-can-i-debrief-results-with-students-)


** A Blast from Winter's Past: Elevate Showcase
------------------------------------------------------------
Last year, PERTS hosted the Elevate Showcase: Centering Classroom Experience to Catalyze Engagement & Learning with great success!

Listen to the classroom experiences from a featured student panel, as well as insights from teachers, researchers, and education leaders from across the country as they showcased their innovative work in centering student voices to catalyze change within the classroom.

You can also access the slides and resources (http://perts.net/elevate/showcase22-resources) from this event.
Watch the Showcase Recording (https://elevate-support.perts.net/support/solutions/articles/67000712638-elevate-showcase-october-2022-full-video)


** 'Tis the Season of Giving!
------------------------------------------------------------
In the spirit of giving, we express our appreciation for the remarkable educators shaping the future. If you're championing 10 or more educators using Elevate or Ascend, connect with us to align your goals.

Enter code WONDERLAND20 when scheduling a consultation before the end of this year and enjoy a generous 20% discount—a gift from us to you!
Schedule a Consultation Today (https://perts.net/consultation)
"
I used to think that I made students feel like they belong in the classroom simply by being fair and respectful. Now, I think that by learning more about my students' backgrounds and interests, I can strengthen their sense of belonging even more.


Teacher,
Mineola School District
New to Elevate? Start Here!
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
** Website (https://www.perts.net)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=9dba3d787d&c=1a87ba0bb8)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=9dba3d787d&c=1a87ba0bb8)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-12-14 19:34 UTC, rumenPERTS commented
December Newsletter 2023


** Season's Greetings!
------------------------------------------------------------

We're excited to present a flurry of resources tailored to help support your efforts in centering student experience. In this winter edition, discover tools, strategies, and practices designed to foster warm conversations between you and your students. Explore ways to make the most of this winter season and elevate the learning experience in your classroom!


** Join Our Team!
------------------------------------------------------------

We are seeking a full-time Research Fellow to help shape the national conversation about equity in education. If you have a strong background in research and are passionate about making a lasting impact in the field, we encourage you to explore this role. Accepting applications through January 31, 2024.
Review the Research Fellow Role (https://perts.net/researchfellow)

Are you a motivated leader and educational equity champion eager to improve the way students experience school and learning? PERTS is looking for an experienced leader to join our team as a Partnership Manager! Accepting applications through February 5, 2024.
Review the Partnership Manager Role (https://perts.net/partnershipmanager)


** New Release from the BELE Network!
------------------------------------------------------------
Centering Student Experience: A playbook for improving student outcomes by centering student experience
Unlocking the full potential of public education requires a collective effort to reshape an outdated system. Modern research shows that students are more engaged when learning aligns with their interests and needs. BELE’s latest release, Centering Student Experience: A Playbook for Improving Student Outcomes, provides a selection of research-backed, role-specific tools (like PERTS Elevate (http://perts.net/elevate) ), resources, and practices to help you impact students’ learning and experiences.
Access the BELE Playbook (https://library.belenetwork.org/resources/playbook/)


** Debrief Survey Results with Students
------------------------------------------------------------

Sharing your survey results with your students and including them in the process of determining how to act on your data is critical.

It lets them know you care about their feedback and helps them take ownership of their learning. The article below includes suggestions to facilitate data conversations with students.
Read How Can I Debrief Results with Students (https://elevate-support.perts.net/support/solutions/articles/67000695496-how-can-i-debrief-results-with-students-)


** A Blast from Winter's Past: Elevate Showcase
------------------------------------------------------------
Last year, PERTS hosted the Elevate Showcase: Centering Classroom Experience to Catalyze Engagement & Learning with great success!

Listen to the classroom experiences from a featured student panel, as well as insights from teachers, researchers, and education leaders from across the country as they showcased their innovative work in centering student voices to catalyze change within the classroom.

You can also access the slides and resources (http://perts.net/elevate/showcase22-resources) from this event.
Watch the Showcase Recording (https://elevate-support.perts.net/support/solutions/articles/67000712638-elevate-showcase-october-2022-full-video)


** 'Tis the Season of Giving!
------------------------------------------------------------
In the spirit of giving, we express our appreciation for the remarkable educators shaping the future. If you're championing 10 or more educators using Elevate or Ascend, connect with us to align your goals.

Enter code WONDERLAND20 when scheduling a consultation before the end of this year and enjoy a generous 20% discount—a gift from us to you!
Schedule a Consultation Today (https://perts.net/consultation)
"
I used to think that I made students feel like they belong in the classroom simply by being fair and respectful. Now, I think that by learning more about my students' backgrounds and interests, I can strengthen their sense of belonging even more.


Teacher,
Mineola School District
New to Elevate? Start Here!
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
** Website (https://www.perts.net)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=8af4b6e57d&c=1a87ba0bb8)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=8af4b6e57d&c=1a87ba0bb8)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-12-14 19:34 UTC, rumenPERTS commented
December Newsletter 2023


** Season's Greetings!
------------------------------------------------------------

We're excited to present a flurry of resources tailored to help support your efforts in centering student experience. In this winter edition, discover tools, strategies, and practices designed to foster warm conversations between you and your students. Explore ways to make the most of this winter season and elevate the learning experience in your classroom!


** Join Our Team!
------------------------------------------------------------

We are seeking a full-time Research Fellow to help shape the national conversation about equity in education. If you have a strong background in research and are passionate about making a lasting impact in the field, we encourage you to explore this role. Accepting applications through January 31, 2024.
Review the Research Fellow Role (https://perts.net/researchfellow)

Are you a motivated leader and educational equity champion eager to improve the way students experience school and learning? PERTS is looking for an experienced leader to join our team as a Partnership Manager! Accepting applications through February 5, 2024.
Review the Partnership Manager Role (https://perts.net/partnershipmanager)


** New Release from the BELE Network!
------------------------------------------------------------
Centering Student Experience: A playbook for improving student outcomes by centering student experience
Unlocking the full potential of public education requires a collective effort to reshape an outdated system. Modern research shows that students are more engaged when learning aligns with their interests and needs. BELE’s latest release, Centering Student Experience: A Playbook for Improving Student Outcomes, provides a selection of research-backed, role-specific tools (like PERTS Elevate (http://perts.net/elevate) ), resources, and practices to help you impact students’ learning and experiences.
Access the BELE Playbook (https://library.belenetwork.org/resources/playbook/)


** Debrief Survey Results with Students
------------------------------------------------------------

Sharing your survey results with your students and including them in the process of determining how to act on your data is critical.

It lets them know you care about their feedback and helps them take ownership of their learning. The article below includes suggestions to facilitate data conversations with students.
Read How Can I Debrief Results with Students (https://elevate-support.perts.net/support/solutions/articles/67000695496-how-can-i-debrief-results-with-students-)


** A Blast from Winter's Past: Elevate Showcase
------------------------------------------------------------
Last year, PERTS hosted the Elevate Showcase: Centering Classroom Experience to Catalyze Engagement & Learning with great success!

Listen to the classroom experiences from a featured student panel, as well as insights from teachers, researchers, and education leaders from across the country as they showcased their innovative work in centering student voices to catalyze change within the classroom.

You can also access the slides and resources (http://perts.net/elevate/showcase22-resources) from this event.
Watch the Showcase Recording (https://elevate-support.perts.net/support/solutions/articles/67000712638-elevate-showcase-october-2022-full-video)


** 'Tis the Season of Giving!
------------------------------------------------------------
In the spirit of giving, we express our appreciation for the remarkable educators shaping the future. If you're championing 10 or more educators using Elevate or Ascend, connect with us to align your goals.

Enter code WONDERLAND20 when scheduling a consultation before the end of this year and enjoy a generous 20% discount—a gift from us to you!
Schedule a Consultation Today (https://perts.net/consultation)
"
I used to think that I made students feel like they belong in the classroom simply by being fair and respectful. Now, I think that by learning more about my students' backgrounds and interests, I can strengthen their sense of belonging even more.


Teacher,
Mineola School District
New to Elevate? Start Here!
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
** Website (https://www.perts.net)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=1a87ba0bb8)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=1a87ba0bb8)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-12-14 19:34 UTC, rumenPERTS commented
December Newsletter 2023


** Season's Greetings!
------------------------------------------------------------

We're excited to present a flurry of resources tailored to help support your efforts in centering student experience. In this winter edition, discover tools, strategies, and practices designed to foster warm conversations between you and your students. Explore ways to make the most of this winter season and elevate the learning experience in your classroom!


** Join Our Team!
------------------------------------------------------------

We are seeking a full-time Research Fellow to help shape the national conversation about equity in education. If you have a strong background in research and are passionate about making a lasting impact in the field, we encourage you to explore this role. Accepting applications through January 31, 2024.
Review the Research Fellow Role (https://perts.net/researchfellow)

Are you a motivated leader and educational equity champion eager to improve the way students experience school and learning? PERTS is looking for an experienced leader to join our team as a Partnership Manager! Accepting applications through February 5, 2024.
Review the Partnership Manager Role (https://perts.net/partnershipmanager)


** New Release from the BELE Network!
------------------------------------------------------------
Centering Student Experience: A playbook for improving student outcomes by centering student experience
Unlocking the full potential of public education requires a collective effort to reshape an outdated system. Modern research shows that students are more engaged when learning aligns with their interests and needs. BELE’s latest release, Centering Student Experience: A Playbook for Improving Student Outcomes, provides a selection of research-backed, role-specific tools (like PERTS Elevate (http://perts.net/elevate) ), resources, and practices to help you impact students’ learning and experiences.
Access the BELE Playbook (https://library.belenetwork.org/resources/playbook/)


** Debrief Survey Results with Students
------------------------------------------------------------

Sharing your survey results with your students and including them in the process of determining how to act on your data is critical.

It lets them know you care about their feedback and helps them take ownership of their learning. The article below includes suggestions to facilitate data conversations with students.
Read How Can I Debrief Results with Students (https://elevate-support.perts.net/support/solutions/articles/67000695496-how-can-i-debrief-results-with-students-)


** A Blast from Winter's Past: Elevate Showcase
------------------------------------------------------------
Last year, PERTS hosted the Elevate Showcase: Centering Classroom Experience to Catalyze Engagement & Learning with great success!

Listen to the classroom experiences from a featured student panel, as well as insights from teachers, researchers, and education leaders from across the country as they showcased their innovative work in centering student voices to catalyze change within the classroom.

You can also access the slides and resources (http://perts.net/elevate/showcase22-resources) from this event.
Watch the Showcase Recording (https://elevate-support.perts.net/support/solutions/articles/67000712638-elevate-showcase-october-2022-full-video)


** 'Tis the Season of Giving!
------------------------------------------------------------
In the spirit of giving, we express our appreciation for the remarkable educators shaping the future. If you're championing 10 or more educators using Elevate or Ascend, connect with us to align your goals.

Enter code WONDERLAND20 when scheduling a consultation before the end of this year and enjoy a generous 20% discount—a gift from us to you!
Schedule a Consultation Today (https://perts.net/consultation)
"
I used to think that I made students feel like they belong in the classroom simply by being fair and respectful. Now, I think that by learning more about my students' backgrounds and interests, I can strengthen their sense of belonging even more.


Teacher,
Mineola School District
New to Elevate? Start Here!
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
** Website (https://www.perts.net)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=1a87ba0bb8)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=1a87ba0bb8)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-12-14 19:34 UTC, rumenPERTS commented
December Newsletter 2023


** Season's Greetings!
------------------------------------------------------------

We're excited to present a flurry of resources tailored to help support your efforts in centering student experience. In this winter edition, discover tools, strategies, and practices designed to foster warm conversations between you and your students. Explore ways to make the most of this winter season and elevate the learning experience in your classroom!


** Join Our Team!
------------------------------------------------------------

We are seeking a full-time Research Fellow to help shape the national conversation about equity in education. If you have a strong background in research and are passionate about making a lasting impact in the field, we encourage you to explore this role. Accepting applications through January 31, 2024.
Review the Research Fellow Role (https://perts.net/researchfellow)

Are you a motivated leader and educational equity champion eager to improve the way students experience school and learning? PERTS is looking for an experienced leader to join our team as a Partnership Manager! Accepting applications through February 5, 2024.
Review the Partnership Manager Role (https://perts.net/partnershipmanager)


** New Release from the BELE Network!
------------------------------------------------------------
Centering Student Experience: A playbook for improving student outcomes by centering student experience
Unlocking the full potential of public education requires a collective effort to reshape an outdated system. Modern research shows that students are more engaged when learning aligns with their interests and needs. BELE’s latest release, Centering Student Experience: A Playbook for Improving Student Outcomes, provides a selection of research-backed, role-specific tools (like PERTS Elevate (http://perts.net/elevate) ), resources, and practices to help you impact students’ learning and experiences.
Access the BELE Playbook (https://library.belenetwork.org/resources/playbook/)


** Debrief Survey Results with Students
------------------------------------------------------------

Sharing your survey results with your students and including them in the process of determining how to act on your data is critical.

It lets them know you care about their feedback and helps them take ownership of their learning. The article below includes suggestions to facilitate data conversations with students.
Read How Can I Debrief Results with Students (https://elevate-support.perts.net/support/solutions/articles/67000695496-how-can-i-debrief-results-with-students-)


** A Blast from Winter's Past: Elevate Showcase
------------------------------------------------------------
Last year, PERTS hosted the Elevate Showcase: Centering Classroom Experience to Catalyze Engagement & Learning with great success!

Listen to the classroom experiences from a featured student panel, as well as insights from teachers, researchers, and education leaders from across the country as they showcased their innovative work in centering student voices to catalyze change within the classroom.

You can also access the slides and resources (http://perts.net/elevate/showcase22-resources) from this event.
Watch the Showcase Recording (https://elevate-support.perts.net/support/solutions/articles/67000712638-elevate-showcase-october-2022-full-video)


** 'Tis the Season of Giving!
------------------------------------------------------------
In the spirit of giving, we express our appreciation for the remarkable educators shaping the future. If you're championing 10 or more educators using Elevate or Ascend, connect with us to align your goals.

Enter code WONDERLAND20 when scheduling a consultation before the end of this year and enjoy a generous 20% discount—a gift from us to you!
Schedule a Consultation Today (https://perts.net/consultation)
"
I used to think that I made students feel like they belong in the classroom simply by being fair and respectful. Now, I think that by learning more about my students' backgrounds and interests, I can strengthen their sense of belonging even more.


Teacher,
Mineola School District
New to Elevate? Start Here!
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
** Website (https://www.perts.net)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=1a87ba0bb8)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=1a87ba0bb8)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-12-14 19:36 UTC, rumenPERTS commented
December Newsletter 2023


** Season's Greetings!
------------------------------------------------------------

We're excited to present a flurry of resources tailored to help support your efforts in centering student experience. In this winter edition, discover tools, strategies, and practices designed to foster warm conversations between you and your students. Explore ways to make the most of this winter season and elevate the learning experience in your classroom!


** Join Our Team!
------------------------------------------------------------

We are seeking a full-time Research Fellow to help shape the national conversation about equity in education. If you have a strong background in research and are passionate about making a lasting impact in the field, we encourage you to explore this role. Accepting applications through January 31, 2024.
Review the Research Fellow Role (https://perts.net/researchfellow)

Are you a motivated leader and educational equity champion eager to improve the way students experience school and learning? PERTS is looking for an experienced leader to join our team as a Partnership Manager! Accepting applications through February 5, 2024.
Review the Partnership Manager Role (https://perts.net/partnershipmanager)


** New Release from the BELE Network!
------------------------------------------------------------
Centering Student Experience: A playbook for improving student outcomes by centering student experience
Unlocking the full potential of public education requires a collective effort to reshape an outdated system. Modern research shows that students are more engaged when learning aligns with their interests and needs. BELE’s latest release, Centering Student Experience: A Playbook for Improving Student Outcomes, provides a selection of research-backed, role-specific tools (like PERTS Elevate (http://perts.net/elevate) ), resources, and practices to help you impact students’ learning and experiences.
Access the BELE Playbook (https://library.belenetwork.org/resources/playbook/)


** Debrief Survey Results with Students
------------------------------------------------------------

Sharing your survey results with your students and including them in the process of determining how to act on your data is critical.

It lets them know you care about their feedback and helps them take ownership of their learning. The article below includes suggestions to facilitate data conversations with students.
Read How Can I Debrief Results with Students (https://elevate-support.perts.net/support/solutions/articles/67000695496-how-can-i-debrief-results-with-students-)


** A Blast from Winter's Past: Elevate Showcase
------------------------------------------------------------
Last year, PERTS hosted the Elevate Showcase: Centering Classroom Experience to Catalyze Engagement & Learning with great success!

Listen to the classroom experiences from a featured student panel, as well as insights from teachers, researchers, and education leaders from across the country as they showcased their innovative work in centering student voices to catalyze change within the classroom.

You can also access the slides and resources (http://perts.net/elevate/showcase22-resources) from this event.
Watch the Showcase Recording (https://elevate-support.perts.net/support/solutions/articles/67000712638-elevate-showcase-october-2022-full-video)


** 'Tis the Season of Giving!
------------------------------------------------------------
In the spirit of giving, we express our appreciation for the remarkable educators shaping the future. If you're championing 10 or more educators using Elevate or Ascend, connect with us to align your goals.

Enter code WONDERLAND20 when scheduling a consultation before the end of this year and enjoy a generous 20% discount—a gift from us to you!
Schedule a Consultation Today (https://perts.net/consultation)
"
I used to think that I made students feel like they belong in the classroom simply by being fair and respectful. Now, I think that by learning more about my students' backgrounds and interests, I can strengthen their sense of belonging even more.


Teacher,
Mineola School District
New to Elevate? Start Here!
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
** Website (https://www.perts.net)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=1a87ba0bb8)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=1a87ba0bb8)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2023-12-14 19:36 UTC, rumenPERTS commented
December Newsletter 2023


** Season's Greetings!
------------------------------------------------------------

We're excited to present a flurry of resources tailored to help support your efforts in centering student experience. In this winter edition, discover tools, strategies, and practices designed to foster warm conversations between you and your students. Explore ways to make the most of this winter season and elevate the learning experience in your classroom!


** Join Our Team!
------------------------------------------------------------

We are seeking a full-time Research Fellow to help shape the national conversation about equity in education. If you have a strong background in research and are passionate about making a lasting impact in the field, we encourage you to explore this role. Accepting applications through January 31, 2024.
Review the Research Fellow Role (https://perts.net/researchfellow)

Are you a motivated leader and educational equity champion eager to improve the way students experience school and learning? PERTS is looking for an experienced leader to join our team as a Partnership Manager! Accepting applications through February 5, 2024.
Review the Partnership Manager Role (https://perts.net/partnershipmanager)


** New Release from the BELE Network!
------------------------------------------------------------
Centering Student Experience: A playbook for improving student outcomes by centering student experience
Unlocking the full potential of public education requires a collective effort to reshape an outdated system. Modern research shows that students are more engaged when learning aligns with their interests and needs. BELE’s latest release, Centering Student Experience: A Playbook for Improving Student Outcomes, provides a selection of research-backed, role-specific tools (like PERTS Elevate (http://perts.net/elevate) ), resources, and practices to help you impact students’ learning and experiences.
Access the BELE Playbook (https://library.belenetwork.org/resources/playbook/)


** Debrief Survey Results with Students
------------------------------------------------------------

Sharing your survey results with your students and including them in the process of determining how to act on your data is critical.

It lets them know you care about their feedback and helps them take ownership of their learning. The article below includes suggestions to facilitate data conversations with students.
Read How Can I Debrief Results with Students (https://elevate-support.perts.net/support/solutions/articles/67000695496-how-can-i-debrief-results-with-students-)


** A Blast from Winter's Past: Elevate Showcase
------------------------------------------------------------
Last year, PERTS hosted the Elevate Showcase: Centering Classroom Experience to Catalyze Engagement & Learning with great success!

Listen to the classroom experiences from a featured student panel, as well as insights from teachers, researchers, and education leaders from across the country as they showcased their innovative work in centering student voices to catalyze change within the classroom.

You can also access the slides and resources (http://perts.net/elevate/showcase22-resources) from this event.
Watch the Showcase Recording (https://elevate-support.perts.net/support/solutions/articles/67000712638-elevate-showcase-october-2022-full-video)


** 'Tis the Season of Giving!
------------------------------------------------------------
In the spirit of giving, we express our appreciation for the remarkable educators shaping the future. If you're championing 10 or more educators using Elevate or Ascend, connect with us to align your goals.

Enter code WONDERLAND20 when scheduling a consultation before the end of this year and enjoy a generous 20% discount—a gift from us to you!
Schedule a Consultation Today (https://perts.net/consultation)
"
I used to think that I made students feel like they belong in the classroom simply by being fair and respectful. Now, I think that by learning more about my students' backgrounds and interests, I can strengthen their sense of belonging even more.


Teacher,
Mineola School District
New to Elevate? Start Here!
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
** Website (https://www.perts.net)
Copyright © 2023 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=c3d5069a39&c=1a87ba0bb8)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=c3d5069a39&c=1a87ba0bb8)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2024-01-18 21:17 UTC, rumenPERTS commented
January 2024
PERTS Newsletter


** Happy New Year from PERTS! 🎉
------------------------------------------------------------

The new year often presents a starting point for new or refreshed intentions. We hope you started the year feeling inspired to create learning experiences for students that will help them achieve their fullest potential.

In this newsletter, we offer some suggestions for current Elevate and Ascend partners; opportunities to raise funds to get started with Elevate; and amazing career opportunities with PERTS!


** Start the Year Strong!
------------------------------------------------------------

Maximize Student Participation
Did you know you can track survey participation to ensure high completion rates? The Participation Dashboard tracks survey participation by Class Lead, Class, Community, and even by student.
Learn How to View Student Participation (https://perts.freshdesk.com/support/solutions/articles/67000677400-how-to-use-the-community-participation-dashboard)


Achieve High Communication Fidelity
A recent analysis (https://perts.net/research/fidelity-predicts-improvement) revealed that when communication fidelity is high, learning conditions improve more significantly after four cycles (12-15 percentage points in some classes). Prioritizing communication fidelity scores below 70% and aiming for 90% is essential for improving student experience.
Learn How to Achieve Communication Fidelity (https://perts.freshdesk.com/en/support/solutions/articles/67000671408-how-to-use-communication-fidelity)


** 📢 A Reminder for All Semester-Long Classes!
------------------------------------------------------------

Once your Fall semester classes end, archive the Fall Community to avoid any confusion with Spring semester classes. We also recommend locking your rosters to prevent students from inadvertently accessing the incorrect class survey.
Learn How to Archive a Community (https://perts.freshdesk.com/support/solutions/articles/67000713424-what-is-community-archiving-)
Learn How to Lock Rosters (https://perts.freshdesk.com/support/solutions/articles/67000676915-what-is-roster-locking-)


** New Interface Updates!
------------------------------------------------------------

We’ve made it easier to manage several classes in Elevate and Ascend. Check out new sort features to the Members, Classes, Schedules, and Surveys pages!
Review the Changes to the Surveys Page (https://perts.freshdesk.com/support/solutions/articles/67000729084-orientation-to-the-surveys-page)


** Secure Federal or State Funds for Your Elevate Implementation
------------------------------------------------------------
Eager to get started with Elevate? Federal and state funds are sometimes earmarked for programs that meet specific “tiers of evidence.” In case you missed it, we have compiled this guide to help education leaders secure those funds by citing the evidence tier relevant to their intended Elevate implementation.
Review the ESSA Evidence Tiers for Elevate (https://perts.net/elevate/essa-tiers)


** The Holiday Cheer Continues!
------------------------------------------------------------
The spirit of gift-giving continues! If you're interested in partnering with PERTS to improve learning conditions for your students, enter code NEWYEAR20 when scheduling a consultation and enjoy a generous 20% discount—a gift from us to you!
Schedule a Consultation Today (https://perts.net/consultation)


** Join Our Team!
------------------------------------------------------------
The PERTS team is growing! If you’re passionate about educational equity and eager to make a lasting impact in the field, take a look at our open roles and apply before the upcoming deadlines!
Research Fellow - Apply by 1/31 (https://perts.net/researchfellow)
Partnership Manager, Higher Education - Apply by 2/5 (https://perts.net/partnershipmanager)


** Welcome Back, Erin!
------------------------------------------------------------

Erin Ashoka, Partnership Manager, has returned from parental leave! In July, Erin had her first baby, Oak.

She is back to supporting partners and leading the Elevate Facilitator Network. Welcome back, Erin!
“
Don't be offended at the responses in the beginning. Use it as an opportunity to give students a voice into building a community with you. Students love to see their suggestions implemented into the class. They can see the growth.

Elevate User
Our Programs
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=c369b92932)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=c369b92932)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2024-01-18 21:17 UTC, rumenPERTS commented
January 2024
PERTS Newsletter


** Happy New Year from PERTS! 🎉
------------------------------------------------------------

The new year often presents a starting point for new or refreshed intentions. We hope you started the year feeling inspired to create learning experiences for students that will help them achieve their fullest potential.

In this newsletter, we offer some suggestions for current Elevate and Ascend partners; opportunities to raise funds to get started with Elevate; and amazing career opportunities with PERTS!


** Start the Year Strong!
------------------------------------------------------------

Maximize Student Participation
Did you know you can track survey participation to ensure high completion rates? The Participation Dashboard tracks survey participation by Class Lead, Class, Community, and even by student.
Learn How to View Student Participation (https://perts.freshdesk.com/support/solutions/articles/67000677400-how-to-use-the-community-participation-dashboard)


Achieve High Communication Fidelity
A recent analysis (https://perts.net/research/fidelity-predicts-improvement) revealed that when communication fidelity is high, learning conditions improve more significantly after four cycles (12-15 percentage points in some classes). Prioritizing communication fidelity scores below 70% and aiming for 90% is essential for improving student experience.
Learn How to Achieve Communication Fidelity (https://perts.freshdesk.com/en/support/solutions/articles/67000671408-how-to-use-communication-fidelity)


** 📢 A Reminder for All Semester-Long Classes!
------------------------------------------------------------

Once your Fall semester classes end, archive the Fall Community to avoid any confusion with Spring semester classes. We also recommend locking your rosters to prevent students from inadvertently accessing the incorrect class survey.
Learn How to Archive a Community (https://perts.freshdesk.com/support/solutions/articles/67000713424-what-is-community-archiving-)
Learn How to Lock Rosters (https://perts.freshdesk.com/support/solutions/articles/67000676915-what-is-roster-locking-)


** New Interface Updates!
------------------------------------------------------------

We’ve made it easier to manage several classes in Elevate and Ascend. Check out new sort features to the Members, Classes, Schedules, and Surveys pages!
Review the Changes to the Surveys Page (https://perts.freshdesk.com/support/solutions/articles/67000729084-orientation-to-the-surveys-page)


** Secure Federal or State Funds for Your Elevate Implementation
------------------------------------------------------------
Eager to get started with Elevate? Federal and state funds are sometimes earmarked for programs that meet specific “tiers of evidence.” In case you missed it, we have compiled this guide to help education leaders secure those funds by citing the evidence tier relevant to their intended Elevate implementation.
Review the ESSA Evidence Tiers for Elevate (https://perts.net/elevate/essa-tiers)


** The Holiday Cheer Continues!
------------------------------------------------------------
The spirit of gift-giving continues! If you're interested in partnering with PERTS to improve learning conditions for your students, enter code NEWYEAR20 when scheduling a consultation and enjoy a generous 20% discount—a gift from us to you!
Schedule a Consultation Today (https://perts.net/consultation)


** Join Our Team!
------------------------------------------------------------
The PERTS team is growing! If you’re passionate about educational equity and eager to make a lasting impact in the field, take a look at our open roles and apply before the upcoming deadlines!
Research Fellow - Apply by 1/31 (https://perts.net/researchfellow)
Partnership Manager, Higher Education - Apply by 2/5 (https://perts.net/partnershipmanager)


** Welcome Back, Erin!
------------------------------------------------------------

Erin Ashoka, Partnership Manager, has returned from parental leave! In July, Erin had her first baby, Oak.

She is back to supporting partners and leading the Elevate Facilitator Network. Welcome back, Erin!
“
Don't be offended at the responses in the beginning. Use it as an opportunity to give students a voice into building a community with you. Students love to see their suggestions implemented into the class. They can see the growth.

Elevate User
Our Programs
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=c369b92932)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=c369b92932)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2024-01-18 21:19 UTC, rumenPERTS commented
January 2024
PERTS Newsletter


** Happy New Year from PERTS! 🎉
------------------------------------------------------------

The new year often presents a starting point for new or refreshed intentions. We hope you started the year feeling inspired to create learning experiences for students that will help them achieve their fullest potential.

In this newsletter, we offer some suggestions for current Elevate and Ascend partners; opportunities to raise funds to get started with Elevate; and amazing career opportunities with PERTS!


** Start the Year Strong!
------------------------------------------------------------

Maximize Student Participation
Did you know you can track survey participation to ensure high completion rates? The Participation Dashboard tracks survey participation by Class Lead, Class, Community, and even by student.
Learn How to View Student Participation (https://perts.freshdesk.com/support/solutions/articles/67000677400-how-to-use-the-community-participation-dashboard)


Achieve High Communication Fidelity
A recent analysis (https://perts.net/research/fidelity-predicts-improvement) revealed that when communication fidelity is high, learning conditions improve more significantly after four cycles (12-15 percentage points in some classes). Prioritizing communication fidelity scores below 70% and aiming for 90% is essential for improving student experience.
Learn How to Achieve Communication Fidelity (https://perts.freshdesk.com/en/support/solutions/articles/67000671408-how-to-use-communication-fidelity)


** 📢 A Reminder for All Semester-Long Classes!
------------------------------------------------------------

Once your Fall semester classes end, archive the Fall Community to avoid any confusion with Spring semester classes. We also recommend locking your rosters to prevent students from inadvertently accessing the incorrect class survey.
Learn How to Archive a Community (https://perts.freshdesk.com/support/solutions/articles/67000713424-what-is-community-archiving-)
Learn How to Lock Rosters (https://perts.freshdesk.com/support/solutions/articles/67000676915-what-is-roster-locking-)


** New Interface Updates!
------------------------------------------------------------

We’ve made it easier to manage several classes in Elevate and Ascend. Check out new sort features to the Members, Classes, Schedules, and Surveys pages!
Review the Changes to the Surveys Page (https://perts.freshdesk.com/support/solutions/articles/67000729084-orientation-to-the-surveys-page)


** Secure Federal or State Funds for Your Elevate Implementation
------------------------------------------------------------
Eager to get started with Elevate? Federal and state funds are sometimes earmarked for programs that meet specific “tiers of evidence.” In case you missed it, we have compiled this guide to help education leaders secure those funds by citing the evidence tier relevant to their intended Elevate implementation.
Review the ESSA Evidence Tiers for Elevate (https://perts.net/elevate/essa-tiers)


** The Holiday Cheer Continues!
------------------------------------------------------------
The spirit of gift-giving continues! If you're interested in partnering with PERTS to improve learning conditions for your students, enter code NEWYEAR20 when scheduling a consultation and enjoy a generous 20% discount—a gift from us to you!
Schedule a Consultation Today (https://perts.net/consultation)


** Join Our Team!
------------------------------------------------------------
The PERTS team is growing! If you’re passionate about educational equity and eager to make a lasting impact in the field, take a look at our open roles and apply before the upcoming deadlines!
Research Fellow - Apply by 1/31 (https://perts.net/researchfellow)
Partnership Manager, Higher Education - Apply by 2/5 (https://perts.net/partnershipmanager)


** Welcome Back, Erin!
------------------------------------------------------------

Erin Ashoka, Partnership Manager, has returned from parental leave! In July, Erin had her first baby, Oak.

She is back to supporting partners and leading the Elevate Facilitator Network. Welcome back, Erin!
“
Don't be offended at the responses in the beginning. Use it as an opportunity to give students a voice into building a community with you. Students love to see their suggestions implemented into the class. They can see the growth.

Elevate User
Our Programs
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=c369b92932)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=c369b92932)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2024-01-18 21:19 UTC, rumenPERTS commented
January 2024
PERTS Newsletter


** Happy New Year from PERTS! 🎉
------------------------------------------------------------

The new year often presents a starting point for new or refreshed intentions. We hope you started the year feeling inspired to create learning experiences for students that will help them achieve their fullest potential.

In this newsletter, we offer some suggestions for current Elevate and Ascend partners; opportunities to raise funds to get started with Elevate; and amazing career opportunities with PERTS!


** Start the Year Strong!
------------------------------------------------------------

Maximize Student Participation
Did you know you can track survey participation to ensure high completion rates? The Participation Dashboard tracks survey participation by Class Lead, Class, Community, and even by student.
Learn How to View Student Participation (https://perts.freshdesk.com/support/solutions/articles/67000677400-how-to-use-the-community-participation-dashboard)


Achieve High Communication Fidelity
A recent analysis (https://perts.net/research/fidelity-predicts-improvement) revealed that when communication fidelity is high, learning conditions improve more significantly after four cycles (12-15 percentage points in some classes). Prioritizing communication fidelity scores below 70% and aiming for 90% is essential for improving student experience.
Learn How to Achieve Communication Fidelity (https://perts.freshdesk.com/en/support/solutions/articles/67000671408-how-to-use-communication-fidelity)


** 📢 A Reminder for All Semester-Long Classes!
------------------------------------------------------------

Once your Fall semester classes end, archive the Fall Community to avoid any confusion with Spring semester classes. We also recommend locking your rosters to prevent students from inadvertently accessing the incorrect class survey.
Learn How to Archive a Community (https://perts.freshdesk.com/support/solutions/articles/67000713424-what-is-community-archiving-)
Learn How to Lock Rosters (https://perts.freshdesk.com/support/solutions/articles/67000676915-what-is-roster-locking-)


** New Interface Updates!
------------------------------------------------------------

We’ve made it easier to manage several classes in Elevate and Ascend. Check out new sort features to the Members, Classes, Schedules, and Surveys pages!
Review the Changes to the Surveys Page (https://perts.freshdesk.com/support/solutions/articles/67000729084-orientation-to-the-surveys-page)


** Secure Federal or State Funds for Your Elevate Implementation
------------------------------------------------------------
Eager to get started with Elevate? Federal and state funds are sometimes earmarked for programs that meet specific “tiers of evidence.” In case you missed it, we have compiled this guide to help education leaders secure those funds by citing the evidence tier relevant to their intended Elevate implementation.
Review the ESSA Evidence Tiers for Elevate (https://perts.net/elevate/essa-tiers)


** The Holiday Cheer Continues!
------------------------------------------------------------
The spirit of gift-giving continues! If you're interested in partnering with PERTS to improve learning conditions for your students, enter code NEWYEAR20 when scheduling a consultation and enjoy a generous 20% discount—a gift from us to you!
Schedule a Consultation Today (https://perts.net/consultation)


** Join Our Team!
------------------------------------------------------------
The PERTS team is growing! If you’re passionate about educational equity and eager to make a lasting impact in the field, take a look at our open roles and apply before the upcoming deadlines!
Research Fellow - Apply by 1/31 (https://perts.net/researchfellow)
Partnership Manager, Higher Education - Apply by 2/5 (https://perts.net/partnershipmanager)


** Welcome Back, Erin!
------------------------------------------------------------

Erin Ashoka, Partnership Manager, has returned from parental leave! In July, Erin had her first baby, Oak.

She is back to supporting partners and leading the Elevate Facilitator Network. Welcome back, Erin!
“
Don't be offended at the responses in the beginning. Use it as an opportunity to give students a voice into building a community with you. Students love to see their suggestions implemented into the class. They can see the growth.

Elevate User
Our Programs
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=c369b92932)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=c369b92932)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2024-01-18 21:19 UTC, rumenPERTS commented
January 2024
PERTS Newsletter


** Happy New Year from PERTS! 🎉
------------------------------------------------------------

The new year often presents a starting point for new or refreshed intentions. We hope you started the year feeling inspired to create learning experiences for students that will help them achieve their fullest potential.

In this newsletter, we offer some suggestions for current Elevate and Ascend partners; opportunities to raise funds to get started with Elevate; and amazing career opportunities with PERTS!


** Start the Year Strong!
------------------------------------------------------------

Maximize Student Participation
Did you know you can track survey participation to ensure high completion rates? The Participation Dashboard tracks survey participation by Class Lead, Class, Community, and even by student.
Learn How to View Student Participation (https://perts.freshdesk.com/support/solutions/articles/67000677400-how-to-use-the-community-participation-dashboard)


Achieve High Communication Fidelity
A recent analysis (https://perts.net/research/fidelity-predicts-improvement) revealed that when communication fidelity is high, learning conditions improve more significantly after four cycles (12-15 percentage points in some classes). Prioritizing communication fidelity scores below 70% and aiming for 90% is essential for improving student experience.
Learn How to Achieve Communication Fidelity (https://perts.freshdesk.com/en/support/solutions/articles/67000671408-how-to-use-communication-fidelity)


** 📢 A Reminder for All Semester-Long Classes!
------------------------------------------------------------

Once your Fall semester classes end, archive the Fall Community to avoid any confusion with Spring semester classes. We also recommend locking your rosters to prevent students from inadvertently accessing the incorrect class survey.
Learn How to Archive a Community (https://perts.freshdesk.com/support/solutions/articles/67000713424-what-is-community-archiving-)
Learn How to Lock Rosters (https://perts.freshdesk.com/support/solutions/articles/67000676915-what-is-roster-locking-)


** New Interface Updates!
------------------------------------------------------------

We’ve made it easier to manage several classes in Elevate and Ascend. Check out new sort features to the Members, Classes, Schedules, and Surveys pages!
Review the Changes to the Surveys Page (https://perts.freshdesk.com/support/solutions/articles/67000729084-orientation-to-the-surveys-page)


** Secure Federal or State Funds for Your Elevate Implementation
------------------------------------------------------------
Eager to get started with Elevate? Federal and state funds are sometimes earmarked for programs that meet specific “tiers of evidence.” In case you missed it, we have compiled this guide to help education leaders secure those funds by citing the evidence tier relevant to their intended Elevate implementation.
Review the ESSA Evidence Tiers for Elevate (https://perts.net/elevate/essa-tiers)


** The Holiday Cheer Continues!
------------------------------------------------------------
The spirit of gift-giving continues! If you're interested in partnering with PERTS to improve learning conditions for your students, enter code NEWYEAR20 when scheduling a consultation and enjoy a generous 20% discount—a gift from us to you!
Schedule a Consultation Today (https://perts.net/consultation)


** Join Our Team!
------------------------------------------------------------
The PERTS team is growing! If you’re passionate about educational equity and eager to make a lasting impact in the field, take a look at our open roles and apply before the upcoming deadlines!
Research Fellow - Apply by 1/31 (https://perts.net/researchfellow)
Partnership Manager, Higher Education - Apply by 2/5 (https://perts.net/partnershipmanager)


** Welcome Back, Erin!
------------------------------------------------------------

Erin Ashoka, Partnership Manager, has returned from parental leave! In July, Erin had her first baby, Oak.

She is back to supporting partners and leading the Elevate Facilitator Network. Welcome back, Erin!
“
Don't be offended at the responses in the beginning. Use it as an opportunity to give students a voice into building a community with you. Students love to see their suggestions implemented into the class. They can see the growth.

Elevate User
Our Programs
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=c369b92932)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=c369b92932)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2024-01-18 21:21 UTC, rumenPERTS commented
January 2024
PERTS Newsletter


** Happy New Year from PERTS! 🎉
------------------------------------------------------------

The new year often presents a starting point for new or refreshed intentions. We hope you started the year feeling inspired to create learning experiences for students that will help them achieve their fullest potential.

In this newsletter, we offer some suggestions for current Elevate and Ascend partners; opportunities to raise funds to get started with Elevate; and amazing career opportunities with PERTS!


** Start the Year Strong!
------------------------------------------------------------

Maximize Student Participation
Did you know you can track survey participation to ensure high completion rates? The Participation Dashboard tracks survey participation by Class Lead, Class, Community, and even by student.
Learn How to View Student Participation (https://perts.freshdesk.com/support/solutions/articles/67000677400-how-to-use-the-community-participation-dashboard)


Achieve High Communication Fidelity
A recent analysis (https://perts.net/research/fidelity-predicts-improvement) revealed that when communication fidelity is high, learning conditions improve more significantly after four cycles (12-15 percentage points in some classes). Prioritizing communication fidelity scores below 70% and aiming for 90% is essential for improving student experience.
Learn How to Achieve Communication Fidelity (https://perts.freshdesk.com/en/support/solutions/articles/67000671408-how-to-use-communication-fidelity)


** 📢 A Reminder for All Semester-Long Classes!
------------------------------------------------------------

Once your Fall semester classes end, archive the Fall Community to avoid any confusion with Spring semester classes. We also recommend locking your rosters to prevent students from inadvertently accessing the incorrect class survey.
Learn How to Archive a Community (https://perts.freshdesk.com/support/solutions/articles/67000713424-what-is-community-archiving-)
Learn How to Lock Rosters (https://perts.freshdesk.com/support/solutions/articles/67000676915-what-is-roster-locking-)


** New Interface Updates!
------------------------------------------------------------

We’ve made it easier to manage several classes in Elevate and Ascend. Check out new sort features to the Members, Classes, Schedules, and Surveys pages!
Review the Changes to the Surveys Page (https://perts.freshdesk.com/support/solutions/articles/67000729084-orientation-to-the-surveys-page)


** Secure Federal or State Funds for Your Elevate Implementation
------------------------------------------------------------
Eager to get started with Elevate? Federal and state funds are sometimes earmarked for programs that meet specific “tiers of evidence.” In case you missed it, we have compiled this guide to help education leaders secure those funds by citing the evidence tier relevant to their intended Elevate implementation.
Review the ESSA Evidence Tiers for Elevate (https://perts.net/elevate/essa-tiers)


** The Holiday Cheer Continues!
------------------------------------------------------------
The spirit of gift-giving continues! If you're interested in partnering with PERTS to improve learning conditions for your students, enter code NEWYEAR20 when scheduling a consultation and enjoy a generous 20% discount—a gift from us to you!
Schedule a Consultation Today (https://perts.net/consultation)


** Join Our Team!
------------------------------------------------------------
The PERTS team is growing! If you’re passionate about educational equity and eager to make a lasting impact in the field, take a look at our open roles and apply before the upcoming deadlines!
Research Fellow - Apply by 1/31 (https://perts.net/researchfellow)
Partnership Manager, Higher Education - Apply by 2/5 (https://perts.net/partnershipmanager)


** Welcome Back, Erin!
------------------------------------------------------------

Erin Ashoka, Partnership Manager, has returned from parental leave! In July, Erin had her first baby, Oak.

She is back to supporting partners and leading the Elevate Facilitator Network. Welcome back, Erin!
“
Don't be offended at the responses in the beginning. Use it as an opportunity to give students a voice into building a community with you. Students love to see their suggestions implemented into the class. They can see the growth.

Elevate User
Our Programs
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=c369b92932)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=c369b92932)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2024-01-18 21:21 UTC, rumenPERTS commented
January 2024
PERTS Newsletter


** Happy New Year from PERTS! 🎉
------------------------------------------------------------

The new year often presents a starting point for new or refreshed intentions. We hope you started the year feeling inspired to create learning experiences for students that will help them achieve their fullest potential.

In this newsletter, we offer some suggestions for current Elevate and Ascend partners; opportunities to raise funds to get started with Elevate; and amazing career opportunities with PERTS!


** Start the Year Strong!
------------------------------------------------------------

Maximize Student Participation
Did you know you can track survey participation to ensure high completion rates? The Participation Dashboard tracks survey participation by Class Lead, Class, Community, and even by student.
Learn How to View Student Participation (https://perts.freshdesk.com/support/solutions/articles/67000677400-how-to-use-the-community-participation-dashboard)


Achieve High Communication Fidelity
A recent analysis (https://perts.net/research/fidelity-predicts-improvement) revealed that when communication fidelity is high, learning conditions improve more significantly after four cycles (12-15 percentage points in some classes). Prioritizing communication fidelity scores below 70% and aiming for 90% is essential for improving student experience.
Learn How to Achieve Communication Fidelity (https://perts.freshdesk.com/en/support/solutions/articles/67000671408-how-to-use-communication-fidelity)


** 📢 A Reminder for All Semester-Long Classes!
------------------------------------------------------------

Once your Fall semester classes end, archive the Fall Community to avoid any confusion with Spring semester classes. We also recommend locking your rosters to prevent students from inadvertently accessing the incorrect class survey.
Learn How to Archive a Community (https://perts.freshdesk.com/support/solutions/articles/67000713424-what-is-community-archiving-)
Learn How to Lock Rosters (https://perts.freshdesk.com/support/solutions/articles/67000676915-what-is-roster-locking-)


** New Interface Updates!
------------------------------------------------------------

We’ve made it easier to manage several classes in Elevate and Ascend. Check out new sort features to the Members, Classes, Schedules, and Surveys pages!
Review the Changes to the Surveys Page (https://perts.freshdesk.com/support/solutions/articles/67000729084-orientation-to-the-surveys-page)


** Secure Federal or State Funds for Your Elevate Implementation
------------------------------------------------------------
Eager to get started with Elevate? Federal and state funds are sometimes earmarked for programs that meet specific “tiers of evidence.” In case you missed it, we have compiled this guide to help education leaders secure those funds by citing the evidence tier relevant to their intended Elevate implementation.
Review the ESSA Evidence Tiers for Elevate (https://perts.net/elevate/essa-tiers)


** The Holiday Cheer Continues!
------------------------------------------------------------
The spirit of gift-giving continues! If you're interested in partnering with PERTS to improve learning conditions for your students, enter code NEWYEAR20 when scheduling a consultation and enjoy a generous 20% discount—a gift from us to you!
Schedule a Consultation Today (https://perts.net/consultation)


** Join Our Team!
------------------------------------------------------------
The PERTS team is growing! If you’re passionate about educational equity and eager to make a lasting impact in the field, take a look at our open roles and apply before the upcoming deadlines!
Research Fellow - Apply by 1/31 (https://perts.net/researchfellow)
Partnership Manager, Higher Education - Apply by 2/5 (https://perts.net/partnershipmanager)


** Welcome Back, Erin!
------------------------------------------------------------

Erin Ashoka, Partnership Manager, has returned from parental leave! In July, Erin had her first baby, Oak.

She is back to supporting partners and leading the Elevate Facilitator Network. Welcome back, Erin!
“
Don't be offended at the responses in the beginning. Use it as an opportunity to give students a voice into building a community with you. Students love to see their suggestions implemented into the class. They can see the growth.

Elevate User
Our Programs
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=c369b92932)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=c369b92932)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2024-01-18 21:23 UTC, rumenPERTS commented
January 2024
PERTS Newsletter


** Happy New Year from PERTS! 🎉
------------------------------------------------------------

The new year often presents a starting point for new or refreshed intentions. We hope you started the year feeling inspired to create learning experiences for students that will help them achieve their fullest potential.

In this newsletter, we offer some suggestions for current Elevate and Ascend partners; opportunities to raise funds to get started with Elevate; and amazing career opportunities with PERTS!


** Start the Year Strong!
------------------------------------------------------------

Maximize Student Participation
Did you know you can track survey participation to ensure high completion rates? The Participation Dashboard tracks survey participation by Class Lead, Class, Community, and even by student.
Learn How to View Student Participation (https://perts.freshdesk.com/support/solutions/articles/67000677400-how-to-use-the-community-participation-dashboard)


Achieve High Communication Fidelity
A recent analysis (https://perts.net/research/fidelity-predicts-improvement) revealed that when communication fidelity is high, learning conditions improve more significantly after four cycles (12-15 percentage points in some classes). Prioritizing communication fidelity scores below 70% and aiming for 90% is essential for improving student experience.
Learn How to Achieve Communication Fidelity (https://perts.freshdesk.com/en/support/solutions/articles/67000671408-how-to-use-communication-fidelity)


** 📢 A Reminder for All Semester-Long Classes!
------------------------------------------------------------

Once your Fall semester classes end, archive the Fall Community to avoid any confusion with Spring semester classes. We also recommend locking your rosters to prevent students from inadvertently accessing the incorrect class survey.
Learn How to Archive a Community (https://perts.freshdesk.com/support/solutions/articles/67000713424-what-is-community-archiving-)
Learn How to Lock Rosters (https://perts.freshdesk.com/support/solutions/articles/67000676915-what-is-roster-locking-)


** New Interface Updates!
------------------------------------------------------------

We’ve made it easier to manage several classes in Elevate and Ascend. Check out new sort features to the Members, Classes, Schedules, and Surveys pages!
Review the Changes to the Surveys Page (https://perts.freshdesk.com/support/solutions/articles/67000729084-orientation-to-the-surveys-page)


** Secure Federal or State Funds for Your Elevate Implementation
------------------------------------------------------------
Eager to get started with Elevate? Federal and state funds are sometimes earmarked for programs that meet specific “tiers of evidence.” In case you missed it, we have compiled this guide to help education leaders secure those funds by citing the evidence tier relevant to their intended Elevate implementation.
Review the ESSA Evidence Tiers for Elevate (https://perts.net/elevate/essa-tiers)


** The Holiday Cheer Continues!
------------------------------------------------------------
The spirit of gift-giving continues! If you're interested in partnering with PERTS to improve learning conditions for your students, enter code NEWYEAR20 when scheduling a consultation and enjoy a generous 20% discount—a gift from us to you!
Schedule a Consultation Today (https://perts.net/consultation)


** Join Our Team!
------------------------------------------------------------
The PERTS team is growing! If you’re passionate about educational equity and eager to make a lasting impact in the field, take a look at our open roles and apply before the upcoming deadlines!
Research Fellow - Apply by 1/31 (https://perts.net/researchfellow)
Partnership Manager, Higher Education - Apply by 2/5 (https://perts.net/partnershipmanager)


** Welcome Back, Erin!
------------------------------------------------------------

Erin Ashoka, Partnership Manager, has returned from parental leave! In July, Erin had her first baby, Oak.

She is back to supporting partners and leading the Elevate Facilitator Network. Welcome back, Erin!
“
Don't be offended at the responses in the beginning. Use it as an opportunity to give students a voice into building a community with you. Students love to see their suggestions implemented into the class. They can see the growth.

Elevate User
Our Programs
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=c369b92932)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=c369b92932)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2024-01-18 21:24 UTC, rumenPERTS commented
January 2024
PERTS Newsletter


** Happy New Year from PERTS! 🎉
------------------------------------------------------------

The new year often presents a starting point for new or refreshed intentions. We hope you started the year feeling inspired to create learning experiences for students that will help them achieve their fullest potential.

In this newsletter, we offer some suggestions for current Elevate and Ascend partners; opportunities to raise funds to get started with Elevate; and amazing career opportunities with PERTS!


** Start the Year Strong!
------------------------------------------------------------

Maximize Student Participation
Did you know you can track survey participation to ensure high completion rates? The Participation Dashboard tracks survey participation by Class Lead, Class, Community, and even by student.
Learn How to View Student Participation (https://perts.freshdesk.com/support/solutions/articles/67000677400-how-to-use-the-community-participation-dashboard)


Achieve High Communication Fidelity
A recent analysis (https://perts.net/research/fidelity-predicts-improvement) revealed that when communication fidelity is high, learning conditions improve more significantly after four cycles (12-15 percentage points in some classes). Prioritizing communication fidelity scores below 70% and aiming for 90% is essential for improving student experience.
Learn How to Achieve Communication Fidelity (https://perts.freshdesk.com/en/support/solutions/articles/67000671408-how-to-use-communication-fidelity)


** 📢 A Reminder for All Semester-Long Classes!
------------------------------------------------------------

Once your Fall semester classes end, archive the Fall Community to avoid any confusion with Spring semester classes. We also recommend locking your rosters to prevent students from inadvertently accessing the incorrect class survey.
Learn How to Archive a Community (https://perts.freshdesk.com/support/solutions/articles/67000713424-what-is-community-archiving-)
Learn How to Lock Rosters (https://perts.freshdesk.com/support/solutions/articles/67000676915-what-is-roster-locking-)


** New Interface Updates!
------------------------------------------------------------

We’ve made it easier to manage several classes in Elevate and Ascend. Check out new sort features to the Members, Classes, Schedules, and Surveys pages!
Review the Changes to the Surveys Page (https://perts.freshdesk.com/support/solutions/articles/67000729084-orientation-to-the-surveys-page)


** Secure Federal or State Funds for Your Elevate Implementation
------------------------------------------------------------
Eager to get started with Elevate? Federal and state funds are sometimes earmarked for programs that meet specific “tiers of evidence.” In case you missed it, we have compiled this guide to help education leaders secure those funds by citing the evidence tier relevant to their intended Elevate implementation.
Review the ESSA Evidence Tiers for Elevate (https://perts.net/elevate/essa-tiers)


** The Holiday Cheer Continues!
------------------------------------------------------------
The spirit of gift-giving continues! If you're interested in partnering with PERTS to improve learning conditions for your students, enter code NEWYEAR20 when scheduling a consultation and enjoy a generous 20% discount—a gift from us to you!
Schedule a Consultation Today (https://perts.net/consultation)


** Join Our Team!
------------------------------------------------------------
The PERTS team is growing! If you’re passionate about educational equity and eager to make a lasting impact in the field, take a look at our open roles and apply before the upcoming deadlines!
Research Fellow - Apply by 1/31 (https://perts.net/researchfellow)
Partnership Manager, Higher Education - Apply by 2/5 (https://perts.net/partnershipmanager)


** Welcome Back, Erin!
------------------------------------------------------------

Erin Ashoka, Partnership Manager, has returned from parental leave! In July, Erin had her first baby, Oak.

She is back to supporting partners and leading the Elevate Facilitator Network. Welcome back, Erin!
“
Don't be offended at the responses in the beginning. Use it as an opportunity to give students a voice into building a community with you. Students love to see their suggestions implemented into the class. They can see the growth.

Elevate User
Our Programs
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=c3d5069a39&c=c369b92932)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=c3d5069a39&c=c369b92932)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2024-02-14 18:15 UTC, rumenPERTS commented
February 2024
PERTS Newsletter
As we celebrate the significance of Black History Month, we reflect on how we've woven threads of equity and empathy into the fabric of our programs.

In collaboration with our partners, we continue our mission to amplify the voices of students and foster learning conditions that promote equity and inclusivity for all.


** New Year, New Look!
------------------------------------------------------------
We have some exciting news: the PERTS website just got a makeover! PERTS has evolved over the last several years and our updated website better represents where we are as an organization. It’s also packed with new features, enhanced navigation, and a fresh look to make your browsing experience even better.
Visit Our Updated Website! (https://perts.net)


** A Clear Focus on Equity
------------------------------------------------------------
The disaggregation options in the Student Experience Overview in Elevate & Ascend reports can provide opportunities to uncover experience gaps across groups of students and can be a great starting point to promote equity.
Learn about the Student Experience Overview (https://perts.freshdesk.com/support/solutions/articles/67000671391-how-to-use-the-student-experience-overview)
Oftentimes, specific groups of individuals are situated further from opportunity. Using the Focal Group feature allows teachers to define a custom group and review disaggregated data for those specific students.
Featured: Focal Groups (https://perts.freshdesk.com/support/solutions/articles/67000443219-what-is-a-focal-group-and-how-do-i-set-one-up-)
Hear directly from students who have experienced positive learning outcomes in classrooms that used Elevate or Ascend.
Listen to Kanaan, Finali, and Nina (https://elevate-support.perts.net/support/solutions/articles/67000713388-student-reflections-on-learning-conditions#studentexperience) share their appreciation of Elevate and the opportunity to amplify their voices.

Hear from Iyana and other students (https://ascend-support.perts.net/support/solutions/articles/67000717955-student-reflections-on-instructors-implementing-ascend#cypress) on how instructors used Ascend to improve their overall college experience.

“
Students feel the Elevate data is actionable and teachers have found that sometimes it is small, consistent changes that matter.

Elevate User


** Join Us at the 2024 Carnegie Summit!
------------------------------------------------------------
We’re delighted to share that we’ve been invited to present at the 2024 Carnegie Foundation Summit on Improvement in Education! This event is dedicated to addressing educational inequities and learning together how to transform education systems.

In our session, we will share what we’ve learned about how students' views on surveys impact classroom improvements, introduce a new single-item process measure to gauge students’ views, and present research showing that this process measure helps account for where we do and do not see improvement in the survey data. Attendees will hear from a panel of educators about their efforts to collect student surveys in genuine partnership with students. The session will conclude with concrete practices and an easy-to-use measure for increasing students’ investment in surveys for improvement.

Dates: March 24-27, 2024
Location: Marriott Marquis San Diego Marina

Register to Secure Your Spot! (https://www.carnegiefoundation.org/carnegie-summit/)


** Did You Know?
------------------------------------------------------------
Did you know you can combine all of your Class reports into one Community report? A Community report can help synthesize data and may provide more robust disaggregated data.
Learn How to Combine Class Reports (https://perts.freshdesk.com/support/solutions/articles/67000729678-can-i-combine-my-class-group-reports-into-a-single-community-report-)


** Interested in a FREE license to pilot Elevate or Ascend this semester?
------------------------------------------------------------
A low-stakes pilot allows educators to learn the platform, build teacher buy-in, and develop a thorough implementation plan for next year! Use code PILOT2024 when you schedule a consultation and earn a free pilot for this semester!
Learn More about the Pilot Program (http://perts.net/consultation)


** Congratulations, Allison!
------------------------------------------------------------

Dr. Allison Londerée, Data Analyst at PERTS, has received her Doctorate in Social Psychology from Ohio State University! Allison co-authored our research report (https://perts.net/research/early-indicators)  and conducted extensive analyses to validate our measurement system. Her most recent analyses will be featured in our upcoming session at the Carnegie Summit in March 2024!

We extend our gratitude for Allison’s contributions. She has been an invaluable part of our team and we wish her continued success in her new role as a Data Scientist at Lirio!
“
Give your students more opportunities with their voice to find out how they want to learn.

Elevate User
Quick Links
Elevate, for Grades 6-12 (http://perts.net/elevate)
Ascend, for Higher Ed (http://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=bd172521c3)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f97dc5981b&c=bd172521c3)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2024-02-14 18:15 UTC, rumenPERTS commented
February 2024
PERTS Newsletter
As we celebrate the significance of Black History Month, we reflect on how we've woven threads of equity and empathy into the fabric of our programs.

In collaboration with our partners, we continue our mission to amplify the voices of students and foster learning conditions that promote equity and inclusivity for all.


** New Year, New Look!
------------------------------------------------------------
We have some exciting news: the PERTS website just got a makeover! PERTS has evolved over the last several years and our updated website better represents where we are as an organization. It’s also packed with new features, enhanced navigation, and a fresh look to make your browsing experience even better.
Visit Our Updated Website! (https://perts.net)


** A Clear Focus on Equity
------------------------------------------------------------
The disaggregation options in the Student Experience Overview in Elevate & Ascend reports can provide opportunities to uncover experience gaps across groups of students and can be a great starting point to promote equity.
Learn about the Student Experience Overview (https://perts.freshdesk.com/support/solutions/articles/67000671391-how-to-use-the-student-experience-overview)
Oftentimes, specific groups of individuals are situated further from opportunity. Using the Focal Group feature allows teachers to define a custom group and review disaggregated data for those specific students.
Featured: Focal Groups (https://perts.freshdesk.com/support/solutions/articles/67000443219-what-is-a-focal-group-and-how-do-i-set-one-up-)
Hear directly from students who have experienced positive learning outcomes in classrooms that used Elevate or Ascend.
Listen to Kanaan, Finali, and Nina (https://elevate-support.perts.net/support/solutions/articles/67000713388-student-reflections-on-learning-conditions#studentexperience) share their appreciation of Elevate and the opportunity to amplify their voices.

Hear from Iyana and other students (https://ascend-support.perts.net/support/solutions/articles/67000717955-student-reflections-on-instructors-implementing-ascend#cypress) on how instructors used Ascend to improve their overall college experience.

“
Students feel the Elevate data is actionable and teachers have found that sometimes it is small, consistent changes that matter.

Elevate User


** Join Us at the 2024 Carnegie Summit!
------------------------------------------------------------
We’re delighted to share that we’ve been invited to present at the 2024 Carnegie Foundation Summit on Improvement in Education! This event is dedicated to addressing educational inequities and learning together how to transform education systems.

In our session, we will share what we’ve learned about how students' views on surveys impact classroom improvements, introduce a new single-item process measure to gauge students’ views, and present research showing that this process measure helps account for where we do and do not see improvement in the survey data. Attendees will hear from a panel of educators about their efforts to collect student surveys in genuine partnership with students. The session will conclude with concrete practices and an easy-to-use measure for increasing students’ investment in surveys for improvement.

Dates: March 24-27, 2024
Location: Marriott Marquis San Diego Marina

Register to Secure Your Spot! (https://www.carnegiefoundation.org/carnegie-summit/)


** Did You Know?
------------------------------------------------------------
Did you know you can combine all of your Class reports into one Community report? A Community report can help synthesize data and may provide more robust disaggregated data.
Learn How to Combine Class Reports (https://perts.freshdesk.com/support/solutions/articles/67000729678-can-i-combine-my-class-group-reports-into-a-single-community-report-)


** Interested in a FREE license to pilot Elevate or Ascend this semester?
------------------------------------------------------------
A low-stakes pilot allows educators to learn the platform, build teacher buy-in, and develop a thorough implementation plan for next year! Use code PILOT2024 when you schedule a consultation and earn a free pilot for this semester!
Learn More about the Pilot Program (http://perts.net/consultation)


** Congratulations, Allison!
------------------------------------------------------------

Dr. Allison Londerée, Data Analyst at PERTS, has received her Doctorate in Social Psychology from Ohio State University! Allison co-authored our research report (https://perts.net/research/early-indicators)  and conducted extensive analyses to validate our measurement system. Her most recent analyses will be featured in our upcoming session at the Carnegie Summit in March 2024!

We extend our gratitude for Allison’s contributions. She has been an invaluable part of our team and we wish her continued success in her new role as a Data Scientist at Lirio!
“
Give your students more opportunities with their voice to find out how they want to learn.

Elevate User
Quick Links
Elevate, for Grades 6-12 (http://perts.net/elevate)
Ascend, for Higher Ed (http://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=bd172521c3)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f66b76caa6&c=bd172521c3)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2024-02-14 18:15 UTC, rumenPERTS commented
February 2024
PERTS Newsletter
As we celebrate the significance of Black History Month, we reflect on how we've woven threads of equity and empathy into the fabric of our programs.

In collaboration with our partners, we continue our mission to amplify the voices of students and foster learning conditions that promote equity and inclusivity for all.


** New Year, New Look!
------------------------------------------------------------
We have some exciting news: the PERTS website just got a makeover! PERTS has evolved over the last several years and our updated website better represents where we are as an organization. It’s also packed with new features, enhanced navigation, and a fresh look to make your browsing experience even better.
Visit Our Updated Website! (https://perts.net)


** A Clear Focus on Equity
------------------------------------------------------------
The disaggregation options in the Student Experience Overview in Elevate & Ascend reports can provide opportunities to uncover experience gaps across groups of students and can be a great starting point to promote equity.
Learn about the Student Experience Overview (https://perts.freshdesk.com/support/solutions/articles/67000671391-how-to-use-the-student-experience-overview)
Oftentimes, specific groups of individuals are situated further from opportunity. Using the Focal Group feature allows teachers to define a custom group and review disaggregated data for those specific students.
Featured: Focal Groups (https://perts.freshdesk.com/support/solutions/articles/67000443219-what-is-a-focal-group-and-how-do-i-set-one-up-)
Hear directly from students who have experienced positive learning outcomes in classrooms that used Elevate or Ascend.
Listen to Kanaan, Finali, and Nina (https://elevate-support.perts.net/support/solutions/articles/67000713388-student-reflections-on-learning-conditions#studentexperience) share their appreciation of Elevate and the opportunity to amplify their voices.

Hear from Iyana and other students (https://ascend-support.perts.net/support/solutions/articles/67000717955-student-reflections-on-instructors-implementing-ascend#cypress) on how instructors used Ascend to improve their overall college experience.

“
Students feel the Elevate data is actionable and teachers have found that sometimes it is small, consistent changes that matter.

Elevate User


** Join Us at the 2024 Carnegie Summit!
------------------------------------------------------------
We’re delighted to share that we’ve been invited to present at the 2024 Carnegie Foundation Summit on Improvement in Education! This event is dedicated to addressing educational inequities and learning together how to transform education systems.

In our session, we will share what we’ve learned about how students' views on surveys impact classroom improvements, introduce a new single-item process measure to gauge students’ views, and present research showing that this process measure helps account for where we do and do not see improvement in the survey data. Attendees will hear from a panel of educators about their efforts to collect student surveys in genuine partnership with students. The session will conclude with concrete practices and an easy-to-use measure for increasing students’ investment in surveys for improvement.

Dates: March 24-27, 2024
Location: Marriott Marquis San Diego Marina

Register to Secure Your Spot! (https://www.carnegiefoundation.org/carnegie-summit/)


** Did You Know?
------------------------------------------------------------
Did you know you can combine all of your Class reports into one Community report? A Community report can help synthesize data and may provide more robust disaggregated data.
Learn How to Combine Class Reports (https://perts.freshdesk.com/support/solutions/articles/67000729678-can-i-combine-my-class-group-reports-into-a-single-community-report-)


** Interested in a FREE license to pilot Elevate or Ascend this semester?
------------------------------------------------------------
A low-stakes pilot allows educators to learn the platform, build teacher buy-in, and develop a thorough implementation plan for next year! Use code PILOT2024 when you schedule a consultation and earn a free pilot for this semester!
Learn More about the Pilot Program (http://perts.net/consultation)


** Congratulations, Allison!
------------------------------------------------------------

Dr. Allison Londerée, Data Analyst at PERTS, has received her Doctorate in Social Psychology from Ohio State University! Allison co-authored our research report (https://perts.net/research/early-indicators)  and conducted extensive analyses to validate our measurement system. Her most recent analyses will be featured in our upcoming session at the Carnegie Summit in March 2024!

We extend our gratitude for Allison’s contributions. She has been an invaluable part of our team and we wish her continued success in her new role as a Data Scientist at Lirio!
“
Give your students more opportunities with their voice to find out how they want to learn.

Elevate User
Quick Links
Elevate, for Grades 6-12 (http://perts.net/elevate)
Ascend, for Higher Ed (http://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=bd172521c3)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=da5cd98d77&c=bd172521c3)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2024-02-14 18:16 UTC, rumenPERTS commented
February 2024
PERTS Newsletter
As we celebrate the significance of Black History Month, we reflect on how we've woven threads of equity and empathy into the fabric of our programs.

In collaboration with our partners, we continue our mission to amplify the voices of students and foster learning conditions that promote equity and inclusivity for all.


** New Year, New Look!
------------------------------------------------------------
We have some exciting news: the PERTS website just got a makeover! PERTS has evolved over the last several years and our updated website better represents where we are as an organization. It’s also packed with new features, enhanced navigation, and a fresh look to make your browsing experience even better.
Visit Our Updated Website! (https://perts.net)


** A Clear Focus on Equity
------------------------------------------------------------
The disaggregation options in the Student Experience Overview in Elevate & Ascend reports can provide opportunities to uncover experience gaps across groups of students and can be a great starting point to promote equity.
Learn about the Student Experience Overview (https://perts.freshdesk.com/support/solutions/articles/67000671391-how-to-use-the-student-experience-overview)
Oftentimes, specific groups of individuals are situated further from opportunity. Using the Focal Group feature allows teachers to define a custom group and review disaggregated data for those specific students.
Featured: Focal Groups (https://perts.freshdesk.com/support/solutions/articles/67000443219-what-is-a-focal-group-and-how-do-i-set-one-up-)
Hear directly from students who have experienced positive learning outcomes in classrooms that used Elevate or Ascend.
Listen to Kanaan, Finali, and Nina (https://elevate-support.perts.net/support/solutions/articles/67000713388-student-reflections-on-learning-conditions#studentexperience) share their appreciation of Elevate and the opportunity to amplify their voices.

Hear from Iyana and other students (https://ascend-support.perts.net/support/solutions/articles/67000717955-student-reflections-on-instructors-implementing-ascend#cypress) on how instructors used Ascend to improve their overall college experience.

“
Students feel the Elevate data is actionable and teachers have found that sometimes it is small, consistent changes that matter.

Elevate User


** Join Us at the 2024 Carnegie Summit!
------------------------------------------------------------
We’re delighted to share that we’ve been invited to present at the 2024 Carnegie Foundation Summit on Improvement in Education! This event is dedicated to addressing educational inequities and learning together how to transform education systems.

In our session, we will share what we’ve learned about how students' views on surveys impact classroom improvements, introduce a new single-item process measure to gauge students’ views, and present research showing that this process measure helps account for where we do and do not see improvement in the survey data. Attendees will hear from a panel of educators about their efforts to collect student surveys in genuine partnership with students. The session will conclude with concrete practices and an easy-to-use measure for increasing students’ investment in surveys for improvement.

Dates: March 24-27, 2024
Location: Marriott Marquis San Diego Marina

Register to Secure Your Spot! (https://www.carnegiefoundation.org/carnegie-summit/)


** Did You Know?
------------------------------------------------------------
Did you know you can combine all of your Class reports into one Community report? A Community report can help synthesize data and may provide more robust disaggregated data.
Learn How to Combine Class Reports (https://perts.freshdesk.com/support/solutions/articles/67000729678-can-i-combine-my-class-group-reports-into-a-single-community-report-)


** Interested in a FREE license to pilot Elevate or Ascend this semester?
------------------------------------------------------------
A low-stakes pilot allows educators to learn the platform, build teacher buy-in, and develop a thorough implementation plan for next year! Use code PILOT2024 when you schedule a consultation and earn a free pilot for this semester!
Learn More about the Pilot Program (http://perts.net/consultation)


** Congratulations, Allison!
------------------------------------------------------------

Dr. Allison Londerée, Data Analyst at PERTS, has received her Doctorate in Social Psychology from Ohio State University! Allison co-authored our research report (https://perts.net/research/early-indicators)  and conducted extensive analyses to validate our measurement system. Her most recent analyses will be featured in our upcoming session at the Carnegie Summit in March 2024!

We extend our gratitude for Allison’s contributions. She has been an invaluable part of our team and we wish her continued success in her new role as a Data Scientist at Lirio!
“
Give your students more opportunities with their voice to find out how they want to learn.

Elevate User
Quick Links
Elevate, for Grades 6-12 (http://perts.net/elevate)
Ascend, for Higher Ed (http://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=bd172521c3)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=b4edfd0dd8&c=bd172521c3)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2024-02-14 18:16 UTC, rumenPERTS commented
February 2024
PERTS Newsletter
As we celebrate the significance of Black History Month, we reflect on how we've woven threads of equity and empathy into the fabric of our programs.

In collaboration with our partners, we continue our mission to amplify the voices of students and foster learning conditions that promote equity and inclusivity for all.


** New Year, New Look!
------------------------------------------------------------
We have some exciting news: the PERTS website just got a makeover! PERTS has evolved over the last several years and our updated website better represents where we are as an organization. It’s also packed with new features, enhanced navigation, and a fresh look to make your browsing experience even better.
Visit Our Updated Website! (https://perts.net)


** A Clear Focus on Equity
------------------------------------------------------------
The disaggregation options in the Student Experience Overview in Elevate & Ascend reports can provide opportunities to uncover experience gaps across groups of students and can be a great starting point to promote equity.
Learn about the Student Experience Overview (https://perts.freshdesk.com/support/solutions/articles/67000671391-how-to-use-the-student-experience-overview)
Oftentimes, specific groups of individuals are situated further from opportunity. Using the Focal Group feature allows teachers to define a custom group and review disaggregated data for those specific students.
Featured: Focal Groups (https://perts.freshdesk.com/support/solutions/articles/67000443219-what-is-a-focal-group-and-how-do-i-set-one-up-)
Hear directly from students who have experienced positive learning outcomes in classrooms that used Elevate or Ascend.
Listen to Kanaan, Finali, and Nina (https://elevate-support.perts.net/support/solutions/articles/67000713388-student-reflections-on-learning-conditions#studentexperience) share their appreciation of Elevate and the opportunity to amplify their voices.

Hear from Iyana and other students (https://ascend-support.perts.net/support/solutions/articles/67000717955-student-reflections-on-instructors-implementing-ascend#cypress) on how instructors used Ascend to improve their overall college experience.

“
Students feel the Elevate data is actionable and teachers have found that sometimes it is small, consistent changes that matter.

Elevate User


** Join Us at the 2024 Carnegie Summit!
------------------------------------------------------------
We’re delighted to share that we’ve been invited to present at the 2024 Carnegie Foundation Summit on Improvement in Education! This event is dedicated to addressing educational inequities and learning together how to transform education systems.

In our session, we will share what we’ve learned about how students' views on surveys impact classroom improvements, introduce a new single-item process measure to gauge students’ views, and present research showing that this process measure helps account for where we do and do not see improvement in the survey data. Attendees will hear from a panel of educators about their efforts to collect student surveys in genuine partnership with students. The session will conclude with concrete practices and an easy-to-use measure for increasing students’ investment in surveys for improvement.

Dates: March 24-27, 2024
Location: Marriott Marquis San Diego Marina

Register to Secure Your Spot! (https://www.carnegiefoundation.org/carnegie-summit/)


** Did You Know?
------------------------------------------------------------
Did you know you can combine all of your Class reports into one Community report? A Community report can help synthesize data and may provide more robust disaggregated data.
Learn How to Combine Class Reports (https://perts.freshdesk.com/support/solutions/articles/67000729678-can-i-combine-my-class-group-reports-into-a-single-community-report-)


** Interested in a FREE license to pilot Elevate or Ascend this semester?
------------------------------------------------------------
A low-stakes pilot allows educators to learn the platform, build teacher buy-in, and develop a thorough implementation plan for next year! Use code PILOT2024 when you schedule a consultation and earn a free pilot for this semester!
Learn More about the Pilot Program (http://perts.net/consultation)


** Congratulations, Allison!
------------------------------------------------------------

Dr. Allison Londerée, Data Analyst at PERTS, has received her Doctorate in Social Psychology from Ohio State University! Allison co-authored our research report (https://perts.net/research/early-indicators)  and conducted extensive analyses to validate our measurement system. Her most recent analyses will be featured in our upcoming session at the Carnegie Summit in March 2024!

We extend our gratitude for Allison’s contributions. She has been an invaluable part of our team and we wish her continued success in her new role as a Data Scientist at Lirio!
“
Give your students more opportunities with their voice to find out how they want to learn.

Elevate User
Quick Links
Elevate, for Grades 6-12 (http://perts.net/elevate)
Ascend, for Higher Ed (http://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=bd172521c3)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=298ead533f&c=bd172521c3)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2024-02-14 18:16 UTC, rumenPERTS commented
February 2024
PERTS Newsletter
As we celebrate the significance of Black History Month, we reflect on how we've woven threads of equity and empathy into the fabric of our programs.

In collaboration with our partners, we continue our mission to amplify the voices of students and foster learning conditions that promote equity and inclusivity for all.


** New Year, New Look!
------------------------------------------------------------
We have some exciting news: the PERTS website just got a makeover! PERTS has evolved over the last several years and our updated website better represents where we are as an organization. It’s also packed with new features, enhanced navigation, and a fresh look to make your browsing experience even better.
Visit Our Updated Website! (https://perts.net)


** A Clear Focus on Equity
------------------------------------------------------------
The disaggregation options in the Student Experience Overview in Elevate & Ascend reports can provide opportunities to uncover experience gaps across groups of students and can be a great starting point to promote equity.
Learn about the Student Experience Overview (https://perts.freshdesk.com/support/solutions/articles/67000671391-how-to-use-the-student-experience-overview)
Oftentimes, specific groups of individuals are situated further from opportunity. Using the Focal Group feature allows teachers to define a custom group and review disaggregated data for those specific students.
Featured: Focal Groups (https://perts.freshdesk.com/support/solutions/articles/67000443219-what-is-a-focal-group-and-how-do-i-set-one-up-)
Hear directly from students who have experienced positive learning outcomes in classrooms that used Elevate or Ascend.
Listen to Kanaan, Finali, and Nina (https://elevate-support.perts.net/support/solutions/articles/67000713388-student-reflections-on-learning-conditions#studentexperience) share their appreciation of Elevate and the opportunity to amplify their voices.

Hear from Iyana and other students (https://ascend-support.perts.net/support/solutions/articles/67000717955-student-reflections-on-instructors-implementing-ascend#cypress) on how instructors used Ascend to improve their overall college experience.

“
Students feel the Elevate data is actionable and teachers have found that sometimes it is small, consistent changes that matter.

Elevate User


** Join Us at the 2024 Carnegie Summit!
------------------------------------------------------------
We’re delighted to share that we’ve been invited to present at the 2024 Carnegie Foundation Summit on Improvement in Education! This event is dedicated to addressing educational inequities and learning together how to transform education systems.

In our session, we will share what we’ve learned about how students' views on surveys impact classroom improvements, introduce a new single-item process measure to gauge students’ views, and present research showing that this process measure helps account for where we do and do not see improvement in the survey data. Attendees will hear from a panel of educators about their efforts to collect student surveys in genuine partnership with students. The session will conclude with concrete practices and an easy-to-use measure for increasing students’ investment in surveys for improvement.

Dates: March 24-27, 2024
Location: Marriott Marquis San Diego Marina

Register to Secure Your Spot! (https://www.carnegiefoundation.org/carnegie-summit/)


** Did You Know?
------------------------------------------------------------
Did you know you can combine all of your Class reports into one Community report? A Community report can help synthesize data and may provide more robust disaggregated data.
Learn How to Combine Class Reports (https://perts.freshdesk.com/support/solutions/articles/67000729678-can-i-combine-my-class-group-reports-into-a-single-community-report-)


** Interested in a FREE license to pilot Elevate or Ascend this semester?
------------------------------------------------------------
A low-stakes pilot allows educators to learn the platform, build teacher buy-in, and develop a thorough implementation plan for next year! Use code PILOT2024 when you schedule a consultation and earn a free pilot for this semester!
Learn More about the Pilot Program (http://perts.net/consultation)


** Congratulations, Allison!
------------------------------------------------------------

Dr. Allison Londerée, Data Analyst at PERTS, has received her Doctorate in Social Psychology from Ohio State University! Allison co-authored our research report (https://perts.net/research/early-indicators)  and conducted extensive analyses to validate our measurement system. Her most recent analyses will be featured in our upcoming session at the Carnegie Summit in March 2024!

We extend our gratitude for Allison’s contributions. She has been an invaluable part of our team and we wish her continued success in her new role as a Data Scientist at Lirio!
“
Give your students more opportunities with their voice to find out how they want to learn.

Elevate User
Quick Links
Elevate, for Grades 6-12 (http://perts.net/elevate)
Ascend, for Higher Ed (http://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=bd172521c3)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=36456eb76b&c=bd172521c3)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2024-02-14 18:16 UTC, rumenPERTS commented
February 2024
PERTS Newsletter
As we celebrate the significance of Black History Month, we reflect on how we've woven threads of equity and empathy into the fabric of our programs.

In collaboration with our partners, we continue our mission to amplify the voices of students and foster learning conditions that promote equity and inclusivity for all.


** New Year, New Look!
------------------------------------------------------------
We have some exciting news: the PERTS website just got a makeover! PERTS has evolved over the last several years and our updated website better represents where we are as an organization. It’s also packed with new features, enhanced navigation, and a fresh look to make your browsing experience even better.
Visit Our Updated Website! (https://perts.net)


** A Clear Focus on Equity
------------------------------------------------------------
The disaggregation options in the Student Experience Overview in Elevate & Ascend reports can provide opportunities to uncover experience gaps across groups of students and can be a great starting point to promote equity.
Learn about the Student Experience Overview (https://perts.freshdesk.com/support/solutions/articles/67000671391-how-to-use-the-student-experience-overview)
Oftentimes, specific groups of individuals are situated further from opportunity. Using the Focal Group feature allows teachers to define a custom group and review disaggregated data for those specific students.
Featured: Focal Groups (https://perts.freshdesk.com/support/solutions/articles/67000443219-what-is-a-focal-group-and-how-do-i-set-one-up-)
Hear directly from students who have experienced positive learning outcomes in classrooms that used Elevate or Ascend.
Listen to Kanaan, Finali, and Nina (https://elevate-support.perts.net/support/solutions/articles/67000713388-student-reflections-on-learning-conditions#studentexperience) share their appreciation of Elevate and the opportunity to amplify their voices.

Hear from Iyana and other students (https://ascend-support.perts.net/support/solutions/articles/67000717955-student-reflections-on-instructors-implementing-ascend#cypress) on how instructors used Ascend to improve their overall college experience.

“
Students feel the Elevate data is actionable and teachers have found that sometimes it is small, consistent changes that matter.

Elevate User


** Join Us at the 2024 Carnegie Summit!
------------------------------------------------------------
We’re delighted to share that we’ve been invited to present at the 2024 Carnegie Foundation Summit on Improvement in Education! This event is dedicated to addressing educational inequities and learning together how to transform education systems.

In our session, we will share what we’ve learned about how students' views on surveys impact classroom improvements, introduce a new single-item process measure to gauge students’ views, and present research showing that this process measure helps account for where we do and do not see improvement in the survey data. Attendees will hear from a panel of educators about their efforts to collect student surveys in genuine partnership with students. The session will conclude with concrete practices and an easy-to-use measure for increasing students’ investment in surveys for improvement.

Dates: March 24-27, 2024
Location: Marriott Marquis San Diego Marina

Register to Secure Your Spot! (https://www.carnegiefoundation.org/carnegie-summit/)


** Did You Know?
------------------------------------------------------------
Did you know you can combine all of your Class reports into one Community report? A Community report can help synthesize data and may provide more robust disaggregated data.
Learn How to Combine Class Reports (https://perts.freshdesk.com/support/solutions/articles/67000729678-can-i-combine-my-class-group-reports-into-a-single-community-report-)


** Interested in a FREE license to pilot Elevate or Ascend this semester?
------------------------------------------------------------
A low-stakes pilot allows educators to learn the platform, build teacher buy-in, and develop a thorough implementation plan for next year! Use code PILOT2024 when you schedule a consultation and earn a free pilot for this semester!
Learn More about the Pilot Program (http://perts.net/consultation)


** Congratulations, Allison!
------------------------------------------------------------

Dr. Allison Londerée, Data Analyst at PERTS, has received her Doctorate in Social Psychology from Ohio State University! Allison co-authored our research report (https://perts.net/research/early-indicators)  and conducted extensive analyses to validate our measurement system. Her most recent analyses will be featured in our upcoming session at the Carnegie Summit in March 2024!

We extend our gratitude for Allison’s contributions. She has been an invaluable part of our team and we wish her continued success in her new role as a Data Scientist at Lirio!
“
Give your students more opportunities with their voice to find out how they want to learn.

Elevate User
Quick Links
Elevate, for Grades 6-12 (http://perts.net/elevate)
Ascend, for Higher Ed (http://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=bd172521c3)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=7b3f3876af&c=bd172521c3)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2024-02-14 18:16 UTC, rumenPERTS commented
February 2024
PERTS Newsletter
As we celebrate the significance of Black History Month, we reflect on how we've woven threads of equity and empathy into the fabric of our programs.

In collaboration with our partners, we continue our mission to amplify the voices of students and foster learning conditions that promote equity and inclusivity for all.


** New Year, New Look!
------------------------------------------------------------
We have some exciting news: the PERTS website just got a makeover! PERTS has evolved over the last several years and our updated website better represents where we are as an organization. It’s also packed with new features, enhanced navigation, and a fresh look to make your browsing experience even better.
Visit Our Updated Website! (https://perts.net)


** A Clear Focus on Equity
------------------------------------------------------------
The disaggregation options in the Student Experience Overview in Elevate & Ascend reports can provide opportunities to uncover experience gaps across groups of students and can be a great starting point to promote equity.
Learn about the Student Experience Overview (https://perts.freshdesk.com/support/solutions/articles/67000671391-how-to-use-the-student-experience-overview)
Oftentimes, specific groups of individuals are situated further from opportunity. Using the Focal Group feature allows teachers to define a custom group and review disaggregated data for those specific students.
Featured: Focal Groups (https://perts.freshdesk.com/support/solutions/articles/67000443219-what-is-a-focal-group-and-how-do-i-set-one-up-)
Hear directly from students who have experienced positive learning outcomes in classrooms that used Elevate or Ascend.
Listen to Kanaan, Finali, and Nina (https://elevate-support.perts.net/support/solutions/articles/67000713388-student-reflections-on-learning-conditions#studentexperience) share their appreciation of Elevate and the opportunity to amplify their voices.

Hear from Iyana and other students (https://ascend-support.perts.net/support/solutions/articles/67000717955-student-reflections-on-instructors-implementing-ascend#cypress) on how instructors used Ascend to improve their overall college experience.

“
Students feel the Elevate data is actionable and teachers have found that sometimes it is small, consistent changes that matter.

Elevate User


** Join Us at the 2024 Carnegie Summit!
------------------------------------------------------------
We’re delighted to share that we’ve been invited to present at the 2024 Carnegie Foundation Summit on Improvement in Education! This event is dedicated to addressing educational inequities and learning together how to transform education systems.

In our session, we will share what we’ve learned about how students' views on surveys impact classroom improvements, introduce a new single-item process measure to gauge students’ views, and present research showing that this process measure helps account for where we do and do not see improvement in the survey data. Attendees will hear from a panel of educators about their efforts to collect student surveys in genuine partnership with students. The session will conclude with concrete practices and an easy-to-use measure for increasing students’ investment in surveys for improvement.

Dates: March 24-27, 2024
Location: Marriott Marquis San Diego Marina

Register to Secure Your Spot! (https://www.carnegiefoundation.org/carnegie-summit/)


** Did You Know?
------------------------------------------------------------
Did you know you can combine all of your Class reports into one Community report? A Community report can help synthesize data and may provide more robust disaggregated data.
Learn How to Combine Class Reports (https://perts.freshdesk.com/support/solutions/articles/67000729678-can-i-combine-my-class-group-reports-into-a-single-community-report-)


** Interested in a FREE license to pilot Elevate or Ascend this semester?
------------------------------------------------------------
A low-stakes pilot allows educators to learn the platform, build teacher buy-in, and develop a thorough implementation plan for next year! Use code PILOT2024 when you schedule a consultation and earn a free pilot for this semester!
Learn More about the Pilot Program (http://perts.net/consultation)


** Congratulations, Allison!
------------------------------------------------------------

Dr. Allison Londerée, Data Analyst at PERTS, has received her Doctorate in Social Psychology from Ohio State University! Allison co-authored our research report (https://perts.net/research/early-indicators)  and conducted extensive analyses to validate our measurement system. Her most recent analyses will be featured in our upcoming session at the Carnegie Summit in March 2024!

We extend our gratitude for Allison’s contributions. She has been an invaluable part of our team and we wish her continued success in her new role as a Data Scientist at Lirio!
“
Give your students more opportunities with their voice to find out how they want to learn.

Elevate User
Quick Links
Elevate, for Grades 6-12 (http://perts.net/elevate)
Ascend, for Higher Ed (http://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=bd172521c3)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f641712fb8&c=bd172521c3)
.
 Email Marketing Powered by Mailchimp
http://www.mailchimp.com/email-referral/?utm_source=freemium_newsletter&utm_medium=email&utm_campaign=referral_marketing&aid=7edccf60df2a8af6ca924978b&afl=1

2024-03-14 14:45 UTC, rumenPERTS commented
March 2024
PERTS Newsletter


** Time to March Forward and Spring into Action! 🌱
------------------------------------------------------------

As spring blooms around us, so do new professional growth and development possibilities. Continue reading to learn more about:
* PERTS Award to Improve Student Engagement - New Opportunity!
* Incorporating Data into Your Teaching Portfolio
* Resources to Gather Feedback and Improve Student Engagement
* PERTS Session at the 2024 Carnegie Summit

Let's march together towards excellence this spring!


** PERTS Award to Improve Student Engagement: Apply Today!
------------------------------------------------------------
Are you interested in increasing student engagement and improving your school’s classroom learning conditions to accelerate student achievement? If so, PERTS is offering a unique opportunity for those that are new to Elevate: apply for the PERTS Award to Improve Student Engagement!

Thanks to generous philanthropic support, PERTS is thrilled to announce an exclusive opportunity to award Elevate to five schools or districts. Each selected institution will receive a free pilot of our highest premium support tier of Elevate in spring 2024, a value of $25,000, and a 40% discount for the 2024-2025 school year. Applications are due by April 30, 2024 and will be reviewed on a rolling basis.
Learn More! (https://perts.net/elevate/engagement-award)


** Use Your Data to Show Your Growth!
------------------------------------------------------------
Are you in an evaluation year? Educators can demonstrate progress toward their professional goals and provide evidence of elevating student voices by integrating data from either Elevate (https://perts.net/elevate) , for grades 6-12, or Ascend (https://perts.net/ascend) , for higher education, into their teaching portfolios. Read below how you can use your data to showcase your skills, growth, and impact in the classroom!
For Grades 6-12 (https://perts.net/elevate/teaching-portfolio)
For Higher Ed (https://perts.net/ascend/teaching-portfolio)


** Struggling with Student Engagement?
------------------------------------------------------------
Optimizing classroom learning conditions in partnership with students can lead to significant improvements in students’ engagement. When students know their teachers value their voices and apply their suggestions, students are more willing to provide honest and thoughtful feedback. If you’re already using Elevate or Ascend, consider these resources to help you partner with your students:
🍀 This lesson plan (https://perts.net/elevate/debrief-lesson) can be adapted to facilitate student-led discussions and surface suggestions for improving classroom conditions.

🍀 Our planning tool is designed to help teachers determine how to respond to students’ feedback.
* Elevate (https://perts.net/elevate/planning-tool) (Grades 6-12)
* Ascend (https://docs.google.com/document/d/1y_atZYowx6lJxz2MlC4FzfHcZcfCF-o17guhJU5UZD4/edit#heading=h.yr5rw6l48z1a) http://perts.net/ascend/planning-tool(Higher Ed)

🍀 Focus on improving 1-2 learning conditions with our research-based practice guides.
* Elevate (https://perts.net/elevate/practices) https://perts.net/elevate/practices(Grades 6-12)
* Ascend (https://perts.net/ascend/practices) https://perts.net/ascend/practices(Higher Ed)


** Join Us at the 2024 Carnegie Summit: Empowering Student Partnerships
------------------------------------------------------------
We are less than a month away from presenting Empowering Student Partnerships: A Key Process Measure to Improve with Student Survey Data at the 2024 Carnegie Foundation Summit! Don’t miss our session on March 26 from 8:30 AM—9:45 AM PT, where you’ll hear from a panel of educators about their efforts to collect student data using Elevate in genuine partnership with students. To learn more about the Carnegie Summit, click here (https://www.carnegiefoundation.org/carnegie-summit/) .

Date of Session: March 26, 2024 | 8:30a - 9:45a PT
Location: Marriott Marquis San Diego Marina

“
The survey results did improve overall, but I found it most informative to bring the idea of student perception and how their input should help drive the instruction and set up in the classroom.

Elevate Teacher
Quick Links
Elevate, for Grades 6-12 (http://perts.net/elevate)
Ascend, for Higher Ed (http://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=7704238e42)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f97dc5981b&c=7704238e42)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-03-14 14:45 UTC, rumenPERTS commented
March 2024
PERTS Newsletter


** Time to March Forward and Spring into Action! 🌱
------------------------------------------------------------

As spring blooms around us, so do new professional growth and development possibilities. Continue reading to learn more about:
* PERTS Award to Improve Student Engagement - New Opportunity!
* Incorporating Data into Your Teaching Portfolio
* Resources to Gather Feedback and Improve Student Engagement
* PERTS Session at the 2024 Carnegie Summit

Let's march together towards excellence this spring!


** PERTS Award to Improve Student Engagement: Apply Today!
------------------------------------------------------------
Are you interested in increasing student engagement and improving your school’s classroom learning conditions to accelerate student achievement? If so, PERTS is offering a unique opportunity for those that are new to Elevate: apply for the PERTS Award to Improve Student Engagement!

Thanks to generous philanthropic support, PERTS is thrilled to announce an exclusive opportunity to award Elevate to five schools or districts. Each selected institution will receive a free pilot of our highest premium support tier of Elevate in spring 2024, a value of $25,000, and a 40% discount for the 2024-2025 school year. Applications are due by April 30, 2024 and will be reviewed on a rolling basis.
Learn More! (https://perts.net/elevate/engagement-award)


** Use Your Data to Show Your Growth!
------------------------------------------------------------
Are you in an evaluation year? Educators can demonstrate progress toward their professional goals and provide evidence of elevating student voices by integrating data from either Elevate (https://perts.net/elevate) , for grades 6-12, or Ascend (https://perts.net/ascend) , for higher education, into their teaching portfolios. Read below how you can use your data to showcase your skills, growth, and impact in the classroom!
For Grades 6-12 (https://perts.net/elevate/teaching-portfolio)
For Higher Ed (https://perts.net/ascend/teaching-portfolio)


** Struggling with Student Engagement?
------------------------------------------------------------
Optimizing classroom learning conditions in partnership with students can lead to significant improvements in students’ engagement. When students know their teachers value their voices and apply their suggestions, students are more willing to provide honest and thoughtful feedback. If you’re already using Elevate or Ascend, consider these resources to help you partner with your students:
🍀 This lesson plan (https://perts.net/elevate/debrief-lesson) can be adapted to facilitate student-led discussions and surface suggestions for improving classroom conditions.

🍀 Our planning tool is designed to help teachers determine how to respond to students’ feedback.
* Elevate (https://perts.net/elevate/planning-tool) (Grades 6-12)
* Ascend (https://docs.google.com/document/d/1y_atZYowx6lJxz2MlC4FzfHcZcfCF-o17guhJU5UZD4/edit#heading=h.yr5rw6l48z1a) http://perts.net/ascend/planning-tool(Higher Ed)

🍀 Focus on improving 1-2 learning conditions with our research-based practice guides.
* Elevate (https://perts.net/elevate/practices) https://perts.net/elevate/practices(Grades 6-12)
* Ascend (https://perts.net/ascend/practices) https://perts.net/ascend/practices(Higher Ed)


** Join Us at the 2024 Carnegie Summit: Empowering Student Partnerships
------------------------------------------------------------
We are less than a month away from presenting Empowering Student Partnerships: A Key Process Measure to Improve with Student Survey Data at the 2024 Carnegie Foundation Summit! Don’t miss our session on March 26 from 8:30 AM—9:45 AM PT, where you’ll hear from a panel of educators about their efforts to collect student data using Elevate in genuine partnership with students. To learn more about the Carnegie Summit, click here (https://www.carnegiefoundation.org/carnegie-summit/) .

Date of Session: March 26, 2024 | 8:30a - 9:45a PT
Location: Marriott Marquis San Diego Marina

“
The survey results did improve overall, but I found it most informative to bring the idea of student perception and how their input should help drive the instruction and set up in the classroom.

Elevate Teacher
Quick Links
Elevate, for Grades 6-12 (http://perts.net/elevate)
Ascend, for Higher Ed (http://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=7704238e42)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=da5cd98d77&c=7704238e42)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-03-14 14:45 UTC, rumenPERTS commented
March 2024
PERTS Newsletter


** Time to March Forward and Spring into Action! 🌱
------------------------------------------------------------

As spring blooms around us, so do new professional growth and development possibilities. Continue reading to learn more about:
* PERTS Award to Improve Student Engagement - New Opportunity!
* Incorporating Data into Your Teaching Portfolio
* Resources to Gather Feedback and Improve Student Engagement
* PERTS Session at the 2024 Carnegie Summit

Let's march together towards excellence this spring!


** PERTS Award to Improve Student Engagement: Apply Today!
------------------------------------------------------------
Are you interested in increasing student engagement and improving your school’s classroom learning conditions to accelerate student achievement? If so, PERTS is offering a unique opportunity for those that are new to Elevate: apply for the PERTS Award to Improve Student Engagement!

Thanks to generous philanthropic support, PERTS is thrilled to announce an exclusive opportunity to award Elevate to five schools or districts. Each selected institution will receive a free pilot of our highest premium support tier of Elevate in spring 2024, a value of $25,000, and a 40% discount for the 2024-2025 school year. Applications are due by April 30, 2024 and will be reviewed on a rolling basis.
Learn More! (https://perts.net/elevate/engagement-award)


** Use Your Data to Show Your Growth!
------------------------------------------------------------
Are you in an evaluation year? Educators can demonstrate progress toward their professional goals and provide evidence of elevating student voices by integrating data from either Elevate (https://perts.net/elevate) , for grades 6-12, or Ascend (https://perts.net/ascend) , for higher education, into their teaching portfolios. Read below how you can use your data to showcase your skills, growth, and impact in the classroom!
For Grades 6-12 (https://perts.net/elevate/teaching-portfolio)
For Higher Ed (https://perts.net/ascend/teaching-portfolio)


** Struggling with Student Engagement?
------------------------------------------------------------
Optimizing classroom learning conditions in partnership with students can lead to significant improvements in students’ engagement. When students know their teachers value their voices and apply their suggestions, students are more willing to provide honest and thoughtful feedback. If you’re already using Elevate or Ascend, consider these resources to help you partner with your students:
🍀 This lesson plan (https://perts.net/elevate/debrief-lesson) can be adapted to facilitate student-led discussions and surface suggestions for improving classroom conditions.

🍀 Our planning tool is designed to help teachers determine how to respond to students’ feedback.
* Elevate (https://perts.net/elevate/planning-tool) (Grades 6-12)
* Ascend (https://docs.google.com/document/d/1y_atZYowx6lJxz2MlC4FzfHcZcfCF-o17guhJU5UZD4/edit#heading=h.yr5rw6l48z1a) http://perts.net/ascend/planning-tool(Higher Ed)

🍀 Focus on improving 1-2 learning conditions with our research-based practice guides.
* Elevate (https://perts.net/elevate/practices) https://perts.net/elevate/practices(Grades 6-12)
* Ascend (https://perts.net/ascend/practices) https://perts.net/ascend/practices(Higher Ed)


** Join Us at the 2024 Carnegie Summit: Empowering Student Partnerships
------------------------------------------------------------
We are less than a month away from presenting Empowering Student Partnerships: A Key Process Measure to Improve with Student Survey Data at the 2024 Carnegie Foundation Summit! Don’t miss our session on March 26 from 8:30 AM—9:45 AM PT, where you’ll hear from a panel of educators about their efforts to collect student data using Elevate in genuine partnership with students. To learn more about the Carnegie Summit, click here (https://www.carnegiefoundation.org/carnegie-summit/) .

Date of Session: March 26, 2024 | 8:30a - 9:45a PT
Location: Marriott Marquis San Diego Marina

“
The survey results did improve overall, but I found it most informative to bring the idea of student perception and how their input should help drive the instruction and set up in the classroom.

Elevate Teacher
Quick Links
Elevate, for Grades 6-12 (http://perts.net/elevate)
Ascend, for Higher Ed (http://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=7704238e42)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=b4edfd0dd8&c=7704238e42)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-03-14 14:45 UTC, rumenPERTS commented
March 2024
PERTS Newsletter


** Time to March Forward and Spring into Action! 🌱
------------------------------------------------------------

As spring blooms around us, so do new professional growth and development possibilities. Continue reading to learn more about:
* PERTS Award to Improve Student Engagement - New Opportunity!
* Incorporating Data into Your Teaching Portfolio
* Resources to Gather Feedback and Improve Student Engagement
* PERTS Session at the 2024 Carnegie Summit

Let's march together towards excellence this spring!


** PERTS Award to Improve Student Engagement: Apply Today!
------------------------------------------------------------
Are you interested in increasing student engagement and improving your school’s classroom learning conditions to accelerate student achievement? If so, PERTS is offering a unique opportunity for those that are new to Elevate: apply for the PERTS Award to Improve Student Engagement!

Thanks to generous philanthropic support, PERTS is thrilled to announce an exclusive opportunity to award Elevate to five schools or districts. Each selected institution will receive a free pilot of our highest premium support tier of Elevate in spring 2024, a value of $25,000, and a 40% discount for the 2024-2025 school year. Applications are due by April 30, 2024 and will be reviewed on a rolling basis.
Learn More! (https://perts.net/elevate/engagement-award)


** Use Your Data to Show Your Growth!
------------------------------------------------------------
Are you in an evaluation year? Educators can demonstrate progress toward their professional goals and provide evidence of elevating student voices by integrating data from either Elevate (https://perts.net/elevate) , for grades 6-12, or Ascend (https://perts.net/ascend) , for higher education, into their teaching portfolios. Read below how you can use your data to showcase your skills, growth, and impact in the classroom!
For Grades 6-12 (https://perts.net/elevate/teaching-portfolio)
For Higher Ed (https://perts.net/ascend/teaching-portfolio)


** Struggling with Student Engagement?
------------------------------------------------------------
Optimizing classroom learning conditions in partnership with students can lead to significant improvements in students’ engagement. When students know their teachers value their voices and apply their suggestions, students are more willing to provide honest and thoughtful feedback. If you’re already using Elevate or Ascend, consider these resources to help you partner with your students:
🍀 This lesson plan (https://perts.net/elevate/debrief-lesson) can be adapted to facilitate student-led discussions and surface suggestions for improving classroom conditions.

🍀 Our planning tool is designed to help teachers determine how to respond to students’ feedback.
* Elevate (https://perts.net/elevate/planning-tool) (Grades 6-12)
* Ascend (https://docs.google.com/document/d/1y_atZYowx6lJxz2MlC4FzfHcZcfCF-o17guhJU5UZD4/edit#heading=h.yr5rw6l48z1a) http://perts.net/ascend/planning-tool(Higher Ed)

🍀 Focus on improving 1-2 learning conditions with our research-based practice guides.
* Elevate (https://perts.net/elevate/practices) https://perts.net/elevate/practices(Grades 6-12)
* Ascend (https://perts.net/ascend/practices) https://perts.net/ascend/practices(Higher Ed)


** Join Us at the 2024 Carnegie Summit: Empowering Student Partnerships
------------------------------------------------------------
We are less than a month away from presenting Empowering Student Partnerships: A Key Process Measure to Improve with Student Survey Data at the 2024 Carnegie Foundation Summit! Don’t miss our session on March 26 from 8:30 AM—9:45 AM PT, where you’ll hear from a panel of educators about their efforts to collect student data using Elevate in genuine partnership with students. To learn more about the Carnegie Summit, click here (https://www.carnegiefoundation.org/carnegie-summit/) .

Date of Session: March 26, 2024 | 8:30a - 9:45a PT
Location: Marriott Marquis San Diego Marina

“
The survey results did improve overall, but I found it most informative to bring the idea of student perception and how their input should help drive the instruction and set up in the classroom.

Elevate Teacher
Quick Links
Elevate, for Grades 6-12 (http://perts.net/elevate)
Ascend, for Higher Ed (http://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=7704238e42)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=298ead533f&c=7704238e42)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-03-14 14:46 UTC, rumenPERTS commented
March 2024
PERTS Newsletter


** Time to March Forward and Spring into Action! 🌱
------------------------------------------------------------

As spring blooms around us, so do new professional growth and development possibilities. Continue reading to learn more about:
* PERTS Award to Improve Student Engagement - New Opportunity!
* Incorporating Data into Your Teaching Portfolio
* Resources to Gather Feedback and Improve Student Engagement
* PERTS Session at the 2024 Carnegie Summit

Let's march together towards excellence this spring!


** PERTS Award to Improve Student Engagement: Apply Today!
------------------------------------------------------------
Are you interested in increasing student engagement and improving your school’s classroom learning conditions to accelerate student achievement? If so, PERTS is offering a unique opportunity for those that are new to Elevate: apply for the PERTS Award to Improve Student Engagement!

Thanks to generous philanthropic support, PERTS is thrilled to announce an exclusive opportunity to award Elevate to five schools or districts. Each selected institution will receive a free pilot of our highest premium support tier of Elevate in spring 2024, a value of $25,000, and a 40% discount for the 2024-2025 school year. Applications are due by April 30, 2024 and will be reviewed on a rolling basis.
Learn More! (https://perts.net/elevate/engagement-award)


** Use Your Data to Show Your Growth!
------------------------------------------------------------
Are you in an evaluation year? Educators can demonstrate progress toward their professional goals and provide evidence of elevating student voices by integrating data from either Elevate (https://perts.net/elevate) , for grades 6-12, or Ascend (https://perts.net/ascend) , for higher education, into their teaching portfolios. Read below how you can use your data to showcase your skills, growth, and impact in the classroom!
For Grades 6-12 (https://perts.net/elevate/teaching-portfolio)
For Higher Ed (https://perts.net/ascend/teaching-portfolio)


** Struggling with Student Engagement?
------------------------------------------------------------
Optimizing classroom learning conditions in partnership with students can lead to significant improvements in students’ engagement. When students know their teachers value their voices and apply their suggestions, students are more willing to provide honest and thoughtful feedback. If you’re already using Elevate or Ascend, consider these resources to help you partner with your students:
🍀 This lesson plan (https://perts.net/elevate/debrief-lesson) can be adapted to facilitate student-led discussions and surface suggestions for improving classroom conditions.

🍀 Our planning tool is designed to help teachers determine how to respond to students’ feedback.
* Elevate (https://perts.net/elevate/planning-tool) (Grades 6-12)
* Ascend (https://docs.google.com/document/d/1y_atZYowx6lJxz2MlC4FzfHcZcfCF-o17guhJU5UZD4/edit#heading=h.yr5rw6l48z1a) http://perts.net/ascend/planning-tool(Higher Ed)

🍀 Focus on improving 1-2 learning conditions with our research-based practice guides.
* Elevate (https://perts.net/elevate/practices) https://perts.net/elevate/practices(Grades 6-12)
* Ascend (https://perts.net/ascend/practices) https://perts.net/ascend/practices(Higher Ed)


** Join Us at the 2024 Carnegie Summit: Empowering Student Partnerships
------------------------------------------------------------
We are less than a month away from presenting Empowering Student Partnerships: A Key Process Measure to Improve with Student Survey Data at the 2024 Carnegie Foundation Summit! Don’t miss our session on March 26 from 8:30 AM—9:45 AM PT, where you’ll hear from a panel of educators about their efforts to collect student data using Elevate in genuine partnership with students. To learn more about the Carnegie Summit, click here (https://www.carnegiefoundation.org/carnegie-summit/) .

Date of Session: March 26, 2024 | 8:30a - 9:45a PT
Location: Marriott Marquis San Diego Marina

“
The survey results did improve overall, but I found it most informative to bring the idea of student perception and how their input should help drive the instruction and set up in the classroom.

Elevate Teacher
Quick Links
Elevate, for Grades 6-12 (http://perts.net/elevate)
Ascend, for Higher Ed (http://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=7704238e42)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f66b76caa6&c=7704238e42)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-03-14 14:46 UTC, rumenPERTS commented
March 2024
PERTS Newsletter


** Time to March Forward and Spring into Action! 🌱
------------------------------------------------------------

As spring blooms around us, so do new professional growth and development possibilities. Continue reading to learn more about:
* PERTS Award to Improve Student Engagement - New Opportunity!
* Incorporating Data into Your Teaching Portfolio
* Resources to Gather Feedback and Improve Student Engagement
* PERTS Session at the 2024 Carnegie Summit

Let's march together towards excellence this spring!


** PERTS Award to Improve Student Engagement: Apply Today!
------------------------------------------------------------
Are you interested in increasing student engagement and improving your school’s classroom learning conditions to accelerate student achievement? If so, PERTS is offering a unique opportunity for those that are new to Elevate: apply for the PERTS Award to Improve Student Engagement!

Thanks to generous philanthropic support, PERTS is thrilled to announce an exclusive opportunity to award Elevate to five schools or districts. Each selected institution will receive a free pilot of our highest premium support tier of Elevate in spring 2024, a value of $25,000, and a 40% discount for the 2024-2025 school year. Applications are due by April 30, 2024 and will be reviewed on a rolling basis.
Learn More! (https://perts.net/elevate/engagement-award)


** Use Your Data to Show Your Growth!
------------------------------------------------------------
Are you in an evaluation year? Educators can demonstrate progress toward their professional goals and provide evidence of elevating student voices by integrating data from either Elevate (https://perts.net/elevate) , for grades 6-12, or Ascend (https://perts.net/ascend) , for higher education, into their teaching portfolios. Read below how you can use your data to showcase your skills, growth, and impact in the classroom!
For Grades 6-12 (https://perts.net/elevate/teaching-portfolio)
For Higher Ed (https://perts.net/ascend/teaching-portfolio)


** Struggling with Student Engagement?
------------------------------------------------------------
Optimizing classroom learning conditions in partnership with students can lead to significant improvements in students’ engagement. When students know their teachers value their voices and apply their suggestions, students are more willing to provide honest and thoughtful feedback. If you’re already using Elevate or Ascend, consider these resources to help you partner with your students:
🍀 This lesson plan (https://perts.net/elevate/debrief-lesson) can be adapted to facilitate student-led discussions and surface suggestions for improving classroom conditions.

🍀 Our planning tool is designed to help teachers determine how to respond to students’ feedback.
* Elevate (https://perts.net/elevate/planning-tool) (Grades 6-12)
* Ascend (https://docs.google.com/document/d/1y_atZYowx6lJxz2MlC4FzfHcZcfCF-o17guhJU5UZD4/edit#heading=h.yr5rw6l48z1a) http://perts.net/ascend/planning-tool(Higher Ed)

🍀 Focus on improving 1-2 learning conditions with our research-based practice guides.
* Elevate (https://perts.net/elevate/practices) https://perts.net/elevate/practices(Grades 6-12)
* Ascend (https://perts.net/ascend/practices) https://perts.net/ascend/practices(Higher Ed)


** Join Us at the 2024 Carnegie Summit: Empowering Student Partnerships
------------------------------------------------------------
We are less than a month away from presenting Empowering Student Partnerships: A Key Process Measure to Improve with Student Survey Data at the 2024 Carnegie Foundation Summit! Don’t miss our session on March 26 from 8:30 AM—9:45 AM PT, where you’ll hear from a panel of educators about their efforts to collect student data using Elevate in genuine partnership with students. To learn more about the Carnegie Summit, click here (https://www.carnegiefoundation.org/carnegie-summit/) .

Date of Session: March 26, 2024 | 8:30a - 9:45a PT
Location: Marriott Marquis San Diego Marina

“
The survey results did improve overall, but I found it most informative to bring the idea of student perception and how their input should help drive the instruction and set up in the classroom.

Elevate Teacher
Quick Links
Elevate, for Grades 6-12 (http://perts.net/elevate)
Ascend, for Higher Ed (http://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=7704238e42)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=36456eb76b&c=7704238e42)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-03-14 14:46 UTC, rumenPERTS commented
March 2024
PERTS Newsletter


** Time to March Forward and Spring into Action! 🌱
------------------------------------------------------------

As spring blooms around us, so do new professional growth and development possibilities. Continue reading to learn more about:
* PERTS Award to Improve Student Engagement - New Opportunity!
* Incorporating Data into Your Teaching Portfolio
* Resources to Gather Feedback and Improve Student Engagement
* PERTS Session at the 2024 Carnegie Summit

Let's march together towards excellence this spring!


** PERTS Award to Improve Student Engagement: Apply Today!
------------------------------------------------------------
Are you interested in increasing student engagement and improving your school’s classroom learning conditions to accelerate student achievement? If so, PERTS is offering a unique opportunity for those that are new to Elevate: apply for the PERTS Award to Improve Student Engagement!

Thanks to generous philanthropic support, PERTS is thrilled to announce an exclusive opportunity to award Elevate to five schools or districts. Each selected institution will receive a free pilot of our highest premium support tier of Elevate in spring 2024, a value of $25,000, and a 40% discount for the 2024-2025 school year. Applications are due by April 30, 2024 and will be reviewed on a rolling basis.
Learn More! (https://perts.net/elevate/engagement-award)


** Use Your Data to Show Your Growth!
------------------------------------------------------------
Are you in an evaluation year? Educators can demonstrate progress toward their professional goals and provide evidence of elevating student voices by integrating data from either Elevate (https://perts.net/elevate) , for grades 6-12, or Ascend (https://perts.net/ascend) , for higher education, into their teaching portfolios. Read below how you can use your data to showcase your skills, growth, and impact in the classroom!
For Grades 6-12 (https://perts.net/elevate/teaching-portfolio)
For Higher Ed (https://perts.net/ascend/teaching-portfolio)


** Struggling with Student Engagement?
------------------------------------------------------------
Optimizing classroom learning conditions in partnership with students can lead to significant improvements in students’ engagement. When students know their teachers value their voices and apply their suggestions, students are more willing to provide honest and thoughtful feedback. If you’re already using Elevate or Ascend, consider these resources to help you partner with your students:
🍀 This lesson plan (https://perts.net/elevate/debrief-lesson) can be adapted to facilitate student-led discussions and surface suggestions for improving classroom conditions.

🍀 Our planning tool is designed to help teachers determine how to respond to students’ feedback.
* Elevate (https://perts.net/elevate/planning-tool) (Grades 6-12)
* Ascend (https://docs.google.com/document/d/1y_atZYowx6lJxz2MlC4FzfHcZcfCF-o17guhJU5UZD4/edit#heading=h.yr5rw6l48z1a) http://perts.net/ascend/planning-tool(Higher Ed)

🍀 Focus on improving 1-2 learning conditions with our research-based practice guides.
* Elevate (https://perts.net/elevate/practices) https://perts.net/elevate/practices(Grades 6-12)
* Ascend (https://perts.net/ascend/practices) https://perts.net/ascend/practices(Higher Ed)


** Join Us at the 2024 Carnegie Summit: Empowering Student Partnerships
------------------------------------------------------------
We are less than a month away from presenting Empowering Student Partnerships: A Key Process Measure to Improve with Student Survey Data at the 2024 Carnegie Foundation Summit! Don’t miss our session on March 26 from 8:30 AM—9:45 AM PT, where you’ll hear from a panel of educators about their efforts to collect student data using Elevate in genuine partnership with students. To learn more about the Carnegie Summit, click here (https://www.carnegiefoundation.org/carnegie-summit/) .

Date of Session: March 26, 2024 | 8:30a - 9:45a PT
Location: Marriott Marquis San Diego Marina

“
The survey results did improve overall, but I found it most informative to bring the idea of student perception and how their input should help drive the instruction and set up in the classroom.

Elevate Teacher
Quick Links
Elevate, for Grades 6-12 (http://perts.net/elevate)
Ascend, for Higher Ed (http://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=7704238e42)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=7b3f3876af&c=7704238e42)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-03-14 14:46 UTC, rumenPERTS commented
March 2024
PERTS Newsletter


** Time to March Forward and Spring into Action! 🌱
------------------------------------------------------------

As spring blooms around us, so do new professional growth and development possibilities. Continue reading to learn more about:
* PERTS Award to Improve Student Engagement - New Opportunity!
* Incorporating Data into Your Teaching Portfolio
* Resources to Gather Feedback and Improve Student Engagement
* PERTS Session at the 2024 Carnegie Summit

Let's march together towards excellence this spring!


** PERTS Award to Improve Student Engagement: Apply Today!
------------------------------------------------------------
Are you interested in increasing student engagement and improving your school’s classroom learning conditions to accelerate student achievement? If so, PERTS is offering a unique opportunity for those that are new to Elevate: apply for the PERTS Award to Improve Student Engagement!

Thanks to generous philanthropic support, PERTS is thrilled to announce an exclusive opportunity to award Elevate to five schools or districts. Each selected institution will receive a free pilot of our highest premium support tier of Elevate in spring 2024, a value of $25,000, and a 40% discount for the 2024-2025 school year. Applications are due by April 30, 2024 and will be reviewed on a rolling basis.
Learn More! (https://perts.net/elevate/engagement-award)


** Use Your Data to Show Your Growth!
------------------------------------------------------------
Are you in an evaluation year? Educators can demonstrate progress toward their professional goals and provide evidence of elevating student voices by integrating data from either Elevate (https://perts.net/elevate) , for grades 6-12, or Ascend (https://perts.net/ascend) , for higher education, into their teaching portfolios. Read below how you can use your data to showcase your skills, growth, and impact in the classroom!
For Grades 6-12 (https://perts.net/elevate/teaching-portfolio)
For Higher Ed (https://perts.net/ascend/teaching-portfolio)


** Struggling with Student Engagement?
------------------------------------------------------------
Optimizing classroom learning conditions in partnership with students can lead to significant improvements in students’ engagement. When students know their teachers value their voices and apply their suggestions, students are more willing to provide honest and thoughtful feedback. If you’re already using Elevate or Ascend, consider these resources to help you partner with your students:
🍀 This lesson plan (https://perts.net/elevate/debrief-lesson) can be adapted to facilitate student-led discussions and surface suggestions for improving classroom conditions.

🍀 Our planning tool is designed to help teachers determine how to respond to students’ feedback.
* Elevate (https://perts.net/elevate/planning-tool) (Grades 6-12)
* Ascend (https://docs.google.com/document/d/1y_atZYowx6lJxz2MlC4FzfHcZcfCF-o17guhJU5UZD4/edit#heading=h.yr5rw6l48z1a) http://perts.net/ascend/planning-tool(Higher Ed)

🍀 Focus on improving 1-2 learning conditions with our research-based practice guides.
* Elevate (https://perts.net/elevate/practices) https://perts.net/elevate/practices(Grades 6-12)
* Ascend (https://perts.net/ascend/practices) https://perts.net/ascend/practices(Higher Ed)


** Join Us at the 2024 Carnegie Summit: Empowering Student Partnerships
------------------------------------------------------------
We are less than a month away from presenting Empowering Student Partnerships: A Key Process Measure to Improve with Student Survey Data at the 2024 Carnegie Foundation Summit! Don’t miss our session on March 26 from 8:30 AM—9:45 AM PT, where you’ll hear from a panel of educators about their efforts to collect student data using Elevate in genuine partnership with students. To learn more about the Carnegie Summit, click here (https://www.carnegiefoundation.org/carnegie-summit/) .

Date of Session: March 26, 2024 | 8:30a - 9:45a PT
Location: Marriott Marquis San Diego Marina

“
The survey results did improve overall, but I found it most informative to bring the idea of student perception and how their input should help drive the instruction and set up in the classroom.

Elevate Teacher
Quick Links
Elevate, for Grades 6-12 (http://perts.net/elevate)
Ascend, for Higher Ed (http://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=7704238e42)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f641712fb8&c=7704238e42)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-04-15 10:00 UTC, rumenPERTS commented
April 2024
PERTS Newsletter
We hope you had an enjoyable spring break. In this newsletter, we share learning conditions that are strong predictors of student success and resources to improve those conditions. Keep reading to learn more about:
* An opportunity to bring Elevate to your institution
* An edWeb webinar on how to improve student engagement
* Practices and resources to improve classroom learning conditions
* Bright spots from students & teachers at San Ramon Valley USD

We’re also thrilled to welcome our newest PERTSie!


** Apply for the PERTS Award to Improve Student Engagement!
------------------------------------------------------------
Are you interested in increasing student engagement across your campus? Apply for the PERTS Award to Improve Student Engagement to pilot Elevate this school year and secure a 40% discount for the 2024-25 school year!

Thanks to philanthropic support, this award will be granted to five schools and/or districts that would like to systematically gather feedback from students and create learning conditions that support students in achieving their full potential.
Apply by April 30 (https://perts.net/elevate/engagement-award)


** Webinar: How to Elevate Student Voice to Improve Student Engagement & Achievement
------------------------------------------------------------
Tuesday, April 30, 5 pm ET
Join PERTS Director of Research, Dr. Sarah Gripshover, and a panel of PERTS partners to learn:
* All about Elevate: an evidence-based tool to leverage student voice for continuous improvement.
* Research on three learning conditions that drive student engagement and achievement.
* Easy-to-implement strategies for nurturing these learning conditions.
* Success stories from educators who have implemented these strategies in their classrooms and schools.

Register today! (https://home.edweb.net/webinar/studentvoice20240430/)


** Convene Together in Communities of Practice!
------------------------------------------------------------
PERTS provides resources for schools implementing Elevate (6-12) or Ascend (higher ed) to facilitate their own “Communities of Practice” to support teachers/instructors in making sense of report data, identifying areas of improvement, and celebrating progress together. For example, take a look at our customizable Final Reflection Protocol as the end of the school year approaches to identify key learnings and make a plan to share with your school community!
Review the Elevate Final Reflection Protocol (http://perts.net/elevate/reflection-meeting)
Review the Ascend Final Reflection Protocol (https://perts.net/ascend/final-reflection-protocol)


** Hear from Students at San Ramon Valley USD about the Power of Their Feedback
------------------------------------------------------------
https://drive.google.com/file/d/1v0_mPFR51Mc-lEukbt2jxaBXaJskUIoK/view
Listen to students share how the feedback they provided with Elevate influenced changes that made their classes more interactive and engaging.
Interested in hearing more student and teacher reflections? Check out the videos linked below!
Students Reflect on Elevate (https://perts.net/elevate/student-reflections)
Teachers Reflect on Elevate (https://perts.net/elevate/teacher-reflections)
Students Reflect on Ascend (https://perts.net/ascend/student-reflections)
Instructors Reflect on Ascend (https://perts.net/ascend/faculty-reflections)


** A Warm Welcome to Our Newest PERTSie!
------------------------------------------------------------

We are thrilled to welcome David Frantzreb to the PERTS team! As of April 2024, he will join us as a Partnership Manager. David is an alum of UNC Charlotte and has experience as a researcher, project manager, and lecturer. David is excited to collaborate with colleges and universities to create more equitable student experiences!
“
[I have noticed in my teaching...] Shift from compliance to ownership—student-centered learning—allowing students to have an active voice and role in their learning.

Elevate Teacher
Quick Links
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=cf73cd1057)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f66b76caa6&c=cf73cd1057)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-04-15 10:00 UTC, rumenPERTS commented
April 2024
PERTS Newsletter
We hope you had an enjoyable spring break. In this newsletter, we share learning conditions that are strong predictors of student success and resources to improve those conditions. Keep reading to learn more about:
* An opportunity to bring Elevate to your institution
* An edWeb webinar on how to improve student engagement
* Practices and resources to improve classroom learning conditions
* Bright spots from students & teachers at San Ramon Valley USD

We’re also thrilled to welcome our newest PERTSie!


** Apply for the PERTS Award to Improve Student Engagement!
------------------------------------------------------------
Are you interested in increasing student engagement across your campus? Apply for the PERTS Award to Improve Student Engagement to pilot Elevate this school year and secure a 40% discount for the 2024-25 school year!

Thanks to philanthropic support, this award will be granted to five schools and/or districts that would like to systematically gather feedback from students and create learning conditions that support students in achieving their full potential.
Apply by April 30 (https://perts.net/elevate/engagement-award)


** Webinar: How to Elevate Student Voice to Improve Student Engagement & Achievement
------------------------------------------------------------
Tuesday, April 30, 5 pm ET
Join PERTS Director of Research, Dr. Sarah Gripshover, and a panel of PERTS partners to learn:
* All about Elevate: an evidence-based tool to leverage student voice for continuous improvement.
* Research on three learning conditions that drive student engagement and achievement.
* Easy-to-implement strategies for nurturing these learning conditions.
* Success stories from educators who have implemented these strategies in their classrooms and schools.

Register today! (https://home.edweb.net/webinar/studentvoice20240430/)


** Convene Together in Communities of Practice!
------------------------------------------------------------
PERTS provides resources for schools implementing Elevate (6-12) or Ascend (higher ed) to facilitate their own “Communities of Practice” to support teachers/instructors in making sense of report data, identifying areas of improvement, and celebrating progress together. For example, take a look at our customizable Final Reflection Protocol as the end of the school year approaches to identify key learnings and make a plan to share with your school community!
Review the Elevate Final Reflection Protocol (http://perts.net/elevate/reflection-meeting)
Review the Ascend Final Reflection Protocol (https://perts.net/ascend/final-reflection-protocol)


** Hear from Students at San Ramon Valley USD about the Power of Their Feedback
------------------------------------------------------------
https://drive.google.com/file/d/1v0_mPFR51Mc-lEukbt2jxaBXaJskUIoK/view
Listen to students share how the feedback they provided with Elevate influenced changes that made their classes more interactive and engaging.
Interested in hearing more student and teacher reflections? Check out the videos linked below!
Students Reflect on Elevate (https://perts.net/elevate/student-reflections)
Teachers Reflect on Elevate (https://perts.net/elevate/teacher-reflections)
Students Reflect on Ascend (https://perts.net/ascend/student-reflections)
Instructors Reflect on Ascend (https://perts.net/ascend/faculty-reflections)


** A Warm Welcome to Our Newest PERTSie!
------------------------------------------------------------

We are thrilled to welcome David Frantzreb to the PERTS team! As of April 2024, he will join us as a Partnership Manager. David is an alum of UNC Charlotte and has experience as a researcher, project manager, and lecturer. David is excited to collaborate with colleges and universities to create more equitable student experiences!
“
[I have noticed in my teaching...] Shift from compliance to ownership—student-centered learning—allowing students to have an active voice and role in their learning.

Elevate Teacher
Quick Links
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=cf73cd1057)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=298ead533f&c=cf73cd1057)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-04-15 10:00 UTC, rumenPERTS commented
April 2024
PERTS Newsletter
We hope you had an enjoyable spring break. In this newsletter, we share learning conditions that are strong predictors of student success and resources to improve those conditions. Keep reading to learn more about:
* An opportunity to bring Elevate to your institution
* An edWeb webinar on how to improve student engagement
* Practices and resources to improve classroom learning conditions
* Bright spots from students & teachers at San Ramon Valley USD

We’re also thrilled to welcome our newest PERTSie!


** Apply for the PERTS Award to Improve Student Engagement!
------------------------------------------------------------
Are you interested in increasing student engagement across your campus? Apply for the PERTS Award to Improve Student Engagement to pilot Elevate this school year and secure a 40% discount for the 2024-25 school year!

Thanks to philanthropic support, this award will be granted to five schools and/or districts that would like to systematically gather feedback from students and create learning conditions that support students in achieving their full potential.
Apply by April 30 (https://perts.net/elevate/engagement-award)


** Webinar: How to Elevate Student Voice to Improve Student Engagement & Achievement
------------------------------------------------------------
Tuesday, April 30, 5 pm ET
Join PERTS Director of Research, Dr. Sarah Gripshover, and a panel of PERTS partners to learn:
* All about Elevate: an evidence-based tool to leverage student voice for continuous improvement.
* Research on three learning conditions that drive student engagement and achievement.
* Easy-to-implement strategies for nurturing these learning conditions.
* Success stories from educators who have implemented these strategies in their classrooms and schools.

Register today! (https://home.edweb.net/webinar/studentvoice20240430/)


** Convene Together in Communities of Practice!
------------------------------------------------------------
PERTS provides resources for schools implementing Elevate (6-12) or Ascend (higher ed) to facilitate their own “Communities of Practice” to support teachers/instructors in making sense of report data, identifying areas of improvement, and celebrating progress together. For example, take a look at our customizable Final Reflection Protocol as the end of the school year approaches to identify key learnings and make a plan to share with your school community!
Review the Elevate Final Reflection Protocol (http://perts.net/elevate/reflection-meeting)
Review the Ascend Final Reflection Protocol (https://perts.net/ascend/final-reflection-protocol)


** Hear from Students at San Ramon Valley USD about the Power of Their Feedback
------------------------------------------------------------
https://drive.google.com/file/d/1v0_mPFR51Mc-lEukbt2jxaBXaJskUIoK/view
Listen to students share how the feedback they provided with Elevate influenced changes that made their classes more interactive and engaging.
Interested in hearing more student and teacher reflections? Check out the videos linked below!
Students Reflect on Elevate (https://perts.net/elevate/student-reflections)
Teachers Reflect on Elevate (https://perts.net/elevate/teacher-reflections)
Students Reflect on Ascend (https://perts.net/ascend/student-reflections)
Instructors Reflect on Ascend (https://perts.net/ascend/faculty-reflections)


** A Warm Welcome to Our Newest PERTSie!
------------------------------------------------------------

We are thrilled to welcome David Frantzreb to the PERTS team! As of April 2024, he will join us as a Partnership Manager. David is an alum of UNC Charlotte and has experience as a researcher, project manager, and lecturer. David is excited to collaborate with colleges and universities to create more equitable student experiences!
“
[I have noticed in my teaching...] Shift from compliance to ownership—student-centered learning—allowing students to have an active voice and role in their learning.

Elevate Teacher
Quick Links
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=cf73cd1057)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=b4edfd0dd8&c=cf73cd1057)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-04-15 10:01 UTC, rumenPERTS commented
April 2024
PERTS Newsletter
We hope you had an enjoyable spring break. In this newsletter, we share learning conditions that are strong predictors of student success and resources to improve those conditions. Keep reading to learn more about:
* An opportunity to bring Elevate to your institution
* An edWeb webinar on how to improve student engagement
* Practices and resources to improve classroom learning conditions
* Bright spots from students & teachers at San Ramon Valley USD

We’re also thrilled to welcome our newest PERTSie!


** Apply for the PERTS Award to Improve Student Engagement!
------------------------------------------------------------
Are you interested in increasing student engagement across your campus? Apply for the PERTS Award to Improve Student Engagement to pilot Elevate this school year and secure a 40% discount for the 2024-25 school year!

Thanks to philanthropic support, this award will be granted to five schools and/or districts that would like to systematically gather feedback from students and create learning conditions that support students in achieving their full potential.
Apply by April 30 (https://perts.net/elevate/engagement-award)


** Webinar: How to Elevate Student Voice to Improve Student Engagement & Achievement
------------------------------------------------------------
Tuesday, April 30, 5 pm ET
Join PERTS Director of Research, Dr. Sarah Gripshover, and a panel of PERTS partners to learn:
* All about Elevate: an evidence-based tool to leverage student voice for continuous improvement.
* Research on three learning conditions that drive student engagement and achievement.
* Easy-to-implement strategies for nurturing these learning conditions.
* Success stories from educators who have implemented these strategies in their classrooms and schools.

Register today! (https://home.edweb.net/webinar/studentvoice20240430/)


** Convene Together in Communities of Practice!
------------------------------------------------------------
PERTS provides resources for schools implementing Elevate (6-12) or Ascend (higher ed) to facilitate their own “Communities of Practice” to support teachers/instructors in making sense of report data, identifying areas of improvement, and celebrating progress together. For example, take a look at our customizable Final Reflection Protocol as the end of the school year approaches to identify key learnings and make a plan to share with your school community!
Review the Elevate Final Reflection Protocol (http://perts.net/elevate/reflection-meeting)
Review the Ascend Final Reflection Protocol (https://perts.net/ascend/final-reflection-protocol)


** Hear from Students at San Ramon Valley USD about the Power of Their Feedback
------------------------------------------------------------
https://drive.google.com/file/d/1v0_mPFR51Mc-lEukbt2jxaBXaJskUIoK/view
Listen to students share how the feedback they provided with Elevate influenced changes that made their classes more interactive and engaging.
Interested in hearing more student and teacher reflections? Check out the videos linked below!
Students Reflect on Elevate (https://perts.net/elevate/student-reflections)
Teachers Reflect on Elevate (https://perts.net/elevate/teacher-reflections)
Students Reflect on Ascend (https://perts.net/ascend/student-reflections)
Instructors Reflect on Ascend (https://perts.net/ascend/faculty-reflections)


** A Warm Welcome to Our Newest PERTSie!
------------------------------------------------------------

We are thrilled to welcome David Frantzreb to the PERTS team! As of April 2024, he will join us as a Partnership Manager. David is an alum of UNC Charlotte and has experience as a researcher, project manager, and lecturer. David is excited to collaborate with colleges and universities to create more equitable student experiences!
“
[I have noticed in my teaching...] Shift from compliance to ownership—student-centered learning—allowing students to have an active voice and role in their learning.

Elevate Teacher
Quick Links
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=cf73cd1057)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=36456eb76b&c=cf73cd1057)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-04-15 10:01 UTC, rumenPERTS commented
April 2024
PERTS Newsletter
We hope you had an enjoyable spring break. In this newsletter, we share learning conditions that are strong predictors of student success and resources to improve those conditions. Keep reading to learn more about:
* An opportunity to bring Elevate to your institution
* An edWeb webinar on how to improve student engagement
* Practices and resources to improve classroom learning conditions
* Bright spots from students & teachers at San Ramon Valley USD

We’re also thrilled to welcome our newest PERTSie!


** Apply for the PERTS Award to Improve Student Engagement!
------------------------------------------------------------
Are you interested in increasing student engagement across your campus? Apply for the PERTS Award to Improve Student Engagement to pilot Elevate this school year and secure a 40% discount for the 2024-25 school year!

Thanks to philanthropic support, this award will be granted to five schools and/or districts that would like to systematically gather feedback from students and create learning conditions that support students in achieving their full potential.
Apply by April 30 (https://perts.net/elevate/engagement-award)


** Webinar: How to Elevate Student Voice to Improve Student Engagement & Achievement
------------------------------------------------------------
Tuesday, April 30, 5 pm ET
Join PERTS Director of Research, Dr. Sarah Gripshover, and a panel of PERTS partners to learn:
* All about Elevate: an evidence-based tool to leverage student voice for continuous improvement.
* Research on three learning conditions that drive student engagement and achievement.
* Easy-to-implement strategies for nurturing these learning conditions.
* Success stories from educators who have implemented these strategies in their classrooms and schools.

Register today! (https://home.edweb.net/webinar/studentvoice20240430/)


** Convene Together in Communities of Practice!
------------------------------------------------------------
PERTS provides resources for schools implementing Elevate (6-12) or Ascend (higher ed) to facilitate their own “Communities of Practice” to support teachers/instructors in making sense of report data, identifying areas of improvement, and celebrating progress together. For example, take a look at our customizable Final Reflection Protocol as the end of the school year approaches to identify key learnings and make a plan to share with your school community!
Review the Elevate Final Reflection Protocol (http://perts.net/elevate/reflection-meeting)
Review the Ascend Final Reflection Protocol (https://perts.net/ascend/final-reflection-protocol)


** Hear from Students at San Ramon Valley USD about the Power of Their Feedback
------------------------------------------------------------
https://drive.google.com/file/d/1v0_mPFR51Mc-lEukbt2jxaBXaJskUIoK/view
Listen to students share how the feedback they provided with Elevate influenced changes that made their classes more interactive and engaging.
Interested in hearing more student and teacher reflections? Check out the videos linked below!
Students Reflect on Elevate (https://perts.net/elevate/student-reflections)
Teachers Reflect on Elevate (https://perts.net/elevate/teacher-reflections)
Students Reflect on Ascend (https://perts.net/ascend/student-reflections)
Instructors Reflect on Ascend (https://perts.net/ascend/faculty-reflections)


** A Warm Welcome to Our Newest PERTSie!
------------------------------------------------------------

We are thrilled to welcome David Frantzreb to the PERTS team! As of April 2024, he will join us as a Partnership Manager. David is an alum of UNC Charlotte and has experience as a researcher, project manager, and lecturer. David is excited to collaborate with colleges and universities to create more equitable student experiences!
“
[I have noticed in my teaching...] Shift from compliance to ownership—student-centered learning—allowing students to have an active voice and role in their learning.

Elevate Teacher
Quick Links
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=cf73cd1057)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=7b3f3876af&c=cf73cd1057)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-04-15 10:02 UTC, rumenPERTS commented
April 2024
PERTS Newsletter
We hope you had an enjoyable spring break. In this newsletter, we share learning conditions that are strong predictors of student success and resources to improve those conditions. Keep reading to learn more about:
* An opportunity to bring Elevate to your institution
* An edWeb webinar on how to improve student engagement
* Practices and resources to improve classroom learning conditions
* Bright spots from students & teachers at San Ramon Valley USD

We’re also thrilled to welcome our newest PERTSie!


** Apply for the PERTS Award to Improve Student Engagement!
------------------------------------------------------------
Are you interested in increasing student engagement across your campus? Apply for the PERTS Award to Improve Student Engagement to pilot Elevate this school year and secure a 40% discount for the 2024-25 school year!

Thanks to philanthropic support, this award will be granted to five schools and/or districts that would like to systematically gather feedback from students and create learning conditions that support students in achieving their full potential.
Apply by April 30 (https://perts.net/elevate/engagement-award)


** Webinar: How to Elevate Student Voice to Improve Student Engagement & Achievement
------------------------------------------------------------
Tuesday, April 30, 5 pm ET
Join PERTS Director of Research, Dr. Sarah Gripshover, and a panel of PERTS partners to learn:
* All about Elevate: an evidence-based tool to leverage student voice for continuous improvement.
* Research on three learning conditions that drive student engagement and achievement.
* Easy-to-implement strategies for nurturing these learning conditions.
* Success stories from educators who have implemented these strategies in their classrooms and schools.

Register today! (https://home.edweb.net/webinar/studentvoice20240430/)


** Convene Together in Communities of Practice!
------------------------------------------------------------
PERTS provides resources for schools implementing Elevate (6-12) or Ascend (higher ed) to facilitate their own “Communities of Practice” to support teachers/instructors in making sense of report data, identifying areas of improvement, and celebrating progress together. For example, take a look at our customizable Final Reflection Protocol as the end of the school year approaches to identify key learnings and make a plan to share with your school community!
Review the Elevate Final Reflection Protocol (http://perts.net/elevate/reflection-meeting)
Review the Ascend Final Reflection Protocol (https://perts.net/ascend/final-reflection-protocol)


** Hear from Students at San Ramon Valley USD about the Power of Their Feedback
------------------------------------------------------------
https://drive.google.com/file/d/1v0_mPFR51Mc-lEukbt2jxaBXaJskUIoK/view
Listen to students share how the feedback they provided with Elevate influenced changes that made their classes more interactive and engaging.
Interested in hearing more student and teacher reflections? Check out the videos linked below!
Students Reflect on Elevate (https://perts.net/elevate/student-reflections)
Teachers Reflect on Elevate (https://perts.net/elevate/teacher-reflections)
Students Reflect on Ascend (https://perts.net/ascend/student-reflections)
Instructors Reflect on Ascend (https://perts.net/ascend/faculty-reflections)


** A Warm Welcome to Our Newest PERTSie!
------------------------------------------------------------

We are thrilled to welcome David Frantzreb to the PERTS team! As of April 2024, he will join us as a Partnership Manager. David is an alum of UNC Charlotte and has experience as a researcher, project manager, and lecturer. David is excited to collaborate with colleges and universities to create more equitable student experiences!
“
[I have noticed in my teaching...] Shift from compliance to ownership—student-centered learning—allowing students to have an active voice and role in their learning.

Elevate Teacher
Quick Links
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=cf73cd1057)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f97dc5981b&c=cf73cd1057)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-04-15 10:02 UTC, rumenPERTS commented
April 2024
PERTS Newsletter
We hope you had an enjoyable spring break. In this newsletter, we share learning conditions that are strong predictors of student success and resources to improve those conditions. Keep reading to learn more about:
* An opportunity to bring Elevate to your institution
* An edWeb webinar on how to improve student engagement
* Practices and resources to improve classroom learning conditions
* Bright spots from students & teachers at San Ramon Valley USD

We’re also thrilled to welcome our newest PERTSie!


** Apply for the PERTS Award to Improve Student Engagement!
------------------------------------------------------------
Are you interested in increasing student engagement across your campus? Apply for the PERTS Award to Improve Student Engagement to pilot Elevate this school year and secure a 40% discount for the 2024-25 school year!

Thanks to philanthropic support, this award will be granted to five schools and/or districts that would like to systematically gather feedback from students and create learning conditions that support students in achieving their full potential.
Apply by April 30 (https://perts.net/elevate/engagement-award)


** Webinar: How to Elevate Student Voice to Improve Student Engagement & Achievement
------------------------------------------------------------
Tuesday, April 30, 5 pm ET
Join PERTS Director of Research, Dr. Sarah Gripshover, and a panel of PERTS partners to learn:
* All about Elevate: an evidence-based tool to leverage student voice for continuous improvement.
* Research on three learning conditions that drive student engagement and achievement.
* Easy-to-implement strategies for nurturing these learning conditions.
* Success stories from educators who have implemented these strategies in their classrooms and schools.

Register today! (https://home.edweb.net/webinar/studentvoice20240430/)


** Convene Together in Communities of Practice!
------------------------------------------------------------
PERTS provides resources for schools implementing Elevate (6-12) or Ascend (higher ed) to facilitate their own “Communities of Practice” to support teachers/instructors in making sense of report data, identifying areas of improvement, and celebrating progress together. For example, take a look at our customizable Final Reflection Protocol as the end of the school year approaches to identify key learnings and make a plan to share with your school community!
Review the Elevate Final Reflection Protocol (http://perts.net/elevate/reflection-meeting)
Review the Ascend Final Reflection Protocol (https://perts.net/ascend/final-reflection-protocol)


** Hear from Students at San Ramon Valley USD about the Power of Their Feedback
------------------------------------------------------------
https://drive.google.com/file/d/1v0_mPFR51Mc-lEukbt2jxaBXaJskUIoK/view
Listen to students share how the feedback they provided with Elevate influenced changes that made their classes more interactive and engaging.
Interested in hearing more student and teacher reflections? Check out the videos linked below!
Students Reflect on Elevate (https://perts.net/elevate/student-reflections)
Teachers Reflect on Elevate (https://perts.net/elevate/teacher-reflections)
Students Reflect on Ascend (https://perts.net/ascend/student-reflections)
Instructors Reflect on Ascend (https://perts.net/ascend/faculty-reflections)


** A Warm Welcome to Our Newest PERTSie!
------------------------------------------------------------

We are thrilled to welcome David Frantzreb to the PERTS team! As of April 2024, he will join us as a Partnership Manager. David is an alum of UNC Charlotte and has experience as a researcher, project manager, and lecturer. David is excited to collaborate with colleges and universities to create more equitable student experiences!
“
[I have noticed in my teaching...] Shift from compliance to ownership—student-centered learning—allowing students to have an active voice and role in their learning.

Elevate Teacher
Quick Links
Elevate, for Grades 6-12 (https://perts.net/elevate)
Ascend, for Higher Ed (https://perts.net/ascend)
Catalyze, for Ed Leadership (https://perts.net/catalyze)

============================================================
** Twitter (https://twitter.com/pertslab)
** Facebook (https://www.facebook.com/pertslab)
** LinkedIn (https://www.linkedin.com/company/perts/)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=cf73cd1057)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=da5cd98d77&c=cf73cd1057)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-06-11 15:00 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

Creating nurturing learning environments is essential for student success, and PERTS is committed to providing you with the tools and resources to make it happen. That's why we're thrilled to share our first field guide in the series: From Data to Impact: Leveraging Student Voice Data for Meaningful Change! (http://perts.net/data-to-impact-1-redirect)

This practical guide provides education leaders with how to lay a strong foundation for effective improvement cycles that will nurture learning conditions and drive student engagement and achievement.

With examples and a series of guiding questions, this guide can help you:
* Draft a motivating statement of purpose
* Identify, engage, and empower educators who can collect and act on student voice data
* Construct an effective measurement plan that includes significant input from students and provides actionable feedback
* Plan improvement cycles

Download the Field Guide (http://perts.net/data-to-impact-1-redirect)

This resource will empower you to create supportive learning environments where every student can thrive. Explore the field guide (http://perts.net/data-to-impact-1-redirect) today and take the first step toward transformative change.

To schedule a short demo and discuss how PERTS can help you catalyze student engagement and achievement, click here to pick a convenient time (https://www.perts.net/demo) .

About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

LILIA DIAZ DE LEWIS
Director of Programs

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=fc969e700e)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f641712fb8&c=fc969e700e)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-06-11 15:01 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

Creating nurturing learning environments is essential for student success, and PERTS is committed to providing you with the tools and resources to make it happen. That's why we're thrilled to share our first field guide in the series: From Data to Impact: Leveraging Student Voice Data for Meaningful Change! (http://perts.net/data-to-impact-1-redirect)

This practical guide provides education leaders with how to lay a strong foundation for effective improvement cycles that will nurture learning conditions and drive student engagement and achievement.

With examples and a series of guiding questions, this guide can help you:
* Draft a motivating statement of purpose
* Identify, engage, and empower educators who can collect and act on student voice data
* Construct an effective measurement plan that includes significant input from students and provides actionable feedback
* Plan improvement cycles

Download the Field Guide (http://perts.net/data-to-impact-1-redirect)

This resource will empower you to create supportive learning environments where every student can thrive. Explore the field guide (http://perts.net/data-to-impact-1-redirect) today and take the first step toward transformative change.

To schedule a short demo and discuss how PERTS can help you catalyze student engagement and achievement, click here to pick a convenient time (https://www.perts.net/demo) .

About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

LILIA DIAZ DE LEWIS
Director of Programs

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=fc969e700e)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=b4edfd0dd8&c=fc969e700e)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-06-11 15:01 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

Creating nurturing learning environments is essential for student success, and PERTS is committed to providing you with the tools and resources to make it happen. That's why we're thrilled to share our first field guide in the series: From Data to Impact: Leveraging Student Voice Data for Meaningful Change! (http://perts.net/data-to-impact-1-redirect)

This practical guide provides education leaders with how to lay a strong foundation for effective improvement cycles that will nurture learning conditions and drive student engagement and achievement.

With examples and a series of guiding questions, this guide can help you:
* Draft a motivating statement of purpose
* Identify, engage, and empower educators who can collect and act on student voice data
* Construct an effective measurement plan that includes significant input from students and provides actionable feedback
* Plan improvement cycles

Download the Field Guide (http://perts.net/data-to-impact-1-redirect)

This resource will empower you to create supportive learning environments where every student can thrive. Explore the field guide (http://perts.net/data-to-impact-1-redirect) today and take the first step toward transformative change.

To schedule a short demo and discuss how PERTS can help you catalyze student engagement and achievement, click here to pick a convenient time (https://www.perts.net/demo) .

About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

LILIA DIAZ DE LEWIS
Director of Programs

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=fc969e700e)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=298ead533f&c=fc969e700e)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-06-11 15:02 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

Creating nurturing learning environments is essential for student success, and PERTS is committed to providing you with the tools and resources to make it happen. That's why we're thrilled to share our first field guide in the series: From Data to Impact: Leveraging Student Voice Data for Meaningful Change! (http://perts.net/data-to-impact-1-redirect)

This practical guide provides education leaders with how to lay a strong foundation for effective improvement cycles that will nurture learning conditions and drive student engagement and achievement.

With examples and a series of guiding questions, this guide can help you:
* Draft a motivating statement of purpose
* Identify, engage, and empower educators who can collect and act on student voice data
* Construct an effective measurement plan that includes significant input from students and provides actionable feedback
* Plan improvement cycles

Download the Field Guide (http://perts.net/data-to-impact-1-redirect)

This resource will empower you to create supportive learning environments where every student can thrive. Explore the field guide (http://perts.net/data-to-impact-1-redirect) today and take the first step toward transformative change.

To schedule a short demo and discuss how PERTS can help you catalyze student engagement and achievement, click here to pick a convenient time (https://www.perts.net/demo) .

About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

LILIA DIAZ DE LEWIS
Director of Programs

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=fc969e700e)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=da5cd98d77&c=fc969e700e)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-06-11 15:02 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

Creating nurturing learning environments is essential for student success, and PERTS is committed to providing you with the tools and resources to make it happen. That's why we're thrilled to share our first field guide in the series: From Data to Impact: Leveraging Student Voice Data for Meaningful Change! (http://perts.net/data-to-impact-1-redirect)

This practical guide provides education leaders with how to lay a strong foundation for effective improvement cycles that will nurture learning conditions and drive student engagement and achievement.

With examples and a series of guiding questions, this guide can help you:
* Draft a motivating statement of purpose
* Identify, engage, and empower educators who can collect and act on student voice data
* Construct an effective measurement plan that includes significant input from students and provides actionable feedback
* Plan improvement cycles

Download the Field Guide (http://perts.net/data-to-impact-1-redirect)

This resource will empower you to create supportive learning environments where every student can thrive. Explore the field guide (http://perts.net/data-to-impact-1-redirect) today and take the first step toward transformative change.

To schedule a short demo and discuss how PERTS can help you catalyze student engagement and achievement, click here to pick a convenient time (https://www.perts.net/demo) .

About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

LILIA DIAZ DE LEWIS
Director of Programs

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=fc969e700e)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f66b76caa6&c=fc969e700e)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-06-11 15:03 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

Creating nurturing learning environments is essential for student success, and PERTS is committed to providing you with the tools and resources to make it happen. That's why we're thrilled to share our first field guide in the series: From Data to Impact: Leveraging Student Voice Data for Meaningful Change! (http://perts.net/data-to-impact-1-redirect)

This practical guide provides education leaders with how to lay a strong foundation for effective improvement cycles that will nurture learning conditions and drive student engagement and achievement.

With examples and a series of guiding questions, this guide can help you:
* Draft a motivating statement of purpose
* Identify, engage, and empower educators who can collect and act on student voice data
* Construct an effective measurement plan that includes significant input from students and provides actionable feedback
* Plan improvement cycles

Download the Field Guide (http://perts.net/data-to-impact-1-redirect)

This resource will empower you to create supportive learning environments where every student can thrive. Explore the field guide (http://perts.net/data-to-impact-1-redirect) today and take the first step toward transformative change.

To schedule a short demo and discuss how PERTS can help you catalyze student engagement and achievement, click here to pick a convenient time (https://www.perts.net/demo) .

About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

LILIA DIAZ DE LEWIS
Director of Programs

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=fc969e700e)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=36456eb76b&c=fc969e700e)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-06-11 15:04 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

Creating nurturing learning environments is essential for student success, and PERTS is committed to providing you with the tools and resources to make it happen. That's why we're thrilled to share our first field guide in the series: From Data to Impact: Leveraging Student Voice Data for Meaningful Change! (http://perts.net/data-to-impact-1-redirect)

This practical guide provides education leaders with how to lay a strong foundation for effective improvement cycles that will nurture learning conditions and drive student engagement and achievement.

With examples and a series of guiding questions, this guide can help you:
* Draft a motivating statement of purpose
* Identify, engage, and empower educators who can collect and act on student voice data
* Construct an effective measurement plan that includes significant input from students and provides actionable feedback
* Plan improvement cycles

Download the Field Guide (http://perts.net/data-to-impact-1-redirect)

This resource will empower you to create supportive learning environments where every student can thrive. Explore the field guide (http://perts.net/data-to-impact-1-redirect) today and take the first step toward transformative change.

To schedule a short demo and discuss how PERTS can help you catalyze student engagement and achievement, click here to pick a convenient time (https://www.perts.net/demo) .

About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

LILIA DIAZ DE LEWIS
Director of Programs

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=fc969e700e)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=7b3f3876af&c=fc969e700e)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-06-11 15:04 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

Creating nurturing learning environments is essential for student success, and PERTS is committed to providing you with the tools and resources to make it happen. That's why we're thrilled to share our first field guide in the series: From Data to Impact: Leveraging Student Voice Data for Meaningful Change! (http://perts.net/data-to-impact-1-redirect)

This practical guide provides education leaders with how to lay a strong foundation for effective improvement cycles that will nurture learning conditions and drive student engagement and achievement.

With examples and a series of guiding questions, this guide can help you:
* Draft a motivating statement of purpose
* Identify, engage, and empower educators who can collect and act on student voice data
* Construct an effective measurement plan that includes significant input from students and provides actionable feedback
* Plan improvement cycles

Download the Field Guide (http://perts.net/data-to-impact-1-redirect)

This resource will empower you to create supportive learning environments where every student can thrive. Explore the field guide (http://perts.net/data-to-impact-1-redirect) today and take the first step toward transformative change.

To schedule a short demo and discuss how PERTS can help you catalyze student engagement and achievement, click here to pick a convenient time (https://www.perts.net/demo) .

About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

LILIA DIAZ DE LEWIS
Director of Programs

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=fc969e700e)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f97dc5981b&c=fc969e700e)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-08-29 10:30 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

Start the new school year strong by establishing your classroom learning conditions. Research has shown that students are more engaged and successful when they positively experience their learning environment. What learning conditions should you create in your classroom and how do you know if they are effective?

PERTS can help. PERTS Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. As part of the Elevate program, the Elevate survey measures students' perceptions of nine learning conditions (https://perts.net/elevate/measures) and provides practical recommendations for research-based instructional strategies that support the unique needs of each class.

What are the nine learning conditions (https://perts.net/elevate/measures) , measured by the PERTS Elevate survey, that influence students' motivation?
Download the Nine Core Learning Conditions (https://perts.net/elevate/measures)

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (https://www.perts.net/demo) .

About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=7d31e4430e)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=298ead533f&c=7d31e4430e)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-08-29 10:30 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

Start the new school year strong by establishing your classroom learning conditions. Research has shown that students are more engaged and successful when they positively experience their learning environment. What learning conditions should you create in your classroom and how do you know if they are effective?

PERTS can help. PERTS Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. As part of the Elevate program, the Elevate survey measures students' perceptions of nine learning conditions (https://perts.net/elevate/measures) and provides practical recommendations for research-based instructional strategies that support the unique needs of each class.

What are the nine learning conditions (https://perts.net/elevate/measures) , measured by the PERTS Elevate survey, that influence students' motivation?
Download the Nine Core Learning Conditions (https://perts.net/elevate/measures)

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (https://www.perts.net/demo) .

About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=7d31e4430e)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f97dc5981b&c=7d31e4430e)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-08-29 10:30 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

Start the new school year strong by establishing your classroom learning conditions. Research has shown that students are more engaged and successful when they positively experience their learning environment. What learning conditions should you create in your classroom and how do you know if they are effective?

PERTS can help. PERTS Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. As part of the Elevate program, the Elevate survey measures students' perceptions of nine learning conditions (https://perts.net/elevate/measures) and provides practical recommendations for research-based instructional strategies that support the unique needs of each class.

What are the nine learning conditions (https://perts.net/elevate/measures) , measured by the PERTS Elevate survey, that influence students' motivation?
Download the Nine Core Learning Conditions (https://perts.net/elevate/measures)

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (https://www.perts.net/demo) .

About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=7d31e4430e)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f641712fb8&c=7d31e4430e)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-08-29 10:30 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

Start the new school year strong by establishing your classroom learning conditions. Research has shown that students are more engaged and successful when they positively experience their learning environment. What learning conditions should you create in your classroom and how do you know if they are effective?

PERTS can help. PERTS Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. As part of the Elevate program, the Elevate survey measures students' perceptions of nine learning conditions (https://perts.net/elevate/measures) and provides practical recommendations for research-based instructional strategies that support the unique needs of each class.

What are the nine learning conditions (https://perts.net/elevate/measures) , measured by the PERTS Elevate survey, that influence students' motivation?
Download the Nine Core Learning Conditions (https://perts.net/elevate/measures)

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (https://www.perts.net/demo) .

About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=7d31e4430e)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=7b3f3876af&c=7d31e4430e)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-08-29 10:30 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

Start the new school year strong by establishing your classroom learning conditions. Research has shown that students are more engaged and successful when they positively experience their learning environment. What learning conditions should you create in your classroom and how do you know if they are effective?

PERTS can help. PERTS Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. As part of the Elevate program, the Elevate survey measures students' perceptions of nine learning conditions (https://perts.net/elevate/measures) and provides practical recommendations for research-based instructional strategies that support the unique needs of each class.

What are the nine learning conditions (https://perts.net/elevate/measures) , measured by the PERTS Elevate survey, that influence students' motivation?
Download the Nine Core Learning Conditions (https://perts.net/elevate/measures)

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (https://www.perts.net/demo) .

About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=7d31e4430e)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=da5cd98d77&c=7d31e4430e)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-08-29 10:31 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

Start the new school year strong by establishing your classroom learning conditions. Research has shown that students are more engaged and successful when they positively experience their learning environment. What learning conditions should you create in your classroom and how do you know if they are effective?

PERTS can help. PERTS Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. As part of the Elevate program, the Elevate survey measures students' perceptions of nine learning conditions (https://perts.net/elevate/measures) and provides practical recommendations for research-based instructional strategies that support the unique needs of each class.

What are the nine learning conditions (https://perts.net/elevate/measures) , measured by the PERTS Elevate survey, that influence students' motivation?
Download the Nine Core Learning Conditions (https://perts.net/elevate/measures)

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (https://www.perts.net/demo) .

About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=7d31e4430e)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=36456eb76b&c=7d31e4430e)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-08-29 10:31 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

Start the new school year strong by establishing your classroom learning conditions. Research has shown that students are more engaged and successful when they positively experience their learning environment. What learning conditions should you create in your classroom and how do you know if they are effective?

PERTS can help. PERTS Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. As part of the Elevate program, the Elevate survey measures students' perceptions of nine learning conditions (https://perts.net/elevate/measures) and provides practical recommendations for research-based instructional strategies that support the unique needs of each class.

What are the nine learning conditions (https://perts.net/elevate/measures) , measured by the PERTS Elevate survey, that influence students' motivation?
Download the Nine Core Learning Conditions (https://perts.net/elevate/measures)

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (https://www.perts.net/demo) .

About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=7d31e4430e)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=b4edfd0dd8&c=7d31e4430e)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-08-29 10:32 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

Start the new school year strong by establishing your classroom learning conditions. Research has shown that students are more engaged and successful when they positively experience their learning environment. What learning conditions should you create in your classroom and how do you know if they are effective?

PERTS can help. PERTS Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. As part of the Elevate program, the Elevate survey measures students' perceptions of nine learning conditions (https://perts.net/elevate/measures) and provides practical recommendations for research-based instructional strategies that support the unique needs of each class.

What are the nine learning conditions (https://perts.net/elevate/measures) , measured by the PERTS Elevate survey, that influence students' motivation?
Download the Nine Core Learning Conditions (https://perts.net/elevate/measures)

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (https://www.perts.net/demo) .

About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=7d31e4430e)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f66b76caa6&c=7d31e4430e)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-10-10 10:01 UTC, rumenPERTS commented
** Dear ,
------------------------------------------------------------
With the school year officially underway, it’s important to be intentional about the classroom culture you build. Research has shown that students are more engaged and successful when they positively experience their learning environment, and amplifying student voice is critical to that experience. But what is student voice, and why does it matter?

Students can take an active role in their learning by sharing their thoughts and opinions with teachers who demonstrate that they value their perspectives. Students are more actively engaged in their schoolwork when they have choices, share their ideas, and feel heard.

Teachers who value student voice should provide opportunities for students to give feedback to the teacher about how they experience their class. The PERTS Elevate program includes a survey tool to continuously monitor students’ perception of the classroom environment and build conditions that catalyze engagement and learning.

Want to learn more about student voice and how to cultivate it in your classroom? Download our student voice guide (http://perts.net/elevate/student-voice) .

Download our Student Voice Guide (http://perts.net/elevate/student-voice)

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (http://perts.net/consultation) .

About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=5689f8bc66)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f97dc5981b&c=5689f8bc66)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-10-10 10:01 UTC, rumenPERTS commented
** Dear ,
------------------------------------------------------------
With the school year officially underway, it’s important to be intentional about the classroom culture you build. Research has shown that students are more engaged and successful when they positively experience their learning environment, and amplifying student voice is critical to that experience. But what is student voice, and why does it matter?

Students can take an active role in their learning by sharing their thoughts and opinions with teachers who demonstrate that they value their perspectives. Students are more actively engaged in their schoolwork when they have choices, share their ideas, and feel heard.

Teachers who value student voice should provide opportunities for students to give feedback to the teacher about how they experience their class. The PERTS Elevate program includes a survey tool to continuously monitor students’ perception of the classroom environment and build conditions that catalyze engagement and learning.

Want to learn more about student voice and how to cultivate it in your classroom? Download our student voice guide (http://perts.net/elevate/student-voice) .

Download our Student Voice Guide (http://perts.net/elevate/student-voice)

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (http://perts.net/consultation) .

About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=5689f8bc66)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=298ead533f&c=5689f8bc66)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-10-10 10:01 UTC, rumenPERTS commented
** Dear ,
------------------------------------------------------------
With the school year officially underway, it’s important to be intentional about the classroom culture you build. Research has shown that students are more engaged and successful when they positively experience their learning environment, and amplifying student voice is critical to that experience. But what is student voice, and why does it matter?

Students can take an active role in their learning by sharing their thoughts and opinions with teachers who demonstrate that they value their perspectives. Students are more actively engaged in their schoolwork when they have choices, share their ideas, and feel heard.

Teachers who value student voice should provide opportunities for students to give feedback to the teacher about how they experience their class. The PERTS Elevate program includes a survey tool to continuously monitor students’ perception of the classroom environment and build conditions that catalyze engagement and learning.

Want to learn more about student voice and how to cultivate it in your classroom? Download our student voice guide (http://perts.net/elevate/student-voice) .

Download our Student Voice Guide (http://perts.net/elevate/student-voice)

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (http://perts.net/consultation) .

About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=5689f8bc66)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=b4edfd0dd8&c=5689f8bc66)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-10-10 10:01 UTC, rumenPERTS commented
** Dear ,
------------------------------------------------------------
With the school year officially underway, it’s important to be intentional about the classroom culture you build. Research has shown that students are more engaged and successful when they positively experience their learning environment, and amplifying student voice is critical to that experience. But what is student voice, and why does it matter?

Students can take an active role in their learning by sharing their thoughts and opinions with teachers who demonstrate that they value their perspectives. Students are more actively engaged in their schoolwork when they have choices, share their ideas, and feel heard.

Teachers who value student voice should provide opportunities for students to give feedback to the teacher about how they experience their class. The PERTS Elevate program includes a survey tool to continuously monitor students’ perception of the classroom environment and build conditions that catalyze engagement and learning.

Want to learn more about student voice and how to cultivate it in your classroom? Download our student voice guide (http://perts.net/elevate/student-voice) .

Download our Student Voice Guide (http://perts.net/elevate/student-voice)

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (http://perts.net/consultation) .

About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=5689f8bc66)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f66b76caa6&c=5689f8bc66)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-10-10 10:02 UTC, rumenPERTS commented
** Dear ,
------------------------------------------------------------
With the school year officially underway, it’s important to be intentional about the classroom culture you build. Research has shown that students are more engaged and successful when they positively experience their learning environment, and amplifying student voice is critical to that experience. But what is student voice, and why does it matter?

Students can take an active role in their learning by sharing their thoughts and opinions with teachers who demonstrate that they value their perspectives. Students are more actively engaged in their schoolwork when they have choices, share their ideas, and feel heard.

Teachers who value student voice should provide opportunities for students to give feedback to the teacher about how they experience their class. The PERTS Elevate program includes a survey tool to continuously monitor students’ perception of the classroom environment and build conditions that catalyze engagement and learning.

Want to learn more about student voice and how to cultivate it in your classroom? Download our student voice guide (http://perts.net/elevate/student-voice) .

Download our Student Voice Guide (http://perts.net/elevate/student-voice)

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (http://perts.net/consultation) .

About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=5689f8bc66)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=36456eb76b&c=5689f8bc66)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-10-10 10:02 UTC, rumenPERTS commented
** Dear ,
------------------------------------------------------------
With the school year officially underway, it’s important to be intentional about the classroom culture you build. Research has shown that students are more engaged and successful when they positively experience their learning environment, and amplifying student voice is critical to that experience. But what is student voice, and why does it matter?

Students can take an active role in their learning by sharing their thoughts and opinions with teachers who demonstrate that they value their perspectives. Students are more actively engaged in their schoolwork when they have choices, share their ideas, and feel heard.

Teachers who value student voice should provide opportunities for students to give feedback to the teacher about how they experience their class. The PERTS Elevate program includes a survey tool to continuously monitor students’ perception of the classroom environment and build conditions that catalyze engagement and learning.

Want to learn more about student voice and how to cultivate it in your classroom? Download our student voice guide (http://perts.net/elevate/student-voice) .

Download our Student Voice Guide (http://perts.net/elevate/student-voice)

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (http://perts.net/consultation) .

About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=5689f8bc66)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f641712fb8&c=5689f8bc66)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-10-10 10:02 UTC, rumenPERTS commented
** Dear ,
------------------------------------------------------------
With the school year officially underway, it’s important to be intentional about the classroom culture you build. Research has shown that students are more engaged and successful when they positively experience their learning environment, and amplifying student voice is critical to that experience. But what is student voice, and why does it matter?

Students can take an active role in their learning by sharing their thoughts and opinions with teachers who demonstrate that they value their perspectives. Students are more actively engaged in their schoolwork when they have choices, share their ideas, and feel heard.

Teachers who value student voice should provide opportunities for students to give feedback to the teacher about how they experience their class. The PERTS Elevate program includes a survey tool to continuously monitor students’ perception of the classroom environment and build conditions that catalyze engagement and learning.

Want to learn more about student voice and how to cultivate it in your classroom? Download our student voice guide (http://perts.net/elevate/student-voice) .

Download our Student Voice Guide (http://perts.net/elevate/student-voice)

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (http://perts.net/consultation) .

About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=5689f8bc66)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=da5cd98d77&c=5689f8bc66)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-10-10 10:02 UTC, rumenPERTS commented
** Dear ,
------------------------------------------------------------
With the school year officially underway, it’s important to be intentional about the classroom culture you build. Research has shown that students are more engaged and successful when they positively experience their learning environment, and amplifying student voice is critical to that experience. But what is student voice, and why does it matter?

Students can take an active role in their learning by sharing their thoughts and opinions with teachers who demonstrate that they value their perspectives. Students are more actively engaged in their schoolwork when they have choices, share their ideas, and feel heard.

Teachers who value student voice should provide opportunities for students to give feedback to the teacher about how they experience their class. The PERTS Elevate program includes a survey tool to continuously monitor students’ perception of the classroom environment and build conditions that catalyze engagement and learning.

Want to learn more about student voice and how to cultivate it in your classroom? Download our student voice guide (http://perts.net/elevate/student-voice) .

Download our Student Voice Guide (http://perts.net/elevate/student-voice)

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (http://perts.net/consultation) .

About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2024 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=5689f8bc66)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=7b3f3876af&c=5689f8bc66)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2024-12-01 11:05 UTC, rumenPERTS commented
Field Guide #2


** Dear Educator,
------------------------------------------------------------

Student voice promotes student engagement and improves learning outcomes. But this doesn’t happen by accident. Educators need the right kind of support to solicit and act on student voice data effectively.


In our new field guide, PERTS is excited to share what we’ve learned about empowering educators to use student voice data to drive meaningful improvement. The guide walks education leaders through three critical principles for empowering educators, as well as concrete examples of what they look like in action. We believe these learnings will benefit anyone who hopes to positively impact student experience.

* Emphasize the role of formative feedback
* Build collaborative structures with strong relational trust
* Do not wait for the “perfect” moment to take action

Download the Field Guide (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=ff501840cd&e=298ead533f)

This resource will empower you to provide support to teachers and adults to allow for positive change in school culture. Explore the field guide (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=175fc0c120&e=298ead533f) today and take the next step toward transformative change.

To schedule a short demo and discuss how PERTS can help you catalyze student engagement and achievement, click here to pick a convenient time (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=55c0187fa2&e=298ead533f) .

About PERTS
The Project for Education Research that Scales (PERTS (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=b30771d959&e=298ead533f) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

LILIA DIAZ DE LEWIS
Director of Programs

https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=d4b129e363&e=298ead533f
https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=3aa9b87938&e=298ead533f
https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=c2efe0ca2a&e=298ead533f
https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=62ce85f928&e=298ead533f

Copyright © 2024 PERTS, All rights reserved.
    You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=4fe57a33fe) or unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=298ead533f&c=4fe57a33fe) .

2024-12-01 11:05 UTC, rumenPERTS commented
Field Guide #2


** Dear Educator,
------------------------------------------------------------

Student voice promotes student engagement and improves learning outcomes. But this doesn’t happen by accident. Educators need the right kind of support to solicit and act on student voice data effectively.


In our new field guide, PERTS is excited to share what we’ve learned about empowering educators to use student voice data to drive meaningful improvement. The guide walks education leaders through three critical principles for empowering educators, as well as concrete examples of what they look like in action. We believe these learnings will benefit anyone who hopes to positively impact student experience.

* Emphasize the role of formative feedback
* Build collaborative structures with strong relational trust
* Do not wait for the “perfect” moment to take action

Download the Field Guide (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=ff501840cd&e=da5cd98d77)

This resource will empower you to provide support to teachers and adults to allow for positive change in school culture. Explore the field guide (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=175fc0c120&e=da5cd98d77) today and take the next step toward transformative change.

To schedule a short demo and discuss how PERTS can help you catalyze student engagement and achievement, click here to pick a convenient time (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=55c0187fa2&e=da5cd98d77) .

About PERTS
The Project for Education Research that Scales (PERTS (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=b30771d959&e=da5cd98d77) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

LILIA DIAZ DE LEWIS
Director of Programs

https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=d4b129e363&e=da5cd98d77
https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=3aa9b87938&e=da5cd98d77
https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=c2efe0ca2a&e=da5cd98d77
https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=62ce85f928&e=da5cd98d77

Copyright © 2024 PERTS, All rights reserved.
    You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=4fe57a33fe) or unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=da5cd98d77&c=4fe57a33fe) .

2024-12-01 11:05 UTC, rumenPERTS commented
Field Guide #2


** Dear Educator,
------------------------------------------------------------

Student voice promotes student engagement and improves learning outcomes. But this doesn’t happen by accident. Educators need the right kind of support to solicit and act on student voice data effectively.


In our new field guide, PERTS is excited to share what we’ve learned about empowering educators to use student voice data to drive meaningful improvement. The guide walks education leaders through three critical principles for empowering educators, as well as concrete examples of what they look like in action. We believe these learnings will benefit anyone who hopes to positively impact student experience.

* Emphasize the role of formative feedback
* Build collaborative structures with strong relational trust
* Do not wait for the “perfect” moment to take action

Download the Field Guide (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=ff501840cd&e=7b3f3876af)

This resource will empower you to provide support to teachers and adults to allow for positive change in school culture. Explore the field guide (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=175fc0c120&e=7b3f3876af) today and take the next step toward transformative change.

To schedule a short demo and discuss how PERTS can help you catalyze student engagement and achievement, click here to pick a convenient time (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=55c0187fa2&e=7b3f3876af) .

About PERTS
The Project for Education Research that Scales (PERTS (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=b30771d959&e=7b3f3876af) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

LILIA DIAZ DE LEWIS
Director of Programs

https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=d4b129e363&e=7b3f3876af
https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=3aa9b87938&e=7b3f3876af
https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=c2efe0ca2a&e=7b3f3876af
https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=62ce85f928&e=7b3f3876af

Copyright © 2024 PERTS, All rights reserved.
    You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=4fe57a33fe) or unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=7b3f3876af&c=4fe57a33fe) .

2024-12-01 11:05 UTC, rumenPERTS commented
Field Guide #2


** Dear Educator,
------------------------------------------------------------

Student voice promotes student engagement and improves learning outcomes. But this doesn’t happen by accident. Educators need the right kind of support to solicit and act on student voice data effectively.


In our new field guide, PERTS is excited to share what we’ve learned about empowering educators to use student voice data to drive meaningful improvement. The guide walks education leaders through three critical principles for empowering educators, as well as concrete examples of what they look like in action. We believe these learnings will benefit anyone who hopes to positively impact student experience.

* Emphasize the role of formative feedback
* Build collaborative structures with strong relational trust
* Do not wait for the “perfect” moment to take action

Download the Field Guide (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=ff501840cd&e=36456eb76b)

This resource will empower you to provide support to teachers and adults to allow for positive change in school culture. Explore the field guide (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=175fc0c120&e=36456eb76b) today and take the next step toward transformative change.

To schedule a short demo and discuss how PERTS can help you catalyze student engagement and achievement, click here to pick a convenient time (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=55c0187fa2&e=36456eb76b) .

About PERTS
The Project for Education Research that Scales (PERTS (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=b30771d959&e=36456eb76b) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

LILIA DIAZ DE LEWIS
Director of Programs

https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=d4b129e363&e=36456eb76b
https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=3aa9b87938&e=36456eb76b
https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=c2efe0ca2a&e=36456eb76b
https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=62ce85f928&e=36456eb76b

Copyright © 2024 PERTS, All rights reserved.
    You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=4fe57a33fe) or unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=36456eb76b&c=4fe57a33fe) .

2024-12-03 23:00 UTC, rumenPERTS commented
Field Guide #2


** Dear Educator,
------------------------------------------------------------

Student voice promotes student engagement and improves learning outcomes. But this doesn’t happen by accident. Educators need the right kind of support to solicit and act on student voice data effectively.


In our new field guide, PERTS is excited to share what we’ve learned about empowering educators to use student voice data to drive meaningful improvement. The guide walks education leaders through three critical principles for empowering educators, as well as concrete examples of what they look like in action. We believe these learnings will benefit anyone who hopes to positively impact student experience.

* Emphasize the role of formative feedback
* Build collaborative structures with strong relational trust
* Do not wait for the “perfect” moment to take action

Download the Field Guide (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=885aabeb69&e=b4edfd0dd8)

This resource will empower you to provide support to teachers and adults to allow for positive change in school culture. Explore the field guide (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=90185e9821&e=b4edfd0dd8) today and take the next step toward transformative change.

To schedule a short demo and discuss how PERTS can help you catalyze student engagement and achievement, click here to pick a convenient time (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=3961147b09&e=b4edfd0dd8) .

About PERTS
The Project for Education Research that Scales (PERTS (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=3473dc1311&e=b4edfd0dd8) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

LILIA DIAZ DE LEWIS
Director of Programs

https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=ad03166806&e=b4edfd0dd8
https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=6a3fac1796&e=b4edfd0dd8
https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=f5ddc6bb4e&e=b4edfd0dd8
https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=a3c225f918&e=b4edfd0dd8

Copyright © 2024 PERTS, All rights reserved.
    You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=c9949a374d) or unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=b4edfd0dd8&c=c9949a374d) .

2024-12-03 23:00 UTC, rumenPERTS commented
Field Guide #2


** Dear Educator,
------------------------------------------------------------

Student voice promotes student engagement and improves learning outcomes. But this doesn’t happen by accident. Educators need the right kind of support to solicit and act on student voice data effectively.


In our new field guide, PERTS is excited to share what we’ve learned about empowering educators to use student voice data to drive meaningful improvement. The guide walks education leaders through three critical principles for empowering educators, as well as concrete examples of what they look like in action. We believe these learnings will benefit anyone who hopes to positively impact student experience.

* Emphasize the role of formative feedback
* Build collaborative structures with strong relational trust
* Do not wait for the “perfect” moment to take action

Download the Field Guide (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=885aabeb69&e=f641712fb8)

This resource will empower you to provide support to teachers and adults to allow for positive change in school culture. Explore the field guide (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=90185e9821&e=f641712fb8) today and take the next step toward transformative change.

To schedule a short demo and discuss how PERTS can help you catalyze student engagement and achievement, click here to pick a convenient time (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=3961147b09&e=f641712fb8) .

About PERTS
The Project for Education Research that Scales (PERTS (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=3473dc1311&e=f641712fb8) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

LILIA DIAZ DE LEWIS
Director of Programs

https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=ad03166806&e=f641712fb8
https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=6a3fac1796&e=f641712fb8
https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=f5ddc6bb4e&e=f641712fb8
https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=a3c225f918&e=f641712fb8

Copyright © 2024 PERTS, All rights reserved.
    You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=c9949a374d) or unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f641712fb8&c=c9949a374d) .

2024-12-03 23:00 UTC, rumenPERTS commented
Field Guide #2


** Dear Educator,
------------------------------------------------------------

Student voice promotes student engagement and improves learning outcomes. But this doesn’t happen by accident. Educators need the right kind of support to solicit and act on student voice data effectively.


In our new field guide, PERTS is excited to share what we’ve learned about empowering educators to use student voice data to drive meaningful improvement. The guide walks education leaders through three critical principles for empowering educators, as well as concrete examples of what they look like in action. We believe these learnings will benefit anyone who hopes to positively impact student experience.

* Emphasize the role of formative feedback
* Build collaborative structures with strong relational trust
* Do not wait for the “perfect” moment to take action

Download the Field Guide (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=885aabeb69&e=f97dc5981b)

This resource will empower you to provide support to teachers and adults to allow for positive change in school culture. Explore the field guide (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=90185e9821&e=f97dc5981b) today and take the next step toward transformative change.

To schedule a short demo and discuss how PERTS can help you catalyze student engagement and achievement, click here to pick a convenient time (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=3961147b09&e=f97dc5981b) .

About PERTS
The Project for Education Research that Scales (PERTS (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=3473dc1311&e=f97dc5981b) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

LILIA DIAZ DE LEWIS
Director of Programs

https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=ad03166806&e=f97dc5981b
https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=6a3fac1796&e=f97dc5981b
https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=f5ddc6bb4e&e=f97dc5981b
https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=a3c225f918&e=f97dc5981b

Copyright © 2024 PERTS, All rights reserved.
    You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=c9949a374d) or unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f97dc5981b&c=c9949a374d) .

2024-12-03 23:00 UTC, rumenPERTS commented
Field Guide #2


** Dear Educator,
------------------------------------------------------------

Student voice promotes student engagement and improves learning outcomes. But this doesn’t happen by accident. Educators need the right kind of support to solicit and act on student voice data effectively.


In our new field guide, PERTS is excited to share what we’ve learned about empowering educators to use student voice data to drive meaningful improvement. The guide walks education leaders through three critical principles for empowering educators, as well as concrete examples of what they look like in action. We believe these learnings will benefit anyone who hopes to positively impact student experience.

* Emphasize the role of formative feedback
* Build collaborative structures with strong relational trust
* Do not wait for the “perfect” moment to take action

Download the Field Guide (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=885aabeb69&e=f66b76caa6)

This resource will empower you to provide support to teachers and adults to allow for positive change in school culture. Explore the field guide (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=90185e9821&e=f66b76caa6) today and take the next step toward transformative change.

To schedule a short demo and discuss how PERTS can help you catalyze student engagement and achievement, click here to pick a convenient time (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=3961147b09&e=f66b76caa6) .

About PERTS
The Project for Education Research that Scales (PERTS (https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=3473dc1311&e=f66b76caa6) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

LILIA DIAZ DE LEWIS
Director of Programs

https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=ad03166806&e=f66b76caa6
https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=6a3fac1796&e=f66b76caa6
https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=f5ddc6bb4e&e=f66b76caa6
https://perts.us10.list-manage.com/track/click?u=7edccf60df2a8af6ca924978b&id=a3c225f918&e=f66b76caa6

Copyright © 2024 PERTS, All rights reserved.
    You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=c9949a374d) or unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f66b76caa6&c=c9949a374d) .

2025-01-12 11:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------
Are you ready to transform your classroom into a dynamic learning environment?

When students experience their work as meaningful and discover the personal relevance of what they're learning, they're more likely to...
* feel proud and energized by their work
* feel a sense of autonomy and ownership over their learning
* persist when they encounter challenges

When teachers not just internalize but take ownership of these principles and act on them, they can create positive and meaningful learning environments. Want to learn more about meaningful work and how to cultivate it in your classroom? Download this guide on Meaningful Work (https://perts.net/elevate/meaningful-work) . The PERTS Elevate program helps educators foster more engaging and meaningful work for students.
Download our Meaningful Work Guide (https://perts.net/elevate/meaningful-work)
About Elevate
Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more (https://www.perts.net/elevate) . ​

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (http://perts.net/consultation) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=40b6a13e84)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f641712fb8&c=40b6a13e84)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-01-12 11:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------
Are you ready to transform your classroom into a dynamic learning environment?

When students experience their work as meaningful and discover the personal relevance of what they're learning, they're more likely to...
* feel proud and energized by their work
* feel a sense of autonomy and ownership over their learning
* persist when they encounter challenges

When teachers not just internalize but take ownership of these principles and act on them, they can create positive and meaningful learning environments. Want to learn more about meaningful work and how to cultivate it in your classroom? Download this guide on Meaningful Work (https://perts.net/elevate/meaningful-work) . The PERTS Elevate program helps educators foster more engaging and meaningful work for students.
Download our Meaningful Work Guide (https://perts.net/elevate/meaningful-work)
About Elevate
Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more (https://www.perts.net/elevate) . ​

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (http://perts.net/consultation) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=40b6a13e84)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=da5cd98d77&c=40b6a13e84)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-01-12 11:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------
Are you ready to transform your classroom into a dynamic learning environment?

When students experience their work as meaningful and discover the personal relevance of what they're learning, they're more likely to...
* feel proud and energized by their work
* feel a sense of autonomy and ownership over their learning
* persist when they encounter challenges

When teachers not just internalize but take ownership of these principles and act on them, they can create positive and meaningful learning environments. Want to learn more about meaningful work and how to cultivate it in your classroom? Download this guide on Meaningful Work (https://perts.net/elevate/meaningful-work) . The PERTS Elevate program helps educators foster more engaging and meaningful work for students.
Download our Meaningful Work Guide (https://perts.net/elevate/meaningful-work)
About Elevate
Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more (https://www.perts.net/elevate) . ​

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (http://perts.net/consultation) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=40b6a13e84)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=7b3f3876af&c=40b6a13e84)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-01-12 11:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------
Are you ready to transform your classroom into a dynamic learning environment?

When students experience their work as meaningful and discover the personal relevance of what they're learning, they're more likely to...
* feel proud and energized by their work
* feel a sense of autonomy and ownership over their learning
* persist when they encounter challenges

When teachers not just internalize but take ownership of these principles and act on them, they can create positive and meaningful learning environments. Want to learn more about meaningful work and how to cultivate it in your classroom? Download this guide on Meaningful Work (https://perts.net/elevate/meaningful-work) . The PERTS Elevate program helps educators foster more engaging and meaningful work for students.
Download our Meaningful Work Guide (https://perts.net/elevate/meaningful-work)
About Elevate
Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more (https://www.perts.net/elevate) . ​

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (http://perts.net/consultation) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=40b6a13e84)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f97dc5981b&c=40b6a13e84)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-01-12 11:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------
Are you ready to transform your classroom into a dynamic learning environment?

When students experience their work as meaningful and discover the personal relevance of what they're learning, they're more likely to...
* feel proud and energized by their work
* feel a sense of autonomy and ownership over their learning
* persist when they encounter challenges

When teachers not just internalize but take ownership of these principles and act on them, they can create positive and meaningful learning environments. Want to learn more about meaningful work and how to cultivate it in your classroom? Download this guide on Meaningful Work (https://perts.net/elevate/meaningful-work) . The PERTS Elevate program helps educators foster more engaging and meaningful work for students.
Download our Meaningful Work Guide (https://perts.net/elevate/meaningful-work)
About Elevate
Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more (https://www.perts.net/elevate) . ​

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (http://perts.net/consultation) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=40b6a13e84)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=298ead533f&c=40b6a13e84)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-01-12 11:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------
Are you ready to transform your classroom into a dynamic learning environment?

When students experience their work as meaningful and discover the personal relevance of what they're learning, they're more likely to...
* feel proud and energized by their work
* feel a sense of autonomy and ownership over their learning
* persist when they encounter challenges

When teachers not just internalize but take ownership of these principles and act on them, they can create positive and meaningful learning environments. Want to learn more about meaningful work and how to cultivate it in your classroom? Download this guide on Meaningful Work (https://perts.net/elevate/meaningful-work) . The PERTS Elevate program helps educators foster more engaging and meaningful work for students.
Download our Meaningful Work Guide (https://perts.net/elevate/meaningful-work)
About Elevate
Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more (https://www.perts.net/elevate) . ​

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (http://perts.net/consultation) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=40b6a13e84)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f66b76caa6&c=40b6a13e84)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-01-12 11:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------
Are you ready to transform your classroom into a dynamic learning environment?

When students experience their work as meaningful and discover the personal relevance of what they're learning, they're more likely to...
* feel proud and energized by their work
* feel a sense of autonomy and ownership over their learning
* persist when they encounter challenges

When teachers not just internalize but take ownership of these principles and act on them, they can create positive and meaningful learning environments. Want to learn more about meaningful work and how to cultivate it in your classroom? Download this guide on Meaningful Work (https://perts.net/elevate/meaningful-work) . The PERTS Elevate program helps educators foster more engaging and meaningful work for students.
Download our Meaningful Work Guide (https://perts.net/elevate/meaningful-work)
About Elevate
Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more (https://www.perts.net/elevate) . ​

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (http://perts.net/consultation) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=40b6a13e84)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=b4edfd0dd8&c=40b6a13e84)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-01-12 11:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------
Are you ready to transform your classroom into a dynamic learning environment?

When students experience their work as meaningful and discover the personal relevance of what they're learning, they're more likely to...
* feel proud and energized by their work
* feel a sense of autonomy and ownership over their learning
* persist when they encounter challenges

When teachers not just internalize but take ownership of these principles and act on them, they can create positive and meaningful learning environments. Want to learn more about meaningful work and how to cultivate it in your classroom? Download this guide on Meaningful Work (https://perts.net/elevate/meaningful-work) . The PERTS Elevate program helps educators foster more engaging and meaningful work for students.
Download our Meaningful Work Guide (https://perts.net/elevate/meaningful-work)
About Elevate
Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more (https://www.perts.net/elevate) . ​

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (http://perts.net/consultation) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=40b6a13e84)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=36456eb76b&c=40b6a13e84)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-02-09 11:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------
One of the most important aspects of a student’s learning environment is a meaningful classroom community that fosters mutual support among classmates and where students feel safe to engage.

When students feel like they belong in their classroom and among groups of their peers, they are more likely to be fully engaged, feel motivated, and succeed academically. Research shows that students who feel like they’re a part of a meaningful classroom community are more likely to:
* Invest themselves deeply in the learning process
* Feel heard, seen, and valued
* Take risks, like volunteering an answer when they’re unsure if it’s correct

Teachers can take many small but impactful actions to encourage a sense of belonging for all students. Ready to learn more about meaningful classroom communities and the actions teachers can take to make it a reality? Download this guide on Classroom Community (https://perts.net/elevate/classroom-community) . The PERTS Elevate program helps educators foster more engaging and meaningful classroom communities for students.
Download our Classroom Community Guide (https://perts.net/elevate/classroom-community)
About Elevate
Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more (https://www.perts.net/elevate) . ​

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (http://perts.net/consultation) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=cca1ab629b)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f97dc5981b&c=cca1ab629b)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-02-09 11:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------
One of the most important aspects of a student’s learning environment is a meaningful classroom community that fosters mutual support among classmates and where students feel safe to engage.

When students feel like they belong in their classroom and among groups of their peers, they are more likely to be fully engaged, feel motivated, and succeed academically. Research shows that students who feel like they’re a part of a meaningful classroom community are more likely to:
* Invest themselves deeply in the learning process
* Feel heard, seen, and valued
* Take risks, like volunteering an answer when they’re unsure if it’s correct

Teachers can take many small but impactful actions to encourage a sense of belonging for all students. Ready to learn more about meaningful classroom communities and the actions teachers can take to make it a reality? Download this guide on Classroom Community (https://perts.net/elevate/classroom-community) . The PERTS Elevate program helps educators foster more engaging and meaningful classroom communities for students.
Download our Classroom Community Guide (https://perts.net/elevate/classroom-community)
About Elevate
Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more (https://www.perts.net/elevate) . ​

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (http://perts.net/consultation) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=cca1ab629b)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=da5cd98d77&c=cca1ab629b)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-02-09 11:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------
One of the most important aspects of a student’s learning environment is a meaningful classroom community that fosters mutual support among classmates and where students feel safe to engage.

When students feel like they belong in their classroom and among groups of their peers, they are more likely to be fully engaged, feel motivated, and succeed academically. Research shows that students who feel like they’re a part of a meaningful classroom community are more likely to:
* Invest themselves deeply in the learning process
* Feel heard, seen, and valued
* Take risks, like volunteering an answer when they’re unsure if it’s correct

Teachers can take many small but impactful actions to encourage a sense of belonging for all students. Ready to learn more about meaningful classroom communities and the actions teachers can take to make it a reality? Download this guide on Classroom Community (https://perts.net/elevate/classroom-community) . The PERTS Elevate program helps educators foster more engaging and meaningful classroom communities for students.
Download our Classroom Community Guide (https://perts.net/elevate/classroom-community)
About Elevate
Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more (https://www.perts.net/elevate) . ​

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (http://perts.net/consultation) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=cca1ab629b)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=36456eb76b&c=cca1ab629b)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-02-09 11:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------
One of the most important aspects of a student’s learning environment is a meaningful classroom community that fosters mutual support among classmates and where students feel safe to engage.

When students feel like they belong in their classroom and among groups of their peers, they are more likely to be fully engaged, feel motivated, and succeed academically. Research shows that students who feel like they’re a part of a meaningful classroom community are more likely to:
* Invest themselves deeply in the learning process
* Feel heard, seen, and valued
* Take risks, like volunteering an answer when they’re unsure if it’s correct

Teachers can take many small but impactful actions to encourage a sense of belonging for all students. Ready to learn more about meaningful classroom communities and the actions teachers can take to make it a reality? Download this guide on Classroom Community (https://perts.net/elevate/classroom-community) . The PERTS Elevate program helps educators foster more engaging and meaningful classroom communities for students.
Download our Classroom Community Guide (https://perts.net/elevate/classroom-community)
About Elevate
Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more (https://www.perts.net/elevate) . ​

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (http://perts.net/consultation) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=cca1ab629b)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=b4edfd0dd8&c=cca1ab629b)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-02-09 11:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------
One of the most important aspects of a student’s learning environment is a meaningful classroom community that fosters mutual support among classmates and where students feel safe to engage.

When students feel like they belong in their classroom and among groups of their peers, they are more likely to be fully engaged, feel motivated, and succeed academically. Research shows that students who feel like they’re a part of a meaningful classroom community are more likely to:
* Invest themselves deeply in the learning process
* Feel heard, seen, and valued
* Take risks, like volunteering an answer when they’re unsure if it’s correct

Teachers can take many small but impactful actions to encourage a sense of belonging for all students. Ready to learn more about meaningful classroom communities and the actions teachers can take to make it a reality? Download this guide on Classroom Community (https://perts.net/elevate/classroom-community) . The PERTS Elevate program helps educators foster more engaging and meaningful classroom communities for students.
Download our Classroom Community Guide (https://perts.net/elevate/classroom-community)
About Elevate
Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more (https://www.perts.net/elevate) . ​

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (http://perts.net/consultation) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=cca1ab629b)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=298ead533f&c=cca1ab629b)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-02-09 11:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------
One of the most important aspects of a student’s learning environment is a meaningful classroom community that fosters mutual support among classmates and where students feel safe to engage.

When students feel like they belong in their classroom and among groups of their peers, they are more likely to be fully engaged, feel motivated, and succeed academically. Research shows that students who feel like they’re a part of a meaningful classroom community are more likely to:
* Invest themselves deeply in the learning process
* Feel heard, seen, and valued
* Take risks, like volunteering an answer when they’re unsure if it’s correct

Teachers can take many small but impactful actions to encourage a sense of belonging for all students. Ready to learn more about meaningful classroom communities and the actions teachers can take to make it a reality? Download this guide on Classroom Community (https://perts.net/elevate/classroom-community) . The PERTS Elevate program helps educators foster more engaging and meaningful classroom communities for students.
Download our Classroom Community Guide (https://perts.net/elevate/classroom-community)
About Elevate
Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more (https://www.perts.net/elevate) . ​

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (http://perts.net/consultation) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=cca1ab629b)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f641712fb8&c=cca1ab629b)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-02-09 11:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------
One of the most important aspects of a student’s learning environment is a meaningful classroom community that fosters mutual support among classmates and where students feel safe to engage.

When students feel like they belong in their classroom and among groups of their peers, they are more likely to be fully engaged, feel motivated, and succeed academically. Research shows that students who feel like they’re a part of a meaningful classroom community are more likely to:
* Invest themselves deeply in the learning process
* Feel heard, seen, and valued
* Take risks, like volunteering an answer when they’re unsure if it’s correct

Teachers can take many small but impactful actions to encourage a sense of belonging for all students. Ready to learn more about meaningful classroom communities and the actions teachers can take to make it a reality? Download this guide on Classroom Community (https://perts.net/elevate/classroom-community) . The PERTS Elevate program helps educators foster more engaging and meaningful classroom communities for students.
Download our Classroom Community Guide (https://perts.net/elevate/classroom-community)
About Elevate
Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more (https://www.perts.net/elevate) . ​

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (http://perts.net/consultation) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=cca1ab629b)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f66b76caa6&c=cca1ab629b)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-02-09 11:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------
One of the most important aspects of a student’s learning environment is a meaningful classroom community that fosters mutual support among classmates and where students feel safe to engage.

When students feel like they belong in their classroom and among groups of their peers, they are more likely to be fully engaged, feel motivated, and succeed academically. Research shows that students who feel like they’re a part of a meaningful classroom community are more likely to:
* Invest themselves deeply in the learning process
* Feel heard, seen, and valued
* Take risks, like volunteering an answer when they’re unsure if it’s correct

Teachers can take many small but impactful actions to encourage a sense of belonging for all students. Ready to learn more about meaningful classroom communities and the actions teachers can take to make it a reality? Download this guide on Classroom Community (https://perts.net/elevate/classroom-community) . The PERTS Elevate program helps educators foster more engaging and meaningful classroom communities for students.
Download our Classroom Community Guide (https://perts.net/elevate/classroom-community)
About Elevate
Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more (https://www.perts.net/elevate) . ​

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, click here to pick a convenient time (http://perts.net/consultation) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=cca1ab629b)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=7b3f3876af&c=cca1ab629b)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-03-19 10:01 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

“We wanted, as a class, to listen to music when doing collaborative class work but [our teacher] said, ‘no, it distracts you’ and we said, ‘no, we just told you that it doesn’t! It really helps us focus!’ But they insist...so why [is our teacher] asking us all these questions in the first place?”

Student interviewed in research by Finefter-Rosenbluh et al. (2021)*

This student is describing an experience that happens all too often: well-intentioned educators ask students for feedback, by way of surveys, exit tickets, or focus groups, but the feedback goes unaddressed or dismissed. What if, instead, we viewed young people as experts in their own experiences and cultivated relationships that supported them to shape their learning environment so they could reach their full potential?

In PERTS’ new field guide (https://www.perts.net/data-to-impact-redirect?utm_source=acq&utm_medium=email&utm_id=fg.3) , “Partnering with Students,” PERTS is excited to offer a practical guide to partnering with students and using their input to drive meaningful improvements in their classroom environment. This guide offers concrete strategies and resources for successfully listening to students, like the following key approaches:

* Using surveys to objectively assess priorities and progress
* Supplementing surveys with honest conversations
* Showing students that educators are taking action

Download the Field Guide (https://www.perts.net/data-to-impact-redirect?utm_source=acq&utm_medium=email&utm_id=fg.3)

This resource will help educators partner with students to create a more engaged, successful classroom. Explore the field guide today and take the next step toward true student-teacher partnerships. This field guide is the third in the series, “From Data to Impact.” To download all three of the field guides, visit the series website (https://www.perts.net/data-to-impact-redirect?utm_source=acq&utm_medium=email&utm_id=fg.3) .


To schedule a short demo and discuss how PERTS can help you catalyze student engagement and achievement,select a convenient time (https://www.perts.net/demo) .


About PERTS

The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

LILIA DIAZ DE LEWIS
Director of Programs

* Finefter-Rosenbluh, I., Ryan, T., & Barnes, M. (2021). The impact of student perception surveys on teachers’ practice: Teacher resistance and struggle in student voice-based assessment initiatives of effective teaching. Teaching and Teacher Education, 106, 103436.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=26a61f1768)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=da5cd98d77&c=26a61f1768)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-03-19 10:01 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

“We wanted, as a class, to listen to music when doing collaborative class work but [our teacher] said, ‘no, it distracts you’ and we said, ‘no, we just told you that it doesn’t! It really helps us focus!’ But they insist...so why [is our teacher] asking us all these questions in the first place?”

Student interviewed in research by Finefter-Rosenbluh et al. (2021)*

This student is describing an experience that happens all too often: well-intentioned educators ask students for feedback, by way of surveys, exit tickets, or focus groups, but the feedback goes unaddressed or dismissed. What if, instead, we viewed young people as experts in their own experiences and cultivated relationships that supported them to shape their learning environment so they could reach their full potential?

In PERTS’ new field guide (https://www.perts.net/data-to-impact-redirect?utm_source=acq&utm_medium=email&utm_id=fg.3) , “Partnering with Students,” PERTS is excited to offer a practical guide to partnering with students and using their input to drive meaningful improvements in their classroom environment. This guide offers concrete strategies and resources for successfully listening to students, like the following key approaches:

* Using surveys to objectively assess priorities and progress
* Supplementing surveys with honest conversations
* Showing students that educators are taking action

Download the Field Guide (https://www.perts.net/data-to-impact-redirect?utm_source=acq&utm_medium=email&utm_id=fg.3)

This resource will help educators partner with students to create a more engaged, successful classroom. Explore the field guide today and take the next step toward true student-teacher partnerships. This field guide is the third in the series, “From Data to Impact.” To download all three of the field guides, visit the series website (https://www.perts.net/data-to-impact-redirect?utm_source=acq&utm_medium=email&utm_id=fg.3) .


To schedule a short demo and discuss how PERTS can help you catalyze student engagement and achievement,select a convenient time (https://www.perts.net/demo) .


About PERTS

The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

LILIA DIAZ DE LEWIS
Director of Programs

* Finefter-Rosenbluh, I., Ryan, T., & Barnes, M. (2021). The impact of student perception surveys on teachers’ practice: Teacher resistance and struggle in student voice-based assessment initiatives of effective teaching. Teaching and Teacher Education, 106, 103436.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=26a61f1768)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f97dc5981b&c=26a61f1768)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-03-19 10:01 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

“We wanted, as a class, to listen to music when doing collaborative class work but [our teacher] said, ‘no, it distracts you’ and we said, ‘no, we just told you that it doesn’t! It really helps us focus!’ But they insist...so why [is our teacher] asking us all these questions in the first place?”

Student interviewed in research by Finefter-Rosenbluh et al. (2021)*

This student is describing an experience that happens all too often: well-intentioned educators ask students for feedback, by way of surveys, exit tickets, or focus groups, but the feedback goes unaddressed or dismissed. What if, instead, we viewed young people as experts in their own experiences and cultivated relationships that supported them to shape their learning environment so they could reach their full potential?

In PERTS’ new field guide (https://www.perts.net/data-to-impact-redirect?utm_source=acq&utm_medium=email&utm_id=fg.3) , “Partnering with Students,” PERTS is excited to offer a practical guide to partnering with students and using their input to drive meaningful improvements in their classroom environment. This guide offers concrete strategies and resources for successfully listening to students, like the following key approaches:

* Using surveys to objectively assess priorities and progress
* Supplementing surveys with honest conversations
* Showing students that educators are taking action

Download the Field Guide (https://www.perts.net/data-to-impact-redirect?utm_source=acq&utm_medium=email&utm_id=fg.3)

This resource will help educators partner with students to create a more engaged, successful classroom. Explore the field guide today and take the next step toward true student-teacher partnerships. This field guide is the third in the series, “From Data to Impact.” To download all three of the field guides, visit the series website (https://www.perts.net/data-to-impact-redirect?utm_source=acq&utm_medium=email&utm_id=fg.3) .


To schedule a short demo and discuss how PERTS can help you catalyze student engagement and achievement,select a convenient time (https://www.perts.net/demo) .


About PERTS

The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

LILIA DIAZ DE LEWIS
Director of Programs

* Finefter-Rosenbluh, I., Ryan, T., & Barnes, M. (2021). The impact of student perception surveys on teachers’ practice: Teacher resistance and struggle in student voice-based assessment initiatives of effective teaching. Teaching and Teacher Education, 106, 103436.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=26a61f1768)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f641712fb8&c=26a61f1768)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-03-19 10:01 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

“We wanted, as a class, to listen to music when doing collaborative class work but [our teacher] said, ‘no, it distracts you’ and we said, ‘no, we just told you that it doesn’t! It really helps us focus!’ But they insist...so why [is our teacher] asking us all these questions in the first place?”

Student interviewed in research by Finefter-Rosenbluh et al. (2021)*

This student is describing an experience that happens all too often: well-intentioned educators ask students for feedback, by way of surveys, exit tickets, or focus groups, but the feedback goes unaddressed or dismissed. What if, instead, we viewed young people as experts in their own experiences and cultivated relationships that supported them to shape their learning environment so they could reach their full potential?

In PERTS’ new field guide (https://www.perts.net/data-to-impact-redirect?utm_source=acq&utm_medium=email&utm_id=fg.3) , “Partnering with Students,” PERTS is excited to offer a practical guide to partnering with students and using their input to drive meaningful improvements in their classroom environment. This guide offers concrete strategies and resources for successfully listening to students, like the following key approaches:

* Using surveys to objectively assess priorities and progress
* Supplementing surveys with honest conversations
* Showing students that educators are taking action

Download the Field Guide (https://www.perts.net/data-to-impact-redirect?utm_source=acq&utm_medium=email&utm_id=fg.3)

This resource will help educators partner with students to create a more engaged, successful classroom. Explore the field guide today and take the next step toward true student-teacher partnerships. This field guide is the third in the series, “From Data to Impact.” To download all three of the field guides, visit the series website (https://www.perts.net/data-to-impact-redirect?utm_source=acq&utm_medium=email&utm_id=fg.3) .


To schedule a short demo and discuss how PERTS can help you catalyze student engagement and achievement,select a convenient time (https://www.perts.net/demo) .


About PERTS

The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

LILIA DIAZ DE LEWIS
Director of Programs

* Finefter-Rosenbluh, I., Ryan, T., & Barnes, M. (2021). The impact of student perception surveys on teachers’ practice: Teacher resistance and struggle in student voice-based assessment initiatives of effective teaching. Teaching and Teacher Education, 106, 103436.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=26a61f1768)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=b4edfd0dd8&c=26a61f1768)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-03-19 10:01 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

“We wanted, as a class, to listen to music when doing collaborative class work but [our teacher] said, ‘no, it distracts you’ and we said, ‘no, we just told you that it doesn’t! It really helps us focus!’ But they insist...so why [is our teacher] asking us all these questions in the first place?”

Student interviewed in research by Finefter-Rosenbluh et al. (2021)*

This student is describing an experience that happens all too often: well-intentioned educators ask students for feedback, by way of surveys, exit tickets, or focus groups, but the feedback goes unaddressed or dismissed. What if, instead, we viewed young people as experts in their own experiences and cultivated relationships that supported them to shape their learning environment so they could reach their full potential?

In PERTS’ new field guide (https://www.perts.net/data-to-impact-redirect?utm_source=acq&utm_medium=email&utm_id=fg.3) , “Partnering with Students,” PERTS is excited to offer a practical guide to partnering with students and using their input to drive meaningful improvements in their classroom environment. This guide offers concrete strategies and resources for successfully listening to students, like the following key approaches:

* Using surveys to objectively assess priorities and progress
* Supplementing surveys with honest conversations
* Showing students that educators are taking action

Download the Field Guide (https://www.perts.net/data-to-impact-redirect?utm_source=acq&utm_medium=email&utm_id=fg.3)

This resource will help educators partner with students to create a more engaged, successful classroom. Explore the field guide today and take the next step toward true student-teacher partnerships. This field guide is the third in the series, “From Data to Impact.” To download all three of the field guides, visit the series website (https://www.perts.net/data-to-impact-redirect?utm_source=acq&utm_medium=email&utm_id=fg.3) .


To schedule a short demo and discuss how PERTS can help you catalyze student engagement and achievement,select a convenient time (https://www.perts.net/demo) .


About PERTS

The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

LILIA DIAZ DE LEWIS
Director of Programs

* Finefter-Rosenbluh, I., Ryan, T., & Barnes, M. (2021). The impact of student perception surveys on teachers’ practice: Teacher resistance and struggle in student voice-based assessment initiatives of effective teaching. Teaching and Teacher Education, 106, 103436.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=26a61f1768)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=298ead533f&c=26a61f1768)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-03-19 10:01 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

“We wanted, as a class, to listen to music when doing collaborative class work but [our teacher] said, ‘no, it distracts you’ and we said, ‘no, we just told you that it doesn’t! It really helps us focus!’ But they insist...so why [is our teacher] asking us all these questions in the first place?”

Student interviewed in research by Finefter-Rosenbluh et al. (2021)*

This student is describing an experience that happens all too often: well-intentioned educators ask students for feedback, by way of surveys, exit tickets, or focus groups, but the feedback goes unaddressed or dismissed. What if, instead, we viewed young people as experts in their own experiences and cultivated relationships that supported them to shape their learning environment so they could reach their full potential?

In PERTS’ new field guide (https://www.perts.net/data-to-impact-redirect?utm_source=acq&utm_medium=email&utm_id=fg.3) , “Partnering with Students,” PERTS is excited to offer a practical guide to partnering with students and using their input to drive meaningful improvements in their classroom environment. This guide offers concrete strategies and resources for successfully listening to students, like the following key approaches:

* Using surveys to objectively assess priorities and progress
* Supplementing surveys with honest conversations
* Showing students that educators are taking action

Download the Field Guide (https://www.perts.net/data-to-impact-redirect?utm_source=acq&utm_medium=email&utm_id=fg.3)

This resource will help educators partner with students to create a more engaged, successful classroom. Explore the field guide today and take the next step toward true student-teacher partnerships. This field guide is the third in the series, “From Data to Impact.” To download all three of the field guides, visit the series website (https://www.perts.net/data-to-impact-redirect?utm_source=acq&utm_medium=email&utm_id=fg.3) .


To schedule a short demo and discuss how PERTS can help you catalyze student engagement and achievement,select a convenient time (https://www.perts.net/demo) .


About PERTS

The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

LILIA DIAZ DE LEWIS
Director of Programs

* Finefter-Rosenbluh, I., Ryan, T., & Barnes, M. (2021). The impact of student perception surveys on teachers’ practice: Teacher resistance and struggle in student voice-based assessment initiatives of effective teaching. Teaching and Teacher Education, 106, 103436.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=26a61f1768)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=7b3f3876af&c=26a61f1768)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-03-19 10:01 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

“We wanted, as a class, to listen to music when doing collaborative class work but [our teacher] said, ‘no, it distracts you’ and we said, ‘no, we just told you that it doesn’t! It really helps us focus!’ But they insist...so why [is our teacher] asking us all these questions in the first place?”

Student interviewed in research by Finefter-Rosenbluh et al. (2021)*

This student is describing an experience that happens all too often: well-intentioned educators ask students for feedback, by way of surveys, exit tickets, or focus groups, but the feedback goes unaddressed or dismissed. What if, instead, we viewed young people as experts in their own experiences and cultivated relationships that supported them to shape their learning environment so they could reach their full potential?

In PERTS’ new field guide (https://www.perts.net/data-to-impact-redirect?utm_source=acq&utm_medium=email&utm_id=fg.3) , “Partnering with Students,” PERTS is excited to offer a practical guide to partnering with students and using their input to drive meaningful improvements in their classroom environment. This guide offers concrete strategies and resources for successfully listening to students, like the following key approaches:

* Using surveys to objectively assess priorities and progress
* Supplementing surveys with honest conversations
* Showing students that educators are taking action

Download the Field Guide (https://www.perts.net/data-to-impact-redirect?utm_source=acq&utm_medium=email&utm_id=fg.3)

This resource will help educators partner with students to create a more engaged, successful classroom. Explore the field guide today and take the next step toward true student-teacher partnerships. This field guide is the third in the series, “From Data to Impact.” To download all three of the field guides, visit the series website (https://www.perts.net/data-to-impact-redirect?utm_source=acq&utm_medium=email&utm_id=fg.3) .


To schedule a short demo and discuss how PERTS can help you catalyze student engagement and achievement,select a convenient time (https://www.perts.net/demo) .


About PERTS

The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

LILIA DIAZ DE LEWIS
Director of Programs

* Finefter-Rosenbluh, I., Ryan, T., & Barnes, M. (2021). The impact of student perception surveys on teachers’ practice: Teacher resistance and struggle in student voice-based assessment initiatives of effective teaching. Teaching and Teacher Education, 106, 103436.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=26a61f1768)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f66b76caa6&c=26a61f1768)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-06 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

​In higher education, one of the most critical factors influencing a student's academic journey is self-efficacy, the belief in their own ability to succeed in specific situations or accomplish tasks.

When students possess a strong sense of self-efficacy, they are more likely to approach challenges confidently, exhibit resilience, and achieve higher levels of academic success. Research shows that students with a strong sense of self-efficacy are more inclined to:​
* Engage deeply with learning materials and classroom activities
* View failures as opportunities for growth
* Set and pursue ambitious academic goals

Ready to explore strategies for cultivating self-efficacy with your students? Browse the self-efficacy practice library (https://accelerateequity.org/practices-category/self-efficacy-practices/) that showcases practices instructors can use to improve students' self-efficacy in college-level courses. The practice library, designed by the Equity Accelerator (https://accelerateequity.org/) , can be used with PERTS' Ascend program to measure the impact of new practices on students' self-efficacy.
View the Self-Efficacy Practice Library (https://accelerateequity.org/practices-category/self-efficacy-practices/)

About Ascend

Ascend is a data-driven professional learning program that enables college instructors and administrators to learn how their students are experiencing courses and what they can do to make those experiences more equitable, more engaging, and more supportive of student success. Learn more. (https://www.perts.net/ascend)

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, select a convenient time (http://perts.net/consultation) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=af09cc0822)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=36456eb76b&c=af09cc0822)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-06 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

​In higher education, one of the most critical factors influencing a student's academic journey is self-efficacy, the belief in their own ability to succeed in specific situations or accomplish tasks.

When students possess a strong sense of self-efficacy, they are more likely to approach challenges confidently, exhibit resilience, and achieve higher levels of academic success. Research shows that students with a strong sense of self-efficacy are more inclined to:​
* Engage deeply with learning materials and classroom activities
* View failures as opportunities for growth
* Set and pursue ambitious academic goals

Ready to explore strategies for cultivating self-efficacy with your students? Browse the self-efficacy practice library (https://accelerateequity.org/practices-category/self-efficacy-practices/) that showcases practices instructors can use to improve students' self-efficacy in college-level courses. The practice library, designed by the Equity Accelerator (https://accelerateequity.org/) , can be used with PERTS' Ascend program to measure the impact of new practices on students' self-efficacy.
View the Self-Efficacy Practice Library (https://accelerateequity.org/practices-category/self-efficacy-practices/)

About Ascend

Ascend is a data-driven professional learning program that enables college instructors and administrators to learn how their students are experiencing courses and what they can do to make those experiences more equitable, more engaging, and more supportive of student success. Learn more. (https://www.perts.net/ascend)

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, select a convenient time (http://perts.net/consultation) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=af09cc0822)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=298ead533f&c=af09cc0822)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-06 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

​In higher education, one of the most critical factors influencing a student's academic journey is self-efficacy, the belief in their own ability to succeed in specific situations or accomplish tasks.

When students possess a strong sense of self-efficacy, they are more likely to approach challenges confidently, exhibit resilience, and achieve higher levels of academic success. Research shows that students with a strong sense of self-efficacy are more inclined to:​
* Engage deeply with learning materials and classroom activities
* View failures as opportunities for growth
* Set and pursue ambitious academic goals

Ready to explore strategies for cultivating self-efficacy with your students? Browse the self-efficacy practice library (https://accelerateequity.org/practices-category/self-efficacy-practices/) that showcases practices instructors can use to improve students' self-efficacy in college-level courses. The practice library, designed by the Equity Accelerator (https://accelerateequity.org/) , can be used with PERTS' Ascend program to measure the impact of new practices on students' self-efficacy.
View the Self-Efficacy Practice Library (https://accelerateequity.org/practices-category/self-efficacy-practices/)

About Ascend

Ascend is a data-driven professional learning program that enables college instructors and administrators to learn how their students are experiencing courses and what they can do to make those experiences more equitable, more engaging, and more supportive of student success. Learn more. (https://www.perts.net/ascend)

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, select a convenient time (http://perts.net/consultation) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=af09cc0822)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=b4edfd0dd8&c=af09cc0822)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-06 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

​In higher education, one of the most critical factors influencing a student's academic journey is self-efficacy, the belief in their own ability to succeed in specific situations or accomplish tasks.

When students possess a strong sense of self-efficacy, they are more likely to approach challenges confidently, exhibit resilience, and achieve higher levels of academic success. Research shows that students with a strong sense of self-efficacy are more inclined to:​
* Engage deeply with learning materials and classroom activities
* View failures as opportunities for growth
* Set and pursue ambitious academic goals

Ready to explore strategies for cultivating self-efficacy with your students? Browse the self-efficacy practice library (https://accelerateequity.org/practices-category/self-efficacy-practices/) that showcases practices instructors can use to improve students' self-efficacy in college-level courses. The practice library, designed by the Equity Accelerator (https://accelerateequity.org/) , can be used with PERTS' Ascend program to measure the impact of new practices on students' self-efficacy.
View the Self-Efficacy Practice Library (https://accelerateequity.org/practices-category/self-efficacy-practices/)

About Ascend

Ascend is a data-driven professional learning program that enables college instructors and administrators to learn how their students are experiencing courses and what they can do to make those experiences more equitable, more engaging, and more supportive of student success. Learn more. (https://www.perts.net/ascend)

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, select a convenient time (http://perts.net/consultation) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=af09cc0822)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f97dc5981b&c=af09cc0822)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-06 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

​In higher education, one of the most critical factors influencing a student's academic journey is self-efficacy, the belief in their own ability to succeed in specific situations or accomplish tasks.

When students possess a strong sense of self-efficacy, they are more likely to approach challenges confidently, exhibit resilience, and achieve higher levels of academic success. Research shows that students with a strong sense of self-efficacy are more inclined to:​
* Engage deeply with learning materials and classroom activities
* View failures as opportunities for growth
* Set and pursue ambitious academic goals

Ready to explore strategies for cultivating self-efficacy with your students? Browse the self-efficacy practice library (https://accelerateequity.org/practices-category/self-efficacy-practices/) that showcases practices instructors can use to improve students' self-efficacy in college-level courses. The practice library, designed by the Equity Accelerator (https://accelerateequity.org/) , can be used with PERTS' Ascend program to measure the impact of new practices on students' self-efficacy.
View the Self-Efficacy Practice Library (https://accelerateequity.org/practices-category/self-efficacy-practices/)

About Ascend

Ascend is a data-driven professional learning program that enables college instructors and administrators to learn how their students are experiencing courses and what they can do to make those experiences more equitable, more engaging, and more supportive of student success. Learn more. (https://www.perts.net/ascend)

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, select a convenient time (http://perts.net/consultation) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=af09cc0822)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=7b3f3876af&c=af09cc0822)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-06 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

​In higher education, one of the most critical factors influencing a student's academic journey is self-efficacy, the belief in their own ability to succeed in specific situations or accomplish tasks.

When students possess a strong sense of self-efficacy, they are more likely to approach challenges confidently, exhibit resilience, and achieve higher levels of academic success. Research shows that students with a strong sense of self-efficacy are more inclined to:​
* Engage deeply with learning materials and classroom activities
* View failures as opportunities for growth
* Set and pursue ambitious academic goals

Ready to explore strategies for cultivating self-efficacy with your students? Browse the self-efficacy practice library (https://accelerateequity.org/practices-category/self-efficacy-practices/) that showcases practices instructors can use to improve students' self-efficacy in college-level courses. The practice library, designed by the Equity Accelerator (https://accelerateequity.org/) , can be used with PERTS' Ascend program to measure the impact of new practices on students' self-efficacy.
View the Self-Efficacy Practice Library (https://accelerateequity.org/practices-category/self-efficacy-practices/)

About Ascend

Ascend is a data-driven professional learning program that enables college instructors and administrators to learn how their students are experiencing courses and what they can do to make those experiences more equitable, more engaging, and more supportive of student success. Learn more. (https://www.perts.net/ascend)

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, select a convenient time (http://perts.net/consultation) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=af09cc0822)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f641712fb8&c=af09cc0822)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-06 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

​In higher education, one of the most critical factors influencing a student's academic journey is self-efficacy, the belief in their own ability to succeed in specific situations or accomplish tasks.

When students possess a strong sense of self-efficacy, they are more likely to approach challenges confidently, exhibit resilience, and achieve higher levels of academic success. Research shows that students with a strong sense of self-efficacy are more inclined to:​
* Engage deeply with learning materials and classroom activities
* View failures as opportunities for growth
* Set and pursue ambitious academic goals

Ready to explore strategies for cultivating self-efficacy with your students? Browse the self-efficacy practice library (https://accelerateequity.org/practices-category/self-efficacy-practices/) that showcases practices instructors can use to improve students' self-efficacy in college-level courses. The practice library, designed by the Equity Accelerator (https://accelerateequity.org/) , can be used with PERTS' Ascend program to measure the impact of new practices on students' self-efficacy.
View the Self-Efficacy Practice Library (https://accelerateequity.org/practices-category/self-efficacy-practices/)

About Ascend

Ascend is a data-driven professional learning program that enables college instructors and administrators to learn how their students are experiencing courses and what they can do to make those experiences more equitable, more engaging, and more supportive of student success. Learn more. (https://www.perts.net/ascend)

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, select a convenient time (http://perts.net/consultation) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=af09cc0822)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f66b76caa6&c=af09cc0822)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-06 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

​In higher education, one of the most critical factors influencing a student's academic journey is self-efficacy, the belief in their own ability to succeed in specific situations or accomplish tasks.

When students possess a strong sense of self-efficacy, they are more likely to approach challenges confidently, exhibit resilience, and achieve higher levels of academic success. Research shows that students with a strong sense of self-efficacy are more inclined to:​
* Engage deeply with learning materials and classroom activities
* View failures as opportunities for growth
* Set and pursue ambitious academic goals

Ready to explore strategies for cultivating self-efficacy with your students? Browse the self-efficacy practice library (https://accelerateequity.org/practices-category/self-efficacy-practices/) that showcases practices instructors can use to improve students' self-efficacy in college-level courses. The practice library, designed by the Equity Accelerator (https://accelerateequity.org/) , can be used with PERTS' Ascend program to measure the impact of new practices on students' self-efficacy.
View the Self-Efficacy Practice Library (https://accelerateequity.org/practices-category/self-efficacy-practices/)

About Ascend

Ascend is a data-driven professional learning program that enables college instructors and administrators to learn how their students are experiencing courses and what they can do to make those experiences more equitable, more engaging, and more supportive of student success. Learn more. (https://www.perts.net/ascend)

To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, select a convenient time (http://perts.net/consultation) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=af09cc0822)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=da5cd98d77&c=af09cc0822)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-09 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

We’re excited to invite you to our upcoming Spring Webinar, "From the District to the Classroom: How Student Voice Drives School Culture," featuring educators from Chicago Public Schools (CPS).
* Date: Wednesday, April 30, 2025
* Time: 5-6p ET | 4-5p CT | 2-3p PT
* Register: perts.net/events-webinar-sp25

Research shows that when students feel heard and empowered, they are more motivated and academically driven. But what does it take to build a culture where student voice truly matters? This webinar (http://perts.net/events-webinar-sp25) brings together three levels of educators from Chicago Public Schools (CPS) Network 15—district, school, and classroom—who have successfully embedded student voice into their practices, sharing strategies and real-world examples of its impact.
Featured Speakers

This panel is designed for school and district administrators, educators, and education leaders who want to implement practical strategies for amplifying student voice in their schools.

Please join us!
Register Today! (http://perts.net/events-webinar-sp25)
About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

PERTS TEAM


============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=81f653d34c)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=7b3f3876af&c=81f653d34c)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-09 10:06 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

We’re excited to invite you to our upcoming Spring Webinar, "From the District to the Classroom: How Student Voice Drives School Culture," featuring educators from Chicago Public Schools (CPS).
* Date: Wednesday, April 30, 2025
* Time: 5-6p ET | 4-5p CT | 2-3p PT
* Register: perts.net/events-webinar-sp25

Research shows that when students feel heard and empowered, they are more motivated and academically driven. But what does it take to build a culture where student voice truly matters? This webinar (http://perts.net/events-webinar-sp25) brings together three levels of educators from Chicago Public Schools (CPS) Network 15—district, school, and classroom—who have successfully embedded student voice into their practices, sharing strategies and real-world examples of its impact.
Featured Speakers

This panel is designed for school and district administrators, educators, and education leaders who want to implement practical strategies for amplifying student voice in their schools.

Please join us!
Register Today! (http://perts.net/events-webinar-sp25)
About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

PERTS TEAM


============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=81f653d34c)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=36456eb76b&c=81f653d34c)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-09 10:06 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

We’re excited to invite you to our upcoming Spring Webinar, "From the District to the Classroom: How Student Voice Drives School Culture," featuring educators from Chicago Public Schools (CPS).
* Date: Wednesday, April 30, 2025
* Time: 5-6p ET | 4-5p CT | 2-3p PT
* Register: perts.net/events-webinar-sp25

Research shows that when students feel heard and empowered, they are more motivated and academically driven. But what does it take to build a culture where student voice truly matters? This webinar (http://perts.net/events-webinar-sp25) brings together three levels of educators from Chicago Public Schools (CPS) Network 15—district, school, and classroom—who have successfully embedded student voice into their practices, sharing strategies and real-world examples of its impact.
Featured Speakers

This panel is designed for school and district administrators, educators, and education leaders who want to implement practical strategies for amplifying student voice in their schools.

Please join us!
Register Today! (http://perts.net/events-webinar-sp25)
About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

PERTS TEAM


============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=81f653d34c)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=b4edfd0dd8&c=81f653d34c)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-09 10:07 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

We’re excited to invite you to our upcoming Spring Webinar, "From the District to the Classroom: How Student Voice Drives School Culture," featuring educators from Chicago Public Schools (CPS).
* Date: Wednesday, April 30, 2025
* Time: 5-6p ET | 4-5p CT | 2-3p PT
* Register: perts.net/events-webinar-sp25

Research shows that when students feel heard and empowered, they are more motivated and academically driven. But what does it take to build a culture where student voice truly matters? This webinar (http://perts.net/events-webinar-sp25) brings together three levels of educators from Chicago Public Schools (CPS) Network 15—district, school, and classroom—who have successfully embedded student voice into their practices, sharing strategies and real-world examples of its impact.
Featured Speakers

This panel is designed for school and district administrators, educators, and education leaders who want to implement practical strategies for amplifying student voice in their schools.

Please join us!
Register Today! (http://perts.net/events-webinar-sp25)
About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

PERTS TEAM


============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=81f653d34c)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f641712fb8&c=81f653d34c)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-09 10:07 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

We’re excited to invite you to our upcoming Spring Webinar, "From the District to the Classroom: How Student Voice Drives School Culture," featuring educators from Chicago Public Schools (CPS).
* Date: Wednesday, April 30, 2025
* Time: 5-6p ET | 4-5p CT | 2-3p PT
* Register: perts.net/events-webinar-sp25

Research shows that when students feel heard and empowered, they are more motivated and academically driven. But what does it take to build a culture where student voice truly matters? This webinar (http://perts.net/events-webinar-sp25) brings together three levels of educators from Chicago Public Schools (CPS) Network 15—district, school, and classroom—who have successfully embedded student voice into their practices, sharing strategies and real-world examples of its impact.
Featured Speakers

This panel is designed for school and district administrators, educators, and education leaders who want to implement practical strategies for amplifying student voice in their schools.

Please join us!
Register Today! (http://perts.net/events-webinar-sp25)
About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

PERTS TEAM


============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=81f653d34c)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f66b76caa6&c=81f653d34c)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-23 10:00 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

Our Spring Webinar, "From the District to the Classroom: How Student Voice Drives School Culture," is just one week away, and we’d love for you to be there.
* Date: Wednesday, April 30, 2025
* Time: 5-6p ET | 4-5p CT | 2-3p PT
* Register: perts.net/events-webinar-sp25

Join the PERTS team and educators from Chicago Public Schools (CPS) Network 15 as they share how they’ve integrated student voice across the district, school, and classroom levels, with measurable results. Whether you’re already elevating student voice or just beginning to explore this work, you’ll gain practical, evidence-based strategies you can bring to your school.
Featured Speakers

This webinar (https://www.perts.net/events-webinar-sp25) is ideal for district administrators, educators, and education leaders interested in creating a school culture where students feel heard, valued, and empowered.

Don’t miss out; register today!
Register Today! (http://perts.net/events-webinar-sp25)
About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

PERTS TEAM


============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=2e7e341070)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f66b76caa6&c=2e7e341070)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-23 10:00 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

Our Spring Webinar, "From the District to the Classroom: How Student Voice Drives School Culture," is just one week away, and we’d love for you to be there.
* Date: Wednesday, April 30, 2025
* Time: 5-6p ET | 4-5p CT | 2-3p PT
* Register: perts.net/events-webinar-sp25

Join the PERTS team and educators from Chicago Public Schools (CPS) Network 15 as they share how they’ve integrated student voice across the district, school, and classroom levels, with measurable results. Whether you’re already elevating student voice or just beginning to explore this work, you’ll gain practical, evidence-based strategies you can bring to your school.
Featured Speakers

This webinar (https://www.perts.net/events-webinar-sp25) is ideal for district administrators, educators, and education leaders interested in creating a school culture where students feel heard, valued, and empowered.

Don’t miss out; register today!
Register Today! (http://perts.net/events-webinar-sp25)
About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

PERTS TEAM


============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=2e7e341070)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=7b3f3876af&c=2e7e341070)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-23 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

Our Spring Webinar, "From the District to the Classroom: How Student Voice Drives School Culture," is just one week away, and we’d love for you to be there.
* Date: Wednesday, April 30, 2025
* Time: 5-6p ET | 4-5p CT | 2-3p PT
* Register: perts.net/events-webinar-sp25

Join the PERTS team and educators from Chicago Public Schools (CPS) Network 15 as they share how they’ve integrated student voice across the district, school, and classroom levels, with measurable results. Whether you’re already elevating student voice or just beginning to explore this work, you’ll gain practical, evidence-based strategies you can bring to your school.
Featured Speakers

This webinar (https://www.perts.net/events-webinar-sp25) is ideal for district administrators, educators, and education leaders interested in creating a school culture where students feel heard, valued, and empowered.

Don’t miss out; register today!
Register Today! (http://perts.net/events-webinar-sp25)
About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

PERTS TEAM


============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=2e7e341070)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f97dc5981b&c=2e7e341070)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-23 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

Our Spring Webinar, "From the District to the Classroom: How Student Voice Drives School Culture," is just one week away, and we’d love for you to be there.
* Date: Wednesday, April 30, 2025
* Time: 5-6p ET | 4-5p CT | 2-3p PT
* Register: perts.net/events-webinar-sp25

Join the PERTS team and educators from Chicago Public Schools (CPS) Network 15 as they share how they’ve integrated student voice across the district, school, and classroom levels, with measurable results. Whether you’re already elevating student voice or just beginning to explore this work, you’ll gain practical, evidence-based strategies you can bring to your school.
Featured Speakers

This webinar (https://www.perts.net/events-webinar-sp25) is ideal for district administrators, educators, and education leaders interested in creating a school culture where students feel heard, valued, and empowered.

Don’t miss out; register today!
Register Today! (http://perts.net/events-webinar-sp25)
About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

PERTS TEAM


============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=2e7e341070)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=298ead533f&c=2e7e341070)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-23 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

Our Spring Webinar, "From the District to the Classroom: How Student Voice Drives School Culture," is just one week away, and we’d love for you to be there.
* Date: Wednesday, April 30, 2025
* Time: 5-6p ET | 4-5p CT | 2-3p PT
* Register: perts.net/events-webinar-sp25

Join the PERTS team and educators from Chicago Public Schools (CPS) Network 15 as they share how they’ve integrated student voice across the district, school, and classroom levels, with measurable results. Whether you’re already elevating student voice or just beginning to explore this work, you’ll gain practical, evidence-based strategies you can bring to your school.
Featured Speakers

This webinar (https://www.perts.net/events-webinar-sp25) is ideal for district administrators, educators, and education leaders interested in creating a school culture where students feel heard, valued, and empowered.

Don’t miss out; register today!
Register Today! (http://perts.net/events-webinar-sp25)
About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

PERTS TEAM


============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=2e7e341070)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f641712fb8&c=2e7e341070)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-23 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

Our Spring Webinar, "From the District to the Classroom: How Student Voice Drives School Culture," is just one week away, and we’d love for you to be there.
* Date: Wednesday, April 30, 2025
* Time: 5-6p ET | 4-5p CT | 2-3p PT
* Register: perts.net/events-webinar-sp25

Join the PERTS team and educators from Chicago Public Schools (CPS) Network 15 as they share how they’ve integrated student voice across the district, school, and classroom levels, with measurable results. Whether you’re already elevating student voice or just beginning to explore this work, you’ll gain practical, evidence-based strategies you can bring to your school.
Featured Speakers

This webinar (https://www.perts.net/events-webinar-sp25) is ideal for district administrators, educators, and education leaders interested in creating a school culture where students feel heard, valued, and empowered.

Don’t miss out; register today!
Register Today! (http://perts.net/events-webinar-sp25)
About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

PERTS TEAM


============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=2e7e341070)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=da5cd98d77&c=2e7e341070)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-23 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

Our Spring Webinar, "From the District to the Classroom: How Student Voice Drives School Culture," is just one week away, and we’d love for you to be there.
* Date: Wednesday, April 30, 2025
* Time: 5-6p ET | 4-5p CT | 2-3p PT
* Register: perts.net/events-webinar-sp25

Join the PERTS team and educators from Chicago Public Schools (CPS) Network 15 as they share how they’ve integrated student voice across the district, school, and classroom levels, with measurable results. Whether you’re already elevating student voice or just beginning to explore this work, you’ll gain practical, evidence-based strategies you can bring to your school.
Featured Speakers

This webinar (https://www.perts.net/events-webinar-sp25) is ideal for district administrators, educators, and education leaders interested in creating a school culture where students feel heard, valued, and empowered.

Don’t miss out; register today!
Register Today! (http://perts.net/events-webinar-sp25)
About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

PERTS TEAM


============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=2e7e341070)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=b4edfd0dd8&c=2e7e341070)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-23 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

Our Spring Webinar, "From the District to the Classroom: How Student Voice Drives School Culture," is just one week away, and we’d love for you to be there.
* Date: Wednesday, April 30, 2025
* Time: 5-6p ET | 4-5p CT | 2-3p PT
* Register: perts.net/events-webinar-sp25

Join the PERTS team and educators from Chicago Public Schools (CPS) Network 15 as they share how they’ve integrated student voice across the district, school, and classroom levels, with measurable results. Whether you’re already elevating student voice or just beginning to explore this work, you’ll gain practical, evidence-based strategies you can bring to your school.
Featured Speakers

This webinar (https://www.perts.net/events-webinar-sp25) is ideal for district administrators, educators, and education leaders interested in creating a school culture where students feel heard, valued, and empowered.

Don’t miss out; register today!
Register Today! (http://perts.net/events-webinar-sp25)
About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

PERTS TEAM


============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=2e7e341070)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=36456eb76b&c=2e7e341070)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-28 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

Just a quick reminder that our Spring Webinar, "From the District to the Classroom: How Student Voice Drives School Culture," is happening this Wednesday, we don't want you to miss it!
* Date: Wednesday, April 30, 2025
* Time: 5-6p ET | 4-5p CT | 2-3p PT
* Register: perts.net/events-webinar-sp25

In "From the District to the Classroom: How Student Voice Drives School Culture (https://www.perts.net/events-webinar-sp25) ," you’ll hear from a dynamic panel of educators from Chicago Public Schools (CPS) Network 15, who are embedding student voice in their practices at the district, school, and classroom levels.

Come ready to be inspired by:
* Real-world examples of the impact of student voice work
* Lessons learned across the district, school, and classroom levels
* Tangible implementation strategies you can implement right away

Featured Speakers

If you haven’t registered yet, there’s still time:
Register Today! (http://perts.net/events-webinar-sp25)
About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

PERTS TEAM


============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=c04c0caa46)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=36456eb76b&c=c04c0caa46)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-28 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

Just a quick reminder that our Spring Webinar, "From the District to the Classroom: How Student Voice Drives School Culture," is happening this Wednesday, we don't want you to miss it!
* Date: Wednesday, April 30, 2025
* Time: 5-6p ET | 4-5p CT | 2-3p PT
* Register: perts.net/events-webinar-sp25

In "From the District to the Classroom: How Student Voice Drives School Culture (https://www.perts.net/events-webinar-sp25) ," you’ll hear from a dynamic panel of educators from Chicago Public Schools (CPS) Network 15, who are embedding student voice in their practices at the district, school, and classroom levels.

Come ready to be inspired by:
* Real-world examples of the impact of student voice work
* Lessons learned across the district, school, and classroom levels
* Tangible implementation strategies you can implement right away

Featured Speakers

If you haven’t registered yet, there’s still time:
Register Today! (http://perts.net/events-webinar-sp25)
About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

PERTS TEAM


============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=c04c0caa46)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f97dc5981b&c=c04c0caa46)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-28 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

Just a quick reminder that our Spring Webinar, "From the District to the Classroom: How Student Voice Drives School Culture," is happening this Wednesday, we don't want you to miss it!
* Date: Wednesday, April 30, 2025
* Time: 5-6p ET | 4-5p CT | 2-3p PT
* Register: perts.net/events-webinar-sp25

In "From the District to the Classroom: How Student Voice Drives School Culture (https://www.perts.net/events-webinar-sp25) ," you’ll hear from a dynamic panel of educators from Chicago Public Schools (CPS) Network 15, who are embedding student voice in their practices at the district, school, and classroom levels.

Come ready to be inspired by:
* Real-world examples of the impact of student voice work
* Lessons learned across the district, school, and classroom levels
* Tangible implementation strategies you can implement right away

Featured Speakers

If you haven’t registered yet, there’s still time:
Register Today! (http://perts.net/events-webinar-sp25)
About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

PERTS TEAM


============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=c04c0caa46)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=b4edfd0dd8&c=c04c0caa46)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-28 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

Just a quick reminder that our Spring Webinar, "From the District to the Classroom: How Student Voice Drives School Culture," is happening this Wednesday, we don't want you to miss it!
* Date: Wednesday, April 30, 2025
* Time: 5-6p ET | 4-5p CT | 2-3p PT
* Register: perts.net/events-webinar-sp25

In "From the District to the Classroom: How Student Voice Drives School Culture (https://www.perts.net/events-webinar-sp25) ," you’ll hear from a dynamic panel of educators from Chicago Public Schools (CPS) Network 15, who are embedding student voice in their practices at the district, school, and classroom levels.

Come ready to be inspired by:
* Real-world examples of the impact of student voice work
* Lessons learned across the district, school, and classroom levels
* Tangible implementation strategies you can implement right away

Featured Speakers

If you haven’t registered yet, there’s still time:
Register Today! (http://perts.net/events-webinar-sp25)
About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

PERTS TEAM


============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=c04c0caa46)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f66b76caa6&c=c04c0caa46)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-28 10:02 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

Just a quick reminder that our Spring Webinar, "From the District to the Classroom: How Student Voice Drives School Culture," is happening this Wednesday, we don't want you to miss it!
* Date: Wednesday, April 30, 2025
* Time: 5-6p ET | 4-5p CT | 2-3p PT
* Register: perts.net/events-webinar-sp25

In "From the District to the Classroom: How Student Voice Drives School Culture (https://www.perts.net/events-webinar-sp25) ," you’ll hear from a dynamic panel of educators from Chicago Public Schools (CPS) Network 15, who are embedding student voice in their practices at the district, school, and classroom levels.

Come ready to be inspired by:
* Real-world examples of the impact of student voice work
* Lessons learned across the district, school, and classroom levels
* Tangible implementation strategies you can implement right away

Featured Speakers

If you haven’t registered yet, there’s still time:
Register Today! (http://perts.net/events-webinar-sp25)
About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

PERTS TEAM


============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=c04c0caa46)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=da5cd98d77&c=c04c0caa46)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-28 10:02 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

Just a quick reminder that our Spring Webinar, "From the District to the Classroom: How Student Voice Drives School Culture," is happening this Wednesday, we don't want you to miss it!
* Date: Wednesday, April 30, 2025
* Time: 5-6p ET | 4-5p CT | 2-3p PT
* Register: perts.net/events-webinar-sp25

In "From the District to the Classroom: How Student Voice Drives School Culture (https://www.perts.net/events-webinar-sp25) ," you’ll hear from a dynamic panel of educators from Chicago Public Schools (CPS) Network 15, who are embedding student voice in their practices at the district, school, and classroom levels.

Come ready to be inspired by:
* Real-world examples of the impact of student voice work
* Lessons learned across the district, school, and classroom levels
* Tangible implementation strategies you can implement right away

Featured Speakers

If you haven’t registered yet, there’s still time:
Register Today! (http://perts.net/events-webinar-sp25)
About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

PERTS TEAM


============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=c04c0caa46)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=7b3f3876af&c=c04c0caa46)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-04-28 10:02 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

Just a quick reminder that our Spring Webinar, "From the District to the Classroom: How Student Voice Drives School Culture," is happening this Wednesday, we don't want you to miss it!
* Date: Wednesday, April 30, 2025
* Time: 5-6p ET | 4-5p CT | 2-3p PT
* Register: perts.net/events-webinar-sp25

In "From the District to the Classroom: How Student Voice Drives School Culture (https://www.perts.net/events-webinar-sp25) ," you’ll hear from a dynamic panel of educators from Chicago Public Schools (CPS) Network 15, who are embedding student voice in their practices at the district, school, and classroom levels.

Come ready to be inspired by:
* Real-world examples of the impact of student voice work
* Lessons learned across the district, school, and classroom levels
* Tangible implementation strategies you can implement right away

Featured Speakers

If you haven’t registered yet, there’s still time:
Register Today! (http://perts.net/events-webinar-sp25)
About PERTS
The Project for Education Research that Scales (PERTS (https://www.perts.net/) ) is a nonprofit research and development institute that translates insights from psychological science into cutting-edge tools, measures, and recommendations that educators anywhere can use to foster healthy and equitable academic engagement and success.

In partnership,

PERTS TEAM


============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=c04c0caa46)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f641712fb8&c=c04c0caa46)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-05-07 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

With the end of the school year in sight, it's natural to reflect on what worked well and start planning for adjustments in the fall, which means it's the perfect time to think about classroom organization. Most of us have heard the saying, "A cluttered space, a cluttered mind," and this holds profoundly true for students’ learning environments. In a classroom setting, disorganization doesn't just mean messy desks; it can also be unclear routines that translate directly into barriers for learning, like difficulty concentrating, uncertainty about tasks, and not always knowing what’s expected.

This is why a well-organized classroom is so crucial. When teachers intentionally establish routines and systems, create clear standards or assignments and grading, and make effective materials available, they’re contributing to an environment where learning can flourish. Research shows that in a well-organized classroom, students are more likely to:
* Understand expectations because instructions are clear and based on agreed-upon norms and examples
* Feel respected and valued because class time is used purposefully
* Develop independence through clear systems and routines that they can access on their own

Ready to learn more about well-organized classrooms and the actions teachers can take to help students thrive? Download PERTS’ guide on Well-Organized Classrooms (http://perts.net/elevate/well-organized-class) .
Download PERTS Well-Organized Classroom Guide (http://perts.net/elevate/well-organized-class)

About Elevate

Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more. (https://www.perts.net/elevate)

​To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, please choose a convenient time (http://perts.net/demo) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=8bdbc6e5d8)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=36456eb76b&c=8bdbc6e5d8)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-05-07 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

With the end of the school year in sight, it's natural to reflect on what worked well and start planning for adjustments in the fall, which means it's the perfect time to think about classroom organization. Most of us have heard the saying, "A cluttered space, a cluttered mind," and this holds profoundly true for students’ learning environments. In a classroom setting, disorganization doesn't just mean messy desks; it can also be unclear routines that translate directly into barriers for learning, like difficulty concentrating, uncertainty about tasks, and not always knowing what’s expected.

This is why a well-organized classroom is so crucial. When teachers intentionally establish routines and systems, create clear standards or assignments and grading, and make effective materials available, they’re contributing to an environment where learning can flourish. Research shows that in a well-organized classroom, students are more likely to:
* Understand expectations because instructions are clear and based on agreed-upon norms and examples
* Feel respected and valued because class time is used purposefully
* Develop independence through clear systems and routines that they can access on their own

Ready to learn more about well-organized classrooms and the actions teachers can take to help students thrive? Download PERTS’ guide on Well-Organized Classrooms (http://perts.net/elevate/well-organized-class) .
Download PERTS Well-Organized Classroom Guide (http://perts.net/elevate/well-organized-class)

About Elevate

Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more. (https://www.perts.net/elevate)

​To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, please choose a convenient time (http://perts.net/demo) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=8bdbc6e5d8)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=b4edfd0dd8&c=8bdbc6e5d8)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-05-07 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

With the end of the school year in sight, it's natural to reflect on what worked well and start planning for adjustments in the fall, which means it's the perfect time to think about classroom organization. Most of us have heard the saying, "A cluttered space, a cluttered mind," and this holds profoundly true for students’ learning environments. In a classroom setting, disorganization doesn't just mean messy desks; it can also be unclear routines that translate directly into barriers for learning, like difficulty concentrating, uncertainty about tasks, and not always knowing what’s expected.

This is why a well-organized classroom is so crucial. When teachers intentionally establish routines and systems, create clear standards or assignments and grading, and make effective materials available, they’re contributing to an environment where learning can flourish. Research shows that in a well-organized classroom, students are more likely to:
* Understand expectations because instructions are clear and based on agreed-upon norms and examples
* Feel respected and valued because class time is used purposefully
* Develop independence through clear systems and routines that they can access on their own

Ready to learn more about well-organized classrooms and the actions teachers can take to help students thrive? Download PERTS’ guide on Well-Organized Classrooms (http://perts.net/elevate/well-organized-class) .
Download PERTS Well-Organized Classroom Guide (http://perts.net/elevate/well-organized-class)

About Elevate

Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more. (https://www.perts.net/elevate)

​To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, please choose a convenient time (http://perts.net/demo) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=8bdbc6e5d8)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f66b76caa6&c=8bdbc6e5d8)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-05-07 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

With the end of the school year in sight, it's natural to reflect on what worked well and start planning for adjustments in the fall, which means it's the perfect time to think about classroom organization. Most of us have heard the saying, "A cluttered space, a cluttered mind," and this holds profoundly true for students’ learning environments. In a classroom setting, disorganization doesn't just mean messy desks; it can also be unclear routines that translate directly into barriers for learning, like difficulty concentrating, uncertainty about tasks, and not always knowing what’s expected.

This is why a well-organized classroom is so crucial. When teachers intentionally establish routines and systems, create clear standards or assignments and grading, and make effective materials available, they’re contributing to an environment where learning can flourish. Research shows that in a well-organized classroom, students are more likely to:
* Understand expectations because instructions are clear and based on agreed-upon norms and examples
* Feel respected and valued because class time is used purposefully
* Develop independence through clear systems and routines that they can access on their own

Ready to learn more about well-organized classrooms and the actions teachers can take to help students thrive? Download PERTS’ guide on Well-Organized Classrooms (http://perts.net/elevate/well-organized-class) .
Download PERTS Well-Organized Classroom Guide (http://perts.net/elevate/well-organized-class)

About Elevate

Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more. (https://www.perts.net/elevate)

​To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, please choose a convenient time (http://perts.net/demo) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=8bdbc6e5d8)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=298ead533f&c=8bdbc6e5d8)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-05-07 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

With the end of the school year in sight, it's natural to reflect on what worked well and start planning for adjustments in the fall, which means it's the perfect time to think about classroom organization. Most of us have heard the saying, "A cluttered space, a cluttered mind," and this holds profoundly true for students’ learning environments. In a classroom setting, disorganization doesn't just mean messy desks; it can also be unclear routines that translate directly into barriers for learning, like difficulty concentrating, uncertainty about tasks, and not always knowing what’s expected.

This is why a well-organized classroom is so crucial. When teachers intentionally establish routines and systems, create clear standards or assignments and grading, and make effective materials available, they’re contributing to an environment where learning can flourish. Research shows that in a well-organized classroom, students are more likely to:
* Understand expectations because instructions are clear and based on agreed-upon norms and examples
* Feel respected and valued because class time is used purposefully
* Develop independence through clear systems and routines that they can access on their own

Ready to learn more about well-organized classrooms and the actions teachers can take to help students thrive? Download PERTS’ guide on Well-Organized Classrooms (http://perts.net/elevate/well-organized-class) .
Download PERTS Well-Organized Classroom Guide (http://perts.net/elevate/well-organized-class)

About Elevate

Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more. (https://www.perts.net/elevate)

​To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, please choose a convenient time (http://perts.net/demo) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=8bdbc6e5d8)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f97dc5981b&c=8bdbc6e5d8)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-05-07 10:02 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

With the end of the school year in sight, it's natural to reflect on what worked well and start planning for adjustments in the fall, which means it's the perfect time to think about classroom organization. Most of us have heard the saying, "A cluttered space, a cluttered mind," and this holds profoundly true for students’ learning environments. In a classroom setting, disorganization doesn't just mean messy desks; it can also be unclear routines that translate directly into barriers for learning, like difficulty concentrating, uncertainty about tasks, and not always knowing what’s expected.

This is why a well-organized classroom is so crucial. When teachers intentionally establish routines and systems, create clear standards or assignments and grading, and make effective materials available, they’re contributing to an environment where learning can flourish. Research shows that in a well-organized classroom, students are more likely to:
* Understand expectations because instructions are clear and based on agreed-upon norms and examples
* Feel respected and valued because class time is used purposefully
* Develop independence through clear systems and routines that they can access on their own

Ready to learn more about well-organized classrooms and the actions teachers can take to help students thrive? Download PERTS’ guide on Well-Organized Classrooms (http://perts.net/elevate/well-organized-class) .
Download PERTS Well-Organized Classroom Guide (http://perts.net/elevate/well-organized-class)

About Elevate

Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more. (https://www.perts.net/elevate)

​To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, please choose a convenient time (http://perts.net/demo) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=8bdbc6e5d8)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f641712fb8&c=8bdbc6e5d8)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-05-07 10:02 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

With the end of the school year in sight, it's natural to reflect on what worked well and start planning for adjustments in the fall, which means it's the perfect time to think about classroom organization. Most of us have heard the saying, "A cluttered space, a cluttered mind," and this holds profoundly true for students’ learning environments. In a classroom setting, disorganization doesn't just mean messy desks; it can also be unclear routines that translate directly into barriers for learning, like difficulty concentrating, uncertainty about tasks, and not always knowing what’s expected.

This is why a well-organized classroom is so crucial. When teachers intentionally establish routines and systems, create clear standards or assignments and grading, and make effective materials available, they’re contributing to an environment where learning can flourish. Research shows that in a well-organized classroom, students are more likely to:
* Understand expectations because instructions are clear and based on agreed-upon norms and examples
* Feel respected and valued because class time is used purposefully
* Develop independence through clear systems and routines that they can access on their own

Ready to learn more about well-organized classrooms and the actions teachers can take to help students thrive? Download PERTS’ guide on Well-Organized Classrooms (http://perts.net/elevate/well-organized-class) .
Download PERTS Well-Organized Classroom Guide (http://perts.net/elevate/well-organized-class)

About Elevate

Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more. (https://www.perts.net/elevate)

​To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, please choose a convenient time (http://perts.net/demo) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=8bdbc6e5d8)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=7b3f3876af&c=8bdbc6e5d8)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-06-04 10:05 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

As summer approaches, many of us look forward to slowing down, recharging, and maybe even picking up a book that re-centers us on a common passion: student success. This month, PERTS is sharing a curated list of readings that highlight the power of student voice, meaningful learning environments, and classroom practices that support student engagement and learning.

Each title below offers a unique perspective on the conditions that help shape student success. We hope that together they offer valuable insights that help inspire you ahead of the new school year.

Summer Reading List
* The Meaningful Middle School Classroom (https://www.ascd.org/books/the-meaningful-middle-school-classroom?variant=125008) , by Jennifer Ciok
Middle school often marks the start of a decline in student engagement that continues into high school and beyond, but it doesn't have to. In this read, Jennifer Ciok, seasoned teacher and coach, offers practical insights on how educators can reimagine the middle school experience by centering student voice, fostering stronger student-teacher relationships, and creating supportive classroom environments.
* Ordinary Magic (https://www.penguinrandomhouse.com/books/722986/ordinary-magic-by-gregory-m-walton-phd/) , by Greg Walton
What really makes students feel like they belong, and why does it matter? In this reflection, Walton, a pioneer in growth mindset research, walks through the science of motivation and the incredible impact that a sense of belonging can have on students. This compelling read also includes a discussion on the research behind Elevate.
* The Anxious Generation (https://www.amazon.com/s?k=the+anxious+generation&hvadid=695081388200&hvdev=c&hvexpln=67&hvlocphy=9006511&hvnetw=g&hvocijid=10428183738194125865--&hvqmt=e&hvrand=10428183738194125865&hvtargid=kwd-1295499898949&hydadcr=22165_13541070&mcid=94f48129e6e83ff8aa161858ed1fefd2&tag=googhydr-20&ref=pd_sl_4fg0xdluo5_e_p67) , by Jonathan Haidt
As mental health concerns rise and screen time becomes more present in students’ lives, Haidt gives a compelling look at the educators’ role in creating safe, connected learning environments that help students thrive.
* Measure Learning Environments, Not Just Students, to Support Learning and Development (https://www.dropbox.com/scl/fi/sewn0mng0g746a1mjz854/Measure-Learning-Environments-Not-Just-Students-to-Support-Learning-and-Development.pdf?rlkey=011woee16jio9heiqase8jwkw&e=1&dl=0) , by Dave Paunesku & Camille Farrington
To improve student outcomes, we must look at where and how students learn. In this article, Dave Paunesku, PERTS Executive Director, and PERTS collaborator, Camille Farrington, challenge educators to focus attention on the environments students learn in as a leading indicator of student success. They offer evidence-based guidance for measuring and strengthening conditions that drive student engagement and belonging.

Each of these works reflects the growing understanding that to truly support student success, we must design environments that enable students to engage, feel a sense of belonging, and thrive.

The PERTS team hopes you have a wonderful and restorative summer!

- PERTS team

About Elevate

Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more. (https://www.perts.net/elevate)

​To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, please choose a convenient time (http://perts.net/demo) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=4a404d3001)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=7b3f3876af&c=4a404d3001)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-06-04 10:06 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

As summer approaches, many of us look forward to slowing down, recharging, and maybe even picking up a book that re-centers us on a common passion: student success. This month, PERTS is sharing a curated list of readings that highlight the power of student voice, meaningful learning environments, and classroom practices that support student engagement and learning.

Each title below offers a unique perspective on the conditions that help shape student success. We hope that together they offer valuable insights that help inspire you ahead of the new school year.

Summer Reading List
* The Meaningful Middle School Classroom (https://www.ascd.org/books/the-meaningful-middle-school-classroom?variant=125008) , by Jennifer Ciok
Middle school often marks the start of a decline in student engagement that continues into high school and beyond, but it doesn't have to. In this read, Jennifer Ciok, seasoned teacher and coach, offers practical insights on how educators can reimagine the middle school experience by centering student voice, fostering stronger student-teacher relationships, and creating supportive classroom environments.
* Ordinary Magic (https://www.penguinrandomhouse.com/books/722986/ordinary-magic-by-gregory-m-walton-phd/) , by Greg Walton
What really makes students feel like they belong, and why does it matter? In this reflection, Walton, a pioneer in growth mindset research, walks through the science of motivation and the incredible impact that a sense of belonging can have on students. This compelling read also includes a discussion on the research behind Elevate.
* The Anxious Generation (https://www.amazon.com/s?k=the+anxious+generation&hvadid=695081388200&hvdev=c&hvexpln=67&hvlocphy=9006511&hvnetw=g&hvocijid=10428183738194125865--&hvqmt=e&hvrand=10428183738194125865&hvtargid=kwd-1295499898949&hydadcr=22165_13541070&mcid=94f48129e6e83ff8aa161858ed1fefd2&tag=googhydr-20&ref=pd_sl_4fg0xdluo5_e_p67) , by Jonathan Haidt
As mental health concerns rise and screen time becomes more present in students’ lives, Haidt gives a compelling look at the educators’ role in creating safe, connected learning environments that help students thrive.
* Measure Learning Environments, Not Just Students, to Support Learning and Development (https://www.dropbox.com/scl/fi/sewn0mng0g746a1mjz854/Measure-Learning-Environments-Not-Just-Students-to-Support-Learning-and-Development.pdf?rlkey=011woee16jio9heiqase8jwkw&e=1&dl=0) , by Dave Paunesku & Camille Farrington
To improve student outcomes, we must look at where and how students learn. In this article, Dave Paunesku, PERTS Executive Director, and PERTS collaborator, Camille Farrington, challenge educators to focus attention on the environments students learn in as a leading indicator of student success. They offer evidence-based guidance for measuring and strengthening conditions that drive student engagement and belonging.

Each of these works reflects the growing understanding that to truly support student success, we must design environments that enable students to engage, feel a sense of belonging, and thrive.

The PERTS team hopes you have a wonderful and restorative summer!

- PERTS team

About Elevate

Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more. (https://www.perts.net/elevate)

​To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, please choose a convenient time (http://perts.net/demo) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=4a404d3001)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=da5cd98d77&c=4a404d3001)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-06-04 10:06 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

As summer approaches, many of us look forward to slowing down, recharging, and maybe even picking up a book that re-centers us on a common passion: student success. This month, PERTS is sharing a curated list of readings that highlight the power of student voice, meaningful learning environments, and classroom practices that support student engagement and learning.

Each title below offers a unique perspective on the conditions that help shape student success. We hope that together they offer valuable insights that help inspire you ahead of the new school year.

Summer Reading List
* The Meaningful Middle School Classroom (https://www.ascd.org/books/the-meaningful-middle-school-classroom?variant=125008) , by Jennifer Ciok
Middle school often marks the start of a decline in student engagement that continues into high school and beyond, but it doesn't have to. In this read, Jennifer Ciok, seasoned teacher and coach, offers practical insights on how educators can reimagine the middle school experience by centering student voice, fostering stronger student-teacher relationships, and creating supportive classroom environments.
* Ordinary Magic (https://www.penguinrandomhouse.com/books/722986/ordinary-magic-by-gregory-m-walton-phd/) , by Greg Walton
What really makes students feel like they belong, and why does it matter? In this reflection, Walton, a pioneer in growth mindset research, walks through the science of motivation and the incredible impact that a sense of belonging can have on students. This compelling read also includes a discussion on the research behind Elevate.
* The Anxious Generation (https://www.amazon.com/s?k=the+anxious+generation&hvadid=695081388200&hvdev=c&hvexpln=67&hvlocphy=9006511&hvnetw=g&hvocijid=10428183738194125865--&hvqmt=e&hvrand=10428183738194125865&hvtargid=kwd-1295499898949&hydadcr=22165_13541070&mcid=94f48129e6e83ff8aa161858ed1fefd2&tag=googhydr-20&ref=pd_sl_4fg0xdluo5_e_p67) , by Jonathan Haidt
As mental health concerns rise and screen time becomes more present in students’ lives, Haidt gives a compelling look at the educators’ role in creating safe, connected learning environments that help students thrive.
* Measure Learning Environments, Not Just Students, to Support Learning and Development (https://www.dropbox.com/scl/fi/sewn0mng0g746a1mjz854/Measure-Learning-Environments-Not-Just-Students-to-Support-Learning-and-Development.pdf?rlkey=011woee16jio9heiqase8jwkw&e=1&dl=0) , by Dave Paunesku & Camille Farrington
To improve student outcomes, we must look at where and how students learn. In this article, Dave Paunesku, PERTS Executive Director, and PERTS collaborator, Camille Farrington, challenge educators to focus attention on the environments students learn in as a leading indicator of student success. They offer evidence-based guidance for measuring and strengthening conditions that drive student engagement and belonging.

Each of these works reflects the growing understanding that to truly support student success, we must design environments that enable students to engage, feel a sense of belonging, and thrive.

The PERTS team hopes you have a wonderful and restorative summer!

- PERTS team

About Elevate

Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more. (https://www.perts.net/elevate)

​To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, please choose a convenient time (http://perts.net/demo) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=4a404d3001)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=36456eb76b&c=4a404d3001)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-06-04 10:06 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

As summer approaches, many of us look forward to slowing down, recharging, and maybe even picking up a book that re-centers us on a common passion: student success. This month, PERTS is sharing a curated list of readings that highlight the power of student voice, meaningful learning environments, and classroom practices that support student engagement and learning.

Each title below offers a unique perspective on the conditions that help shape student success. We hope that together they offer valuable insights that help inspire you ahead of the new school year.

Summer Reading List
* The Meaningful Middle School Classroom (https://www.ascd.org/books/the-meaningful-middle-school-classroom?variant=125008) , by Jennifer Ciok
Middle school often marks the start of a decline in student engagement that continues into high school and beyond, but it doesn't have to. In this read, Jennifer Ciok, seasoned teacher and coach, offers practical insights on how educators can reimagine the middle school experience by centering student voice, fostering stronger student-teacher relationships, and creating supportive classroom environments.
* Ordinary Magic (https://www.penguinrandomhouse.com/books/722986/ordinary-magic-by-gregory-m-walton-phd/) , by Greg Walton
What really makes students feel like they belong, and why does it matter? In this reflection, Walton, a pioneer in growth mindset research, walks through the science of motivation and the incredible impact that a sense of belonging can have on students. This compelling read also includes a discussion on the research behind Elevate.
* The Anxious Generation (https://www.amazon.com/s?k=the+anxious+generation&hvadid=695081388200&hvdev=c&hvexpln=67&hvlocphy=9006511&hvnetw=g&hvocijid=10428183738194125865--&hvqmt=e&hvrand=10428183738194125865&hvtargid=kwd-1295499898949&hydadcr=22165_13541070&mcid=94f48129e6e83ff8aa161858ed1fefd2&tag=googhydr-20&ref=pd_sl_4fg0xdluo5_e_p67) , by Jonathan Haidt
As mental health concerns rise and screen time becomes more present in students’ lives, Haidt gives a compelling look at the educators’ role in creating safe, connected learning environments that help students thrive.
* Measure Learning Environments, Not Just Students, to Support Learning and Development (https://www.dropbox.com/scl/fi/sewn0mng0g746a1mjz854/Measure-Learning-Environments-Not-Just-Students-to-Support-Learning-and-Development.pdf?rlkey=011woee16jio9heiqase8jwkw&e=1&dl=0) , by Dave Paunesku & Camille Farrington
To improve student outcomes, we must look at where and how students learn. In this article, Dave Paunesku, PERTS Executive Director, and PERTS collaborator, Camille Farrington, challenge educators to focus attention on the environments students learn in as a leading indicator of student success. They offer evidence-based guidance for measuring and strengthening conditions that drive student engagement and belonging.

Each of these works reflects the growing understanding that to truly support student success, we must design environments that enable students to engage, feel a sense of belonging, and thrive.

The PERTS team hopes you have a wonderful and restorative summer!

- PERTS team

About Elevate

Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more. (https://www.perts.net/elevate)

​To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, please choose a convenient time (http://perts.net/demo) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=4a404d3001)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=b4edfd0dd8&c=4a404d3001)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-06-04 10:06 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

As summer approaches, many of us look forward to slowing down, recharging, and maybe even picking up a book that re-centers us on a common passion: student success. This month, PERTS is sharing a curated list of readings that highlight the power of student voice, meaningful learning environments, and classroom practices that support student engagement and learning.

Each title below offers a unique perspective on the conditions that help shape student success. We hope that together they offer valuable insights that help inspire you ahead of the new school year.

Summer Reading List
* The Meaningful Middle School Classroom (https://www.ascd.org/books/the-meaningful-middle-school-classroom?variant=125008) , by Jennifer Ciok
Middle school often marks the start of a decline in student engagement that continues into high school and beyond, but it doesn't have to. In this read, Jennifer Ciok, seasoned teacher and coach, offers practical insights on how educators can reimagine the middle school experience by centering student voice, fostering stronger student-teacher relationships, and creating supportive classroom environments.
* Ordinary Magic (https://www.penguinrandomhouse.com/books/722986/ordinary-magic-by-gregory-m-walton-phd/) , by Greg Walton
What really makes students feel like they belong, and why does it matter? In this reflection, Walton, a pioneer in growth mindset research, walks through the science of motivation and the incredible impact that a sense of belonging can have on students. This compelling read also includes a discussion on the research behind Elevate.
* The Anxious Generation (https://www.amazon.com/s?k=the+anxious+generation&hvadid=695081388200&hvdev=c&hvexpln=67&hvlocphy=9006511&hvnetw=g&hvocijid=10428183738194125865--&hvqmt=e&hvrand=10428183738194125865&hvtargid=kwd-1295499898949&hydadcr=22165_13541070&mcid=94f48129e6e83ff8aa161858ed1fefd2&tag=googhydr-20&ref=pd_sl_4fg0xdluo5_e_p67) , by Jonathan Haidt
As mental health concerns rise and screen time becomes more present in students’ lives, Haidt gives a compelling look at the educators’ role in creating safe, connected learning environments that help students thrive.
* Measure Learning Environments, Not Just Students, to Support Learning and Development (https://www.dropbox.com/scl/fi/sewn0mng0g746a1mjz854/Measure-Learning-Environments-Not-Just-Students-to-Support-Learning-and-Development.pdf?rlkey=011woee16jio9heiqase8jwkw&e=1&dl=0) , by Dave Paunesku & Camille Farrington
To improve student outcomes, we must look at where and how students learn. In this article, Dave Paunesku, PERTS Executive Director, and PERTS collaborator, Camille Farrington, challenge educators to focus attention on the environments students learn in as a leading indicator of student success. They offer evidence-based guidance for measuring and strengthening conditions that drive student engagement and belonging.

Each of these works reflects the growing understanding that to truly support student success, we must design environments that enable students to engage, feel a sense of belonging, and thrive.

The PERTS team hopes you have a wonderful and restorative summer!

- PERTS team

About Elevate

Elevate is a program for teachers to measure and build classroom conditions that catalyze engagement and learning. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more. (https://www.perts.net/elevate)

​To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, please choose a convenient time (http://perts.net/demo) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=4a404d3001)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=298ead533f&c=4a404d3001)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-09-02 10:00 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

The start of a new school year is filled with fresh possibilities and the opportunity for teachers to establish a supportive learning environment that sets the tone for connection, trust, and learning. Supportive teaching plays a key role in helping students feel valued, confident, and ready to succeed.

Supportive teaching (http://perts.net/elevate/supportive-teaching) goes beyond the daily delivery of lessons. It’s about noticing when students need extra help, adapting instruction so all learners can engage, and demonstrating patience and empathy when challenges arise. Prioritizing these practices sends a powerful message that every student belongs and is capable of learning. Research shows that when teachers use supportive teaching practices, students are more likely to:
* Take risks in their learning because growth and progress are celebrated.
* Stay engaged and motivated with lessons that take into account how they learn best.
* Persevere through challenges with confidence, knowing they’ll be met where they are.

As classroom structures continue to grow and develop, consider how small, intentional steps can establish a strong foundation for learning all year long. Ready to start the year with supportive teaching at the center? Download PERTS’ guide on Supportive Teaching (http://perts.net/elevate/supportive-teaching) .
Download PERTS Supportive Teaching Classroom Guide (http://perts.net/elevate/supportive-teaching)

About Elevate

Elevate is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more. (https://www.perts.net/elevate)


​To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, please choose a convenient time (http://perts.net/demo) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=1e33f59ca5)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=36456eb76b&c=1e33f59ca5)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-09-02 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

The start of a new school year is filled with fresh possibilities and the opportunity for teachers to establish a supportive learning environment that sets the tone for connection, trust, and learning. Supportive teaching plays a key role in helping students feel valued, confident, and ready to succeed.

Supportive teaching (http://perts.net/elevate/supportive-teaching) goes beyond the daily delivery of lessons. It’s about noticing when students need extra help, adapting instruction so all learners can engage, and demonstrating patience and empathy when challenges arise. Prioritizing these practices sends a powerful message that every student belongs and is capable of learning. Research shows that when teachers use supportive teaching practices, students are more likely to:
* Take risks in their learning because growth and progress are celebrated.
* Stay engaged and motivated with lessons that take into account how they learn best.
* Persevere through challenges with confidence, knowing they’ll be met where they are.

As classroom structures continue to grow and develop, consider how small, intentional steps can establish a strong foundation for learning all year long. Ready to start the year with supportive teaching at the center? Download PERTS’ guide on Supportive Teaching (http://perts.net/elevate/supportive-teaching) .
Download PERTS Supportive Teaching Classroom Guide (http://perts.net/elevate/supportive-teaching)

About Elevate

Elevate is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more. (https://www.perts.net/elevate)


​To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, please choose a convenient time (http://perts.net/demo) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=1e33f59ca5)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=298ead533f&c=1e33f59ca5)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-09-02 10:01 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

The start of a new school year is filled with fresh possibilities and the opportunity for teachers to establish a supportive learning environment that sets the tone for connection, trust, and learning. Supportive teaching plays a key role in helping students feel valued, confident, and ready to succeed.

Supportive teaching (http://perts.net/elevate/supportive-teaching) goes beyond the daily delivery of lessons. It’s about noticing when students need extra help, adapting instruction so all learners can engage, and demonstrating patience and empathy when challenges arise. Prioritizing these practices sends a powerful message that every student belongs and is capable of learning. Research shows that when teachers use supportive teaching practices, students are more likely to:
* Take risks in their learning because growth and progress are celebrated.
* Stay engaged and motivated with lessons that take into account how they learn best.
* Persevere through challenges with confidence, knowing they’ll be met where they are.

As classroom structures continue to grow and develop, consider how small, intentional steps can establish a strong foundation for learning all year long. Ready to start the year with supportive teaching at the center? Download PERTS’ guide on Supportive Teaching (http://perts.net/elevate/supportive-teaching) .
Download PERTS Supportive Teaching Classroom Guide (http://perts.net/elevate/supportive-teaching)

About Elevate

Elevate is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more. (https://www.perts.net/elevate)


​To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, please choose a convenient time (http://perts.net/demo) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=1e33f59ca5)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=7b3f3876af&c=1e33f59ca5)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-09-02 10:02 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

The start of a new school year is filled with fresh possibilities and the opportunity for teachers to establish a supportive learning environment that sets the tone for connection, trust, and learning. Supportive teaching plays a key role in helping students feel valued, confident, and ready to succeed.

Supportive teaching (http://perts.net/elevate/supportive-teaching) goes beyond the daily delivery of lessons. It’s about noticing when students need extra help, adapting instruction so all learners can engage, and demonstrating patience and empathy when challenges arise. Prioritizing these practices sends a powerful message that every student belongs and is capable of learning. Research shows that when teachers use supportive teaching practices, students are more likely to:
* Take risks in their learning because growth and progress are celebrated.
* Stay engaged and motivated with lessons that take into account how they learn best.
* Persevere through challenges with confidence, knowing they’ll be met where they are.

As classroom structures continue to grow and develop, consider how small, intentional steps can establish a strong foundation for learning all year long. Ready to start the year with supportive teaching at the center? Download PERTS’ guide on Supportive Teaching (http://perts.net/elevate/supportive-teaching) .
Download PERTS Supportive Teaching Classroom Guide (http://perts.net/elevate/supportive-teaching)

About Elevate

Elevate is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more. (https://www.perts.net/elevate)


​To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, please choose a convenient time (http://perts.net/demo) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=1e33f59ca5)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f97dc5981b&c=1e33f59ca5)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-09-02 10:02 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

The start of a new school year is filled with fresh possibilities and the opportunity for teachers to establish a supportive learning environment that sets the tone for connection, trust, and learning. Supportive teaching plays a key role in helping students feel valued, confident, and ready to succeed.

Supportive teaching (http://perts.net/elevate/supportive-teaching) goes beyond the daily delivery of lessons. It’s about noticing when students need extra help, adapting instruction so all learners can engage, and demonstrating patience and empathy when challenges arise. Prioritizing these practices sends a powerful message that every student belongs and is capable of learning. Research shows that when teachers use supportive teaching practices, students are more likely to:
* Take risks in their learning because growth and progress are celebrated.
* Stay engaged and motivated with lessons that take into account how they learn best.
* Persevere through challenges with confidence, knowing they’ll be met where they are.

As classroom structures continue to grow and develop, consider how small, intentional steps can establish a strong foundation for learning all year long. Ready to start the year with supportive teaching at the center? Download PERTS’ guide on Supportive Teaching (http://perts.net/elevate/supportive-teaching) .
Download PERTS Supportive Teaching Classroom Guide (http://perts.net/elevate/supportive-teaching)

About Elevate

Elevate is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more. (https://www.perts.net/elevate)


​To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, please choose a convenient time (http://perts.net/demo) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=1e33f59ca5)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=da5cd98d77&c=1e33f59ca5)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-09-02 10:02 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

The start of a new school year is filled with fresh possibilities and the opportunity for teachers to establish a supportive learning environment that sets the tone for connection, trust, and learning. Supportive teaching plays a key role in helping students feel valued, confident, and ready to succeed.

Supportive teaching (http://perts.net/elevate/supportive-teaching) goes beyond the daily delivery of lessons. It’s about noticing when students need extra help, adapting instruction so all learners can engage, and demonstrating patience and empathy when challenges arise. Prioritizing these practices sends a powerful message that every student belongs and is capable of learning. Research shows that when teachers use supportive teaching practices, students are more likely to:
* Take risks in their learning because growth and progress are celebrated.
* Stay engaged and motivated with lessons that take into account how they learn best.
* Persevere through challenges with confidence, knowing they’ll be met where they are.

As classroom structures continue to grow and develop, consider how small, intentional steps can establish a strong foundation for learning all year long. Ready to start the year with supportive teaching at the center? Download PERTS’ guide on Supportive Teaching (http://perts.net/elevate/supportive-teaching) .
Download PERTS Supportive Teaching Classroom Guide (http://perts.net/elevate/supportive-teaching)

About Elevate

Elevate is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more. (https://www.perts.net/elevate)


​To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, please choose a convenient time (http://perts.net/demo) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=1e33f59ca5)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f66b76caa6&c=1e33f59ca5)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-09-02 10:02 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

The start of a new school year is filled with fresh possibilities and the opportunity for teachers to establish a supportive learning environment that sets the tone for connection, trust, and learning. Supportive teaching plays a key role in helping students feel valued, confident, and ready to succeed.

Supportive teaching (http://perts.net/elevate/supportive-teaching) goes beyond the daily delivery of lessons. It’s about noticing when students need extra help, adapting instruction so all learners can engage, and demonstrating patience and empathy when challenges arise. Prioritizing these practices sends a powerful message that every student belongs and is capable of learning. Research shows that when teachers use supportive teaching practices, students are more likely to:
* Take risks in their learning because growth and progress are celebrated.
* Stay engaged and motivated with lessons that take into account how they learn best.
* Persevere through challenges with confidence, knowing they’ll be met where they are.

As classroom structures continue to grow and develop, consider how small, intentional steps can establish a strong foundation for learning all year long. Ready to start the year with supportive teaching at the center? Download PERTS’ guide on Supportive Teaching (http://perts.net/elevate/supportive-teaching) .
Download PERTS Supportive Teaching Classroom Guide (http://perts.net/elevate/supportive-teaching)

About Elevate

Elevate is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more. (https://www.perts.net/elevate)


​To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, please choose a convenient time (http://perts.net/demo) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=1e33f59ca5)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=b4edfd0dd8&c=1e33f59ca5)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2025-09-02 10:02 UTC, rumenPERTS commented
** Dear educator,
------------------------------------------------------------

The start of a new school year is filled with fresh possibilities and the opportunity for teachers to establish a supportive learning environment that sets the tone for connection, trust, and learning. Supportive teaching plays a key role in helping students feel valued, confident, and ready to succeed.

Supportive teaching (http://perts.net/elevate/supportive-teaching) goes beyond the daily delivery of lessons. It’s about noticing when students need extra help, adapting instruction so all learners can engage, and demonstrating patience and empathy when challenges arise. Prioritizing these practices sends a powerful message that every student belongs and is capable of learning. Research shows that when teachers use supportive teaching practices, students are more likely to:
* Take risks in their learning because growth and progress are celebrated.
* Stay engaged and motivated with lessons that take into account how they learn best.
* Persevere through challenges with confidence, knowing they’ll be met where they are.

As classroom structures continue to grow and develop, consider how small, intentional steps can establish a strong foundation for learning all year long. Ready to start the year with supportive teaching at the center? Download PERTS’ guide on Supportive Teaching (http://perts.net/elevate/supportive-teaching) .
Download PERTS Supportive Teaching Classroom Guide (http://perts.net/elevate/supportive-teaching)

About Elevate

Elevate is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions. Elevate was developed by PERTS (https://www.perts.net/) in partnership with the University of Chicago Consortium on School Research and is used by hundreds of schools across the country. Learn more. (https://www.perts.net/elevate)


​To schedule a short demo and discuss how PERTS Elevate can help your school or district catalyze student engagement and achievement, please choose a convenient time (http://perts.net/demo) .

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2025 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=1e33f59ca5)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f641712fb8&c=1e33f59ca5)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-01-04 14:00 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

The new year typically invites reflection and renewed intentions. At PERTS, it’s no different; our conviction to provide students across the country with outstanding learning experiences remains steady. We’re pleased to share that in this new year, PERTS is piloting a new program: PERTS Compass.

What is Compass?
As the name implies, Compass is a research-based survey platform designed to support education leaders with steady direction to ensure all students experience critical learning conditions. Compass can be used schoolwide to identify student experience gaps, inform professional development opportunities, or assess the impact of a new program or initiative.

Attend a Demo to Get Free Access to Compass
We invite education leaders to pilot PERTS Compass in 2026. To learn more, visit perts.net/compass and register now for a demo. Demo participants will gain free access to Compass and may also be eligible for free expert services.
Register for Tuesday, Jan. 20, 10a PT (https://us02web.zoom.us/meeting/register/rA_GeShgRB2vt_a8s0jjAQ)
Register for Thursday, Jan. 22, 10a PT (https://us02web.zoom.us/meeting/register/HbOBV3PdS3-3nwL_wqFC2Q)

We wish you an inspiring new year and hope to connect in 2026.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=fb4c90693c)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f97dc5981b&c=fb4c90693c)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-01-04 14:00 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

The new year typically invites reflection and renewed intentions. At PERTS, it’s no different; our conviction to provide students across the country with outstanding learning experiences remains steady. We’re pleased to share that in this new year, PERTS is piloting a new program: PERTS Compass.

What is Compass?
As the name implies, Compass is a research-based survey platform designed to support education leaders with steady direction to ensure all students experience critical learning conditions. Compass can be used schoolwide to identify student experience gaps, inform professional development opportunities, or assess the impact of a new program or initiative.

Attend a Demo to Get Free Access to Compass
We invite education leaders to pilot PERTS Compass in 2026. To learn more, visit perts.net/compass and register now for a demo. Demo participants will gain free access to Compass and may also be eligible for free expert services.
Register for Tuesday, Jan. 20, 10a PT (https://us02web.zoom.us/meeting/register/rA_GeShgRB2vt_a8s0jjAQ)
Register for Thursday, Jan. 22, 10a PT (https://us02web.zoom.us/meeting/register/HbOBV3PdS3-3nwL_wqFC2Q)

We wish you an inspiring new year and hope to connect in 2026.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=fb4c90693c)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=36456eb76b&c=fb4c90693c)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-01-04 14:00 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

The new year typically invites reflection and renewed intentions. At PERTS, it’s no different; our conviction to provide students across the country with outstanding learning experiences remains steady. We’re pleased to share that in this new year, PERTS is piloting a new program: PERTS Compass.

What is Compass?
As the name implies, Compass is a research-based survey platform designed to support education leaders with steady direction to ensure all students experience critical learning conditions. Compass can be used schoolwide to identify student experience gaps, inform professional development opportunities, or assess the impact of a new program or initiative.

Attend a Demo to Get Free Access to Compass
We invite education leaders to pilot PERTS Compass in 2026. To learn more, visit perts.net/compass and register now for a demo. Demo participants will gain free access to Compass and may also be eligible for free expert services.
Register for Tuesday, Jan. 20, 10a PT (https://us02web.zoom.us/meeting/register/rA_GeShgRB2vt_a8s0jjAQ)
Register for Thursday, Jan. 22, 10a PT (https://us02web.zoom.us/meeting/register/HbOBV3PdS3-3nwL_wqFC2Q)

We wish you an inspiring new year and hope to connect in 2026.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=fb4c90693c)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=7b3f3876af&c=fb4c90693c)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-01-04 14:01 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

The new year typically invites reflection and renewed intentions. At PERTS, it’s no different; our conviction to provide students across the country with outstanding learning experiences remains steady. We’re pleased to share that in this new year, PERTS is piloting a new program: PERTS Compass.

What is Compass?
As the name implies, Compass is a research-based survey platform designed to support education leaders with steady direction to ensure all students experience critical learning conditions. Compass can be used schoolwide to identify student experience gaps, inform professional development opportunities, or assess the impact of a new program or initiative.

Attend a Demo to Get Free Access to Compass
We invite education leaders to pilot PERTS Compass in 2026. To learn more, visit perts.net/compass and register now for a demo. Demo participants will gain free access to Compass and may also be eligible for free expert services.
Register for Tuesday, Jan. 20, 10a PT (https://us02web.zoom.us/meeting/register/rA_GeShgRB2vt_a8s0jjAQ)
Register for Thursday, Jan. 22, 10a PT (https://us02web.zoom.us/meeting/register/HbOBV3PdS3-3nwL_wqFC2Q)

We wish you an inspiring new year and hope to connect in 2026.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=fb4c90693c)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=298ead533f&c=fb4c90693c)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-01-04 14:01 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

The new year typically invites reflection and renewed intentions. At PERTS, it’s no different; our conviction to provide students across the country with outstanding learning experiences remains steady. We’re pleased to share that in this new year, PERTS is piloting a new program: PERTS Compass.

What is Compass?
As the name implies, Compass is a research-based survey platform designed to support education leaders with steady direction to ensure all students experience critical learning conditions. Compass can be used schoolwide to identify student experience gaps, inform professional development opportunities, or assess the impact of a new program or initiative.

Attend a Demo to Get Free Access to Compass
We invite education leaders to pilot PERTS Compass in 2026. To learn more, visit perts.net/compass and register now for a demo. Demo participants will gain free access to Compass and may also be eligible for free expert services.
Register for Tuesday, Jan. 20, 10a PT (https://us02web.zoom.us/meeting/register/rA_GeShgRB2vt_a8s0jjAQ)
Register for Thursday, Jan. 22, 10a PT (https://us02web.zoom.us/meeting/register/HbOBV3PdS3-3nwL_wqFC2Q)

We wish you an inspiring new year and hope to connect in 2026.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=fb4c90693c)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=da5cd98d77&c=fb4c90693c)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-01-04 14:01 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

The new year typically invites reflection and renewed intentions. At PERTS, it’s no different; our conviction to provide students across the country with outstanding learning experiences remains steady. We’re pleased to share that in this new year, PERTS is piloting a new program: PERTS Compass.

What is Compass?
As the name implies, Compass is a research-based survey platform designed to support education leaders with steady direction to ensure all students experience critical learning conditions. Compass can be used schoolwide to identify student experience gaps, inform professional development opportunities, or assess the impact of a new program or initiative.

Attend a Demo to Get Free Access to Compass
We invite education leaders to pilot PERTS Compass in 2026. To learn more, visit perts.net/compass and register now for a demo. Demo participants will gain free access to Compass and may also be eligible for free expert services.
Register for Tuesday, Jan. 20, 10a PT (https://us02web.zoom.us/meeting/register/rA_GeShgRB2vt_a8s0jjAQ)
Register for Thursday, Jan. 22, 10a PT (https://us02web.zoom.us/meeting/register/HbOBV3PdS3-3nwL_wqFC2Q)

We wish you an inspiring new year and hope to connect in 2026.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=fb4c90693c)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f66b76caa6&c=fb4c90693c)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-01-04 14:05 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

The new year typically invites reflection and renewed intentions. At PERTS, it’s no different; our conviction to provide students across the country with outstanding learning experiences remains steady. We’re pleased to share that in this new year, PERTS is piloting a new program: PERTS Compass.

What is Compass?
As the name implies, Compass is a research-based survey platform designed to support education leaders with steady direction to ensure all students experience critical learning conditions. Compass can be used schoolwide to identify student experience gaps, inform professional development opportunities, or assess the impact of a new program or initiative.

Attend a Demo to Get Free Access to Compass
We invite education leaders to pilot PERTS Compass in 2026. To learn more, visit perts.net/compass and register now for a demo. Demo participants will gain free access to Compass and may also be eligible for free expert services.
Register for Tuesday, Jan. 20, 10a PT (https://us02web.zoom.us/meeting/register/rA_GeShgRB2vt_a8s0jjAQ)
Register for Thursday, Jan. 22, 10a PT (https://us02web.zoom.us/meeting/register/HbOBV3PdS3-3nwL_wqFC2Q)

We wish you an inspiring new year and hope to connect in 2026.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=fb4c90693c)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f641712fb8&c=fb4c90693c)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-01-04 14:05 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

The new year typically invites reflection and renewed intentions. At PERTS, it’s no different; our conviction to provide students across the country with outstanding learning experiences remains steady. We’re pleased to share that in this new year, PERTS is piloting a new program: PERTS Compass.

What is Compass?
As the name implies, Compass is a research-based survey platform designed to support education leaders with steady direction to ensure all students experience critical learning conditions. Compass can be used schoolwide to identify student experience gaps, inform professional development opportunities, or assess the impact of a new program or initiative.

Attend a Demo to Get Free Access to Compass
We invite education leaders to pilot PERTS Compass in 2026. To learn more, visit perts.net/compass and register now for a demo. Demo participants will gain free access to Compass and may also be eligible for free expert services.
Register for Tuesday, Jan. 20, 10a PT (https://us02web.zoom.us/meeting/register/rA_GeShgRB2vt_a8s0jjAQ)
Register for Thursday, Jan. 22, 10a PT (https://us02web.zoom.us/meeting/register/HbOBV3PdS3-3nwL_wqFC2Q)

We wish you an inspiring new year and hope to connect in 2026.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=fb4c90693c)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=b4edfd0dd8&c=fb4c90693c)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-01-16 20:05 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

PERTS is pleased to invite schools, districts, and education organizations to pilot our new program, Compass (http://perts.net/compass) , at no cost!

Educators are undeniably committed to students’ academic success and schools invest tremendously in initiatives that they hope can have a significant impact on measurable outcomes like grades, test scores, and attendance. However, understanding how students experience these initiatives is often missing, along with the opportunity to course correct throughout the school year. This is precisely why PERTS created Compass — to support schools and districts to make student experience visible and actionable for educators and education leaders.

What is Compass?
Compass is a research-based survey platform designed to support education leaders to ensure all students experience critical learning conditions. Compass can be used schoolwide to identify student experience gaps, inform professional development opportunities, or assess the impact of a new program or initiative.

Attend a Demo to Get Free Access to Compass
We invite education leaders to pilot PERTS Compass in 2026. To learn more, visit perts.net/compass and register now for a demo. Demo participants will gain free access to Compass and may also be eligible for free expert services.
Register for Tuesday, Jan. 20, 10a PT (https://us02web.zoom.us/meeting/register/rA_GeShgRB2vt_a8s0jjAQ)
Register for Thursday, Jan. 22, 10a PT (https://us02web.zoom.us/meeting/register/HbOBV3PdS3-3nwL_wqFC2Q)

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=fa3827f876)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f97dc5981b&c=fa3827f876)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-01-16 20:05 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

PERTS is pleased to invite schools, districts, and education organizations to pilot our new program, Compass (http://perts.net/compass) , at no cost!

Educators are undeniably committed to students’ academic success and schools invest tremendously in initiatives that they hope can have a significant impact on measurable outcomes like grades, test scores, and attendance. However, understanding how students experience these initiatives is often missing, along with the opportunity to course correct throughout the school year. This is precisely why PERTS created Compass — to support schools and districts to make student experience visible and actionable for educators and education leaders.

What is Compass?
Compass is a research-based survey platform designed to support education leaders to ensure all students experience critical learning conditions. Compass can be used schoolwide to identify student experience gaps, inform professional development opportunities, or assess the impact of a new program or initiative.

Attend a Demo to Get Free Access to Compass
We invite education leaders to pilot PERTS Compass in 2026. To learn more, visit perts.net/compass and register now for a demo. Demo participants will gain free access to Compass and may also be eligible for free expert services.
Register for Tuesday, Jan. 20, 10a PT (https://us02web.zoom.us/meeting/register/rA_GeShgRB2vt_a8s0jjAQ)
Register for Thursday, Jan. 22, 10a PT (https://us02web.zoom.us/meeting/register/HbOBV3PdS3-3nwL_wqFC2Q)

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=fa3827f876)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=da5cd98d77&c=fa3827f876)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-01-16 20:05 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

PERTS is pleased to invite schools, districts, and education organizations to pilot our new program, Compass (http://perts.net/compass) , at no cost!

Educators are undeniably committed to students’ academic success and schools invest tremendously in initiatives that they hope can have a significant impact on measurable outcomes like grades, test scores, and attendance. However, understanding how students experience these initiatives is often missing, along with the opportunity to course correct throughout the school year. This is precisely why PERTS created Compass — to support schools and districts to make student experience visible and actionable for educators and education leaders.

What is Compass?
Compass is a research-based survey platform designed to support education leaders to ensure all students experience critical learning conditions. Compass can be used schoolwide to identify student experience gaps, inform professional development opportunities, or assess the impact of a new program or initiative.

Attend a Demo to Get Free Access to Compass
We invite education leaders to pilot PERTS Compass in 2026. To learn more, visit perts.net/compass and register now for a demo. Demo participants will gain free access to Compass and may also be eligible for free expert services.
Register for Tuesday, Jan. 20, 10a PT (https://us02web.zoom.us/meeting/register/rA_GeShgRB2vt_a8s0jjAQ)
Register for Thursday, Jan. 22, 10a PT (https://us02web.zoom.us/meeting/register/HbOBV3PdS3-3nwL_wqFC2Q)

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=fa3827f876)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=b4edfd0dd8&c=fa3827f876)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-01-16 20:05 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

PERTS is pleased to invite schools, districts, and education organizations to pilot our new program, Compass (http://perts.net/compass) , at no cost!

Educators are undeniably committed to students’ academic success and schools invest tremendously in initiatives that they hope can have a significant impact on measurable outcomes like grades, test scores, and attendance. However, understanding how students experience these initiatives is often missing, along with the opportunity to course correct throughout the school year. This is precisely why PERTS created Compass — to support schools and districts to make student experience visible and actionable for educators and education leaders.

What is Compass?
Compass is a research-based survey platform designed to support education leaders to ensure all students experience critical learning conditions. Compass can be used schoolwide to identify student experience gaps, inform professional development opportunities, or assess the impact of a new program or initiative.

Attend a Demo to Get Free Access to Compass
We invite education leaders to pilot PERTS Compass in 2026. To learn more, visit perts.net/compass and register now for a demo. Demo participants will gain free access to Compass and may also be eligible for free expert services.
Register for Tuesday, Jan. 20, 10a PT (https://us02web.zoom.us/meeting/register/rA_GeShgRB2vt_a8s0jjAQ)
Register for Thursday, Jan. 22, 10a PT (https://us02web.zoom.us/meeting/register/HbOBV3PdS3-3nwL_wqFC2Q)

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=fa3827f876)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f66b76caa6&c=fa3827f876)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-01-16 20:05 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

PERTS is pleased to invite schools, districts, and education organizations to pilot our new program, Compass (http://perts.net/compass) , at no cost!

Educators are undeniably committed to students’ academic success and schools invest tremendously in initiatives that they hope can have a significant impact on measurable outcomes like grades, test scores, and attendance. However, understanding how students experience these initiatives is often missing, along with the opportunity to course correct throughout the school year. This is precisely why PERTS created Compass — to support schools and districts to make student experience visible and actionable for educators and education leaders.

What is Compass?
Compass is a research-based survey platform designed to support education leaders to ensure all students experience critical learning conditions. Compass can be used schoolwide to identify student experience gaps, inform professional development opportunities, or assess the impact of a new program or initiative.

Attend a Demo to Get Free Access to Compass
We invite education leaders to pilot PERTS Compass in 2026. To learn more, visit perts.net/compass and register now for a demo. Demo participants will gain free access to Compass and may also be eligible for free expert services.
Register for Tuesday, Jan. 20, 10a PT (https://us02web.zoom.us/meeting/register/rA_GeShgRB2vt_a8s0jjAQ)
Register for Thursday, Jan. 22, 10a PT (https://us02web.zoom.us/meeting/register/HbOBV3PdS3-3nwL_wqFC2Q)

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=fa3827f876)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=36456eb76b&c=fa3827f876)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-01-16 20:05 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

PERTS is pleased to invite schools, districts, and education organizations to pilot our new program, Compass (http://perts.net/compass) , at no cost!

Educators are undeniably committed to students’ academic success and schools invest tremendously in initiatives that they hope can have a significant impact on measurable outcomes like grades, test scores, and attendance. However, understanding how students experience these initiatives is often missing, along with the opportunity to course correct throughout the school year. This is precisely why PERTS created Compass — to support schools and districts to make student experience visible and actionable for educators and education leaders.

What is Compass?
Compass is a research-based survey platform designed to support education leaders to ensure all students experience critical learning conditions. Compass can be used schoolwide to identify student experience gaps, inform professional development opportunities, or assess the impact of a new program or initiative.

Attend a Demo to Get Free Access to Compass
We invite education leaders to pilot PERTS Compass in 2026. To learn more, visit perts.net/compass and register now for a demo. Demo participants will gain free access to Compass and may also be eligible for free expert services.
Register for Tuesday, Jan. 20, 10a PT (https://us02web.zoom.us/meeting/register/rA_GeShgRB2vt_a8s0jjAQ)
Register for Thursday, Jan. 22, 10a PT (https://us02web.zoom.us/meeting/register/HbOBV3PdS3-3nwL_wqFC2Q)

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=fa3827f876)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f641712fb8&c=fa3827f876)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-01-16 20:06 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

PERTS is pleased to invite schools, districts, and education organizations to pilot our new program, Compass (http://perts.net/compass) , at no cost!

Educators are undeniably committed to students’ academic success and schools invest tremendously in initiatives that they hope can have a significant impact on measurable outcomes like grades, test scores, and attendance. However, understanding how students experience these initiatives is often missing, along with the opportunity to course correct throughout the school year. This is precisely why PERTS created Compass — to support schools and districts to make student experience visible and actionable for educators and education leaders.

What is Compass?
Compass is a research-based survey platform designed to support education leaders to ensure all students experience critical learning conditions. Compass can be used schoolwide to identify student experience gaps, inform professional development opportunities, or assess the impact of a new program or initiative.

Attend a Demo to Get Free Access to Compass
We invite education leaders to pilot PERTS Compass in 2026. To learn more, visit perts.net/compass and register now for a demo. Demo participants will gain free access to Compass and may also be eligible for free expert services.
Register for Tuesday, Jan. 20, 10a PT (https://us02web.zoom.us/meeting/register/rA_GeShgRB2vt_a8s0jjAQ)
Register for Thursday, Jan. 22, 10a PT (https://us02web.zoom.us/meeting/register/HbOBV3PdS3-3nwL_wqFC2Q)

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=fa3827f876)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=298ead533f&c=fa3827f876)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-01-16 20:06 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

PERTS is pleased to invite schools, districts, and education organizations to pilot our new program, Compass (http://perts.net/compass) , at no cost!

Educators are undeniably committed to students’ academic success and schools invest tremendously in initiatives that they hope can have a significant impact on measurable outcomes like grades, test scores, and attendance. However, understanding how students experience these initiatives is often missing, along with the opportunity to course correct throughout the school year. This is precisely why PERTS created Compass — to support schools and districts to make student experience visible and actionable for educators and education leaders.

What is Compass?
Compass is a research-based survey platform designed to support education leaders to ensure all students experience critical learning conditions. Compass can be used schoolwide to identify student experience gaps, inform professional development opportunities, or assess the impact of a new program or initiative.

Attend a Demo to Get Free Access to Compass
We invite education leaders to pilot PERTS Compass in 2026. To learn more, visit perts.net/compass and register now for a demo. Demo participants will gain free access to Compass and may also be eligible for free expert services.
Register for Tuesday, Jan. 20, 10a PT (https://us02web.zoom.us/meeting/register/rA_GeShgRB2vt_a8s0jjAQ)
Register for Thursday, Jan. 22, 10a PT (https://us02web.zoom.us/meeting/register/HbOBV3PdS3-3nwL_wqFC2Q)

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=fa3827f876)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=7b3f3876af&c=fa3827f876)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-03-15 11:01 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

What does it look like when elevating student voice becomes a core part of how a school system functions—not just a moment in time, but a driver of real change?

We’re excited to invite you to our upcoming webinar, Student Voice in Action: Systems for Districts to Drive Belonging, Engagement, and Effective Teaching (https://www.perts.net/webinar-sp26) , to learn just that. This webinar will take place on April 14th at 2-3p PT/4-5p CT/ 5-6p ET and will feature educators from the Waunakee Community School District in Wisconsin.
Register Now! (https://www.perts.net/webinar-sp26)

We’ll explore how, over multiple years, Waunakee has turned student feedback into a powerful engine for change — closing belonging gaps, boosting engagement, and deepening teacher-student relationships. Hear directly from district and school leaders, teachers, and students on what it really takes to engage in continuous improvement that leverages student voice.

In this webinar, you’ll learn practical strategies to:
* Use student feedback to achieve your school improvement goals
* Support teacher professional learning with actionable data
* Collect student voice data and debrief results with both teachers and students

We hope you’ll join us for this informative conversation. If someone in your network would benefit, extend the invitation!

Learn About PERTS Elevate
Elevate (https://www.perts.net/elevate) is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=b5b9ef16ea)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f641712fb8&c=b5b9ef16ea)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-03-15 11:01 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

What does it look like when elevating student voice becomes a core part of how a school system functions—not just a moment in time, but a driver of real change?

We’re excited to invite you to our upcoming webinar, Student Voice in Action: Systems for Districts to Drive Belonging, Engagement, and Effective Teaching (https://www.perts.net/webinar-sp26) , to learn just that. This webinar will take place on April 14th at 2-3p PT/4-5p CT/ 5-6p ET and will feature educators from the Waunakee Community School District in Wisconsin.
Register Now! (https://www.perts.net/webinar-sp26)

We’ll explore how, over multiple years, Waunakee has turned student feedback into a powerful engine for change — closing belonging gaps, boosting engagement, and deepening teacher-student relationships. Hear directly from district and school leaders, teachers, and students on what it really takes to engage in continuous improvement that leverages student voice.

In this webinar, you’ll learn practical strategies to:
* Use student feedback to achieve your school improvement goals
* Support teacher professional learning with actionable data
* Collect student voice data and debrief results with both teachers and students

We hope you’ll join us for this informative conversation. If someone in your network would benefit, extend the invitation!

Learn About PERTS Elevate
Elevate (https://www.perts.net/elevate) is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=b5b9ef16ea)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=36456eb76b&c=b5b9ef16ea)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-03-15 11:01 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

What does it look like when elevating student voice becomes a core part of how a school system functions—not just a moment in time, but a driver of real change?

We’re excited to invite you to our upcoming webinar, Student Voice in Action: Systems for Districts to Drive Belonging, Engagement, and Effective Teaching (https://www.perts.net/webinar-sp26) , to learn just that. This webinar will take place on April 14th at 2-3p PT/4-5p CT/ 5-6p ET and will feature educators from the Waunakee Community School District in Wisconsin.
Register Now! (https://www.perts.net/webinar-sp26)

We’ll explore how, over multiple years, Waunakee has turned student feedback into a powerful engine for change — closing belonging gaps, boosting engagement, and deepening teacher-student relationships. Hear directly from district and school leaders, teachers, and students on what it really takes to engage in continuous improvement that leverages student voice.

In this webinar, you’ll learn practical strategies to:
* Use student feedback to achieve your school improvement goals
* Support teacher professional learning with actionable data
* Collect student voice data and debrief results with both teachers and students

We hope you’ll join us for this informative conversation. If someone in your network would benefit, extend the invitation!

Learn About PERTS Elevate
Elevate (https://www.perts.net/elevate) is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=b5b9ef16ea)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=7b3f3876af&c=b5b9ef16ea)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-03-15 11:01 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

What does it look like when elevating student voice becomes a core part of how a school system functions—not just a moment in time, but a driver of real change?

We’re excited to invite you to our upcoming webinar, Student Voice in Action: Systems for Districts to Drive Belonging, Engagement, and Effective Teaching (https://www.perts.net/webinar-sp26) , to learn just that. This webinar will take place on April 14th at 2-3p PT/4-5p CT/ 5-6p ET and will feature educators from the Waunakee Community School District in Wisconsin.
Register Now! (https://www.perts.net/webinar-sp26)

We’ll explore how, over multiple years, Waunakee has turned student feedback into a powerful engine for change — closing belonging gaps, boosting engagement, and deepening teacher-student relationships. Hear directly from district and school leaders, teachers, and students on what it really takes to engage in continuous improvement that leverages student voice.

In this webinar, you’ll learn practical strategies to:
* Use student feedback to achieve your school improvement goals
* Support teacher professional learning with actionable data
* Collect student voice data and debrief results with both teachers and students

We hope you’ll join us for this informative conversation. If someone in your network would benefit, extend the invitation!

Learn About PERTS Elevate
Elevate (https://www.perts.net/elevate) is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=b5b9ef16ea)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=298ead533f&c=b5b9ef16ea)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-03-15 11:01 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

What does it look like when elevating student voice becomes a core part of how a school system functions—not just a moment in time, but a driver of real change?

We’re excited to invite you to our upcoming webinar, Student Voice in Action: Systems for Districts to Drive Belonging, Engagement, and Effective Teaching (https://www.perts.net/webinar-sp26) , to learn just that. This webinar will take place on April 14th at 2-3p PT/4-5p CT/ 5-6p ET and will feature educators from the Waunakee Community School District in Wisconsin.
Register Now! (https://www.perts.net/webinar-sp26)

We’ll explore how, over multiple years, Waunakee has turned student feedback into a powerful engine for change — closing belonging gaps, boosting engagement, and deepening teacher-student relationships. Hear directly from district and school leaders, teachers, and students on what it really takes to engage in continuous improvement that leverages student voice.

In this webinar, you’ll learn practical strategies to:
* Use student feedback to achieve your school improvement goals
* Support teacher professional learning with actionable data
* Collect student voice data and debrief results with both teachers and students

We hope you’ll join us for this informative conversation. If someone in your network would benefit, extend the invitation!

Learn About PERTS Elevate
Elevate (https://www.perts.net/elevate) is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=b5b9ef16ea)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=b4edfd0dd8&c=b5b9ef16ea)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-03-15 11:01 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

What does it look like when elevating student voice becomes a core part of how a school system functions—not just a moment in time, but a driver of real change?

We’re excited to invite you to our upcoming webinar, Student Voice in Action: Systems for Districts to Drive Belonging, Engagement, and Effective Teaching (https://www.perts.net/webinar-sp26) , to learn just that. This webinar will take place on April 14th at 2-3p PT/4-5p CT/ 5-6p ET and will feature educators from the Waunakee Community School District in Wisconsin.
Register Now! (https://www.perts.net/webinar-sp26)

We’ll explore how, over multiple years, Waunakee has turned student feedback into a powerful engine for change — closing belonging gaps, boosting engagement, and deepening teacher-student relationships. Hear directly from district and school leaders, teachers, and students on what it really takes to engage in continuous improvement that leverages student voice.

In this webinar, you’ll learn practical strategies to:
* Use student feedback to achieve your school improvement goals
* Support teacher professional learning with actionable data
* Collect student voice data and debrief results with both teachers and students

We hope you’ll join us for this informative conversation. If someone in your network would benefit, extend the invitation!

Learn About PERTS Elevate
Elevate (https://www.perts.net/elevate) is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=b5b9ef16ea)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f66b76caa6&c=b5b9ef16ea)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-03-15 11:02 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

What does it look like when elevating student voice becomes a core part of how a school system functions—not just a moment in time, but a driver of real change?

We’re excited to invite you to our upcoming webinar, Student Voice in Action: Systems for Districts to Drive Belonging, Engagement, and Effective Teaching (https://www.perts.net/webinar-sp26) , to learn just that. This webinar will take place on April 14th at 2-3p PT/4-5p CT/ 5-6p ET and will feature educators from the Waunakee Community School District in Wisconsin.
Register Now! (https://www.perts.net/webinar-sp26)

We’ll explore how, over multiple years, Waunakee has turned student feedback into a powerful engine for change — closing belonging gaps, boosting engagement, and deepening teacher-student relationships. Hear directly from district and school leaders, teachers, and students on what it really takes to engage in continuous improvement that leverages student voice.

In this webinar, you’ll learn practical strategies to:
* Use student feedback to achieve your school improvement goals
* Support teacher professional learning with actionable data
* Collect student voice data and debrief results with both teachers and students

We hope you’ll join us for this informative conversation. If someone in your network would benefit, extend the invitation!

Learn About PERTS Elevate
Elevate (https://www.perts.net/elevate) is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=b5b9ef16ea)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f97dc5981b&c=b5b9ef16ea)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-03-15 11:02 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

What does it look like when elevating student voice becomes a core part of how a school system functions—not just a moment in time, but a driver of real change?

We’re excited to invite you to our upcoming webinar, Student Voice in Action: Systems for Districts to Drive Belonging, Engagement, and Effective Teaching (https://www.perts.net/webinar-sp26) , to learn just that. This webinar will take place on April 14th at 2-3p PT/4-5p CT/ 5-6p ET and will feature educators from the Waunakee Community School District in Wisconsin.
Register Now! (https://www.perts.net/webinar-sp26)

We’ll explore how, over multiple years, Waunakee has turned student feedback into a powerful engine for change — closing belonging gaps, boosting engagement, and deepening teacher-student relationships. Hear directly from district and school leaders, teachers, and students on what it really takes to engage in continuous improvement that leverages student voice.

In this webinar, you’ll learn practical strategies to:
* Use student feedback to achieve your school improvement goals
* Support teacher professional learning with actionable data
* Collect student voice data and debrief results with both teachers and students

We hope you’ll join us for this informative conversation. If someone in your network would benefit, extend the invitation!

Learn About PERTS Elevate
Elevate (https://www.perts.net/elevate) is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=b5b9ef16ea)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=da5cd98d77&c=b5b9ef16ea)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-03-31 19:01 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

We invite you to join PERTS for our upcoming webinar, Student Voice in Action (https://www.perts.net/webinar-sp26) , where educators and a student from the Waunakee Community School District share how they use student feedback to improve school culture. Join PERTS on April 14th to hear their story.
Register Now! (https://www.perts.net/webinar-sp26)

Every day, teachers implement strategies to increase student engagement and belonging, but aren’t always sure whether those strategies are working. The Waunakee Community School District found a way to bridge that gap.
Each of our speakers will share more about their role in the process of collecting and acting on student feedback:
* Tim Schell, Director of Secondary Curriculum & Instruction, will describe Waunakee’s district-wide goals and how they connected district-wide goals to student feedback data.
* Lynn Stenroos, Instructional Coach, will explain the systems she created and sustained to help teachers interpret and act on data.
* Stephanie Boegh, teacher, will share how she leveraged student feedback to make meaningful changes for students in the classroom.
* A student will share what it was like to give feedback to their teacher and see it acted on.

You’ll walk away with a stronger understanding of how student voice strengthens school culture, and we hope you’ll join us for this conversation on April 14th at 2–3 PM PT / 4–5 PM CT / 5–6 PM ET!

If someone in your network would benefit from attending, extend the invitation (https://www.perts.net/webinar-sp26) ! This session will be recorded and shared with all registrants if you can't make it live.

About PERTS Elevate
Elevate (https://www.perts.net/elevate) is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=021cbaec91)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f97dc5981b&c=021cbaec91)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-03-31 19:01 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

We invite you to join PERTS for our upcoming webinar, Student Voice in Action (https://www.perts.net/webinar-sp26) , where educators and a student from the Waunakee Community School District share how they use student feedback to improve school culture. Join PERTS on April 14th to hear their story.
Register Now! (https://www.perts.net/webinar-sp26)

Every day, teachers implement strategies to increase student engagement and belonging, but aren’t always sure whether those strategies are working. The Waunakee Community School District found a way to bridge that gap.
Each of our speakers will share more about their role in the process of collecting and acting on student feedback:
* Tim Schell, Director of Secondary Curriculum & Instruction, will describe Waunakee’s district-wide goals and how they connected district-wide goals to student feedback data.
* Lynn Stenroos, Instructional Coach, will explain the systems she created and sustained to help teachers interpret and act on data.
* Stephanie Boegh, teacher, will share how she leveraged student feedback to make meaningful changes for students in the classroom.
* A student will share what it was like to give feedback to their teacher and see it acted on.

You’ll walk away with a stronger understanding of how student voice strengthens school culture, and we hope you’ll join us for this conversation on April 14th at 2–3 PM PT / 4–5 PM CT / 5–6 PM ET!

If someone in your network would benefit from attending, extend the invitation (https://www.perts.net/webinar-sp26) ! This session will be recorded and shared with all registrants if you can't make it live.

About PERTS Elevate
Elevate (https://www.perts.net/elevate) is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=021cbaec91)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=b4edfd0dd8&c=021cbaec91)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-03-31 19:01 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

We invite you to join PERTS for our upcoming webinar, Student Voice in Action (https://www.perts.net/webinar-sp26) , where educators and a student from the Waunakee Community School District share how they use student feedback to improve school culture. Join PERTS on April 14th to hear their story.
Register Now! (https://www.perts.net/webinar-sp26)

Every day, teachers implement strategies to increase student engagement and belonging, but aren’t always sure whether those strategies are working. The Waunakee Community School District found a way to bridge that gap.
Each of our speakers will share more about their role in the process of collecting and acting on student feedback:
* Tim Schell, Director of Secondary Curriculum & Instruction, will describe Waunakee’s district-wide goals and how they connected district-wide goals to student feedback data.
* Lynn Stenroos, Instructional Coach, will explain the systems she created and sustained to help teachers interpret and act on data.
* Stephanie Boegh, teacher, will share how she leveraged student feedback to make meaningful changes for students in the classroom.
* A student will share what it was like to give feedback to their teacher and see it acted on.

You’ll walk away with a stronger understanding of how student voice strengthens school culture, and we hope you’ll join us for this conversation on April 14th at 2–3 PM PT / 4–5 PM CT / 5–6 PM ET!

If someone in your network would benefit from attending, extend the invitation (https://www.perts.net/webinar-sp26) ! This session will be recorded and shared with all registrants if you can't make it live.

About PERTS Elevate
Elevate (https://www.perts.net/elevate) is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=021cbaec91)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=da5cd98d77&c=021cbaec91)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-03-31 19:01 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

We invite you to join PERTS for our upcoming webinar, Student Voice in Action (https://www.perts.net/webinar-sp26) , where educators and a student from the Waunakee Community School District share how they use student feedback to improve school culture. Join PERTS on April 14th to hear their story.
Register Now! (https://www.perts.net/webinar-sp26)

Every day, teachers implement strategies to increase student engagement and belonging, but aren’t always sure whether those strategies are working. The Waunakee Community School District found a way to bridge that gap.
Each of our speakers will share more about their role in the process of collecting and acting on student feedback:
* Tim Schell, Director of Secondary Curriculum & Instruction, will describe Waunakee’s district-wide goals and how they connected district-wide goals to student feedback data.
* Lynn Stenroos, Instructional Coach, will explain the systems she created and sustained to help teachers interpret and act on data.
* Stephanie Boegh, teacher, will share how she leveraged student feedback to make meaningful changes for students in the classroom.
* A student will share what it was like to give feedback to their teacher and see it acted on.

You’ll walk away with a stronger understanding of how student voice strengthens school culture, and we hope you’ll join us for this conversation on April 14th at 2–3 PM PT / 4–5 PM CT / 5–6 PM ET!

If someone in your network would benefit from attending, extend the invitation (https://www.perts.net/webinar-sp26) ! This session will be recorded and shared with all registrants if you can't make it live.

About PERTS Elevate
Elevate (https://www.perts.net/elevate) is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=021cbaec91)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=298ead533f&c=021cbaec91)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-03-31 19:01 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

We invite you to join PERTS for our upcoming webinar, Student Voice in Action (https://www.perts.net/webinar-sp26) , where educators and a student from the Waunakee Community School District share how they use student feedback to improve school culture. Join PERTS on April 14th to hear their story.
Register Now! (https://www.perts.net/webinar-sp26)

Every day, teachers implement strategies to increase student engagement and belonging, but aren’t always sure whether those strategies are working. The Waunakee Community School District found a way to bridge that gap.
Each of our speakers will share more about their role in the process of collecting and acting on student feedback:
* Tim Schell, Director of Secondary Curriculum & Instruction, will describe Waunakee’s district-wide goals and how they connected district-wide goals to student feedback data.
* Lynn Stenroos, Instructional Coach, will explain the systems she created and sustained to help teachers interpret and act on data.
* Stephanie Boegh, teacher, will share how she leveraged student feedback to make meaningful changes for students in the classroom.
* A student will share what it was like to give feedback to their teacher and see it acted on.

You’ll walk away with a stronger understanding of how student voice strengthens school culture, and we hope you’ll join us for this conversation on April 14th at 2–3 PM PT / 4–5 PM CT / 5–6 PM ET!

If someone in your network would benefit from attending, extend the invitation (https://www.perts.net/webinar-sp26) ! This session will be recorded and shared with all registrants if you can't make it live.

About PERTS Elevate
Elevate (https://www.perts.net/elevate) is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=021cbaec91)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f66b76caa6&c=021cbaec91)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-03-31 19:02 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

We invite you to join PERTS for our upcoming webinar, Student Voice in Action (https://www.perts.net/webinar-sp26) , where educators and a student from the Waunakee Community School District share how they use student feedback to improve school culture. Join PERTS on April 14th to hear their story.
Register Now! (https://www.perts.net/webinar-sp26)

Every day, teachers implement strategies to increase student engagement and belonging, but aren’t always sure whether those strategies are working. The Waunakee Community School District found a way to bridge that gap.
Each of our speakers will share more about their role in the process of collecting and acting on student feedback:
* Tim Schell, Director of Secondary Curriculum & Instruction, will describe Waunakee’s district-wide goals and how they connected district-wide goals to student feedback data.
* Lynn Stenroos, Instructional Coach, will explain the systems she created and sustained to help teachers interpret and act on data.
* Stephanie Boegh, teacher, will share how she leveraged student feedback to make meaningful changes for students in the classroom.
* A student will share what it was like to give feedback to their teacher and see it acted on.

You’ll walk away with a stronger understanding of how student voice strengthens school culture, and we hope you’ll join us for this conversation on April 14th at 2–3 PM PT / 4–5 PM CT / 5–6 PM ET!

If someone in your network would benefit from attending, extend the invitation (https://www.perts.net/webinar-sp26) ! This session will be recorded and shared with all registrants if you can't make it live.

About PERTS Elevate
Elevate (https://www.perts.net/elevate) is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=021cbaec91)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f641712fb8&c=021cbaec91)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-03-31 19:02 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

We invite you to join PERTS for our upcoming webinar, Student Voice in Action (https://www.perts.net/webinar-sp26) , where educators and a student from the Waunakee Community School District share how they use student feedback to improve school culture. Join PERTS on April 14th to hear their story.
Register Now! (https://www.perts.net/webinar-sp26)

Every day, teachers implement strategies to increase student engagement and belonging, but aren’t always sure whether those strategies are working. The Waunakee Community School District found a way to bridge that gap.
Each of our speakers will share more about their role in the process of collecting and acting on student feedback:
* Tim Schell, Director of Secondary Curriculum & Instruction, will describe Waunakee’s district-wide goals and how they connected district-wide goals to student feedback data.
* Lynn Stenroos, Instructional Coach, will explain the systems she created and sustained to help teachers interpret and act on data.
* Stephanie Boegh, teacher, will share how she leveraged student feedback to make meaningful changes for students in the classroom.
* A student will share what it was like to give feedback to their teacher and see it acted on.

You’ll walk away with a stronger understanding of how student voice strengthens school culture, and we hope you’ll join us for this conversation on April 14th at 2–3 PM PT / 4–5 PM CT / 5–6 PM ET!

If someone in your network would benefit from attending, extend the invitation (https://www.perts.net/webinar-sp26) ! This session will be recorded and shared with all registrants if you can't make it live.

About PERTS Elevate
Elevate (https://www.perts.net/elevate) is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=021cbaec91)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=36456eb76b&c=021cbaec91)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-03-31 19:02 UTC, rumenPERTS commented
** Dear Educator,
------------------------------------------------------------

We invite you to join PERTS for our upcoming webinar, Student Voice in Action (https://www.perts.net/webinar-sp26) , where educators and a student from the Waunakee Community School District share how they use student feedback to improve school culture. Join PERTS on April 14th to hear their story.
Register Now! (https://www.perts.net/webinar-sp26)

Every day, teachers implement strategies to increase student engagement and belonging, but aren’t always sure whether those strategies are working. The Waunakee Community School District found a way to bridge that gap.
Each of our speakers will share more about their role in the process of collecting and acting on student feedback:
* Tim Schell, Director of Secondary Curriculum & Instruction, will describe Waunakee’s district-wide goals and how they connected district-wide goals to student feedback data.
* Lynn Stenroos, Instructional Coach, will explain the systems she created and sustained to help teachers interpret and act on data.
* Stephanie Boegh, teacher, will share how she leveraged student feedback to make meaningful changes for students in the classroom.
* A student will share what it was like to give feedback to their teacher and see it acted on.

You’ll walk away with a stronger understanding of how student voice strengthens school culture, and we hope you’ll join us for this conversation on April 14th at 2–3 PM PT / 4–5 PM CT / 5–6 PM ET!

If someone in your network would benefit from attending, extend the invitation (https://www.perts.net/webinar-sp26) ! This session will be recorded and shared with all registrants if you can't make it live.

About PERTS Elevate
Elevate (https://www.perts.net/elevate) is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=021cbaec91)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=7b3f3876af&c=021cbaec91)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-04-08 19:01 UTC, rumenPERTS commented
** Dear Education Leader,
------------------------------------------------------------

On April 14, 2pm PT, Waunakee Community School District is joining PERTS’ webinar (https://www.perts.net/webinar-sp26) to share how they've made student feedback an integral part of how their schools operate, from driving professional learning priorities to shaping everyday classroom experiences. There’s still time to register so you can learn what's working and how you can bring these practices to your own school or district!
Register Now! (https://www.perts.net/webinar-sp26)

Whether belonging and engagement are district strategic priorities or personal passions, our upcoming webinar (https://www.perts.net/webinar-sp26) will provide concrete systems to make them a reality.

About PERTS Elevate
Elevate (https://www.perts.net/elevate) is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=fdc33bef19)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=36456eb76b&c=fdc33bef19)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-04-08 19:02 UTC, rumenPERTS commented
** Dear Education Leader,
------------------------------------------------------------

On April 14, 2pm PT, Waunakee Community School District is joining PERTS’ webinar (https://www.perts.net/webinar-sp26) to share how they've made student feedback an integral part of how their schools operate, from driving professional learning priorities to shaping everyday classroom experiences. There’s still time to register so you can learn what's working and how you can bring these practices to your own school or district!
Register Now! (https://www.perts.net/webinar-sp26)

Whether belonging and engagement are district strategic priorities or personal passions, our upcoming webinar (https://www.perts.net/webinar-sp26) will provide concrete systems to make them a reality.

About PERTS Elevate
Elevate (https://www.perts.net/elevate) is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=fdc33bef19)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=7b3f3876af&c=fdc33bef19)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-04-08 19:02 UTC, rumenPERTS commented
** Dear Education Leader,
------------------------------------------------------------

On April 14, 2pm PT, Waunakee Community School District is joining PERTS’ webinar (https://www.perts.net/webinar-sp26) to share how they've made student feedback an integral part of how their schools operate, from driving professional learning priorities to shaping everyday classroom experiences. There’s still time to register so you can learn what's working and how you can bring these practices to your own school or district!
Register Now! (https://www.perts.net/webinar-sp26)

Whether belonging and engagement are district strategic priorities or personal passions, our upcoming webinar (https://www.perts.net/webinar-sp26) will provide concrete systems to make them a reality.

About PERTS Elevate
Elevate (https://www.perts.net/elevate) is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=fdc33bef19)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f641712fb8&c=fdc33bef19)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-04-08 19:02 UTC, rumenPERTS commented
** Dear Education Leader,
------------------------------------------------------------

On April 14, 2pm PT, Waunakee Community School District is joining PERTS’ webinar (https://www.perts.net/webinar-sp26) to share how they've made student feedback an integral part of how their schools operate, from driving professional learning priorities to shaping everyday classroom experiences. There’s still time to register so you can learn what's working and how you can bring these practices to your own school or district!
Register Now! (https://www.perts.net/webinar-sp26)

Whether belonging and engagement are district strategic priorities or personal passions, our upcoming webinar (https://www.perts.net/webinar-sp26) will provide concrete systems to make them a reality.

About PERTS Elevate
Elevate (https://www.perts.net/elevate) is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=fdc33bef19)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f97dc5981b&c=fdc33bef19)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-04-08 19:02 UTC, rumenPERTS commented
** Dear Education Leader,
------------------------------------------------------------

On April 14, 2pm PT, Waunakee Community School District is joining PERTS’ webinar (https://www.perts.net/webinar-sp26) to share how they've made student feedback an integral part of how their schools operate, from driving professional learning priorities to shaping everyday classroom experiences. There’s still time to register so you can learn what's working and how you can bring these practices to your own school or district!
Register Now! (https://www.perts.net/webinar-sp26)

Whether belonging and engagement are district strategic priorities or personal passions, our upcoming webinar (https://www.perts.net/webinar-sp26) will provide concrete systems to make them a reality.

About PERTS Elevate
Elevate (https://www.perts.net/elevate) is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=fdc33bef19)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=da5cd98d77&c=fdc33bef19)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-04-08 19:02 UTC, rumenPERTS commented
** Dear Education Leader,
------------------------------------------------------------

On April 14, 2pm PT, Waunakee Community School District is joining PERTS’ webinar (https://www.perts.net/webinar-sp26) to share how they've made student feedback an integral part of how their schools operate, from driving professional learning priorities to shaping everyday classroom experiences. There’s still time to register so you can learn what's working and how you can bring these practices to your own school or district!
Register Now! (https://www.perts.net/webinar-sp26)

Whether belonging and engagement are district strategic priorities or personal passions, our upcoming webinar (https://www.perts.net/webinar-sp26) will provide concrete systems to make them a reality.

About PERTS Elevate
Elevate (https://www.perts.net/elevate) is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=fdc33bef19)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=298ead533f&c=fdc33bef19)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-04-08 19:02 UTC, rumenPERTS commented
** Dear Education Leader,
------------------------------------------------------------

On April 14, 2pm PT, Waunakee Community School District is joining PERTS’ webinar (https://www.perts.net/webinar-sp26) to share how they've made student feedback an integral part of how their schools operate, from driving professional learning priorities to shaping everyday classroom experiences. There’s still time to register so you can learn what's working and how you can bring these practices to your own school or district!
Register Now! (https://www.perts.net/webinar-sp26)

Whether belonging and engagement are district strategic priorities or personal passions, our upcoming webinar (https://www.perts.net/webinar-sp26) will provide concrete systems to make them a reality.

About PERTS Elevate
Elevate (https://www.perts.net/elevate) is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=fdc33bef19)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=b4edfd0dd8&c=fdc33bef19)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-04-08 19:02 UTC, rumenPERTS commented
** Dear Education Leader,
------------------------------------------------------------

On April 14, 2pm PT, Waunakee Community School District is joining PERTS’ webinar (https://www.perts.net/webinar-sp26) to share how they've made student feedback an integral part of how their schools operate, from driving professional learning priorities to shaping everyday classroom experiences. There’s still time to register so you can learn what's working and how you can bring these practices to your own school or district!
Register Now! (https://www.perts.net/webinar-sp26)

Whether belonging and engagement are district strategic priorities or personal passions, our upcoming webinar (https://www.perts.net/webinar-sp26) will provide concrete systems to make them a reality.

About PERTS Elevate
Elevate (https://www.perts.net/elevate) is a research-based professional learning program that gives teachers clear structures, timely student feedback, and ongoing support to improve classroom learning conditions.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=fdc33bef19)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f66b76caa6&c=fdc33bef19)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-04-13 16:33 UTC, rumenPERTS commented
** Dear Education Leader,
------------------------------------------------------------

PERTS’ Student Voice in Action (https://www.perts.net/webinar-sp26) webinar is tomorrow, April 14, and there’s still time to register (https://www.perts.net/webinar-sp26) . In this one-hour webinar, you'll hear from leaders and students at Waunakee Community School District on how they've built systems to collect, act on, and integrate student feedback across their schools.
Register Now! (https://www.perts.net/webinar-sp26)

This could be the starting point of a meaningful shift in your district. We hope you'll join us.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=36456eb76b&c=32729a6b99)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=36456eb76b&c=32729a6b99)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-04-13 16:33 UTC, rumenPERTS commented
** Dear Education Leader,
------------------------------------------------------------

PERTS’ Student Voice in Action (https://www.perts.net/webinar-sp26) webinar is tomorrow, April 14, and there’s still time to register (https://www.perts.net/webinar-sp26) . In this one-hour webinar, you'll hear from leaders and students at Waunakee Community School District on how they've built systems to collect, act on, and integrate student feedback across their schools.
Register Now! (https://www.perts.net/webinar-sp26)

This could be the starting point of a meaningful shift in your district. We hope you'll join us.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=7b3f3876af&c=32729a6b99)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=7b3f3876af&c=32729a6b99)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-04-13 16:33 UTC, rumenPERTS commented
** Dear Education Leader,
------------------------------------------------------------

PERTS’ Student Voice in Action (https://www.perts.net/webinar-sp26) webinar is tomorrow, April 14, and there’s still time to register (https://www.perts.net/webinar-sp26) . In this one-hour webinar, you'll hear from leaders and students at Waunakee Community School District on how they've built systems to collect, act on, and integrate student feedback across their schools.
Register Now! (https://www.perts.net/webinar-sp26)

This could be the starting point of a meaningful shift in your district. We hope you'll join us.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=da5cd98d77&c=32729a6b99)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=da5cd98d77&c=32729a6b99)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-04-13 16:33 UTC, rumenPERTS commented
** Dear Education Leader,
------------------------------------------------------------

PERTS’ Student Voice in Action (https://www.perts.net/webinar-sp26) webinar is tomorrow, April 14, and there’s still time to register (https://www.perts.net/webinar-sp26) . In this one-hour webinar, you'll hear from leaders and students at Waunakee Community School District on how they've built systems to collect, act on, and integrate student feedback across their schools.
Register Now! (https://www.perts.net/webinar-sp26)

This could be the starting point of a meaningful shift in your district. We hope you'll join us.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f97dc5981b&c=32729a6b99)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f97dc5981b&c=32729a6b99)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-04-13 16:34 UTC, rumenPERTS commented
** Dear Education Leader,
------------------------------------------------------------

PERTS’ Student Voice in Action (https://www.perts.net/webinar-sp26) webinar is tomorrow, April 14, and there’s still time to register (https://www.perts.net/webinar-sp26) . In this one-hour webinar, you'll hear from leaders and students at Waunakee Community School District on how they've built systems to collect, act on, and integrate student feedback across their schools.
Register Now! (https://www.perts.net/webinar-sp26)

This could be the starting point of a meaningful shift in your district. We hope you'll join us.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f66b76caa6&c=32729a6b99)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f66b76caa6&c=32729a6b99)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-04-13 16:34 UTC, rumenPERTS commented
** Dear Education Leader,
------------------------------------------------------------

PERTS’ Student Voice in Action (https://www.perts.net/webinar-sp26) webinar is tomorrow, April 14, and there’s still time to register (https://www.perts.net/webinar-sp26) . In this one-hour webinar, you'll hear from leaders and students at Waunakee Community School District on how they've built systems to collect, act on, and integrate student feedback across their schools.
Register Now! (https://www.perts.net/webinar-sp26)

This could be the starting point of a meaningful shift in your district. We hope you'll join us.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=b4edfd0dd8&c=32729a6b99)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=b4edfd0dd8&c=32729a6b99)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-04-13 16:34 UTC, rumenPERTS commented
** Dear Education Leader,
------------------------------------------------------------

PERTS’ Student Voice in Action (https://www.perts.net/webinar-sp26) webinar is tomorrow, April 14, and there’s still time to register (https://www.perts.net/webinar-sp26) . In this one-hour webinar, you'll hear from leaders and students at Waunakee Community School District on how they've built systems to collect, act on, and integrate student feedback across their schools.
Register Now! (https://www.perts.net/webinar-sp26)

This could be the starting point of a meaningful shift in your district. We hope you'll join us.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=298ead533f&c=32729a6b99)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=298ead533f&c=32729a6b99)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b

2026-04-13 16:34 UTC, rumenPERTS commented
** Dear Education Leader,
------------------------------------------------------------

PERTS’ Student Voice in Action (https://www.perts.net/webinar-sp26) webinar is tomorrow, April 14, and there’s still time to register (https://www.perts.net/webinar-sp26) . In this one-hour webinar, you'll hear from leaders and students at Waunakee Community School District on how they've built systems to collect, act on, and integrate student feedback across their schools.
Register Now! (https://www.perts.net/webinar-sp26)

This could be the starting point of a meaningful shift in your district. We hope you'll join us.

============================================================
** Facebook (http://www.facebook.com/pertslab)
** Twitter (http://www.twitter.com/pertslab)
** LinkedIn (http://www.linkedin.com/perts)
** Website (https://perts.net)
Copyright © 2026 PERTS, All rights reserved.
 You are receiving this email because you registered for the Mindset Kit, a PERTS program, and/or subscribed to updates from PERTS.

Our mailing address is:
PERTS
PO Box 641019
San Francisco, CA 94164
USA
Want to change how you receive these emails?
You can ** update your preferences (https://perts.us10.list-manage.com/profile?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&e=f641712fb8&c=32729a6b99)
or ** unsubscribe from this list (https://perts.us10.list-manage.com/unsubscribe?u=7edccf60df2a8af6ca924978b&id=fb3a4dfa59&t=b&e=f641712fb8&c=32729a6b99)
.
 Email Marketing Powered by Mailchimp
https://login.mailchimp.com/signup/email-referral/?aid=7edccf60df2a8af6ca924978b